import type { StringKey } from "./en";
import type { Lang } from "./types";

type Pack = Record<StringKey, string>;

const pcm: Pack = {
  "nav.about": "About",
  "nav.signin": "Sign in",
  "nav.setup": "Set up your business",
  "foot.made": "Lobby, na {name} build am.",
  "foot.mit": "Open source wey dey under MIT licence.",
  "lang.title": "Choose your language",
  "lang.sub": "You fit change am later with the flag wey dey for top corner.",
  "lang.change": "Change language",
  "lang.done": "Done",
  "common.loading": "Loading…",
  "common.retry": "Try again",
  "hero.eyebrow": "Queues for shops, clinics and salons",
  "hero.h1a": "Take your number.",
  "hero.h1b": "Wait for anywhere.",
  "hero.lede":
    "One QR code for your business. Customer go scan am, take number, and see where e dey for line. When e reach im turn, im phone go tell am.",
  "hero.fine":
    "No app for customer, no account for dem. Open source, e dey run for your own server.",
  "demo.nowServing": "We dey serve",
  "demo.yourNumber": "Your number",
  "how.title": "How e dey work",
  "how.t1": "Print your QR code",
  "how.d1": "One permanent code for your door or counter.",
  "how.t2": "Customer take number",
  "how.d2": "Dem go scan, add name if dem want, nothing to install.",
  "how.t3": "Press Call next",
  "how.d3": "The line go move and im screen go update by itself.",
  "see.title": "Wetin your customer go see",
  "see.copy":
    "One screen, same answer every time. E dey work for any phone browser, and when you call im number e go change to It's your turn.",
  "see.youreNumber": "Your number be",
  "see.peopleAhead": "People wey dey before you",
  "see.when": "When e happen",
  "see.itsTurn": "Na your turn!",
  "places.title": "Made for places wey get counter",
  "places.list":
    "Pharmacies · Clinics · Salons · Barbershops · Repair shops · Banks · Post offices · Government offices",
  "band.title": "Setup take about one minute.",
  "auth.welcome": "Welcome back",
  "auth.setupSub": "Small typing, your queue don ready.",
  "auth.loginSub": "Sign in go your queue.",
  "auth.bizName": "Business name",
  "auth.yourName": "Your name",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.pwHint": "8 characters at least.",
  "auth.creating": "We dey set am up…",
  "auth.signingIn": "We dey sign you in…",
  "auth.create": "Create my business",
  "auth.haveAccount": "You don get account?",
  "auth.noAccount": "No account yet?",
  "auth.backHome": "Back to home",
  "err.bizName": "Type your business name.",
  "err.name": "Type your name.",
  "err.email": "Type your email.",
  "err.password": "Type your password.",
  "err.pwLen": "Password must follow at least 8 characters.",
  "cust.opening": "E dey open the queue…",
  "cust.wrong": "Something don go wrong.",
  "cust.pausedT": "Queue don pause.",
  "cust.pausedB": "This business no dey take number now, abeg check back soon.",
  "cust.nobody": "Nobody dey serve yet",
  "cust.noOneWaiting": "nobody dey wait",
  "cust.waitingN": "{n} dey wait",
  "cust.joinT": "Join the queue",
  "cust.nameLabel": "Your name (optional)",
  "cust.joinBusy": "E dey take your number…",
  "cust.joinReassure": "No app to install, no account, just number.",
  "cust.youreNumber": "Your number be",
  "cust.youreNext": "You next",
  "cust.oneAhead": "1 person dey before you",
  "cust.nAhead": "{n} people dey before you",
  "cust.peopleWaiting": "People wey dey wait",
  "cust.reassure": "This page go update by itself, keep am open.",
  "cust.leave": "Comot for queue",
  "cust.leaveConfirm": "Comot for queue? You go lose your number.",
  "cust.turnT": "Na your turn",
  "cust.turnB": "Abeg come the counter.",
  "cust.imHere": "I dey here",
  "cust.sending": "E dey send…",
  "cust.confirmed": "Thank you, we don tell dem say you ready.",
  "cust.done": "All done",
  "cust.servedBody": "Thank you for wait.",
  "cust.skippedBody": "Dem skip you. If you still dey here, take another number.",
  "cust.noShowBody": "We close this number. If you still dey here, take another number.",
  "cust.joinAgain": "Join again",
  "cust.poweredBy": "Powered by",
  "dash.navQueue": "Queue",
  "dash.navQr": "QR code",
  "dash.navSettings": "Settings",
  "dash.signOut": "Sign out",
  "dash.opening": "E dey open your queue…",
  "dash.pausedB": "Customer no fit take number now.",
  "dash.nobodyCounter": "Nobody dey the counter",
  "dash.noNameGiven": "No name",
  "dash.confirmedHere": "don talk say e dey here",
  "dash.notConfirmed": "never confirm",
  "dash.callNext": "Call next",
  "dash.calling": "E dey call…",
  "dash.noWaitingHint": "Nobody dey wait now.",
  "dash.pause": "Pause queue",
  "dash.resume": "Resume queue",
  "dash.atCounter": "For the counter",
  "dash.waitingTitle": "Waiting",
  "dash.noName": "No name",
  "dash.stWait": "Waiting",
  "dash.stCalled": "Dem don call",
  "dash.stServed": "Served",
  "dash.stSkipped": "Skipped",
  "dash.stNoShow": "No show",
  "dash.firstRun": "Nobody don enter yet. Three quick steps make your queue start:",
  "dash.step1": "Get your QR code. Print am, or put am for screen for door.",
  "dash.step1link": "Open my QR code →",
  "dash.step2": "Customer dey take number. Dem go scan, type name small, and e don do.",
  "dash.step3": "Press Call next. Im phone go update that very moment.",
  "dash.emptyWaiting": "Nobody dey wait. New numbers go show here when people join.",
  "dash.nextUp": "Next up",
  "dash.finished": "Finished",
  "dash.counts": "{s} served, {k} skipped, {n} no show",
  "dash.markServed": "Mark as served",
  "dash.skip": "Skip",
  "qr.intro":
    "Print this one put am for door or counter. The link no dey change, so code wey you print today go still dey work.",
  "qr.linkLabel": "Your queue link",
  "qr.download": "Download PNG",
  "qr.print": "Print",
  "qr.copy": "Copy link",
  "qr.copied": "Link don copy.",
  "qr.making": "E dey make your QR code…",
  "qr.sheetCta": "Scan to join the queue",
  "qr.fine":
    "Customer dey scan this to take number, no app, no account. The QR dey remain black and white for every theme so phone fit read am.",
  "set.noteLabel": "Note for customer",
  "set.noteHint": "E go show above the Join button for your queue page. Optional.",
  "set.save": "Save changes",
  "set.saving": "E dey save…",
  "set.saved": "Don save.",
  "set.goodToKnow": "Good to know",
  "set.linkBody": "The link permanent, so printed QR go dey work even if you change business name.",
  "set.signedInAs": "You dey sign in as",
  "set.errNote": "Your note suppose 200 characters or less.",
  "nf.title": "This page no exist.",
  "nf.body": "E fit don move, or the link no correct.",
  "nf.cta": "Go to the home page",
};

const yo: Pack = {
  "nav.about": "Nípa",
  "nav.signin": "Wọ inú",
  "nav.setup": "Àtọ́ṣọ́ ilé-iṣẹ́ rẹ",
  "foot.made": "Lobby, ó dá si i ní ọwọ́ {name}.",
  "foot.mit": "Aṣẹ òwọ̀ ní òfin MIT.",
  "lang.title": "Yan èdè rẹ",
  "lang.sub": "O lè yí i padà lẹ́yìn, pẹ̀lú àmì ìfáàrá tó wà ní apá òkè.",
  "lang.change": "Yí èdè padà",
  "lang.done": "Parí",
  "common.loading": "Ǹjẹ́rísí…",
  "common.retry": "Gbìyànjú mọ́",
  "hero.eyebrow": "Ọ̀rọ̀̀jọ́ fún àwọn ilé-iṣẹ́, ọdẹ̀gàn àti àwọn ilé ìwòsàn",
  "hero.h1a": "Gba nọ́ńbà.",
  "hero.h1b": "Dúró níbì kankan.",
  "hero.lede":
    "QR kan fún ilé-iṣẹ́ rẹ. Àwọn oníbàárà yóò fì wò, gba nọ́ńbà, ó sì rí ibi wọn nínú ọ̀rọ̀̀jọ́. Nígbà tí ó bá dé, fóònù rẹ̀ yóò sọ fún un.",
  "hero.fine": "Kò sí ẹ̀rọ̀ ọ̀tọ̀ fún wọn, kò sí àkọ̀lẹ̀fọ̀ọ̀mù. Aṣẹ òwọ̀, ó sì ń ṣiṣẹ́ ní sáfàrì rẹ.",
  "demo.nowServing": "Ó ń ẹ̀ sí i",
  "demo.yourNumber": "Nọ́ńbà rẹ",
  "how.title": "Bí ó ṣe ń ṣiṣẹ́",
  "how.t1": "Tì QR code rẹ sókè",
  "how.d1": "Àmì kan pàtó fún ọ̀nà tàbí kọ́ntá rẹ.",
  "how.t2": "Àwọn oníbàárà gbà nọ́ńbà",
  "how.d2": "Wọ́n yóò fòótù wò, fi orúkọ tí wọ́n fẹ́ kún un, kò sí ohun tí wọ́n fẹ́ dáwọ́lẹ̀.",
  "how.t3": "Tẹ Call next lọ́wọ́",
  "how.d3": "Ọ̀rọ̀̀jọ́ yóò lọ, ìfáhàn wọn yóò sì ṣeìmúdòjú ìwọ̀n fún wọn.",
  "see.title": "Ohun tí àwọn oníbàárà rẹ wò",
  "see.copy":
    "Ìfáhàn kan pàtó ni ó máa ń jà nígbà gbogbo. Ó ń ṣiṣẹ́ ní kọ̀lọ̀mí kọ̀lọ̀mí kọ̀, tí wọ́n bá pè nọ́ńbà wọn, yóò yí padà sí It's your turn.",
  "see.youreNumber": "Nọ́ńbà rẹ ni",
  "see.peopleAhead": "Àwọn ènìyàn tó wà níwájú rẹ",
  "see.when": "Nígbà tí ó bá ṣẹlẹ̀",
  "see.itsTurn": "Ìgbà rẹ ni!",
  "places.title": "Fún ibi tí ó ní kọ́ntá",
  "places.list":
    "Ilé òògùn · Ilé ìwòsàn · Ilé ìdọ̀gbọ̀n irun · Ilé ìtúnàẹ̀rọ · Banki · Ilé ìfímúìwé · Iṣẹ́ ìjọba",
  "band.title": "Àtọ́ṣọ́ yóò pọ̀ mìíràn.",
  "auth.welcome": "Kaabo sí i",
  "auth.setupSub": "Kò pọ̀ ìtẹ̀wọ́gbà, ọ̀rọ̀̀jọ́ rẹ tiṣetán.",
  "auth.loginSub": "Wọ inú ọ̀rọ̀̀jọ́ rẹ.",
  "auth.bizName": "Orúkọ ilé-iṣẹ́",
  "auth.yourName": "Orúkọ rẹ",
  "auth.email": "Ímèélì",
  "auth.password": "Ọ̀rọ̀̀ ìkọ̀kọ̀",
  "auth.pwHint": "Àmì ọ̀tọ̀̀ 8 lọ.",
  "auth.creating": "A ń tọ́ ọ sí i…",
  "auth.signingIn": "A ń wọọ inú…",
  "auth.create": "Ṣàkọsọ ilé-iṣẹ́ mi",
  "auth.haveAccount": "Ǹí àkọ̀lẹ̀fọ̀ọ̀mù tẹ́lẹ̀?",
  "auth.noAccount": "Kò sí àkọ̀lẹ̀fọ̀ọ̀mù báyìí?",
  "auth.backHome": "Padà sí ilé",
  "err.bizName": "Tẹ orúkọ ilé-iṣẹ́ rẹ sí i.",
  "err.name": "Tẹ orúkọ rẹ sí i.",
  "err.email": "Tẹ ímèélì rẹ sí i.",
  "err.password": "Tẹ ọ̀rọ̀̀ ìkọ̀kọ̀ rẹ sí i.",
  "err.pwLen": "Ọ̀rọ̀̀ ìkọ̀kọ̀ gbọdọ̀ ní àmì ọ̀tọ̀̀ 8 lọ.",
  "cust.opening": "A ń ṣí ọ̀rọ̀̀jọ́…",
  "cust.wrong": "Nǹkan kan báṣẹ̀.",
  "cust.pausedT": "Ọ̀rọ̀̀jọ́ dúró.",
  "cust.pausedB": "Ilé-iṣẹ́ yìí kò gba nọ́ńbà báyìí, máa wá àtúnwádìí lẹ́ẹ̀kan.",
  "cust.nobody": "Kò sí ẹni tó wà níbẹ̀ títí di báyìí",
  "cust.noOneWaiting": "kò sí ẹni tó ń dúró",
  "cust.waitingN": "{n} ń dúró",
  "cust.joinT": "Darapọ̀ mọ́ ọ̀rọ̀̀jọ́",
  "cust.nameLabel": "Orúkọ rẹ (a fúnra rẹ)",
  "cust.joinBusy": "A ń gba nọ́ńbà rẹ…",
  "cust.joinReassure": "Kò sí ẹ̀rọ̀ ọ̀tọ̀, kò sí àkọ̀lẹ̀fọ̀ọ̀mù, nọ́ńbà kan ni.",
  "cust.youreNumber": "Nọ́ńbà rẹ ni",
  "cust.youreNext": "O lẹ́yìn náà",
  "cust.oneAhead": "Ènìyàn kan wà níwájú rẹ",
  "cust.nAhead": "Àwọn ènìyàn {n} wà níwájú rẹ",
  "cust.peopleWaiting": "Àwọn tó ń dúró",
  "cust.reassure": "Ìfáhàn yìí yóò fúnra rẹ dí àtúnṣe, fi síbẹ̀.",
  "cust.leave": "Fòpọ̀ sí ọ̀rọ̀̀jọ́",
  "cust.leaveConfirm": "Fòpọ̀ sí ọ̀rọ̀̀jọ́? O yóò sọ̀nà nọ́ńbà rẹ.",
  "cust.turnT": "Ìgbà rẹ ni",
  "cust.turnB": "Èun wá sí kọ́ntá.",
  "cust.imHere": "Mo wà níbẹ̀",
  "cust.sending": "A ń ránṣẹ́…",
  "cust.confirmed": "O ṣé, a ti sọ fún wọn pé oṣetán.",
  "cust.done": "Ti parí",
  "cust.servedBody": "O ṣé tí o dúró.",
  "cust.skippedBody": "Wọ́n fi bẹ́yẹ̀n. Bí o bá wà níbẹ̀, gba nọ́ńbà mìíràn.",
  "cust.noShowBody": "A ti pa nọ́ńbà yìí rẹ. Bí o bá wà níbẹ̀, gba nọ́ńbà mìíràn.",
  "cust.joinAgain": "Darapọ̀ mọ́ lẹ́ẹ̀kan sí i",
  "cust.poweredBy": "Ní iṣẹ́",
  "dash.navQueue": "Ọ̀rọ̀̀jọ́",
  "dash.navQr": "QR code",
  "dash.navSettings": "Àwọn àṣàyàn",
  "dash.signOut": "Jáde",
  "dash.opening": "A ń ṣí ọ̀rọ̀̀jọ́ rẹ…",
  "dash.pausedB": "Àwọn oníbàárà kò lè gba nọ́ńbà báyìí.",
  "dash.nobodyCounter": "Kò sí ẹni ní kọ́ntá",
  "dash.noNameGiven": "Kò sí orúkọ",
  "dash.confirmedHere": "ti sọ pé ó wà níbẹ̀",
  "dash.notConfirmed": "kò tíìṣètọ́",
  "dash.callNext": "Pè tókè tó",
  "dash.calling": "A ń pè…",
  "dash.noWaitingHint": "Kò sí ẹni tó ń dúró báyìí.",
  "dash.pause": "Dá ọ̀rọ̀̀jọ́ dúró",
  "dash.resume": "Tún ọ̀rọ̀̀jọ́ bẹ̀rẹ̀",
  "dash.atCounter": "Ní kọ́ntá",
  "dash.waitingTitle": "Ǹjẹ́rísí",
  "dash.noName": "Kò sí orúkọ",
  "dash.stWait": "Ǹjẹ́rísí",
  "dash.stCalled": "A ti pè",
  "dash.stServed": "Ti fún un ní iṣẹ́",
  "dash.stSkipped": "Fi bẹ́yẹ̀n",
  "dash.stNoShow": "Kò dé",
  "dash.firstRun": "Kò sí ẹni tó wà báyìí. Ìgbésẹ̀ mẹ́ta kéré ni yóò gbé ọ̀rọ̀̀jọ́ rẹ lọ:",
  "dash.step1": "Gba QR code rẹ. Tì i sókè, tàbí fi hàn ní ọ̀nà.",
  "dash.step1link": "Ṣí QR code mi →",
  "dash.step2": "Àwọn oníbàárà gba nọ́ńbà. Wọ́n fòótù wò, kún orúkọ tí wọ́n fẹ́, wọ́n sì darapọ̀.",
  "dash.step3": "Tẹ Call next. Fóònù wọn yóò fúnra wọn dí àtúnṣe nígbà náà.",
  "dash.emptyWaiting": "Kò sí ẹni tó ń dúró. Àwọn nọ́ńbà tuntun yóò hàn níbí tí àwọn ènìyàn bá darapọ̀.",
  "dash.nextUp": "Tókè tó",
  "dash.finished": "Ti parí",
  "dash.counts": "{s} ti fún ní iṣẹ́, {k} fi bẹ́yẹ̀n, {n} kò dé",
  "dash.markServed": "Èlò tó ṣe",
  "dash.skip": "Fòbẹ́yẹ̀n",
  "qr.intro":
    "Tì i sókè, fi hàn ní ọ̀nà tàbí lórí kọ́ntá. Línkì kò ní yí padà, tí a bá tì lónìí yóò ń ṣiṣẹ́.",
  "qr.linkLabel": "Línkì ọ̀rọ̀̀jọ́ rẹ",
  "qr.download": "Gba PNG",
  "qr.print": "Tì i sókè",
  "qr.copy": "Kọpù línkì",
  "qr.copied": "A ti kọpù línkì.",
  "qr.making": "A ń ṣe QR code rẹ…",
  "qr.sheetCta": "Fòótù wò kó o darapọ̀",
  "qr.fine":
    "Àwọn oníbàárà ń fòótù wò èyí láti gba nọ́ńbà, kò sí ẹ̀rọ̀ ọ̀tọ̀, kò sí àkọ̀lẹ̀fọ̀ọ̀mù. QR yóò dúró dí àwùjọ fún gbogbo ìtọ́jọ̀ kí fóònù lè kà á.",
  "set.noteLabel": "Àkọlé fún àwọn oníbàárà",
  "set.noteHint": "Ó máa ń hàn lórí tẹ́mípẹ́ẹ̀tì Join nínú ìfáhàn ọ̀rọ̀̀jọ́ rẹ. A fúnra rẹ ni.",
  "set.save": "Fúnpa àwọn àyípà",
  "set.saving": "A ń fúnpa…",
  "set.saved": "A ti fúnpa.",
  "set.goodToKnow": "Ohun tí o yẹ ká mọ̀",
  "set.linkBody": "Línkì yìí pàtó, tí a bá tì QR code lónìí yóò ń ṣiṣẹ́ kódà bí o bá yí orúkọ padà.",
  "set.signedInAs": "O wà nínu",
  "set.errNote": "Àkọlé rẹ gbọdọ̀ jù àmì ọ̀tọ̀̀ 200 lọ.",
  "nf.title": "Ìfáhàn yìí kò wà.",
  "nf.body": "Ó lè ti kọjá, tàbí línkì kò tọ́.",
  "nf.cta": "Lọ sí ìfáhàn ìbẹ̀rẹ̀",
};

const ha: Pack = {
  "nav.about": "Game da",
  "nav.signin": "Shiga",
  "nav.setup": "Kafa kasuwancinka",
  "foot.made": "Lobby, an gina ta da {name}.",
  "foot.mit": "Bude waya ƙarƙash lasisin MIT.",
  "lang.title": "Zaɓi harshe naka",
  "lang.sub": "Za ka iya canza shi daga baya, ta hanyar tuta a gefen sama.",
  "lang.change": "Canza harshe",
  "lang.done": "An gama",
  "common.loading": "Ana lodi…",
  "common.retry": "Sake gwada",
  "hero.eyebrow": "Jerin kufofi ga shago, asibiti da salon",
  "hero.h1a": "Kaɗauki lamba.",
  "hero.h1b": "Ki jira a wani wuri.",
  "hero.lede":
    "QR ɗaya ga kasuwancinka. Maƙwabci suna scan, suna ɗaukar lamba, suna kuma gano wurinsu a jergei. Sa ya kai tasa, wayar tasa zata gaya masa.",
  "hero.fine":
    "Babu app ga maƙwabci, babu asusu ga su. Bude waya, kuma yana gudana a server ɗinka.",
  "demo.nowServing": "Ana badarwa",
  "demo.yourNumber": "Lambarka",
  "how.title": "Yadda yake aiki",
  "how.t1": "Buga QR ɗinka",
  "how.d1": "Lamba ɗaya mai ci gaba ga ƙofarka ko kaunta.",
  "how.t2": "Maƙwabci suna ɗaukar lamba",
  "how.d2": "Suna scan, suna ƙara suna idan su so, babu shigar.",
  "how.t3": "Danna Call next",
  "how.d3": "Jerin yana motsawa, allonsa yana sabuntawa da kansa.",
  "see.title": "Abin da maƙwabcenka ke gani",
  "see.copy":
    "Allon guda ɗaya da amsa iri ɗaya kowane lokaci. Yana aiki a duk wayoyi, kuma sa aka kira lambarsa yana canzawa zuwa It's your turn.",
  "see.youreNumber": "Lambarka ita ce",
  "see.peopleAhead": "Mutane a gabanka",
  "see.when": "Lokacin da ya faru",
  "see.itsTurn": "Lokacinka ya yi!",
  "places.title": "Ga wuraren da suke da kaunta",
  "places.list":
    "Kwaroron magani · Asibiti · Salon · Masanin sace · Masanin gyaran kayayyaki · Banki · Ofisoshin labarai · Ofisoshin gwamnati",
  "band.title": "Kafa yana ɗaukar minti ɗaya.",
  "auth.welcome": "Barka da dawowa",
  "auth.setupSub": "Ga ƙaramin rubutu, jerinka ya shirya.",
  "auth.loginSub": "Shiga jerinka.",
  "auth.bizName": "Sunan kasuwanci",
  "auth.yourName": "Sunanka",
  "auth.email": "Imel",
  "auth.password": "Kalmar sirri",
  "auth.pwHint": "Ƙalma 8 ne za a iya.",
  "auth.creating": "Ana kafa…",
  "auth.signingIn": "Ana shiga…",
  "auth.create": "Kafa kasuwancina",
  "auth.haveAccount": "Kana da asusu a gabana?",
  "auth.noAccount": "Babu asusu ko da yanzu?",
  "auth.backHome": "Koma gida",
  "err.bizName": "Shigar da sunan kasuwancinka.",
  "err.name": "Shigar da sunanka.",
  "err.email": "Shigar da imelka.",
  "err.password": "Shigar da kalmar sirrinka.",
  "err.pwLen": "Kalmar sirri dole ne ta kasance ƙalma 8.",
  "cust.opening": "Ana buɗe jeri…",
  "cust.wrong": "Wani abu ya kasa.",
  "cust.pausedT": "Jerin ya huta.",
  "cust.pausedB": "Wannan kasuwanci ba ya ɗaukar lamba yanzu, don Allah dawo nan daiso.",
  "cust.nobody": "Babu wanda ake badarwa har yanzu",
  "cust.noOneWaiting": "babu wanda ke jira",
  "cust.waitingN": "{n} ake jira",
  "cust.joinT": "Shiga jerin",
  "cust.nameLabel": "Sunanka (na son rai)",
  "cust.joinBusy": "Ana ɗauko lambarka…",
  "cust.joinReassure": "Babu shigarwa, babu asusu, lamba ɗaya ce.",
  "cust.youreNumber": "Lambarka ita ce",
  "cust.youreNext": "Ka gaba",
  "cust.oneAhead": "Mutum ɗaya ne a gabanka",
  "cust.nAhead": "Mutane {n} ne a gabanka",
  "cust.peopleWaiting": "Manyan jira",
  "cust.reassure": "Wannan allon yana sabuntawa da kansa, ka bar shi a buɗe.",
  "cust.leave": "Fita daga jerin",
  "cust.leaveConfirm": "Fita daga jerin? Za ka rasa lambarka.",
  "cust.turnT": "Lokacinka ya yi",
  "cust.turnB": "Don Allah zuwa ga kaunta.",
  "cust.imHere": "Ina nan",
  "cust.sending": "Ana aikawa…",
  "cust.confirmed": "Na gode, mun gaya musu ka shirya.",
  "cust.done": "An gama",
  "cust.servedBody": "Na gode da jira.",
  "cust.skippedBody": "An manta da ka. Idan kana nan, ɗauki lamba ta.",
  "cust.noShowBody": "An rufe lambar. Idan kana nan, ɗauki lamba ta.",
  "cust.joinAgain": "Shiga ɗaya",
  "cust.poweredBy": "Ta hannun",
  "dash.navQueue": "Jeri",
  "dash.navQr": "QR",
  "dash.navSettings": "Saituna",
  "dash.signOut": "Fita",
  "dash.opening": "Ana buɗe jerinka…",
  "dash.pausedB": "Maƙwabci ba za su iya ɗaukar lamba yanzu ba.",
  "dash.nobodyCounter": "Babu wani a kan kaunta",
  "dash.noNameGiven": "Babu suna",
  "dash.confirmedHere": "ya ce yana nan",
  "dash.notConfirmed": "ba ta tabbatar ba",
  "dash.callNext": "Kira na gaba",
  "dash.calling": "Ana kira…",
  "dash.noWaitingHint": "Babu wanda ke jira yanzu.",
  "dash.pause": "Huta da jeri",
  "dash.resume": "Ci gaba da jeri",
  "dash.atCounter": "A kan kaunta",
  "dash.waitingTitle": "Ajaki",
  "dash.noName": "Babu suna",
  "dash.stWait": "Ajaki",
  "dash.stCalled": "Ana kira",
  "dash.stServed": "An badar",
  "dash.stSkipped": "An manta",
  "dash.stNoShow": "Babu zuwa",
  "dash.firstRun": "Babu wanda ya zo tukuna. Matauka uku masu sauri ne za su kafa jerinka:",
  "dash.step1": "Samu QR ɗinka. Buga shi, ko a allon kusa da ƙofa.",
  "dash.step1link": "Buɗe QR nawa →",
  "dash.step2": "Maƙwabci suna ɗaukar lamba. Suna scan, suna rubuta suna ko da so, suna shiga.",
  "dash.step3": "Danna Call next. Wayarta za ta sabunta a wannan lokacin.",
  "dash.emptyWaiting": "Babu wanda ke jira. Sabbin lambobin za su bayyana nan lokacin da mutane suka shiga.",
  "dash.nextUp": "Na gaba",
  "dash.finished": "An gama",
  "dash.counts": "{s} an badar, {k} an manta, {n} babu zuwa",
  "dash.markServed": "Yi da alama an badar",
  "dash.skip": "Manta",
  "qr.intro":
    "Buga wannan ka ajiye shi a ƙofa ko kaunta. Haɗin ba ya canza, kodai buga ka yau zai ci gaba.",
  "qr.linkLabel": "Haɗin jerinka",
  "qr.download": "Sauke PNG",
  "qr.print": "Buga",
  "qr.copy": "Kwafa haɗi",
  "qr.copied": "An kwafa haɗi.",
  "qr.making": "Ana yin QR ɗinka…",
  "qr.sheetCta": "Scan don shiga jeri",
  "qr.fine":
    "Maƙwabci suna scan wannan don ɗaukar lamba, babu app, babu asusu. QR yana nan baƙi da fari a kowane salam, don wayoyin su iya karantawa.",
  "set.noteLabel": "Bayani ga maƙwabci",
  "set.noteHint": "Yana bayyana sama da maɓallin Join a allon jerinka. Na son rai.",
  "set.save": "Ajiye canje-canje",
  "set.saving": "Ana ajiye…",
  "set.saved": "An ajiye.",
  "set.goodToKnow": "Ya kamata ka sani",
  "set.linkBody": "Haɗin ne mai ci gaba, buga QR a yau zai ci gaba ko ka canza sunan kasuwanci.",
  "set.signedInAs": "Ka shiga a matsayin",
  "set.errNote": "Bayani ba za ta wuce harufe 200 ba.",
  "nf.title": "Wannan allon ba ya nan.",
  "nf.body": "Zai iya motsi, ko kuma haɗin ya lalace.",
  "nf.cta": "Je zuwa shafin gida",
};

const ig: Pack = {
  "nav.about": "Banyere",
  "nav.signin": "Banye",
  "nav.setup": "Teebe azụmahịa gị",
  "foot.made": "Lobby, {name} mere ya.",
  "foot.mit": "Mepere eme n'okpuru lasisi MIT.",
  "lang.title": "Họrọ asụsụ gị",
  "lang.sub": "Ị nwere ike ịgbanwe ya n'azụ, site na akara dị n'elu n'akụkpụtụ.",
  "lang.change": "Gbanwe asụsụ",
  "lang.done": "E zugwala",
  "common.loading": "Na-ebu…",
  "common.retry": "Gbalịa ọzọ",
  "hero.eyebrow": "Ntụrụndụ maka ahịa, ụlọ ọwụwa na salon",
  "hero.h1a": "Nweta nọmba.",
  "hero.h1b": "Chere ebe ọ bụla.",
  "hero.lede":
    "QR otu maka azụmahịa gị. Ndị ahịa ga-escan, were nọmba, wee hụ ebe ha n'otu ntụrụndụ. Mgbe oge ha rutere, ekwentị ha ga-akwusị ha.",
  "hero.fine":
    "Enweghị app maka ndị ahịa, enweghị akara maka ha. Mepere eme, na-arụọrụ n'seva gị.",
  "demo.nowServing": "Na-ese ugbu a",
  "demo.yourNumber": "Nọmba gị",
  "how.title": "Ka ọ na-eme",
  "how.t1": "Mepụta QR gị",
  "how.d1": "Nọmba mgbanwe maka ụzọ ma ọ bụ kanta gị.",
  "how.t2": "Ndị ahịa na-eweta nọmba",
  "how.d2": "Ha na-esca, ha na-emetụ aha ha chọrọ, enweghị ihe ị banye.",
  "how.t3": "Pịa Call next",
  "how.d3": "Ntụrụndụ na-aga, mgbasaso ha na-emezigharị onwe ya.",
  "see.title": "Ihe ndị ahịa gị na-ahụ",
  "see.copy":
    "Mgbasaso otu, azịza otu oge niile. Ọ na-arụọrụ na ekwentị ọ bụla, ma mgbe ha ekpọtula nọmba ha ọ na-agbanwe na It's your turn.",
  "see.youreNumber": "Nọmba gị bụ",
  "see.peopleAhead": "Ndị dị n'ihu gị",
  "see.when": "Mgbe ọ mere",
  "see.itsTurn": "Oge gị dị!",
  "places.title": "Maka ebe dị na kanta",
  "places.list":
    "Ụlọ aṅụ · Ụlọ ọwụwa · Salon · Ụlọ mkpuchi isi · Ụlọ zozo ọrụ · Bankee · Ụlọ akwụkwọ ozi · Ọrụ gọọmentị",
  "band.title": "Ị mee na-adịghị karịrị nkeji.",
  "auth.welcome": "Nnọọla azụ",
  "auth.setupSub": "Igbara obere oge, ntụrụndụ gị dị njikere.",
  "auth.loginSub": "Banye na ntụrụndụ gị.",
  "auth.bizName": "Aha azụmahịa",
  "auth.yourName": "Aha gị",
  "auth.email": "Email",
  "auth.password": "Okwuntughe",
  "auth.pwHint": "Ọbụna 8 akụkụ.",
  "auth.creating": "Na-eteebe…",
  "auth.signingIn": "Na-abanye…",
  "auth.create": "Mee azụmahịa m",
  "auth.haveAccount": "Ị nwere akara n'ihu?",
  "auth.noAccount": "Akara adịghị ugbu a?",
  "auth.backHome": "Laghachi n'ụlọ",
  "err.bizName": "Tinye aha azụmahịa gị.",
  "err.name": "Tinye aha gị.",
  "err.email": "Tinye email gị.",
  "err.password": "Tinye okwuntughe gị.",
  "err.pwLen": "Okwuntughe ga-adịkarịrị n'akụkụ 8.",
  "cust.opening": "Na-emeghe ntụrụndụ…",
  "cust.wrong": "Ihe emetụla nke ọma.",
  "cust.pausedT": "Ntụrụndụ echereela.",
  "cust.pausedB": "Azụmahịa a anaghị eweta nọmba ugbu a, biko gbanwee n'oge ọzọ.",
  "cust.nobody": "Onweghị ihe ha na-ese ugbu a",
  "cust.noOneWaiting": "onweghị na-echere",
  "cust.waitingN": "{n} na-echere",
  "cust.joinT": "Jikọtara na ntụrụndụ",
  "cust.nameLabel": "Aha gị (nwere ikike)",
  "cust.joinBusy": "Na-aweta nọmba gị…",
  "cust.joinReassure": "Enweghị ihe ị banye, enweghị akara, nọmba otu.",
  "cust.youreNumber": "Nọmba gị bụ",
  "cust.youreNext": "Ị bụ n'ihu",
  "cust.oneAhead": "Onye otu dị n'ihu gị",
  "cust.nAhead": "Ndị {n} dị n'ihu gị",
  "cust.peopleWaiting": "Ndị na-echere",
  "cust.reassure": "Mgbasaso a na-emezigharị onwe ya, hapụ ya ka e meghe.",
  "cust.leave": "Wepụ na ntụrụndụ",
  "cust.leaveConfirm": "Wepụ na ntụrụndụ?Ị ga-ebufe nọmba gị.",
  "cust.turnT": "Oge gị dị",
  "cust.turnB": "Biko gaa n'ikpe.",
  "cust.imHere": "Anọ m ebe a",
  "cust.sending": "Na-ezigarị…",
  "cust.confirmed": "Daalụ, anyị kwuru na gị njikere.",
  "cust.done": "E zugwala",
  "cust.servedBody": "Daalụ ka i chere.",
  "cust.skippedBody": "Ha kwụsịrị gị. Ọ bụrụ na ị nọ ebe a, nweta nọmba ọzọ.",
  "cust.noShowBody": "Nọmba a kwụsịrị. Ọ bụrụ na ị nọ ebe a, nweta nọmba ọzọ.",
  "cust.joinAgain": "Jikọtara ọzọ",
  "cust.poweredBy": "Site na",
  "dash.navQueue": "Ntụrụndụ",
  "dash.navQr": "QR",
  "dash.navSettings": "Ntọala",
  "dash.signOut": "Pụpụta",
  "dash.opening": "Na-emeghe ntụrụndụ gị…",
  "dash.pausedB": "Ndị ahịa enweghị ike iweta nọmba ugbu a.",
  "dash.nobodyCounter": "Onweghị na kanta",
  "dash.noNameGiven": "Aha adịghị",
  "dash.confirmedHere": "osiri sị na ọ nọ ebe a",
  "dash.notConfirmed": "ọ akụrịghị",
  "dash.callNext": "Kpọọ n'ihu",
  "dash.calling": "Na-ekpọọ…",
  "dash.noWaitingHint": "Onweghị na-echere ugbu a.",
  "dash.pause": "Kwụsị ntụrụndụ",
  "dash.resume": "Malite ntụrụndụ ọzọ",
  "dash.atCounter": "Na kanta",
  "dash.waitingTitle": "Na-echere",
  "dash.noName": "Aha adịghị",
  "dash.stWait": "Na-echere",
  "dash.stCalled": "Akpọrọ",
  "dash.stServed": "E ezighị",
  "dash.stSkipped": "E kwụsịrị",
  "dash.stNoShow": "O zoghị",
  "dash.firstRun": "Onweghị ebughịla. Ihe atụ atụ nke atọ ga-emeghe ntụrụndụ gị:",
  "dash.step1": "Nweta QR gị. Mepụta ya, tinye ya n'akụkpụtụ nso n'ụzọ.",
  "dash.step1link": "Meghe QR m →",
  "dash.step2": "Ndị ahịa na-eweta nọmba. Ha na-esca, ha na-edekwa aha, ha na-abịa.",
  "dash.step3": "Pịa Call next. Ekwentị ha ga-emeghari ugbu ahụ.",
  "dash.emptyWaiting": "Onweghị na-echere. Nọmba ọhụrụ ga-ahụ n'ebe a mgbe ndị bịa na ndá.",
  "dash.nextUp": "N'ihu",
  "dash.finished": "E zugwala",
  "dash.counts": "{s} e ezighị, {k} e kwụsịrị, {n} o zoghị",
  "dash.markServed": "Kara dị ka e ezighị",
  "dash.skip": "Gafee",
  "qr.intro":
    "Mepụta a tinye ya n'ụzọ ma ọ bụ na kanta. Ngwalangwalu agaghị agbanwe, QR i mepere taa ga-adịgide adịgide.",
  "qr.linkLabel": "Ngwalangwalu ntụrụndụ gị",
  "qr.download": "Budata PNG",
  "qr.print": "Mepụta",
  "qr.copy": "Kopụtaghị",
  "qr.copied": "E kopụtara ngwalangwalu.",
  "qr.making": "Na-emepụta QR gị…",
  "qr.sheetCta": "Escan i jikọta",
  "qr.fine":
    "Ndị ahịa na-esca iwere nọmba, enweghị app, enweghị akara. QR nọ na-acha ojii na ojii na nhazi ọ bụla ka ekwentị ga-agụ ya.",
  "set.noteLabel": "Nzọrọ ndị ahịa",
  "set.noteHint": "A na-ahụ ya n'elu ma bọtụn Join na mgbasaso ntụrụndụ gị. Nwere ikike.",
  "set.save": "Chekwaa mgbanwe",
  "set.saving": "Na-echekwa…",
  "set.saved": "E chekwara.",
  "set.goodToKnow": "Ihe kwesịrị ịmata",
  "set.linkBody": "Ọ bụ mgbanwe, QR i mepere ga-adịgide ọ bụrụ na ị gbanwere aha azụmahịa.",
  "set.signedInAs": "I banyere dịka",
  "set.errNote": "Nzọrọ gị ga-adịrị ala 200.",
  "nf.title": "Mgbasaso a adịghị.",
  "nf.body": "Ọ tụfara, ma ọ bụ ngwalangwalu gbasara.",
  "nf.cta": "Gaa n'isi mmemme",
};

const sw: Pack = {
  "nav.about": "Kuhusu",
  "nav.signin": "Ingia",
  "nav.setup": "Sanzili biashara yako",
  "foot.made": "Lobby, imetengenezwa na {name}.",
  "foot.mit": "Chanzo wazi chini ya leseni ya MIT.",
  "lang.title": "Chagua lugha yako",
  "lang.sub": "Unaweza kubadilisha baadaye kwa bendera kwenye kona ya juu.",
  "lang.change": "Badilisha lugha",
  "lang.done": "Imekamilika",
  "common.loading": "Inapakia…",
  "common.retry": "Jaribu tena",
  "hero.eyebrow": "Foleni kwa maduka, kliniki na saluni",
  "hero.h1a": "Chukua namba.",
  "hero.h1b": "Subiri popote.",
  "hero.lede":
    "Msamba mmoja QR kwa biashara yako. Wateja hupiga picha na kuchukua namba, kisha kuona mahali pao kwenye foleni. Wakati wao umefika, simu yao huwaambia.",
  "hero.fine":
    "Hakuna programu kwa wateja, hakuna akaunti. Chanzo wazi na hufanya kazi kwenye seva yako.",
  "demo.nowServing": "Inahudumia sasa",
  "demo.yourNumber": "Namba yako",
  "how.title": "Jinsi inavyofanya kazi",
  "how.t1": "Chapisha QR yako",
  "how.d1": "Namba moja ya kudumu kwa mlango au kaunta yako.",
  "how.t2": "Wateja huchukua namba",
  "how.d2": "Hupiga picha, huongeza jina kama wanavyotaka, hakuna kusakinisha.",
  "how.t3": "Bonyeza Call next",
  "how.d3": "Foleni husogeza, skrini yao hujiwasilisha peke yake.",
  "see.title": "Wateja wako wanaona nini",
  "see.copy":
    "Skrini moja yenye majibu yale yale kila wakati. Hufanya kazi kwenye kivutio chochote, na wakati wakipiga namba yao hubadilika kuwa It's your turn.",
  "see.youreNumber": "Namba yako ni",
  "see.peopleAhead": "Watu mbele yako",
  "see.when": "Wakati kinapotokea",
  "see.itsTurn": "Ni zamu yako!",
  "places.title": "Kwa maeneo yenye kaunta",
  "places.list":
    "Maduka ya dawa · Kliniki · Saluni · Kinyozi · Karakana · Benki · Ofisi za posta · Ofisi za serikali",
  "band.title": "Usanidi huchukua takriban dakika moja.",
  "auth.welcome": "Karibu tena",
  "auth.setupSub": "Dakika chache za kuandika, foleni yako iko tayari.",
  "auth.loginSub": "Ingia kwenye foleni yako.",
  "auth.bizName": "Jina la biashara",
  "auth.yourName": "Jina lako",
  "auth.email": "Barua pepe",
  "auth.password": "Nenosiri",
  "auth.pwHint": "Herufi 8 au zaidi.",
  "auth.creating": "Inasanzili…",
  "auth.signingIn": "Inaingia…",
  "auth.create": "Tengeneza biashara yangu",
  "auth.haveAccount": "Tayari una akaunti?",
  "auth.noAccount": "Bado huna akaunti?",
  "auth.backHome": "Rudi nyumbani",
  "err.bizName": "Weka jina la biashara yako.",
  "err.name": "Weka jina lako.",
  "err.email": "Weka barua pepe yako.",
  "err.password": "Weka nenosiri lako.",
  "err.pwLen": "Nenosiri lazima liwe na herufi 8.",
  "cust.opening": "Inafungua foleni…",
  "cust.wrong": "Kuna kitu kimeenda vibaya.",
  "cust.pausedT": "Foleni imesimama.",
  "cust.pausedB": "Biashara hii haichukui namba sasa, tafadhali angalia tena baadaye.",
  "cust.nobody": "Hakuna anayehudumia sasa",
  "cust.noOneWaiting": "hakuna anayesubiri",
  "cust.waitingN": "{n} wanasubiri",
  "cust.joinT": "Jiunge na foleni",
  "cust.nameLabel": "Jina lako (hiari)",
  "cust.joinBusy": "Inachukua namba yako…",
  "cust.joinReassure": "Hakuna programu ya kusakinisha, hakuna akaunti, namba tu.",
  "cust.youreNumber": "Namba yako ni",
  "cust.youreNext": "Ni zamu yako",
  "cust.oneAhead": "Mtu mmoja mbele yako",
  "cust.nAhead": "Watu {n} mbele yako",
  "cust.peopleWaiting": "Wanaosubiri",
  "cust.reassure": "Ukurasa huu hujiwasilisha peke yake, uiwe wazi.",
  "cust.leave": "Toka kwenye foleni",
  "cust.leaveConfirm": "Toka kwenye foleni? Utapoteza namba yako.",
  "cust.turnT": "Ni zamu yako",
  "cust.turnB": "Tafadhali nenda kwenye kaunta.",
  "cust.imHere": "Nipo hapa",
  "cust.sending": "Inatuma…",
  "cust.confirmed": "Asante, tumewaambia wako tayari.",
  "cust.done": "Imekamilika",
  "cust.servedBody": "Asante kusubiri.",
  "cust.skippedBody": "Umepishwa. Ukipo hapa, chukua namba nyingine.",
  "cust.noShowBody": "Namba hii imefungwa. Ukipo hapa, chukua namba nyingine.",
  "cust.joinAgain": "Jiunge tena",
  "cust.poweredBy": "Imeendeshwa na",
  "dash.navQueue": "Foleni",
  "dash.navQr": "QR",
  "dash.navSettings": "Mipangilio",
  "dash.signOut": "Toka",
  "dash.opening": "Inafungua foleni yako…",
  "dash.pausedB": "Wateja hawachukui namba sasa.",
  "dash.nobodyCounter": "Hakupo kwenye kaunta",
  "dash.noNameGiven": "Hakuna jina",
  "dash.confirmedHere": "amesema yuko hapa",
  "dash.notConfirmed": "hajathibitisha",
  "dash.callNext": "Ita ifuatayo",
  "dash.calling": "Inaita…",
  "dash.noWaitingHint": "Hakuna anayesubiri sasa.",
  "dash.pause": "Simamisha foleni",
  "dash.resume": "Endeleza foleni",
  "dash.atCounter": "Kwenye kaunta",
  "dash.waitingTitle": "Wanasubiri",
  "dash.noName": "Hakuna jina",
  "dash.stWait": "Wanasubiri",
  "dash.stCalled": "Inahudumia",
  "dash.stServed": "Imehudumiwa",
  "dash.stSkipped": "Imepishwa",
  "dash.stNoShow": "Hawapo",
  "dash.firstRun": "Hakuna bado. Hatua tatu fupi zitafungua foleni yako:",
  "dash.step1": "Pata QR yako. Chapisha, au iweke kwenye skrini karibu na mlango.",
  "dash.step1link": "Fungua QR yangu →",
  "dash.step2": "Wateja huchukua namba. Hupiga picha, kuandika jina, wanaingia.",
  "dash.step3": "Bonyeza Call next. Simu zao hubadilika wakati huo huo.",
  "dash.emptyWaiting": "Hakuna anayesubiri. Namba mpya zitaonekana hapa watu wanapojiunga.",
  "dash.nextUp": "Ifuatayo",
  "dash.finished": "Imekamilika",
  "dash.counts": "{s} wahudumiwa, {k} wamepishwa, {n} hawapo",
  "dash.markServed": "Weka kama imehudumiwa",
  "dash.skip": "Ruka",
  "qr.intro":
    "Chapisha hii uweke kwenye mlango au kaunta. Kiungo hiki hubadiliki, msamba ukipachika leo utaendelea kufanya kazi.",
  "qr.linkLabel": "Kiungo chako cha foleni",
  "qr.download": "Pakua PNG",
  "qr.print": "Chapisha",
  "qr.copy": "Nakili kiungo",
  "qr.copied": "Kiungo kimenakiliwa.",
  "qr.making": "Inatengeneza QR yako…",
  "qr.sheetCta": "Piga picha ili kujiunga",
  "qr.fine":
    "Wateja hupiga picha hii kuchukua namba, hakuna programu, hakuna akaunti. QR hubaki nyeupe na nyeusi kwenye mandhari yote ili simu ziweze kuisoma.",
  "set.noteLabel": "Maelezo kwa wateja",
  "set.noteHint": "Huonekana juu ya kitufe cha Join kwenye ukurasa wako. Hiari.",
  "set.save": "Hifadhi mabadiliko",
  "set.saving": "Inahifadhi…",
  "set.saved": "Imehifadhiwa.",
  "set.goodToKnow": "Ni vizuri kujua",
  "set.linkBody": "Ni ya kudumu, msamba ukipachika utaendelea kufanya kazi hata kubadilisha jina la biashara.",
  "set.signedInAs": "Umeingia kama",
  "set.errNote": "Maelezo yako yasipaze herufi 200.",
  "nf.title": "Ukurasa huu haupo.",
  "nf.body": "Umehamishika, au kiungo kimeandikwa vibaya.",
  "nf.cta": "Nenda kwenye ukurasa wa mwanzo",
};

export const africa: Lang[] = [
  { code: "pcm", label: "Nigerian Pidgin English", native: "Naijá Pidgin", flag: "ng", dict: pcm },
  { code: "yo", label: "Yoruba", native: "Yorùbá", flag: "ng", dict: yo },
  { code: "ha", label: "Hausa", native: "Hausa", flag: "ng", dict: ha },
  { code: "ig", label: "Igbo", native: "Igbo", flag: "ng", dict: ig },
  { code: "sw", label: "Swahili", native: "Kiswahili", flag: "ke", dict: sw },
];
