import type { StringKey } from "./en";
import type { Lang } from "./types";

type Pack = Partial<Record<StringKey, string>>;

const pcm: Pack = {
  "nav.about": "About",
  "nav.signin": "Sign in",
  "nav.setup": "Set up your shop",
  "foot.made": "Lobby, na {name} build am.",
  "foot.mit": "Open source wey dey under MIT licence.",
  "lang.title": "Choose your language",
  "lang.sub": "You fit change am later with the flag wey dey for top corner.",
  "lang.change": "Change language",
  "lang.done": "Done",
  "common.loading": "Dey load…",
  "common.retry": "Try again",
  "hero.eyebrow": "Queue for shop, clinic and salon",
  "hero.h1a": "Take your number.",
  "hero.h1b": "Wait for anywhere.",
  "hero.lede":
    "One QR code for your business. Customer go scan am, take number, and see where e dey for line. When e reach im turn, im phone go tell am.",
  "hero.fine":
    "No app for customer, no account for dem. Open source, e dey run for your own server.",
  "demo.nowServing": "We dey serve",
  "demo.yourNumber": "Your number",
  "how.title": "How e dey work",
  "how.t1": "Print your QR code",
  "how.d1": "One permanent code for your door or counter.",
  "how.t2": "Customer take number",
  "how.d2": "Dem go scan, add name if dem want, nothing to install.",
  "how.t3": "Press Call next",
  "how.d3": "The line go move and im screen go update by itself.",
  "see.title": "Wetin your customer go see",
  "see.copy":
    "One screen, same answer every time. E dey work for any phone browser, and when you call im number e go change to It's your turn.",
  "see.youreNumber": "Your number be",
  "see.peopleAhead": "People wey dey before you",
  "see.when": "When e happen",
  "see.itsTurn": "Na your turn!",
  "places.title": "Made for places wey get counter",
  "places.list": "Pharmacy · Clinic · Salon · Barbing shop · Repair shop · Bank · Post office · Government office",
  "band.title": "Setup take about one minute.",
  "auth.welcome": "Welcome back",
  "auth.setupSub": "Small typing, your queue don ready.",
  "auth.loginSub": "Sign in go your queue.",
  "auth.bizName": "Shop name",
  "auth.yourName": "Your name",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.pwHint": "8 characters at least.",
  "auth.creating": "We dey set am up…",
  "auth.signingIn": "We dey sign you in…",
  "auth.create": "Create my shop",
  "auth.haveAccount": "You don get account?",
  "auth.noAccount": "You never get account yet?",
  "auth.backHome": "Go back home",
  "err.bizName": "Type your business name.",
  "err.name": "Type your name.",
  "err.email": "Type your email.",
  "err.password": "Type your password.",
  "err.pwLen": "Password must follow at least 8 characters.",
  "cust.opening": "E dey open the queue…",
  "cust.wrong": "Something don go wrong.",
  "cust.pausedT": "Queue don pause.",
  "cust.pausedB": "This business no dey take number now, abeg check back soon.",
  "cust.nobody": "Nobody dey serve yet",
  "cust.noOneWaiting": "nobody dey wait",
  "cust.waitingN": "{n} dey wait",
  "cust.joinT": "Join di queue",
  "cust.nameLabel": "Your name (optional)",
  "cust.joinBusy": "E dey take your number…",
  "cust.joinReassure": "No app to install, no account, just number.",
  "cust.youreNumber": "Your number be",
  "cust.youreNext": "You next",
  "cust.oneAhead": "1 person dey before you",
  "cust.nAhead": "{n} people dey before you",
  "cust.peopleWaiting": "People wey dey wait",
  "cust.reassure": "This page go update by itself, keep am open.",
  "cust.leave": "Comot for queue",
  "cust.leaveConfirm": "Comot for queue? You go lose your number.",
  "cust.turnT": "Na your turn",
  "cust.turnB": "Abeg come the counter.",
  "cust.imHere": "I dey here",
  "cust.sending": "E dey send…",
  "cust.confirmed": "Thank you, we don tell dem say you ready.",
  "cust.done": "All done",
  "cust.servedBody": "Thank you for wait.",
  "cust.skippedBody": "Dem skip you. If you still dey here, take another number.",
  "cust.noShowBody": "We close this number. If you still dey here, take another number.",
  "cust.joinAgain": "Join again",
  "cust.poweredBy": "Powered by",
  "dash.navQueue": "Queue",
  "dash.navQr": "QR code",
  "dash.navSettings": "Setting",
  "dash.signOut": "Sign out",
  "dash.opening": "E dey open your queue…",
  "dash.pausedB": "Customer no fit take number now.",
  "dash.nobodyCounter": "Nobody dey the counter",
  "dash.noNameGiven": "No name",
  "dash.confirmedHere": "don talk say e dey here",
  "dash.notConfirmed": "never confirm",
  "dash.callNext": "Call next one",
  "dash.calling": "E dey call…",
  "dash.noWaitingHint": "Nobody dey wait now.",
  "dash.pause": "Pause queue",
  "dash.resume": "Resume queue",
  "dash.atCounter": "For the counter",
  "dash.waitingTitle": "Waiting",
  "dash.noName": "No name",
  "dash.stWait": "Waiting",
  "dash.stCalled": "Dem don call",
  "dash.stServed": "Served",
  "dash.stSkipped": "Skipped",
  "dash.stNoShow": "No show",
  "dash.firstRun": "Nobody don enter yet. Three quick steps make your queue start:",
  "dash.step1": "Get your QR code. Print am, or put am for screen for door.",
  "dash.step1link": "Open my QR code →",
  "dash.step2": "Customer dey take number. Dem go scan, type name small, and e don do.",
  "dash.step3": "Press Call next. Im phone go update that very moment.",
  "dash.emptyWaiting": "Nobody dey wait. New numbers go show here when people join.",
  "dash.nextUp": "Next up",
  "dash.finished": "Finished",
  "dash.counts": "{s} don serve, {k} don skip, {n} no show",
  "dash.markServed": "Mark say don serve",
  "dash.skip": "Skip",
  "qr.intro":
    "Print this one put am for door or counter. The link no dey change, so code wey you print today go still dey work.",
  "qr.linkLabel": "Your queue link",
  "qr.download": "Download PNG",
  "qr.print": "Print",
  "qr.copy": "Copy link",
  "qr.copied": "Link don copy.",
  "qr.making": "E dey make your QR code…",
  "qr.sheetCta": "Scan am join di queue",
  "qr.fine":
    "Customer dey scan this to take number, no app, no account. The QR dey remain black and white for every theme so phone fit read am.",
  "set.noteLabel": "Note for customer",
  "set.noteHint": "E go show above the Join button for your queue page. Optional.",
  "set.save": "Save changes",
  "set.saving": "E dey save…",
  "set.saved": "Don save.",
  "set.goodToKnow": "Good to know",
  "set.linkBody": "The link permanent, so printed QR go dey work even if you change business name.",
  "set.signedInAs": "You dey sign in as",
  "set.errNote": "Your note suppose 200 characters or less.",
  "nf.title": "This page no exist.",
  "nf.body": "E fit don move, or the link no correct.",
  "nf.cta": "Go back home page",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "Live demo",
  "common.live": "Live",
  "common.reconnecting": "Dey connect again…",
  "common.offline": "You don dey offline. Dis page go update itself.",
  "common.optional": "optional",
  "common.cancel": "Cancel",
  "common.remove": "Remove",
  "common.add": "Add",
  "common.save": "Save",
  "common.saved": "Don save.",
  "common.minutes": "{n} min",
  "common.branch": "Place",
  "common.allBranches": "All di places",
  "common.back": "Back",
  "band.body": "Start from shop type — restaurant, clinic, salon, repair — den change di names. Add another place when you open new one.",
  "band.try": "Try live demo",
  "demo.title": "See how e dey work",
  "demo.sub": "Practice shop wey you fit press button. Join as customer, call number as staff, watch the TV screen. Nothing here dey real.",
  "demo.paneCustomer": "Customer phone",
  "demo.paneStaff": "Staff phone",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "TV screen",
  "demo.joinName": "Name (optional)",
  "demo.join": "Collect number",
  "demo.reset": "Reset di demo",
  "demo.callNext": "Call next one",
  "demo.serve": "Don finish",
  "demo.skip": "Skip am",
  "demo.waitingList": "Waiting",
  "demo.hint": "Try call one number den watch all four panel dey update together.",
  "auth.shopType": "Wetin kain shop be?",
  "auth.shopTypeHint": "We go create di queue and counter. You fit change any name after.",
  "auth.branchName": "First place",
  "auth.inviteTitle": "Dem don invite you",
  "auth.inviteBody": "{business} don invite you manage di queue as {role}.",
  "auth.joinTeam": "Join di team",
  "auth.inviteBad": "This invitation don expire. Ask your manager for new one.",
  "cust.phoneLabel": "Phone (optional)",
  "cust.estWait": "E go take {n} min wait",
  "cust.pickQueue": "Wetin you need?",
  "cust.pickBranch": "Which place?",
  "cust.pickQueueHint": "Pick queue to collect number.",
  "cust.held": "Dey wait",
  "cust.heldBody": "Staff go call you shortly.",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "Queue dem",
  "dash.navTeam": "Team",
  "dash.navReports": "History",
  "dash.holdTitle": "Dey hold",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "E don comot",
  "dash.hold": "Hold am",
  "dash.release": "Put am back for queue",
  "dash.recall": "Call am again",
  "dash.cancel": "Remove from queue",
  "dash.move": "Move am",
  "dash.moveTo": "Move go another queue",
  "dash.call": "Call am",
  "dash.addWalkIn": "Add customer",
  "dash.addWalkInBody": "For phone booking and people wey dey front you.",
  "dash.noteLabel": "Note (optional)",
  "dash.counterLabel": "Counter",
  "dash.anyCounter": "Any counter",
  "dash.avgWait": "Average wait {n} min",
  "dash.peopleWaiting": "{n} dey wait",
  "dash.tvLink": "Open TV screen",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "Dis branch never get queue yet.",
  "dash.pickQueue": "Pick queue",
  "dash.roleTag": "Your role: {role}",
  "dash.noPermission": "Your role no fit do am.",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "Queue for this code",
  "qr.displayLink": "TV screen link",
  "sq.title": "Queue and counter",
  "sq.sub": "Each queue get e own number and e own line.",
  "sq.locations": "Places",
  "sq.addLocation": "Add place",
  "sq.locationName": "Place name",
  "sq.address": "Address (optional)",
  "sq.phone": "Phone (optional)",
  "sq.noLocations": "No place yet.",
  "sq.queues": "Queue dem",
  "sq.addQueue": "Add queue",
  "sq.queueName": "Queue name",
  "sq.prefix": "Number letters",
  "sq.prefixHint": "Up to two letter before number, like A12.",
  "sq.description": "Wetin be this queue for? (optional)",
  "sq.avgTime": "Typical time (minutes)",
  "sq.counters": "Counter dem",
  "sq.counterName": "Counter name",
  "sq.addCounter": "Add counter",
  "sq.paused": "Don pause",
  "sq.open": "Open",
  "sq.closed": "Closed",
  "sq.noQueues": "No queue for this place yet.",
  "sq.deleteQueue": "Remove this queue",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "Start from shop type",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "Customer no fit collect number for this queue while e dey pause.",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "Your team",
  "team.sub": "Invite the people wey dey work for counter, den choose wetin each person fit do.",
  "team.invite": "Invite person",
  "team.invited": "Invitation don send",
  "team.inviteEmail": "Dem email",
  "team.inviteRole": "Wetin dem fit do",
  "team.pending": "Dey wait to join",
  "team.noPending": "No invitation dey wait.",
  "team.revoke": "Cancel invitation",
  "team.role": "Role",
  "team.roleOwner": "Owner",
  "team.roleManager": "Manager",
  "team.roleStaff": "Staff",
  "team.roleViewer": "Read only",
  "team.remove": "Comot am for team",
  "team.lock": "Sign out everywhere",
  "team.unlock": "Allow sign in",
  "team.allBranches": "All di places",
  "team.oneBranch": "One location",
  "team.pickBranch": "Place",
  "team.noTeam": "You be di only one for now.",
  "team.linkCopied": "Invitation link don copy. Send am give dem.",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "How today and last week really take.",
  "rep.joined": "Number wey dem collect",
  "rep.served": "Customer wey dem serve",
  "rep.avgWait": "Average wait",
  "rep.avgService": "Average service",
  "rep.peak": "Peak hour",
  "rep.abandoned": "Comot without service",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "Last 7 days",
  "rep.days30": "Last 30 days",
  "rep.days90": "Last 90 days",
  "rep.byDay": "Each day",
  "rep.byHour": "Busy hours",
  "rep.byQueue": "Each queue",
  "rep.waited": "don wait {n} min",
  "rep.servedIn": "serve for {n} min",
  "rep.history": "Everybody wey come",
  "rep.noHistory": "Nobody don pass through this queue for this period.",
  "rep.audit": "Changes wey your team don make",
  "rep.noAudit": "No change don record yet.",
  "rep.noReports": "Your role no fit see report.",
  "set.brand": "Look and feel",
  "set.brandHint": "Your colour and logo dey show for customer page and TV screen.",
  "set.mainColour": "Main colour",
  "set.accentColour": "Highlight colour",
  "set.logo": "Logo",
  "set.logoHint": "Paste web link or upload picture. Small one dey better.",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "Remove logo",
  "set.security": "Your password",
  "set.currentPassword": "Current password",
  "set.newPassword": "New password",
  "set.changePassword": "Change password",
  "set.passwordChanged": "Password don change. Other device don sign out.",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "Dey call now",
  "disp.waiting": "Dey wait",
  "disp.others": "Other queue dem",
  "disp.fullscreen": "Full screen",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "Dey wait for first number",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "Waiting time wey we think",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "Live by default",
  "hero.statPhone": "E dey work for any phone",
  "feat.title": "Everything wey queue need, nothing more",
  "feat.copy": "Lobby just dey do one thing well. Every screen you see down there don dey part of di product today.",
  "feat.qr.t": "One code, e dey current always",
  "feat.qr.d": "Permanent QR code for each place. Print am once — if you change shop name e go still work.",
  "feat.multi.t": "Many queue, one screen",
  "feat.multi.d": "Split di counter go services — talk, pickup, return — with di own number and counter.",
  "feat.team.t": "Roles wey fit shop",
  "feat.team.d": "Invite staff with link, pin am to branch, den keep di keys for owner side.",
  "feat.brand.t": "Carry your shop look",
  "feat.brand.d": "Your colour, logo and note dey show for every customer phone and di TV.",
  "feat.reports.t": "Facts for quiet evening",
  "feat.reports.d": "Wait time, busy hours and full history — next week rota no be guess again.",
  "feat.pause.t": "Close without wahala",
  "feat.pause.d": "Pause queue with one tap. Door sign go show am, and nobody go collect number go closed counter.",
  "flow.title": "From door go done for four steps",
  "flow.s1.t": "Customer dey join queue",
  "flow.s1.d": "Dem scan di code, pick service, den collect number. No app, no account.",
  "flow.s2.t": "Staff dey call next person",
  "flow.s2.d": "One big button dey serve next person, e dey keep di queue fair.",
  "flow.s3.t": "Everybody dey see their status",
  "flow.s3.d": "Every phone dey show position, how many people dey front, and wait time — live, no refresh.",
  "flow.s4.t": "Di display dey keep order",
  "flow.s4.d": "TV for waiting area dey show who dem dey serve and who come next.",
  "dispsect.title": "Display wey fit your waiting room",
  "dispsect.copy": "Open di display for any TV browser. Big number, next five, and other queue — you go see them at once. E dey update the moment staff do am.",
  "dispsect.cta": "See live display",
  "dash.servingCounters": "{n} dey serve",
};

const yo: Pack = {
  "nav.about": "Nípa",
  "nav.signin": "Wọ inú",
  "nav.setup": "Àtọ́ṣọ́ ilé-iṣẹ́ rẹ",
  "foot.made": "Lobby, ó dá si i ní ọwọ́ {name}.",
  "foot.mit": "Aṣẹ òwọ̀ ní òfin MIT.",
  "lang.title": "Yan èdè rẹ",
  "lang.sub": "O lè yí i padà lẹ́yìn, pẹ̀lú àmì ìfáàrá tó wà ní apá òkè.",
  "lang.change": "Yí èdè padà",
  "lang.done": "Parí",
  "common.loading": "Ǹjẹ́rísí…",
  "common.retry": "Gbìyànjú mọ́",
  "hero.eyebrow": "Ọ̀rọ̀̀jọ́ fún àwọn ilé-iṣẹ́, ọdẹ̀gàn àti àwọn ilé ìwòsàn",
  "hero.h1a": "Gba nọ́ńbà.",
  "hero.h1b": "Dúró níbì kankan.",
  "hero.lede":
    "QR kan fún ilé-iṣẹ́ rẹ. Àwọn oníbàárà yóò fì wò, gba nọ́ńbà, ó sì rí ibi wọn nínú ọ̀rọ̀̀jọ́. Nígbà tí ó bá dé, fóònù rẹ̀ yóò sọ fún un.",
  "hero.fine": "Kò sí ẹ̀rọ̀ ọ̀tọ̀ fún wọn, kò sí àkọ̀lẹ̀fọ̀ọ̀mù. Aṣẹ òwọ̀, ó sì ń ṣiṣẹ́ ní sáfàrì rẹ.",
  "demo.nowServing": "Ó ń ẹ̀ sí i",
  "demo.yourNumber": "Nọ́ńbà rẹ",
  "how.title": "Bí ó ṣe ń ṣiṣẹ́",
  "how.t1": "Tì QR code rẹ sókè",
  "how.d1": "Àmì kan pàtó fún ọ̀nà tàbí kọ́ntá rẹ.",
  "how.t2": "Àwọn oníbàárà gbà nọ́ńbà",
  "how.d2": "Wọ́n yóò fòótù wò, fi orúkọ tí wọ́n fẹ́ kún un, kò sí ohun tí wọ́n fẹ́ dáwọ́lẹ̀.",
  "how.t3": "Tẹ Call next lọ́wọ́",
  "how.d3": "Ọ̀rọ̀̀jọ́ yóò lọ, ìfáhàn wọn yóò sì ṣeìmúdòjú ìwọ̀n fún wọn.",
  "see.title": "Ohun tí àwọn oníbàárà rẹ wò",
  "see.copy":
    "Ìfáhàn kan pàtó ni ó máa ń jà nígbà gbogbo. Ó ń ṣiṣẹ́ ní kọ̀lọ̀mí kọ̀lọ̀mí kọ̀, tí wọ́n bá pè nọ́ńbà wọn, yóò yí padà sí It's your turn.",
  "see.youreNumber": "Nọ́ńbà rẹ ni",
  "see.peopleAhead": "Àwọn ènìyàn tó wà níwájú rẹ",
  "see.when": "Nígbà tí ó bá ṣẹlẹ̀",
  "see.itsTurn": "Ìgbà rẹ ni!",
  "places.title": "Fún ibi tí ó ní kọ́ntá",
  "places.list":
    "Ilé òògùn · Ilé ìwòsàn · Ilé ìdọ̀gbọ̀n irun · Ilé ìtúnàẹ̀rọ · Banki · Ilé ìfímúìwé · Iṣẹ́ ìjọba",
  "band.title": "Àtọ́ṣọ́ yóò pọ̀ mìíràn.",
  "auth.welcome": "Kaabo sí i",
  "auth.setupSub": "Kò pọ̀ ìtẹ̀wọ́gbà, ọ̀rọ̀̀jọ́ rẹ tiṣetán.",
  "auth.loginSub": "Wọ inú ọ̀rọ̀̀jọ́ rẹ.",
  "auth.bizName": "Orúkọ ilé-iṣẹ́",
  "auth.yourName": "Orúkọ rẹ",
  "auth.email": "Ímèélì",
  "auth.password": "Ọ̀rọ̀̀ ìkọ̀kọ̀",
  "auth.pwHint": "Àmì ọ̀tọ̀̀ 8 lọ.",
  "auth.creating": "A ń tọ́ ọ sí i…",
  "auth.signingIn": "A ń wọọ inú…",
  "auth.create": "Ṣàkọsọ ilé-iṣẹ́ mi",
  "auth.haveAccount": "Ǹí àkọ̀lẹ̀fọ̀ọ̀mù tẹ́lẹ̀?",
  "auth.noAccount": "Kò sí àkọ̀lẹ̀fọ̀ọ̀mù báyìí?",
  "auth.backHome": "Padà sí ilé",
  "err.bizName": "Tẹ orúkọ ilé-iṣẹ́ rẹ sí i.",
  "err.name": "Tẹ orúkọ rẹ sí i.",
  "err.email": "Tẹ ímèélì rẹ sí i.",
  "err.password": "Tẹ ọ̀rọ̀̀ ìkọ̀kọ̀ rẹ sí i.",
  "err.pwLen": "Ọ̀rọ̀̀ ìkọ̀kọ̀ gbọdọ̀ ní àmì ọ̀tọ̀̀ 8 lọ.",
  "cust.opening": "A ń ṣí ọ̀rọ̀̀jọ́…",
  "cust.wrong": "Nǹkan kan báṣẹ̀.",
  "cust.pausedT": "Ọ̀rọ̀̀jọ́ dúró.",
  "cust.pausedB": "Ilé-iṣẹ́ yìí kò gba nọ́ńbà báyìí, máa wá àtúnwádìí lẹ́ẹ̀kan.",
  "cust.nobody": "Kò sí ẹni tó wà níbẹ̀ títí di báyìí",
  "cust.noOneWaiting": "kò sí ẹni tó ń dúró",
  "cust.waitingN": "{n} ń dúró",
  "cust.joinT": "Darapọ̀ mọ́ ọ̀rọ̀̀jọ́",
  "cust.nameLabel": "Orúkọ rẹ (a fúnra rẹ)",
  "cust.joinBusy": "A ń gba nọ́ńbà rẹ…",
  "cust.joinReassure": "Kò sí ẹ̀rọ̀ ọ̀tọ̀, kò sí àkọ̀lẹ̀fọ̀ọ̀mù, nọ́ńbà kan ni.",
  "cust.youreNumber": "Nọ́ńbà rẹ ni",
  "cust.youreNext": "O lẹ́yìn náà",
  "cust.oneAhead": "Ènìyàn kan wà níwájú rẹ",
  "cust.nAhead": "Àwọn ènìyàn {n} wà níwájú rẹ",
  "cust.peopleWaiting": "Àwọn tó ń dúró",
  "cust.reassure": "Ìfáhàn yìí yóò fúnra rẹ dí àtúnṣe, fi síbẹ̀.",
  "cust.leave": "Fòpọ̀ sí ọ̀rọ̀̀jọ́",
  "cust.leaveConfirm": "Fòpọ̀ sí ọ̀rọ̀̀jọ́? O yóò sọ̀nà nọ́ńbà rẹ.",
  "cust.turnT": "Ìgbà rẹ ni",
  "cust.turnB": "Èun wá sí kọ́ntá.",
  "cust.imHere": "Mo wà níbẹ̀",
  "cust.sending": "A ń ránṣẹ́…",
  "cust.confirmed": "O ṣé, a ti sọ fún wọn pé oṣetán.",
  "cust.done": "Ti parí",
  "cust.servedBody": "O ṣé tí o dúró.",
  "cust.skippedBody": "Wọ́n fi bẹ́yẹ̀n. Bí o bá wà níbẹ̀, gba nọ́ńbà mìíràn.",
  "cust.noShowBody": "A ti pa nọ́ńbà yìí rẹ. Bí o bá wà níbẹ̀, gba nọ́ńbà mìíràn.",
  "cust.joinAgain": "Darapọ̀ mọ́ lẹ́ẹ̀kan sí i",
  "cust.poweredBy": "Ní iṣẹ́",
  "dash.navQueue": "Ọ̀rọ̀̀jọ́",
  "dash.navQr": "Kọ́dù QR",
  "dash.navSettings": "Àwọn àṣàyàn",
  "dash.signOut": "Jáde",
  "dash.opening": "A ń ṣí ọ̀rọ̀̀jọ́ rẹ…",
  "dash.pausedB": "Àwọn oníbàárà kò lè gba nọ́ńbà báyìí.",
  "dash.nobodyCounter": "Kò sí ẹni ní kọ́ntá",
  "dash.noNameGiven": "Kò sí orúkọ",
  "dash.confirmedHere": "ti sọ pé ó wà níbẹ̀",
  "dash.notConfirmed": "kò tíìṣètọ́",
  "dash.callNext": "Pè tókè tó",
  "dash.calling": "A ń pè…",
  "dash.noWaitingHint": "Kò sí ẹni tó ń dúró báyìí.",
  "dash.pause": "Dá ọ̀rọ̀̀jọ́ dúró",
  "dash.resume": "Tún ọ̀rọ̀̀jọ́ bẹ̀rẹ̀",
  "dash.atCounter": "Ní kọ́ntá",
  "dash.waitingTitle": "Ǹjẹ́rísí",
  "dash.noName": "Kò sí orúkọ",
  "dash.stWait": "Ǹjẹ́rísí",
  "dash.stCalled": "A ti pè",
  "dash.stServed": "Ti fún un ní iṣẹ́",
  "dash.stSkipped": "Fi bẹ́yẹ̀n",
  "dash.stNoShow": "Kò dé",
  "dash.firstRun": "Kò sí ẹni tó wà báyìí. Ìgbésẹ̀ mẹ́ta kéré ni yóò gbé ọ̀rọ̀̀jọ́ rẹ lọ:",
  "dash.step1": "Gba QR code rẹ. Tì i sókè, tàbí fi hàn ní ọ̀nà.",
  "dash.step1link": "Ṣí QR code mi →",
  "dash.step2": "Àwọn oníbàárà gba nọ́ńbà. Wọ́n fòótù wò, kún orúkọ tí wọ́n fẹ́, wọ́n sì darapọ̀.",
  "dash.step3": "Tẹ Call next. Fóònù wọn yóò fúnra wọn dí àtúnṣe nígbà náà.",
  "dash.emptyWaiting": "Kò sí ẹni tó ń dúró. Àwọn nọ́ńbà tuntun yóò hàn níbí tí àwọn ènìyàn bá darapọ̀.",
  "dash.nextUp": "Tókè tó",
  "dash.finished": "Ti parí",
  "dash.counts": "{s} ti fún ní iṣẹ́, {k} fi bẹ́yẹ̀n, {n} kò dé",
  "dash.markServed": "Èlò tó ṣe",
  "dash.skip": "Fòbẹ́yẹ̀n",
  "qr.intro":
    "Tì i sókè, fi hàn ní ọ̀nà tàbí lórí kọ́ntá. Línkì kò ní yí padà, tí a bá tì lónìí yóò ń ṣiṣẹ́.",
  "qr.linkLabel": "Línkì ọ̀rọ̀̀jọ́ rẹ",
  "qr.download": "Gba PNG",
  "qr.print": "Tì i sókè",
  "qr.copy": "Kọpù línkì",
  "qr.copied": "A ti kọpù línkì.",
  "qr.making": "A ń ṣe QR code rẹ…",
  "qr.sheetCta": "Fòótù wò kó o darapọ̀",
  "qr.fine":
    "Àwọn oníbàárà ń fòótù wò èyí láti gba nọ́ńbà, kò sí ẹ̀rọ̀ ọ̀tọ̀, kò sí àkọ̀lẹ̀fọ̀ọ̀mù. QR yóò dúró dí àwùjọ fún gbogbo ìtọ́jọ̀ kí fóònù lè kà á.",
  "set.noteLabel": "Àkọlé fún àwọn oníbàárà",
  "set.noteHint": "Ó máa ń hàn lórí tẹ́mípẹ́ẹ̀tì Join nínú ìfáhàn ọ̀rọ̀̀jọ́ rẹ. A fúnra rẹ ni.",
  "set.save": "Fúnpa àwọn àyípà",
  "set.saving": "A ń fúnpa…",
  "set.saved": "A ti fúnpa.",
  "set.goodToKnow": "Ohun tí o yẹ ká mọ̀",
  "set.linkBody": "Línkì yìí pàtó, tí a bá tì QR code lónìí yóò ń ṣiṣẹ́ kódà bí o bá yí orúkọ padà.",
  "set.signedInAs": "O wà nínu",
  "set.errNote": "Àkọlé rẹ gbọdọ̀ jù àmì ọ̀tọ̀̀ 200 lọ.",
  "nf.title": "Ìfáhàn yìí kò wà.",
  "nf.body": "Ó lè ti kọjá, tàbí línkì kò tọ́.",
  "nf.cta": "Lọ sí ìfáhàn ìbẹ̀rẹ̀",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "Ìtàn ìṣẹlẹ̀",
  "common.live": "Nípyá",
  "common.reconnecting": "Ń sọ̀kan sí i…",
  "common.offline": "Ọ̀yẹ́ ni o wà. Yí ìwé yìí yóò ṣe àtúnṣe fún ara rẹ̀.",
  "common.optional": "optional",
  "common.cancel": "Fagile",
  "common.remove": "Yọ kúrò",
  "common.add": "Fi kun",
  "common.save": "Save",
  "common.saved": "Ti fìyèsí.",
  "common.minutes": "{n} ìṣẹ́jú",
  "common.branch": "Ibùgbé",
  "common.allBranches": "Gbogbo àwọn ibi",
  "common.back": "Back",
  "band.body": "Bẹ̀rẹ̀ pẹ̀lú irú ọ̀wọ̀ — àjọ̀ yọjọ́, ilé ìwòsàn, ẹ̀wà, adánì — sí i àwọn orúkọ. Fi àwọn ibi mìíràn kun nígbà tí o bá tẹ̀ úṣẹ́ tuntun.",
  "band.try": "Wo ìtàn ìṣẹlẹ̀ tó ṣìlẹ̀",
  "demo.title": "Wo bí ó ṣe ń ṣiṣẹ́",
  "demo.sub": "Ìtajà ọjà tí o lè tẹ̀ bọ́tùnù. Darapọ gẹ́gẹ́ bí alábàásì, pè nọ́ńbà gẹ́gẹ́ bí ọmọ iṣẹ́, wo ìtàn TV. Kì í ṣe ohun tó yè níbí.",
  "demo.paneCustomer": "Ọ̀pọ̀lọpọ̀ alábàásì",
  "demo.paneStaff": "Ọ̀pọ̀lọpọ̀ ọmọ iṣẹ́",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "Àpótí TV",
  "demo.joinName": "Orúkọ (àbáyọ́)",
  "demo.join": "Gbà nọ́ńbà",
  "demo.reset": "Tunada ìtàn ìṣẹlẹ̀",
  "demo.callNext": "Pè ẹ̀yàn tó kàn",
  "demo.serve": "Ti parí",
  "demo.skip": "Fi kọjá",
  "demo.waitingList": "Waiting",
  "demo.hint": "Gbìyànjú láti pè ẹ̀wé kan, wò bí àwọn pẹ́lù mẹ́rin bá ń ṣe àtúnṣe pọ̀lọ̀pọ̀lọ̀.",
  "auth.shopType": "Ohun èlò ohun ìṣèlú kíní?",
  "auth.shopTypeHint": "A ó ṣe àwọn ìfà àti àwọn pín. O lè yí orúkọ kọ̀ọ̀kan padà nígbà tí ó bá fẹ́.",
  "auth.branchName": "Ibẹ̀krẹ̀ àkọ́kọ́",
  "auth.inviteTitle": "A pè ọ",
  "auth.inviteBody": "{business} pè ọ láti ṣàkójọ sí i gẹ́gẹ́ bí {role}.",
  "auth.joinTeam": "Darapọ mẹ́kúnná",
  "auth.inviteBad": "Ìpè yìí ti fòpin. Bè aṣáájú rẹ fún tuntun.",
  "cust.phoneLabel": "Fóònù (àbáyọ́)",
  "cust.estWait": "Ìdákẹ́rò ~{n} ìṣẹ́jú",
  "cust.pickQueue": "Kí ni o nílò?",
  "cust.pickBranch": "Ìbùgbé wo?",
  "cust.pickQueueHint": "Yan ìfà kan láti gbà nọ́ńbà.",
  "cust.held": "Ń dúró",
  "cust.heldBody": "Ọmọ iṣẹ́ yóò pè ọ lójoojúmọ́.",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "Àwọn ìfà",
  "dash.navTeam": "Ẹgbẹ́",
  "dash.navReports": "Ìtàn",
  "dash.holdTitle": "Tó dúró",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "Lọ",
  "dash.hold": "Dín yẹ́",
  "dash.release": "Padà sí ìfà",
  "dash.recall": "Pè lẹ́ẹ̀kan sí i",
  "dash.cancel": "Remove from queue",
  "dash.move": "Fìkọ síbẹ̀",
  "dash.moveTo": "Fì sí ìfà mìíràn",
  "dash.call": "Pè",
  "dash.addWalkIn": "Fi alábàásì kun",
  "dash.addWalkInBody": "Fún àwọn fún àwọn ẹ̀rọ àti àwọn ẹ̀yàn tó wà lẹ́yìn ojú rẹ.",
  "dash.noteLabel": "Àkọsílẹ̀ (àbáyọ́)",
  "dash.counterLabel": "Pín",
  "dash.anyCounter": "Kọ̀kan pàápàá",
  "dash.avgWait": "Àárín àkókò ìdúró {n} ìṣẹ́jú",
  "dash.peopleWaiting": "{n} ń dúró salẹ̀",
  "dash.tvLink": "Ṣí àpótí TV",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "Ìpínlẹ̀ yìí kò sí ìfà rẹ̀ láìpẹ́.",
  "dash.pickQueue": "Yan ìfà kan",
  "dash.roleTag": "Ìpò rẹ: {role}",
  "dash.noPermission": "Ìpò rẹ kò lè ṣe bẹ́ẹ̀.",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "Ìfà fún kọ́dù yìí",
  "qr.displayLink": "Ìsopọ̀ àpótí TV",
  "sq.title": "Àwọn ìfà àti àwọn pín",
  "sq.sub": "Ọ̀kọ̀ọ̀kan ìfà ní àwọn nọ́ńbà rẹ̀ àti òtítọ́ rẹ̀.",
  "sq.locations": "Àwọn ibi",
  "sq.addLocation": "Fi ibi kun",
  "sq.locationName": "Orúkọ ìbìgbé",
  "sq.address": "Adrésì (àbáyọ́)",
  "sq.phone": "Fóònù (àbáyọ́)",
  "sq.noLocations": "Kò sí ibi kankan títí báyìí.",
  "sq.queues": "Àwọn ìfà",
  "sq.addQueue": "Fi ìfà kun",
  "sq.queueName": "Orúkọ ìfà",
  "sq.prefix": "Lẹ́tà nọ́ńbà",
  "sq.prefixHint": "Lẹ́ta méjì lágbẹ́rẹ́ nọ́ńbà, bí A12.",
  "sq.description": "Kí ni ìfà yìí fún? (àbáyọ́)",
  "sq.avgTime": "Àkókò àfikún (ìṣẹ́jú)",
  "sq.counters": "Àwọn pín",
  "sq.counterName": "Counter name",
  "sq.addCounter": "Fi pín kun",
  "sq.paused": "Ti dúró",
  "sq.open": "Ó ṣí",
  "sq.closed": "Closed",
  "sq.noQueues": "Kò sí ìfà níbí títí báyìí.",
  "sq.deleteQueue": "Yọ ìfà yìí kúrò",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "Bẹ̀rẹ̀ pẹ̀lú irú ọ̀wọ̀",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "Àwọn alábàásì kò lè gbà nọ́ńbà nínú ìfà yìí nígbà tí ó bá dúró.",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "Ẹgbẹ́ rẹ",
  "team.sub": "Pè àwọn ènìyàn tí wọ́n ń ṣiṣẹ́ lórí pín, yan ohun tí ọ̀kọ̀ọ̀kan lè ṣe.",
  "team.invite": "Pè ẹnìkan",
  "team.invited": "A ti fi ìpè ránṣẹ́",
  "team.inviteEmail": "Ìmèèlì wọn",
  "team.inviteRole": "Ohun tí wọ́n lè ṣe",
  "team.pending": "Ń dúró láti darapọ̀",
  "team.noPending": "Kò sí ìpè tó ń dúró.",
  "team.revoke": "Fagile ìpè",
  "team.role": "Ìpò",
  "team.roleOwner": "Ẹni-ẹlẹ́rà",
  "team.roleManager": "Olùdarí",
  "team.roleStaff": "Ọmọ iṣẹ́",
  "team.roleViewer": "Ka nìkan",
  "team.remove": "Yọ kúrò nínú ẹgbẹ́",
  "team.lock": "Jáde níbùgbé gbogbo",
  "team.unlock": "Jẹ́ kó wọlé",
  "team.allBranches": "Gbogbo àwọn ibi",
  "team.oneBranch": "One location",
  "team.pickBranch": "Ibùgbé",
  "team.noTeam": "O lòsìsìì ẹ̀yàn kan nìkan.",
  "team.linkCopied": "A ti kọ̀ ìsopọ̀ ìpè. Fi ránṣẹ́ sí wọ́n.",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "Bí ọ̀jọ́ yìí àti ọ̀sẹ̀ tó kọjá ṣe ṣẹlẹ̀ tǹgbẹ́rẹ̀.",
  "rep.joined": "Àwọn nọ́ńbà tí wọ́n gbà",
  "rep.served": "Àwọn alábàásì tí wọ́n ṣiṣẹ́",
  "rep.avgWait": "Àárín ìdúró",
  "rep.avgService": "Àárín iṣẹ́",
  "rep.peak": "Wákàtí tó pọ̀ jùlọ",
  "rep.abandoned": "Lọ láì rí iṣẹ́",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "Òjoojúmọ́ ọ̀sẹ̀ 7 tó kọjá",
  "rep.days30": "Òjoojúmọ́ ọ̀sẹ̀ 30 tó kọjá",
  "rep.days90": "Òjoojúmọ́ ọ̀sẹ̀ 90 tó kọjá",
  "rep.byDay": "Each day",
  "rep.byHour": "Àwọn wákàtí tó ṣe pọ̀",
  "rep.byQueue": "Ọ̀kọ̀ọ̀kan ìfà",
  "rep.waited": "dúró {n} ìṣẹ́jú",
  "rep.servedIn": "ṣiṣẹ́ nínú {n} ìṣẹ́jú",
  "rep.history": "Gbogbo ènìyàn tó kọjá",
  "rep.noHistory": "Ẹnìkankan kò kọjá lọ́nà ìfà yìí lórí àkókò yìí.",
  "rep.audit": "Àwọn ìyípadà tí ẹgbẹ́ rẹ ṣe",
  "rep.noAudit": "Kò sí ìyípadà tí a kọ kankan títí báyìí.",
  "rep.noReports": "Ìpò rẹ kò lè wo ìjábọ̀.",
  "set.brand": "Ohun tí ó rí",
  "set.brandHint": "Àwọn àwò àti àmì rẹ ń hàn lórí ìwé alábàásì àti ìtànjí TV.",
  "set.mainColour": "Àwò pàtàkì",
  "set.accentColour": "Àwò ìtọ́pin",
  "set.logo": "Àmì",
  "set.logoHint": "Tẹ̀ ìsopọ̀ wẹ́bù tàbí gbé àwòrán sókè. Kékereké ni ó dára jùlọ.",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "Yọ àmì kúrò",
  "set.security": "Ìkọ̀wẹ́ rẹ",
  "set.currentPassword": "Ìkọ̀wẹ́ lọ́wọ́lọ́wọ́",
  "set.newPassword": "Ìkọ̀wẹ́ tuntun",
  "set.changePassword": "Yí ìkọ̀wẹ́ padà",
  "set.passwordChanged": "A ti yí ìkọ̀wẹ́ padà. Àwọn mìíràn ti jáde.",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "Ǹ ń pè báyìí",
  "disp.waiting": "Ń dúró",
  "disp.others": "Àwọn ìfà mìíràn",
  "disp.fullscreen": "Àpótí pípẹ́",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "Ń dúró fún nọ́ńbà àkọ́kọ́",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "Ìdákẹ́rò àkókò ìdúró",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "Nípyá lápapọ̀",
  "hero.statPhone": "Ó ń ṣiṣẹ́ lórí fóònù kankan",
  "feat.title": "Ohun gbogbo tí ìfà nílò, kì í ṣe èyí mìíràn",
  "feat.copy": "Lobby ń ṣe ohun kan dáadáa.Gbogbo ìtànjí nísàlẹ̀ ti jẹ́ àkànṣe ọ̀jọ̀ yìí.",
  "feat.qr.t": "Kọ́dù kan, ò ṣe kékeré",
  "feat.qr.d": "Kọ́dù QR péré fún kọ̀ọ̀kan ibi. Tẹ̀ sí i lẹ́ẹ̀kan kan — yí orúkọ ọjà padà kò lè baà fagile.",
  "feat.multi.t": "Púpọ̀ ìfà, ìtànjí kan",
  "feat.multi.d": "Fì àwọn pín pààrà sí àwọn iṣẹ́ — ìbánisọ̀rọ̀, ìgbé àti ì padà — pẹ̀lú àwọn nọ́ńbà àti àwọn pín wọn.",
  "feat.team.t": "Ìpò tó bá ọjà mu",
  "feat.team.d": "Pè ọmọ iṣẹ́ pẹ̀lú ìsopọ̀, so wọ́n pọ̀ mọ́ ìpínlẹ̀, kí àwọn ẹni-ẹlẹ́rà ní àwọn ìmọ́lẹ̀.",
  "feat.brand.t": "Bí ọjà rẹ ṣe rí",
  "feat.brand.d": "Àwọn àwò rẹ, àmì rẹ àti fúnra rẹ ń hàn lórí fóònù kọ̀ọ̀kan àti TV.",
  "feat.reports.t": "Òtítọ́ fún alẹ̀ aláìníwòyì",
  "feat.reports.d": "Àkókò ìdúró, àwọn wákàtí ìṣẹ́ àti ìtàn kékeré — ètò ọ̀sẹ̀ tó ń bọ̀ kò mọ́ ìbùdá.",
  "feat.pause.t": "Pa níṣẹ́ láì dà bíbẹ̀rẹ̀",
  "feat.pause.d": "Dín ìfà pẹ̀lú ìbẹ̀ẹ́ kan. Àmì ọ̀nà yóò sọ, kì í ṣe ẹ̀yàn gbà nọ́ńbà lọ sí pín tí ó ti pa.",
  "flow.title": "Láti ọ̀nà títí dípò lórín ìgbésẹ̀ mẹ́rin",
  "flow.s1.t": "Àwọn alábàásì ń darapọ̀ sí ìfà",
  "flow.s1.d": "Wọ́n ń ka kọ́dù, yan iṣẹ́, kí wọ́n gbà nọ́ńbà. Kì í ṣe app, kì í ṣe àkọ́lẹ̀bùkẹ́.",
  "flow.s2.t": "Ọmọ iṣẹ́ ń pè tó kàn",
  "flow.s2.d": "Bọ́tùnù ńlá kan ń ṣiṣẹ́ ẹ̀yàn tó kàn, ó sì ń dá ìfà dájú.",
  "flow.s3.t": "Gbogbo ènìyàn ń wo ipò wọn",
  "flow.s3.d": "Ọ̀pọ̀lọpọ̀ fóònù ń hàn ipò, bí ẹ̀yàn bá wà lẹ́jì àti àkókò ìdúró — nípyá, láì àtúnṣe.",
  "flow.s4.t": "Ìtànjí ń paàṣẹ dájú",
  "flow.s4.d": "TV nínú ọ̀nà ìdúró ń hàn ẹ̀yàn tí wọ́n ń ṣiṣẹ́ àti tó kàn.",
  "dispsect.title": "Ìtànjí tó yẹ fún ọ̀nà ìdúró rẹ",
  "dispsect.copy": "Ṣí ìtànjí ní ìṣàkóso TV kankan. Àwọn nọ́ńbà ńlá, àwọn márùn-ún tó kàn àti àwọn ìfà mìíràn ní ojú kan. Ó ń ṣe àtúnṣe bí ọmọ iṣẹ́ bá ṣe ohun kan.",
  "dispsect.cta": "Wo ìtànjí tó ṣìlẹ̀",
  "dash.servingCounters": "{n} ń ṣiṣẹ́",
};

const ha: Pack = {
  "nav.about": "Game da",
  "nav.signin": "Shiga",
  "nav.setup": "Kafa kasuwancinka",
  "foot.made": "Lobby, an gina ta da {name}.",
  "foot.mit": "Bude waya ƙarƙash lasisin MIT.",
  "lang.title": "Zaɓi harshe naka",
  "lang.sub": "Za ka iya canza shi daga baya, ta hanyar tuta a gefen sama.",
  "lang.change": "Canza harshe",
  "lang.done": "An gama",
  "common.loading": "Ana lodi…",
  "common.retry": "Sake gwada",
  "hero.eyebrow": "Jerin kufofi ga shago, asibiti da salon",
  "hero.h1a": "Kaɗauki lamba.",
  "hero.h1b": "Ki jira a wani wuri.",
  "hero.lede":
    "QR ɗaya ga kasuwancinka. Maƙwabci suna scan, suna ɗaukar lamba, suna kuma gano wurinsu a jergei. Sa ya kai tasa, wayar tasa zata gaya masa.",
  "hero.fine":
    "Babu app ga maƙwabci, babu asusu ga su. Bude waya, kuma yana gudana a server ɗinka.",
  "demo.nowServing": "Ana badarwa",
  "demo.yourNumber": "Lambarka",
  "how.title": "Yadda yake aiki",
  "how.t1": "Buga QR ɗinka",
  "how.d1": "Lamba ɗaya mai ci gaba ga ƙofarka ko kaunta.",
  "how.t2": "Maƙwabci suna ɗaukar lamba",
  "how.d2": "Suna scan, suna ƙara suna idan su so, babu shigar.",
  "how.t3": "Danna Call next",
  "how.d3": "Jerin yana motsawa, allonsa yana sabuntawa da kansa.",
  "see.title": "Abin da maƙwabcenka ke gani",
  "see.copy":
    "Allon guda ɗaya da amsa iri ɗaya kowane lokaci. Yana aiki a duk wayoyi, kuma sa aka kira lambarsa yana canzawa zuwa It's your turn.",
  "see.youreNumber": "Lambarka ita ce",
  "see.peopleAhead": "Mutane a gabanka",
  "see.when": "Lokacin da ya faru",
  "see.itsTurn": "Lokacinka ya yi!",
  "places.title": "Ga wuraren da suke da kaunta",
  "places.list":
    "Kwaroron magani · Asibiti · Salon · Masanin sace · Masanin gyaran kayayyaki · Banki · Ofisoshin labarai · Ofisoshin gwamnati",
  "band.title": "Kafa yana ɗaukar minti ɗaya.",
  "auth.welcome": "Barka da dawowa",
  "auth.setupSub": "Ga ƙaramin rubutu, jerinka ya shirya.",
  "auth.loginSub": "Shiga jerinka.",
  "auth.bizName": "Sunan kasuwanci",
  "auth.yourName": "Sunanka",
  "auth.email": "Imel",
  "auth.password": "Kalmar sirri",
  "auth.pwHint": "Ƙalma 8 ne za a iya.",
  "auth.creating": "Ana kafa…",
  "auth.signingIn": "Ana shiga…",
  "auth.create": "Kafa kasuwancina",
  "auth.haveAccount": "Kana da asusu a gabana?",
  "auth.noAccount": "Babu asusu ko da yanzu?",
  "auth.backHome": "Koma gida",
  "err.bizName": "Shigar da sunan kasuwancinka.",
  "err.name": "Shigar da sunanka.",
  "err.email": "Shigar da imelka.",
  "err.password": "Shigar da kalmar sirrinka.",
  "err.pwLen": "Kalmar sirri dole ne ta kasance ƙalma 8.",
  "cust.opening": "Ana buɗe jeri…",
  "cust.wrong": "Wani abu ya kasa.",
  "cust.pausedT": "Jerin ya huta.",
  "cust.pausedB": "Wannan kasuwanci ba ya ɗaukar lamba yanzu, don Allah dawo nan daiso.",
  "cust.nobody": "Babu wanda ake badarwa har yanzu",
  "cust.noOneWaiting": "babu wanda ke jira",
  "cust.waitingN": "{n} ake jira",
  "cust.joinT": "Shiga jerin",
  "cust.nameLabel": "Sunanka (na son rai)",
  "cust.joinBusy": "Ana ɗauko lambarka…",
  "cust.joinReassure": "Babu shigarwa, babu asusu, lamba ɗaya ce.",
  "cust.youreNumber": "Lambarka ita ce",
  "cust.youreNext": "Ka gaba",
  "cust.oneAhead": "Mutum ɗaya ne a gabanka",
  "cust.nAhead": "Mutane {n} ne a gabanka",
  "cust.peopleWaiting": "Manyan jira",
  "cust.reassure": "Wannan allon yana sabuntawa da kansa, ka bar shi a buɗe.",
  "cust.leave": "Fita daga jerin",
  "cust.leaveConfirm": "Fita daga jerin? Za ka rasa lambarka.",
  "cust.turnT": "Lokacinka ya yi",
  "cust.turnB": "Don Allah zuwa ga kaunta.",
  "cust.imHere": "Ina nan",
  "cust.sending": "Ana aikawa…",
  "cust.confirmed": "Na gode, mun gaya musu ka shirya.",
  "cust.done": "An gama",
  "cust.servedBody": "Na gode da jira.",
  "cust.skippedBody": "An manta da ka. Idan kana nan, ɗauki lamba ta.",
  "cust.noShowBody": "An rufe lambar. Idan kana nan, ɗauki lamba ta.",
  "cust.joinAgain": "Shiga ɗaya",
  "cust.poweredBy": "Ta hannun",
  "dash.navQueue": "Jeri",
  "dash.navQr": "QR",
  "dash.navSettings": "Saituna",
  "dash.signOut": "Fita",
  "dash.opening": "Ana buɗe jerinka…",
  "dash.pausedB": "Maƙwabci ba za su iya ɗaukar lamba yanzu ba.",
  "dash.nobodyCounter": "Babu wani a kan kaunta",
  "dash.noNameGiven": "Babu suna",
  "dash.confirmedHere": "ya ce yana nan",
  "dash.notConfirmed": "ba ta tabbatar ba",
  "dash.callNext": "Kira na gaba",
  "dash.calling": "Ana kira…",
  "dash.noWaitingHint": "Babu wanda ke jira yanzu.",
  "dash.pause": "Huta da jeri",
  "dash.resume": "Ci gaba da jeri",
  "dash.atCounter": "A kan kaunta",
  "dash.waitingTitle": "Ajaki",
  "dash.noName": "Babu suna",
  "dash.stWait": "Ajaki",
  "dash.stCalled": "Ana kira",
  "dash.stServed": "An badar",
  "dash.stSkipped": "An manta",
  "dash.stNoShow": "Babu zuwa",
  "dash.firstRun": "Babu wanda ya zo tukuna. Matauka uku masu sauri ne za su kafa jerinka:",
  "dash.step1": "Samu QR ɗinka. Buga shi, ko a allon kusa da ƙofa.",
  "dash.step1link": "Buɗe QR nawa →",
  "dash.step2": "Maƙwabci suna ɗaukar lamba. Suna scan, suna rubuta suna ko da so, suna shiga.",
  "dash.step3": "Danna Call next. Wayarta za ta sabunta a wannan lokacin.",
  "dash.emptyWaiting": "Babu wanda ke jira. Sabbin lambobin za su bayyana nan lokacin da mutane suka shiga.",
  "dash.nextUp": "Na gaba",
  "dash.finished": "An gama",
  "dash.counts": "{s} an badar, {k} an manta, {n} babu zuwa",
  "dash.markServed": "Yi da alama an badar",
  "dash.skip": "Manta",
  "qr.intro":
    "Buga wannan ka ajiye shi a ƙofa ko kaunta. Haɗin ba ya canza, kodai buga ka yau zai ci gaba.",
  "qr.linkLabel": "Haɗin jerinka",
  "qr.download": "Sauke PNG",
  "qr.print": "Buga",
  "qr.copy": "Kwafa haɗi",
  "qr.copied": "An kwafa haɗi.",
  "qr.making": "Ana yin QR ɗinka…",
  "qr.sheetCta": "Scan don shiga jeri",
  "qr.fine":
    "Maƙwabci suna scan wannan don ɗaukar lamba, babu app, babu asusu. QR yana nan baƙi da fari a kowane salam, don wayoyin su iya karantawa.",
  "set.noteLabel": "Bayani ga maƙwabci",
  "set.noteHint": "Yana bayyana sama da maɓallin Join a allon jerinka. Na son rai.",
  "set.save": "Ajiye canje-canje",
  "set.saving": "Ana ajiye…",
  "set.saved": "An ajiye.",
  "set.goodToKnow": "Ya kamata ka sani",
  "set.linkBody": "Haɗin ne mai ci gaba, buga QR a yau zai ci gaba ko ka canza sunan kasuwanci.",
  "set.signedInAs": "Ka shiga a matsayin",
  "set.errNote": "Bayani ba za ta wuce harufe 200 ba.",
  "nf.title": "Wannan allon ba ya nan.",
  "nf.body": "Zai iya motsi, ko kuma haɗin ya lalace.",
  "nf.cta": "Je zuwa shafin gida",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "Live demo",
  "common.live": "Kai tsaye",
  "common.reconnecting": "Sake haɗa…",
  "common.offline": "Ba ka da haɗin yanar gizo. Wannan shafi zai sabunta kansa.",
  "common.optional": "optional",
  "common.cancel": "Soce",
  "common.remove": "Cire",
  "common.add": "Ƙara",
  "common.save": "Save",
  "common.saved": "An ajiye.",
  "common.minutes": "{n} minti",
  "common.branch": "Wuri",
  "common.allBranches": "Duk wurare",
  "common.back": "Back",
  "band.body": "Fara daga irin kasuwanci — abinci, asibiti, salon, gyaran kaya — sanya canjin suna. ƙara wurare lokacin da ka buɗe sabo.",
  "band.try": "Duba live demo",
  "demo.title": "Duba yadda yake aiki",
  "demo.sub": "Shagon gwaji inda za ka danna maɓallai. Shiga matsayi aboki, kira lambobi matsayi ma'aikaci, kalliallan TV. Babu wani na gaske a nan.",
  "demo.paneCustomer": "Wayar aboki",
  "demo.paneStaff": "Wayar ma'aikaci",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "Mallan TV",
  "demo.joinName": "Suna (na son zaɓi)",
  "demo.join": "Sau lamba",
  "demo.reset": "Sake demo",
  "demo.callNext": "Kira na gaba",
  "demo.serve": "An gama",
  "demo.skip": "Tsallace",
  "demo.waitingList": "Waiting",
  "demo.hint": "Gwada kira lambar da ka ga duk hoto huɗu sun sabunta lokaci ɗaya.",
  "auth.shopType": "Wane irin kasuwanci ne?",
  "auth.shopTypeHint": "Za mu ƙirƙira lambobi da bugunge. Za ka iya canza kowane suna daga nan gwaura.",
  "auth.branchName": "Wurin farko",
  "auth.inviteTitle": "An kira ku",
  "auth.inviteBody": "{business} ya kira ku shiga matsayar {role} don sarrafa lambun.",
  "auth.joinTeam": "Shiga ƙungiya",
  "auth.inviteBad": "Wannan kira ya ƙare. Nemi sabo daga manajanka.",
  "cust.phoneLabel": "Wayar (na son zaɓi)",
  "cust.estWait": "Kusan dakika {n} jira",
  "cust.pickQueue": "Me kike buƙata?",
  "cust.pickBranch": "Wane wuri?",
  "cust.pickQueueHint": "Zaɓi lamba don samun lamba.",
  "cust.held": "Ana jira",
  "cust.heldBody": "Ma'aikata za su kira ka nan ba da jimawa.",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "Lambobi",
  "dash.navTeam": "Ƙungiya",
  "dash.navReports": "Tarihi",
  "dash.holdTitle": "An riƙe",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "Ya barra",
  "dash.hold": "Riƙe",
  "dash.release": "Maidowa a lamba",
  "dash.recall": "Kira ƙaira",
  "dash.cancel": "Remove from queue",
  "dash.move": "Musa",
  "dash.moveTo": "Musa zuwa lamba ɗaya",
  "dash.call": "Kira",
  "dash.addWalkIn": "Ƙara aboki",
  "dash.addWalkInBody": "Don booking na waya da mutane da ke gabanka.",
  "dash.noteLabel": "Shafi (na son zaɓi)",
  "dash.counterLabel": "Bugu",
  "dash.anyCounter": "Kowane bugu",
  "dash.avgWait": "Matsakaicin lokacin jira {n} minti",
  "dash.peopleWaiting": "{n} na jira",
  "dash.tvLink": "Buɗeallan TV",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "Wannan rukuni har yanzu babu lamba.",
  "dash.pickQueue": "Zaɓi lamba",
  "dash.roleTag": "Matsayinka: {role}",
  "dash.noPermission": "Matsayinka ba za ya iya aiwatan ba.",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "Lamba don wannan lambar",
  "qr.displayLink": "Haɗin allon TV",
  "sq.title": "Lambobi da bugunge",
  "sq.sub": "Kowane lamba na da nassoshi da layin sa na musamman.",
  "sq.locations": "Wurare",
  "sq.addLocation": "Ƙara wuri",
  "sq.locationName": "Sunan wuri",
  "sq.address": "Adireshi (na son zaɓi)",
  "sq.phone": "Wayar (na son zaɓi)",
  "sq.noLocations": "Har yanzu babu wuri.",
  "sq.queues": "Lambobi",
  "sq.addQueue": "Ƙara lamba",
  "sq.queueName": "Sunan lamba",
  "sq.prefix": "Haruffin lamba",
  "sq.prefixHint": "Haruffi biyu kafin lamba, kamar A12.",
  "sq.description": "Me wannan lamba take bukata? (na son zaɓi)",
  "sq.avgTime": "Lokacin gama-gari (minti)",
  "sq.counters": "Bugunge",
  "sq.counterName": "Counter name",
  "sq.addCounter": "Ƙara bugu",
  "sq.paused": "An huta",
  "sq.open": "Buɗewa",
  "sq.closed": "Closed",
  "sq.noQueues": "Har yanzu babu lamba a wannan wuri.",
  "sq.deleteQueue": "Cire wannan lamba",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "Fara daga irin kasuwanci",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "Abokan ciniki ba za su iya sau lamba a wannan lamba lokacin da aka huta ba.",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "Ƙungiyarka",
  "team.sub": "Kira waɗanda ke aiki a ƙofa, zaɓi abin da kowa zai iya yi.",
  "team.invite": "Kira wani",
  "team.invited": "An aika kira",
  "team.inviteEmail": "Adireshin su",
  "team.inviteRole": "Abin da za su iya yi",
  "team.pending": "Ana jiran shiga",
  "team.noPending": "Ba a kira da aka jira ba.",
  "team.revoke": "Soce kira",
  "team.role": "Matsayi",
  "team.roleOwner": "Shugaba",
  "team.roleManager": "Manaja",
  "team.roleStaff": "Ma'aikaci",
  "team.roleViewer": "Karantaka",
  "team.remove": "Cire daga ƙungiya",
  "team.lock": "Fita a duk wuri",
  "team.unlock": "Ba da izini shiga",
  "team.allBranches": "Duk wurare",
  "team.oneBranch": "One location",
  "team.pickBranch": "Wuri",
  "team.noTeam": "Har yanzu kai kaɗai ne.",
  "team.linkCopied": "An kwace haɗin kira. Aika musu.",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "Yadda yau da mako mai ya gaba suka kasance a gaske.",
  "rep.joined": "Lambobi da aka sau",
  "rep.served": "Abokan ciniki da aka hidana",
  "rep.avgWait": "Matsakaicin lokacin jira",
  "rep.avgService": "Matsakaicin hidima",
  "rep.peak": "Lokacin cikewa",
  "rep.abandoned": "Bara ba tare da hidima ba",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "Kwanan 7 da suka wuce",
  "rep.days30": "Kwanan 30 da suka wuce",
  "rep.days90": "Kwanan 90 da suka wuce",
  "rep.byDay": "Each day",
  "rep.byHour": "Salo'in da suka yi dere",
  "rep.byQueue": "Kowane lamba",
  "rep.waited": "ya jira {n} minti",
  "rep.servedIn": "an hidana cikin {n} minti",
  "rep.history": "Duk wanda ya zo",
  "rep.noHistory": "Ba wanda ya bi ta wannan lamba a wannan lokaci ba.",
  "rep.audit": "Canjeji da ƙungiyarka ta yi",
  "rep.noAudit": "Ba a rubuta canjeji ba har yanzu.",
  "rep.noReports": "Matsayinka ba za ya iya ganin rahoto ba.",
  "set.brand": "Kamanni",
  "set.brandHint": "Launinka da alamarka suna bayyana a shafin aboki da allon TV.",
  "set.mainColour": "Launi na asali",
  "set.accentColour": "Launin bayyana",
  "set.logo": "Alamar",
  "set.logoHint": "Liƙa haɗin gajera ko ɗauki hota. Ƙarami shi ne mafi kyau.",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "Cire alamar",
  "set.security": "Harshe ka",
  "set.currentPassword": "Harshe na yanzu",
  "set.newPassword": "Sabon harshe",
  "set.changePassword": "Canza harshe",
  "set.passwordChanged": "An canza harshe. Wasu na'urori sun fita.",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "Ana kira wannan",
  "disp.waiting": "Ana jira",
  "disp.others": "Wasu lambobi",
  "disp.fullscreen": "Cikakken allon",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "Ana jiran lambar na farko",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "Kiyin lokacin jira",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "Kai tsaye ta asali",
  "hero.statPhone": "Yana aiki a kowane waya",
  "feat.title": "Duk abin da lamba ta buƙata, wani ba",
  "feat.copy": "Lobby yana yi wani abuki da kyau. Duk allon da ke ƙasa yana ɓata na inji a yau.",
  "feat.qr.t": "Lambar ɗaya, kullum sabuwa",
  "feat.qr.d": "QR na ɗorewa ga kowane wuri. Buɗa sau ɗaya — canza sunan shaida ba zai karye shi ba.",
  "feat.multi.t": "Daɗaɗɗun lambobi, allon ɗaya",
  "feat.multi.d": "Raba bugu zuwa hidodidi — tattaunawa, ɗauka, mayarwa — da nassoshi da bugunge na musamman.",
  "feat.team.t": "Matsayi masu dacewa da shaida",
  "feat.team.d": "Kira ma'aikata da haɗi, su danganta su rukuni, ana maza su riƙe mafita.",
  "feat.brand.t": "Kamar kasuwancinka",
  "feat.brand.d": "Launinka, alamar da bayaninka suna bayyana a wayar kowane aboki da a TV.",
  "feat.reports.t": "Gaskiya don yammacin sauƙi",
  "feat.reports.d": "Lokacin jira, lokutan sa'o'i da cikakken tarihi — tsarin mako mai zuwa ba gaskiya ne ba.",
  "feat.pause.t": "Rufe ba tare da rashin cikakkiya ba",
  "feat.pause.d": "Huta lamba da ɗanna ɗaya. Allon ƙofa zai faɗa, kuma babu wanda ya sau lamba zuwa bugu da aka rufe.",
  "flow.title": "Daga ƙofa zuwa ƙarshe a matakai huɗu",
  "flow.s1.t": "Abokan ciniki na shiga lamba",
  "flow.s1.d": "Suna karanta lambar, zaɓi hidima, da samun lamba. Babu app, babu asusu.",
  "flow.s2.t": "Ma'aikaci na kira na gaba",
  "flow.s2.d": "Maballan manya yana hidana wanda ke gaba, yana kiyaye lamba da adalci.",
  "flow.s3.t": "Kowa yana ganin matsayinsa",
  "flow.s3.d": "Kowane waya na nuna wuri, mutane nawa ke gabanka da lokacin jira — kai tsaye, ba tare da sabuntawa ba.",
  "flow.s4.t": "Allon yana riƙe tsari",
  "flow.s4.d": "TV a wurin jira na nuna wanda ake hidana da wanda zai zo gaba.",
  "dispsect.title": "Allon da ya dace da wurin jiran ka",
  "dispsect.copy": "Buɗe allon a kowane mai bayanan TV. Lambobi manya, biyar na gaba da wasu lambobi a gani ɗaya. Yana sabunta da wudanar ma'aikacin ya yi wani mataki.",
  "dispsect.cta": "Duba allon kai tsaye",
  "dash.servingCounters": "{n} ana hidana",
};

const ig: Pack = {
  "nav.about": "Banyere",
  "nav.signin": "Banye",
  "nav.setup": "Teebe azụmahịa gị",
  "foot.made": "Lobby, {name} mere ya.",
  "foot.mit": "Mepere eme n'okpuru lasisi MIT.",
  "lang.title": "Họrọ asụsụ gị",
  "lang.sub": "Ị nwere ike ịgbanwe ya n'azụ, site na akara dị n'elu n'akụkpụtụ.",
  "lang.change": "Gbanwe asụsụ",
  "lang.done": "E zugwala",
  "common.loading": "Na-ebu…",
  "common.retry": "Gbalịa ọzọ",
  "hero.eyebrow": "Ntụrụndụ maka ahịa, ụlọ ọwụwa na salon",
  "hero.h1a": "Nweta nọmba.",
  "hero.h1b": "Chere ebe ọ bụla.",
  "hero.lede":
    "QR otu maka azụmahịa gị. Ndị ahịa ga-escan, were nọmba, wee hụ ebe ha n'otu ntụrụndụ. Mgbe oge ha rutere, ekwentị ha ga-akwusị ha.",
  "hero.fine":
    "Enweghị app maka ndị ahịa, enweghị akara maka ha. Mepere eme, na-arụọrụ n'seva gị.",
  "demo.nowServing": "Na-ese ugbu a",
  "demo.yourNumber": "Nọmba gị",
  "how.title": "Ka ọ na-eme",
  "how.t1": "Mepụta QR gị",
  "how.d1": "Nọmba mgbanwe maka ụzọ ma ọ bụ kanta gị.",
  "how.t2": "Ndị ahịa na-eweta nọmba",
  "how.d2": "Ha na-esca, ha na-emetụ aha ha chọrọ, enweghị ihe ị banye.",
  "how.t3": "Pịa Call next",
  "how.d3": "Ntụrụndụ na-aga, mgbasaso ha na-emezigharị onwe ya.",
  "see.title": "Ihe ndị ahịa gị na-ahụ",
  "see.copy":
    "Mgbasaso otu, azịza otu oge niile. Ọ na-arụọrụ na ekwentị ọ bụla, ma mgbe ha ekpọtula nọmba ha ọ na-agbanwe na It's your turn.",
  "see.youreNumber": "Nọmba gị bụ",
  "see.peopleAhead": "Ndị dị n'ihu gị",
  "see.when": "Mgbe ọ mere",
  "see.itsTurn": "Oge gị dị!",
  "places.title": "Maka ebe dị na kanta",
  "places.list":
    "Ụlọ aṅụ · Ụlọ ọwụwa · Salon · Ụlọ mkpuchi isi · Ụlọ zozo ọrụ · Bankee · Ụlọ akwụkwọ ozi · Ọrụ gọọmentị",
  "band.title": "Ị mee na-adịghị karịrị nkeji.",
  "auth.welcome": "Nnọọla azụ",
  "auth.setupSub": "Igbara obere oge, ntụrụndụ gị dị njikere.",
  "auth.loginSub": "Banye na ntụrụndụ gị.",
  "auth.bizName": "Aha azụmahịa",
  "auth.yourName": "Aha gị",
  "auth.email": "Email",
  "auth.password": "Okwuntughe",
  "auth.pwHint": "Ọbụna 8 akụkụ.",
  "auth.creating": "Na-eteebe…",
  "auth.signingIn": "Na-abanye…",
  "auth.create": "Mee azụmahịa m",
  "auth.haveAccount": "Ị nwere akara n'ihu?",
  "auth.noAccount": "Akara adịghị ugbu a?",
  "auth.backHome": "Laghachi n'ụlọ",
  "err.bizName": "Tinye aha azụmahịa gị.",
  "err.name": "Tinye aha gị.",
  "err.email": "Tinye email gị.",
  "err.password": "Tinye okwuntughe gị.",
  "err.pwLen": "Okwuntughe ga-adịkarịrị n'akụkụ 8.",
  "cust.opening": "Na-emeghe ntụrụndụ…",
  "cust.wrong": "Ihe emetụla nke ọma.",
  "cust.pausedT": "Ntụrụndụ echereela.",
  "cust.pausedB": "Azụmahịa a anaghị eweta nọmba ugbu a, biko gbanwee n'oge ọzọ.",
  "cust.nobody": "Onweghị ihe ha na-ese ugbu a",
  "cust.noOneWaiting": "onweghị na-echere",
  "cust.waitingN": "{n} na-echere",
  "cust.joinT": "Jikọtara na ntụrụndụ",
  "cust.nameLabel": "Aha gị (nwere ikike)",
  "cust.joinBusy": "Na-aweta nọmba gị…",
  "cust.joinReassure": "Enweghị ihe ị banye, enweghị akara, nọmba otu.",
  "cust.youreNumber": "Nọmba gị bụ",
  "cust.youreNext": "Ị bụ n'ihu",
  "cust.oneAhead": "Onye otu dị n'ihu gị",
  "cust.nAhead": "Ndị {n} dị n'ihu gị",
  "cust.peopleWaiting": "Ndị na-echere",
  "cust.reassure": "Mgbasaso a na-emezigharị onwe ya, hapụ ya ka e meghe.",
  "cust.leave": "Wepụ na ntụrụndụ",
  "cust.leaveConfirm": "Wepụ na ntụrụndụ?Ị ga-ebufe nọmba gị.",
  "cust.turnT": "Oge gị dị",
  "cust.turnB": "Biko gaa n'ikpe.",
  "cust.imHere": "Anọ m ebe a",
  "cust.sending": "Na-ezigarị…",
  "cust.confirmed": "Daalụ, anyị kwuru na gị njikere.",
  "cust.done": "E zugwala",
  "cust.servedBody": "Daalụ ka i chere.",
  "cust.skippedBody": "Ha kwụsịrị gị. Ọ bụrụ na ị nọ ebe a, nweta nọmba ọzọ.",
  "cust.noShowBody": "Nọmba a kwụsịrị. Ọ bụrụ na ị nọ ebe a, nweta nọmba ọzọ.",
  "cust.joinAgain": "Jikọtara ọzọ",
  "cust.poweredBy": "Site na",
  "dash.navQueue": "Ntụrụndụ",
  "dash.navQr": "QR",
  "dash.navSettings": "Ntọala",
  "dash.signOut": "Pụpụta",
  "dash.opening": "Na-emeghe ntụrụndụ gị…",
  "dash.pausedB": "Ndị ahịa enweghị ike iweta nọmba ugbu a.",
  "dash.nobodyCounter": "Onweghị na kanta",
  "dash.noNameGiven": "Aha adịghị",
  "dash.confirmedHere": "osiri sị na ọ nọ ebe a",
  "dash.notConfirmed": "ọ akụrịghị",
  "dash.callNext": "Kpọọ n'ihu",
  "dash.calling": "Na-ekpọọ…",
  "dash.noWaitingHint": "Onweghị na-echere ugbu a.",
  "dash.pause": "Kwụsị ntụrụndụ",
  "dash.resume": "Malite ntụrụndụ ọzọ",
  "dash.atCounter": "Na kanta",
  "dash.waitingTitle": "Na-echere",
  "dash.noName": "Aha adịghị",
  "dash.stWait": "Na-echere",
  "dash.stCalled": "Akpọrọ",
  "dash.stServed": "E ezighị",
  "dash.stSkipped": "E kwụsịrị",
  "dash.stNoShow": "O zoghị",
  "dash.firstRun": "Onweghị ebughịla. Ihe atụ atụ nke atọ ga-emeghe ntụrụndụ gị:",
  "dash.step1": "Nweta QR gị. Mepụta ya, tinye ya n'akụkpụtụ nso n'ụzọ.",
  "dash.step1link": "Meghe QR m →",
  "dash.step2": "Ndị ahịa na-eweta nọmba. Ha na-esca, ha na-edekwa aha, ha na-abịa.",
  "dash.step3": "Pịa Call next. Ekwentị ha ga-emeghari ugbu ahụ.",
  "dash.emptyWaiting": "Onweghị na-echere. Nọmba ọhụrụ ga-ahụ n'ebe a mgbe ndị bịa na ndá.",
  "dash.nextUp": "N'ihu",
  "dash.finished": "E zugwala",
  "dash.counts": "{s} e ezighị, {k} e kwụsịrị, {n} o zoghị",
  "dash.markServed": "Kara dị ka e ezighị",
  "dash.skip": "Gafee",
  "qr.intro":
    "Mepụta a tinye ya n'ụzọ ma ọ bụ na kanta. Ngwalangwalu agaghị agbanwe, QR i mepere taa ga-adịgide adịgide.",
  "qr.linkLabel": "Ngwalangwalu ntụrụndụ gị",
  "qr.download": "Budata PNG",
  "qr.print": "Mepụta",
  "qr.copy": "Kopụtaghị",
  "qr.copied": "E kopụtara ngwalangwalu.",
  "qr.making": "Na-emepụta QR gị…",
  "qr.sheetCta": "Escan i jikọta",
  "qr.fine":
    "Ndị ahịa na-esca iwere nọmba, enweghị app, enweghị akara. QR nọ na-acha ojii na ojii na nhazi ọ bụla ka ekwentị ga-agụ ya.",
  "set.noteLabel": "Nzọrọ ndị ahịa",
  "set.noteHint": "A na-ahụ ya n'elu ma bọtụn Join na mgbasaso ntụrụndụ gị. Nwere ikike.",
  "set.save": "Chekwaa mgbanwe",
  "set.saving": "Na-echekwa…",
  "set.saved": "E chekwara.",
  "set.goodToKnow": "Ihe kwesịrị ịmata",
  "set.linkBody": "Ọ bụ mgbanwe, QR i mepere ga-adịgide ọ bụrụ na ị gbanwere aha azụmahịa.",
  "set.signedInAs": "I banyere dịka",
  "set.errNote": "Nzọrọ gị ga-adịrị ala 200.",
  "nf.title": "Mgbasaso a adịghị.",
  "nf.body": "Ọ tụfara, ma ọ bụ ngwalangwalu gbasara.",
  "nf.cta": "Gaa n'isi mmemme",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "Ndọka dị adị",
  "common.live": "Nzoputa",
  "common.reconnecting": "Na-akọpụta ọzọ…",
  "common.offline": "Ị dị n'èzí. Ipgea ga-emezi onwe ya.",
  "common.optional": "optional",
  "common.cancel": "Kagbuo",
  "common.remove": "Wepụ",
  "common.add": "Tinye",
  "common.save": "Save",
  "common.saved": "Echere.",
  "common.minutes": "{n} nkeji",
  "common.branch": "Ebe",
  "common.allBranches": "S mụọ ebe",
  "common.back": "Back",
  "band.body": "Malite site na ụdọ azụmahịa — nri, ọgwụ, ụlọ ọsọ ọla, nchọọta — gbanwee aha. Tinye ebe ndị ọzọ ma ị tinye ọhụrụ.",
  "band.try": "Lee ndọka dị adị",
  "demo.title": "Lee ka ọ na-arụ ọrụ",
  "demo.sub": "Ebe ị nwere ike ibụ ọkụrụ. Banye dịka ahịa, kpọọ nọmba dịka ọrụ, lelee screen TV. Ọ bụla dị ebe a adịghị ebubesịla.",
  "demo.paneCustomer": "Ego nchụkwapụta ndị ahịa",
  "demo.paneStaff": "Ego nchọrọ ndị ọrụ",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "Screen TV",
  "demo.joinName": "Aha (nhọrọ)",
  "demo.join": "Nweta nọmba",
  "demo.reset": "Tọgharia ndọka",
  "demo.callNext": "Kpọọ na-esote",
  "demo.serve": "Mechaa",
  "demo.skip": "Gafee",
  "demo.waitingList": "Waiting",
  "demo.hint": "Gbalịa ịkpọọ nọmba ahụ, lelee ka panel anọ na-emezi ngwa ngwa.",
  "auth.shopType": "Ụdọ nsịlịlị bụ ekele?",
  "auth.shopTypeHint": "Anyị ga-awepụta ogige na window. Ị nwere ike ịgbanwe ọ bụla aha mgbe niile.",
  "auth.branchName": "Ebe mbụ",
  "auth.inviteTitle": "Akpọrị gị",
  "auth.inviteBody": "{business} na-akpọ gị ka ị jikwa ogige dịka {role}.",
  "auth.joinTeam": "Banye na òtu",
  "auth.inviteBad": "Ọụghị ahụ adịghị ihe ọ bụla ọzọ. Rịọ nọọzụ n'aka onye njikwa gị.",
  "cust.phoneLabel": "Ego (nhọrọ)",
  "cust.estWait": "Uru ogologo {n} nkeji",
  "cust.pickQueue": "Kị bụ ihe ị chọrọ?",
  "cust.pickBranch": "Kedu ebe ahụ?",
  "cust.pickQueueHint": "Họrọ ogige ịnweta nọmba.",
  "cust.held": "Na-echere",
  "cust.heldBody": "Ndị ọrụ ga-akpọ gị ugbu a.",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "Ogige",
  "dash.navTeam": "Òtu",
  "dash.navReports": "Akụkọ",
  "dash.holdTitle": "E chere",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "Laapụọ",
  "dash.hold": "Echere",
  "dash.release": "Laghaazụ na ogige",
  "dash.recall": "Kpọọ ọzọ",
  "dash.cancel": "Remove from queue",
  "dash.move": "Kụọ",
  "dash.moveTo": "Kụọ na ogige ndị ọzọ",
  "dash.call": "Kpọọ",
  "dash.addWalkIn": "Tinye ahịa",
  "dash.addWalkInBody": "Maka nde e kwuru na ego na ndị dị n'ihu gị.",
  "dash.noteLabel": "Nte (nhọrọ)",
  "dash.counterLabel": "Window",
  "dash.anyCounter": "Onye na-ahụ aka nke ọ bụla",
  "dash.avgWait": "Nkiri iche na iche {n} nkeji",
  "dash.peopleWaiting": "{n} na-echere",
  "dash.tvLink": "Megherie screen TV",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "Ebe a agaghị enweta ogige ugbu a.",
  "dash.pickQueue": "Họrọ ogige",
  "dash.roleTag": "Njirimara gị: {role}",
  "dash.noPermission": "Njirimara gị agaghị agbakwụzi nke ahụ.",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "Ogige maka kọdụ a",
  "qr.displayLink": "Njikọ TV screen",
  "sq.title": "Ogige na window",
  "sq.sub": "Ogike ọ bụla nwee nọmba ya na mkpụrụ ndị ya.",
  "sq.locations": "Ebe",
  "sq.addLocation": "Tinye ebe",
  "sq.locationName": "Aha ebe",
  "sq.address": "Adreesị (nhọrọ)",
  "sq.phone": "Ego (nhọrọ)",
  "sq.noLocations": "Adịghị ebe ugbu a.",
  "sq.queues": "Ogige",
  "sq.addQueue": "Tinye ogige",
  "sq.queueName": "Aha ogige",
  "sq.prefix": "Mkpụrụokwu nọmba",
  "sq.prefixHint": "Mkpụrụokwu abụọ tupu nọmba, dịka A12.",
  "sq.description": "Gịnị bụ otu ogige a ji aṅa? (nhọrọ)",
  "sq.avgTime": "Oge ka ọ dị (nkeji)",
  "sq.counters": "Window",
  "sq.counterName": "Counter name",
  "sq.addCounter": "Tinye window",
  "sq.paused": "E kwụsịrị",
  "sq.open": "Emebigie",
  "sq.closed": "Closed",
  "sq.noQueues": "Adịghị ogige n'ebe a ugbu a.",
  "sq.deleteQueue": "Wepụ ogige a",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "Malite site na ụdọ azụmahịa",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "Ndị ahịa agaghị enweta nọmba n'ogige a mgbe e kwụsịrị ya.",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "Òtu gị",
  "team.sub": "Kpọọ ndị na-arụ ọrụ na window, họrọ ihe ọ bụla nwere ike ịrụ.",
  "team.invite": "Kpọọ onye",
  "team.invited": "E zigara akpọ",
  "team.inviteEmail": "Email ha",
  "team.inviteRole": "Ihe nwere ike ịrụ",
  "team.pending": "Na-echere ịbanye",
  "team.noPending": "Adịghị akpọ ndị na-echere.",
  "team.revoke": "Kagbuo akpọ",
  "team.role": "Njirimara",
  "team.roleOwner": "Onye nwe",
  "team.roleManager": "Onye njikwa",
  "team.roleStaff": "Ọrụ",
  "team.roleViewer": "Gụọ naanị",
  "team.remove": "Wepụ na òtu",
  "team.lock": "Pụọ n'ebe niile",
  "team.unlock": "Kwenye ịbanye",
  "team.allBranches": "S mụọ ebe",
  "team.oneBranch": "One location",
  "team.pickBranch": "Ebe",
  "team.noTeam": "Ugbu a ọ bụ gị nọ naanị.",
  "team.linkCopied": "E mesịrị njikọ akpọ. Zie ha.",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "Ka taa na izu gara aga si dị n'ezie.",
  "rep.joined": "Nọmba ndị a nwetara",
  "rep.served": "Ndị ahịa e mere ndị ọrụ",
  "rep.avgWait": "Nkiri echere iche na iche",
  "rep.avgService": "Nkiri ọrụ iche na iche",
  "rep.peak": "Awa akpọrị akpọ",
  "rep.abandoned": "Laapụọ n'enweghị ọrụ",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "Ụbọchị 7 gara aga",
  "rep.days30": "Ụbọchị 30 gara aga",
  "rep.days90": "Ụbọchị 90 gara aga",
  "rep.byDay": "Each day",
  "rep.byHour": "Awa e dere e dere",
  "rep.byQueue": "Ogige ọ bụla",
  "rep.waited": "echere {n} nkeji",
  "rep.servedIn": "e mere ndị ọrụ na {n} nkeji",
  "rep.history": "Udo niile bịarị",
  "rep.noHistory": "Ọ dịghị onye gafere ogige a n'oge a.",
  "rep.audit": "Mgbanwe ndị otu gị mere",
  "rep.noAudit": "Adịghị mgbanwe edetara ugbu a.",
  "rep.noReports": "Njirimara gị agaghị ahụ ngosi.",
  "set.brand": "Ịdị mma",
  "set.brandHint": "Ọṅṅụ na aha gị na-apụta na peeji ahịa na TV screen.",
  "set.mainColour": "Ọnụ ọkụkọ mbụ",
  "set.accentColour": "Ọnụ ọkụkọ",
  "set.logo": "Aha",
  "set.logoHint": "Tee njikọ web ọbaa ma ọ bụ bulie foto. Ntakiri ka ọ dị mma.",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "Wepụ aha",
  "set.security": "Okwuntughe gị",
  "set.currentPassword": "Okwuntughe ugbu a",
  "set.newPassword": "Okwuntughe ọhụrụ",
  "set.changePassword": "Gbanwee okwuntughe",
  "set.passwordChanged": "Okwuntughe agbanwere. Ngwugwu ndị ọzọ apụọla.",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "Na-akpọ ugbu a",
  "disp.waiting": "Na-echere",
  "disp.others": "Ogige ndị ọzọ",
  "disp.fullscreen": "Ngwugwu niile",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "Na-echere nọmba mbụ",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "Mmetụ iche na iche n'echere",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "Nzoputa site na mbido",
  "hero.statPhone": "Na-arụ ọrụ na ego ọ bụla",
  "feat.title": "Ihe niile ogige chọrọ, ọzọ adịghị",
  "feat.copy": "Lobby na-arụ otu ebe dị mma. Mgboshi ọ bụla n'okpuru bụ ugbu a ngwá ọrụ.",
  "feat.qr.t": "Kọdụ otu, dabara mgbe niile",
  "feat.qr.d": "Kọdụ QR ekwesịgbị maka ọ bụla ebe. Pịa n'otu ugboro — ịgbanwe aha ebe agaghị emebi ya.",
  "feat.multi.t": "Ogige dị ọtụtụ, screen otu",
  "feat.multi.d": "Kewapụta window mee ọrụ — mkpa okwu, nweta, nweghachi — na nọmba na window ya.",
  "feat.team.t": "Njirimara dabara na ebe ahịa",
  "feat.team.d": "Kpọọ ndị ọrụ site na njikọ, jikọrị ha ebe, ka ndị nwe nwee igodo.",
  "feat.brand.t": "Dịka azụmahịa gị",
  "feat.brand.d": "Ọṅṅụ gị, aha gị na nke gị na-apụta na ego ọ bụla na TV.",
  "feat.reports.t": "Eziokwu maka efifie dị ala",
  "feat.reports.d": "Oge echere, awa e dere e dere na akuko niile — nhazi izu na-esote adịghị echefuọla.",
  "feat.pause.t": "Mechie ya n'enweghị ihe mgbagwoju anya",
  "feat.pause.d": "Kwụsị ogige site na tap ntakiri. Akara ezụrụ na-egosi ya, na ọ dịghị onye na-enweta nọmba gaa na window mechiri.",
  "flow.title": "Site n'ezụrụ ruo n'ezumike na ọtụtụ ọgụgụ anọ",
  "flow.s1.t": "Ndị ahịa na-abanye na ogige",
  "flow.s1.d": "Ha na-ascan kọdụ, họrọ ọrụ, wee nweta nọmba. Adịghị app, adịghị akaụntụ.",
  "flow.s2.t": "Ndị ọrụ na-akpọ na-esote",
  "flow.s2.d": "Buto ukwu otu na-erụhụ onye na-esote, na-emetụ aka ogige ka ọ dị mfe.",
  "flow.s3.t": "Ụlọ niile na-ahụ nchịkọta ha",
  "flow.s3.d": "Ego ọ bụla na-egosi ebe, oleka ndị dị n'ihu na oge echere — n'ozugbo, n'enweghị ịgbanwe.",
  "flow.s4.t": "Ngwugwu na-echekwa mmephechi",
  "flow.s4.d": "TV n'ebe echere na-egosi onye na-ejikọta ụgwọ na onye na-esote.",
  "dispsect.title": "Ngwugwu ga-adị na ebe echere gị",
  "dispsect.copy": "Megherie ngwugwu na browser TV ọ bụla. Nọmba ukwu, ndị ise na-esote na ogige ndị ọzọ n'anya dị ọma. Ọ na-emezi ozugbo ndị ọrụ na-eme ihe.",
  "dispsect.cta": "Lee ngwugwu dị adị",
  "dash.servingCounters": "{n} na-eje ọrụ",
};

const sw: Pack = {
  "nav.about": "Kuhusu",
  "nav.signin": "Ingia",
  "nav.setup": "Sanzili biashara yako",
  "foot.made": "Lobby, imetengenezwa na {name}.",
  "foot.mit": "Chanzo wazi chini ya leseni ya MIT.",
  "lang.title": "Chagua lugha yako",
  "lang.sub": "Unaweza kubadilisha baadaye kwa bendera kwenye kona ya juu.",
  "lang.change": "Badilisha lugha",
  "lang.done": "Imekamilika",
  "common.loading": "Inapakia…",
  "common.retry": "Jaribu tena",
  "hero.eyebrow": "Foleni kwa maduka, kliniki na saluni",
  "hero.h1a": "Chukua namba.",
  "hero.h1b": "Subiri popote.",
  "hero.lede":
    "Msamba mmoja QR kwa biashara yako. Wateja hupiga picha na kuchukua namba, kisha kuona mahali pao kwenye foleni. Wakati wao umefika, simu yao huwaambia.",
  "hero.fine":
    "Hakuna programu kwa wateja, hakuna akaunti. Chanzo wazi na hufanya kazi kwenye seva yako.",
  "demo.nowServing": "Inahudumia sasa",
  "demo.yourNumber": "Namba yako",
  "how.title": "Jinsi inavyofanya kazi",
  "how.t1": "Chapisha QR yako",
  "how.d1": "Namba moja ya kudumu kwa mlango au kaunta yako.",
  "how.t2": "Wateja huchukua namba",
  "how.d2": "Hupiga picha, huongeza jina kama wanavyotaka, hakuna kusakinisha.",
  "how.t3": "Bonyeza Call next",
  "how.d3": "Foleni husogeza, skrini yao hujiwasilisha peke yake.",
  "see.title": "Wateja wako wanaona nini",
  "see.copy":
    "Skrini moja yenye majibu yale yale kila wakati. Hufanya kazi kwenye kivutio chochote, na wakati wakipiga namba yao hubadilika kuwa It's your turn.",
  "see.youreNumber": "Namba yako ni",
  "see.peopleAhead": "Watu mbele yako",
  "see.when": "Wakati kinapotokea",
  "see.itsTurn": "Ni zamu yako!",
  "places.title": "Kwa maeneo yenye kaunta",
  "places.list":
    "Maduka ya dawa · Kliniki · Saluni · Kinyozi · Karakana · Benki · Ofisi za posta · Ofisi za serikali",
  "band.title": "Usanidi huchukua takriban dakika moja.",
  "auth.welcome": "Karibu tena",
  "auth.setupSub": "Dakika chache za kuandika, foleni yako iko tayari.",
  "auth.loginSub": "Ingia kwenye foleni yako.",
  "auth.bizName": "Jina la biashara",
  "auth.yourName": "Jina lako",
  "auth.email": "Barua pepe",
  "auth.password": "Nenosiri",
  "auth.pwHint": "Herufi 8 au zaidi.",
  "auth.creating": "Inasanzili…",
  "auth.signingIn": "Inaingia…",
  "auth.create": "Tengeneza biashara yangu",
  "auth.haveAccount": "Tayari una akaunti?",
  "auth.noAccount": "Bado huna akaunti?",
  "auth.backHome": "Rudi nyumbani",
  "err.bizName": "Weka jina la biashara yako.",
  "err.name": "Weka jina lako.",
  "err.email": "Weka barua pepe yako.",
  "err.password": "Weka nenosiri lako.",
  "err.pwLen": "Nenosiri lazima liwe na herufi 8.",
  "cust.opening": "Inafungua foleni…",
  "cust.wrong": "Kuna kitu kimeenda vibaya.",
  "cust.pausedT": "Foleni imesimama.",
  "cust.pausedB": "Biashara hii haichukui namba sasa, tafadhali angalia tena baadaye.",
  "cust.nobody": "Hakuna anayehudumia sasa",
  "cust.noOneWaiting": "hakuna anayesubiri",
  "cust.waitingN": "{n} wanasubiri",
  "cust.joinT": "Jiunge na foleni",
  "cust.nameLabel": "Jina lako (hiari)",
  "cust.joinBusy": "Inachukua namba yako…",
  "cust.joinReassure": "Hakuna programu ya kusakinisha, hakuna akaunti, namba tu.",
  "cust.youreNumber": "Namba yako ni",
  "cust.youreNext": "Ni zamu yako",
  "cust.oneAhead": "Mtu mmoja mbele yako",
  "cust.nAhead": "Watu {n} mbele yako",
  "cust.peopleWaiting": "Wanaosubiri",
  "cust.reassure": "Ukurasa huu hujiwasilisha peke yake, uiwe wazi.",
  "cust.leave": "Toka kwenye foleni",
  "cust.leaveConfirm": "Toka kwenye foleni? Utapoteza namba yako.",
  "cust.turnT": "Ni zamu yako",
  "cust.turnB": "Tafadhali nenda kwenye kaunta.",
  "cust.imHere": "Nipo hapa",
  "cust.sending": "Inatuma…",
  "cust.confirmed": "Asante, tumewaambia wako tayari.",
  "cust.done": "Imekamilika",
  "cust.servedBody": "Asante kusubiri.",
  "cust.skippedBody": "Umepishwa. Ukipo hapa, chukua namba nyingine.",
  "cust.noShowBody": "Namba hii imefungwa. Ukipo hapa, chukua namba nyingine.",
  "cust.joinAgain": "Jiunge tena",
  "cust.poweredBy": "Imeendeshwa na",
  "dash.navQueue": "Foleni",
  "dash.navQr": "QR",
  "dash.navSettings": "Mipangilio",
  "dash.signOut": "Toka",
  "dash.opening": "Inafungua foleni yako…",
  "dash.pausedB": "Wateja hawachukui namba sasa.",
  "dash.nobodyCounter": "Hakupo kwenye kaunta",
  "dash.noNameGiven": "Hakuna jina",
  "dash.confirmedHere": "amesema yuko hapa",
  "dash.notConfirmed": "hajathibitisha",
  "dash.callNext": "Ita ifuatayo",
  "dash.calling": "Inaita…",
  "dash.noWaitingHint": "Hakuna anayesubiri sasa.",
  "dash.pause": "Simamisha foleni",
  "dash.resume": "Endeleza foleni",
  "dash.atCounter": "Kwenye kaunta",
  "dash.waitingTitle": "Wanasubiri",
  "dash.noName": "Hakuna jina",
  "dash.stWait": "Wanasubiri",
  "dash.stCalled": "Inahudumia",
  "dash.stServed": "Imehudumiwa",
  "dash.stSkipped": "Imepishwa",
  "dash.stNoShow": "Hawapo",
  "dash.firstRun": "Hakuna bado. Hatua tatu fupi zitafungua foleni yako:",
  "dash.step1": "Pata QR yako. Chapisha, au iweke kwenye skrini karibu na mlango.",
  "dash.step1link": "Fungua QR yangu →",
  "dash.step2": "Wateja huchukua namba. Hupiga picha, kuandika jina, wanaingia.",
  "dash.step3": "Bonyeza Call next. Simu zao hubadilika wakati huo huo.",
  "dash.emptyWaiting": "Hakuna anayesubiri. Namba mpya zitaonekana hapa watu wanapojiunga.",
  "dash.nextUp": "Ifuatayo",
  "dash.finished": "Imekamilika",
  "dash.counts": "{s} wahudumiwa, {k} wamepishwa, {n} hawapo",
  "dash.markServed": "Weka kama imehudumiwa",
  "dash.skip": "Ruka",
  "qr.intro":
    "Chapisha hii uweke kwenye mlango au kaunta. Kiungo hiki hubadiliki, msamba ukipachika leo utaendelea kufanya kazi.",
  "qr.linkLabel": "Kiungo chako cha foleni",
  "qr.download": "Pakua PNG",
  "qr.print": "Chapisha",
  "qr.copy": "Nakili kiungo",
  "qr.copied": "Kiungo kimenakiliwa.",
  "qr.making": "Inatengeneza QR yako…",
  "qr.sheetCta": "Piga picha ili kujiunga",
  "qr.fine":
    "Wateja hupiga picha hii kuchukua namba, hakuna programu, hakuna akaunti. QR hubaki nyeupe na nyeusi kwenye mandhari yote ili simu ziweze kuisoma.",
  "set.noteLabel": "Maelezo kwa wateja",
  "set.noteHint": "Huonekana juu ya kitufe cha Join kwenye ukurasa wako. Hiari.",
  "set.save": "Hifadhi mabadiliko",
  "set.saving": "Inahifadhi…",
  "set.saved": "Imehifadhiwa.",
  "set.goodToKnow": "Ni vizuri kujua",
  "set.linkBody": "Ni ya kudumu, msamba ukipachika utaendelea kufanya kazi hata kubadilisha jina la biashara.",
  "set.signedInAs": "Umeingia kama",
  "set.errNote": "Maelezo yako yasipaze herufi 200.",
  "nf.title": "Ukurasa huu haupo.",
  "nf.body": "Umehamishika, au kiungo kimeandikwa vibaya.",
  "nf.cta": "Nenda kwenye ukurasa wa mwanzo",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "Onyesho",
  "common.live": "Moja kwa moja",
  "common.reconnecting": "Inaunganisha upya…",
  "common.offline": "Uko nje ya mtandao. Ukurasa huu vastawiwa wenyewe.",
  "common.optional": "optional",
  "common.cancel": "Ghairi",
  "common.remove": "Ondoa",
  "common.add": "Ongeza",
  "common.save": "Save",
  "common.saved": "Imehifadhiwa.",
  "common.minutes": "dakika {n}",
  "common.branch": "Eneo",
  "common.allBranches": "Maeneo yote",
  "common.back": "Back",
  "band.body": "Anza na aina ya biashara — mgahawa, kliniki, saluni, karakana — kisha ibadilishe majina. Ongeza maeneo mpya unapofungua lingine.",
  "band.try": "Angalia onyesho la moja kwa moja",
  "demo.title": "Kiona kikifanya kazi",
  "demo.sub": "Duka la kujifunza unapobonyeza vitufe. Jiunge kama mteja, wita namba kama mfanyakazi, na uone skrini ya TV. Hakuna cha kweli hapa.",
  "demo.paneCustomer": "Simu ya mteja",
  "demo.paneStaff": "Simu ya mfanyakazi",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "Skrini ya TV",
  "demo.joinName": "Jina (hiari)",
  "demo.join": "Chukua namba",
  "demo.reset": "Weka upya onyesho",
  "demo.callNext": "Mwite yule anayefuata",
  "demo.serve": "Imekamilika",
  "demo.skip": "Ruka",
  "demo.waitingList": "Waiting",
  "demo.hint": "Jaribu kuita namba na uone paneli zote nne zinasasishwa kwa wakati mmoja.",
  "auth.shopType": "Biashara ya aina gani hii?",
  "auth.shopTypeHint": "Tutatengeneza foleni na kaunta. Unaweza kubadilisha kila jina baadaye.",
  "auth.branchName": "Eneo la kwanza",
  "auth.inviteTitle": "Umealikwa",
  "auth.inviteBody": "{business} anakualika kusimamia foleni kama {role}.",
  "auth.joinTeam": "Jiunge na timu",
  "auth.inviteBad": "Mwaliko huu umekwisha. Omba jipya kwa meneja wako.",
  "cust.phoneLabel": "Simu (hiari)",
  "cust.estWait": "Kusubiri karibu dakika {n}",
  "cust.pickQueue": "Unahitaji nini?",
  "cust.pickBranch": "Eneo gani?",
  "cust.pickQueueHint": "Chagua foleni ili kupokea namba.",
  "cust.held": "Imeshikwa",
  "cust.heldBody": "Wafanyakazi watakuita hivi punde.",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "Foleni",
  "dash.navTeam": "Timu",
  "dash.navReports": "Historia",
  "dash.holdTitle": "Imeshikwa",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "Ametoka",
  "dash.hold": "Shikilia",
  "dash.release": "Rudi kwenye foleni",
  "dash.recall": "Mwite tena",
  "dash.cancel": "Remove from queue",
  "dash.move": "Hamisha",
  "dash.moveTo": "Hamisha kwenda foleni nyingine",
  "dash.call": "Mwite",
  "dash.addWalkIn": "Ongeza mteja",
  "dash.addWalkInBody": "Kwa namba za simu na watu walioko mbele yako.",
  "dash.noteLabel": "Maelezo (hiari)",
  "dash.counterLabel": "Kaunta",
  "dash.anyCounter": "Kaunta yoyote",
  "dash.avgWait": "Wastani wa kusubiri dakika {n}",
  "dash.peopleWaiting": "{n} wakisubiri",
  "dash.tvLink": "Fungua skrini ya TV",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "Tawi hili bado halina foleni.",
  "dash.pickQueue": "Chagua foleni",
  "dash.roleTag": "Wadhako: {role}",
  "dash.noPermission": "Wadhako hauwezi kufanya hivyo.",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "Foleni ya msimbo huu",
  "qr.displayLink": "Kiungo cha skrini ya TV",
  "sq.title": "Foleni na kaunta",
  "sq.sub": "Kila foleni ina namba zake na mstari wake.",
  "sq.locations": "Maeneo",
  "sq.addLocation": "Ongeza eneo",
  "sq.locationName": "Jina la eneo",
  "sq.address": "Anwani (hiari)",
  "sq.phone": "Simu (hiari)",
  "sq.noLocations": "Bado hakuna maeneo.",
  "sq.queues": "Foleni",
  "sq.addQueue": "Ongeza foleni",
  "sq.queueName": "Jina la foleni",
  "sq.prefix": "Herufi za namba",
  "sq.prefixHint": "Herufi hadi mbili kabla ya namba, kama A12.",
  "sq.description": "Foleni hii ni kwa ajili gani? (hiari)",
  "sq.avgTime": "Muda wa kawaida (dakika)",
  "sq.counters": "Kaunta",
  "sq.counterName": "Counter name",
  "sq.addCounter": "Ongeza kaunta",
  "sq.paused": "Imesimama",
  "sq.open": "Wazi",
  "sq.closed": "Closed",
  "sq.noQueues": "Bado hakuna foleni katika eneo hili.",
  "sq.deleteQueue": "Ondoa foleni hii",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "Anza na aina ya biashara",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "Wateja hawachukui namba kwenye foleni hii wakati imesimama.",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "Timu yako",
  "team.sub": "Alika wanaofanya kazi kwenye kaunta na chagua kila mmoja anaweza kufanya nini.",
  "team.invite": "Alika mtu",
  "team.invited": "Mwaliko umetumwa",
  "team.inviteEmail": "Barua pepe yao",
  "team.inviteRole": "Walivyo nneza kufanya",
  "team.pending": "Inasubiri kujiunga",
  "team.noPending": "Hakuna mwaliko unaosubiri.",
  "team.revoke": "Ghairi mwaliko",
  "team.role": "Wadhako",
  "team.roleOwner": "Mmiliki",
  "team.roleManager": "Meneja",
  "team.roleStaff": "Mfanyakazi",
  "team.roleViewer": "Kusoma tu",
  "team.remove": "Ondoa katika timu",
  "team.lock": "Toka kila mahali",
  "team.unlock": "Ruhusu kuingia",
  "team.allBranches": "Maeneo yote",
  "team.oneBranch": "One location",
  "team.pickBranch": "Eneo",
  "team.noTeam": "Kwa sasa wewe pekee yako.",
  "team.linkCopied": "Kiungo cha mwaliko kimenakiliwa. Kiwatumie.",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "Jinsi leo na wiki iliyopita zilivyokuwa kweli.",
  "rep.joined": "Namba zilizochukuliwa",
  "rep.served": "Wateja waliohudumiwa",
  "rep.avgWait": "Wastani wa kusubiri",
  "rep.avgService": "Wastani wa huduma",
  "rep.peak": "Saa ya msongamano",
  "rep.abandoned": "Walatoka bila kuhudumiwa",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "Siku 7 zilizopita",
  "rep.days30": "Siku 30 zilizopita",
  "rep.days90": "Siku 90 zilizopita",
  "rep.byDay": "Each day",
  "rep.byHour": "Saa zinazopita sana",
  "rep.byQueue": "Kila foleni",
  "rep.waited": "alisubiri dakika {n}",
  "rep.servedIn": "hudumiwa katika dakika {n}",
  "rep.history": "Kila aliyefika",
  "rep.noHistory": "Hakuna aliyepita kwenye foleni hii katika kipindi hiki.",
  "rep.audit": "Mabadiliko timu yako iliyofanya",
  "rep.noAudit": "Bado hakuna mabadiliko yaliyorekodiwa.",
  "rep.noReports": "Wadhako hauwezi kuona ripoti.",
  "set.brand": "Mwonekano",
  "set.brandHint": "Rangi na nembo yako huonekana kwenye ukurasa wa mteja na skrini ya TV.",
  "set.mainColour": "Rangi kuu",
  "set.accentColour": "Rangi ya lilele",
  "set.logo": "Nembo",
  "set.logoHint": "Bandika kiungo cha wavuti au pakia picha. Ndogo ndiyo nzuri.",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "Ondoa nembo",
  "set.security": "Nenosiri lako",
  "set.currentPassword": "Nenosiri la sasa",
  "set.newPassword": "Nenosiri jipya",
  "set.changePassword": "Badilisha nenosiri",
  "set.passwordChanged": "Nenosiri limebadilishwa. Vifaa vingine vimetoka.",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "Inaitwa sasa",
  "disp.waiting": "Wanasubiri",
  "disp.others": "Foleni nyingine",
  "disp.fullscreen": "Skrini nzima",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "Inasubiri namba ya kwanza",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "Muda wa kusubiri uliokadiriwa",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "Moja kwa moja kwa chaguomsingi",
  "hero.statPhone": "Hufanya kazi kwenye simu yoyote",
  "feat.title": "Kila kitu foleni inachohitaji, na zaidi hapana",
  "feat.copy": "Lobby hufanya kitu kimoja vizuri. Kila skrini hapa chini tayari ni sehemu ya bidhaa.",
  "feat.qr.t": "Msimbo mmoja, daima sasa",
  "feat.qr.d": "Msimbo wa QR wa kudumu kwa kila eneo. Chapisha mara moja — kubadilisha jina la duka huuvunja kamwe.",
  "feat.multi.t": "Foleni nyingi, skrini moja",
  "feat.multi.d": "Gawanya kaunta kuwa huduma — ushauri, kuchukua, kurudisha — na namba na kaunta zake.",
  "feat.team.t": "Wadhao unaofaa duka",
  "feat.team.d": "Alika wafanyakazi kwa kiungo, waweke kwenye tawi, na mifunguo ibaki kwa wamiliki.",
  "feat.brand.t": "Kama biashara yako",
  "feat.brand.d": "Rangi, nembo na maelezo yako yanaonekana kwenye simu ya kila mteja na kwenye TV.",
  "feat.reports.t": "Ukweli kwa jioni tulivu",
  "feat.reports.d": "Muda wa kusubiri, saa za msongamano na historia kamili — ratiba ya wiki ijayo si makisio tena.",
  "feat.pause.t": "Funga bila usumbufu",
  "feat.pause.d": "Simamisha foleni kwa uguso mmoja. Bango la mlango hulisha habari, na hakuna anayechukua namba kuelekea kaunta iliyofungwa.",
  "flow.title": "Kutoka mlango hadi kukamilika kwa hatua nne",
  "flow.s1.t": "Wateja kujiunga na foleni",
  "flow.s1.d": "Husoma msimbo, kuchagua huduma, na kupokea namba. Hakuna app, hakuna akaunti.",
  "flow.s2.t": "Wafanyakazi wanamwite yule anayefuata",
  "flow.s2.d": "Kitufe kikubwa hudumisha mtu anayefuata na kudumisha usawa wa foleni.",
  "flow.s3.t": "Kila mmoja anaona hali yake",
  "flow.s3.d": "Kila simu inaonya nafasi, wangapi mbele na muda wa kusubiri — moja kwa moja, bila kusasisha.",
  "flow.s4.t": "Skrini inadumisha mpangilio",
  "flow.s4.d": "TV katika sehemu ya kusubiri inaonya anayehudumiwa na atakayefuata.",
  "dispsect.title": "Skrini inayostahili sehemu yako ya kusubiri",
  "dispsect.copy": "Fungua skrini kwenye kivinjari chochote cha TV. Namba kubwa, watano wanaofuata na foleni nyingine kwa mtazamo mmoja. Husasishwa mara tu wafanyakazi wanapofanya kazi.",
  "dispsect.cta": "Ona skrini ya moja kwa moja",
  "dash.servingCounters": "{n} zinahudumia",
};

export const africa: Lang[] = [
  { code: "pcm", label: "Nigerian Pidgin English", native: "Naijá Pidgin", flag: "🇳🇬", dict: pcm },
  { code: "yo", label: "Yoruba", native: "Yorùbá", flag: "🇳🇬", dict: yo },
  { code: "ha", label: "Hausa", native: "Hausa", flag: "🇳🇬", dict: ha },
  { code: "ig", label: "Igbo", native: "Igbo", flag: "🇳🇬", dict: ig },
  { code: "sw", label: "Swahili", native: "Kiswahili", flag: "🇰🇪", dict: sw },
];
