import type { StringKey } from "./en";
import type { Lang } from "./types";

type Pack = Record<StringKey, string>;

const hi: Pack = {
  "nav.about": "परिचय",
  "nav.signin": "साइन इन",
  "nav.setup": "अपना व्यवसाय सेट करें",
  "foot.made": "Lobby, {name} द्वारा बनाया गया।",
  "foot.mit": "MIT लाइसेंस के तहत ओपन सोर्स।",
  "lang.title": "अपनी भाषा चुनें",
  "lang.sub": "इसे बाद में ऊपर दाईं ओर झंडे से बदल सकते हैं।",
  "lang.change": "भाषा बदलें",
  "lang.done": "हो गया",
  "common.loading": "लोड हो रहा है…",
  "common.retry": "फिर कोशिश करें",
  "hero.eyebrow": "दुकानों, क्लीनिकों और सैलून के लिए कतारें",
  "hero.h1a": "एक नंबर लें।",
  "hero.h1b": "जहां चाहें वहीं इंतज़ार करें।",
  "hero.lede":
    "आपके व्यवसाय के लिए एक QR कोड। ग्राहक इसे स्कैन करते हैं, नंबर लेते हैं और कतार में अपनी जगह देखते हैं। उनकी बारी आने पर उनका फ़ोन बता देता है।",
  "hero.fine":
    "ग्राहकों के लिए कोई ऐप नहीं, उनके लिए कोई अकाउंट नहीं। ओपन सोर्स और आपके अपने सर्वर पर चलता है।",
  "demo.nowServing": "अभी सेवा में",
  "demo.yourNumber": "आपका नंबर",
  "how.title": "यह कैसे काम करता है",
  "how.t1": "अपना QR कोड छापें",
  "how.d1": "आपके दरवाज़े या काउंटर के लिए एक स्थायी कोड।",
  "how.t2": "ग्राहक नंबर लेते हैं",
  "how.d2": "वे स्कैन करते हैं, चाहें तो नाम डालते हैं, कुछ इंस्टॉल नहीं करना।",
  "how.t3": "\"अगला बुलाएं\" दबाएं",
  "how.d3": "कतार आगे बढ़ती है और उनकी स्क्रीन अपने आप अपडेट होती है।",
  "see.title": "आपके ग्राहक क्या देखते हैं",
  "see.copy":
    "हर बार एक ही स्क्रीन, एक ही जवाब। किसी भी फ़ोन ब्राउज़र में चलता है, और जब आप उनका नंबर बुलाते हैं तो यह \"आपकी बारी है\" पर बदल जाता है।",
  "see.youreNumber": "आपका नंबर",
  "see.peopleAhead": "आपसे पहले लोग",
  "see.when": "जब यह होता है",
  "see.itsTurn": "आपकी बारी है!",
  "places.title": "काउंटर वाली जगहों के लिए",
  "places.list":
    "फ़ार्मेसी · क्लीनिक · सैलून · बारबर शॉप · रिपेयर शॉप · बैंक · डाकघर · सरकारी दफ़्तर",
  "band.title": "सेटअप में लगभग एक मिनट लगता है।",
  "auth.welcome": "वापसी पर स्वागत है",
  "auth.setupSub": "एक मिनट टाइप करें और आपकी कतार तैयार।",
  "auth.loginSub": "अपनी कतार में साइन इन करें।",
  "auth.bizName": "व्यवसाय का नाम",
  "auth.yourName": "आपका नाम",
  "auth.email": "ईमेल",
  "auth.password": "पासवर्ड",
  "auth.pwHint": "कम से कम 8 अक्षर।",
  "auth.creating": "सेट हो रहा है…",
  "auth.signingIn": "साइन इन हो रहा है…",
  "auth.create": "मेरा व्यवसाय बनाएं",
  "auth.haveAccount": "पहले से अकाउंट है?",
  "auth.noAccount": "अभी अकाउंट नहीं है?",
  "auth.backHome": "होम पर वापस",
  "err.bizName": "अपने व्यवसाय का नाम डालें।",
  "err.name": "अपना नाम डालें।",
  "err.email": "अपना ईमेल डालें।",
  "err.password": "अपना पासवर्ड डालें।",
  "err.pwLen": "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए।",
  "cust.opening": "कतार खुल रही है…",
  "cust.wrong": "कुछ गड़बड़ हो गई।",
  "cust.pausedT": "कतार रुकी हुई है।",
  "cust.pausedB": "यह व्यवसाय अभी नंबर नहीं दे रहा, जल्दी फिर देखें।",
  "cust.nobody": "अभी किसे सेवा नहीं दी जा रही",
  "cust.noOneWaiting": "कोई इंतज़ार नहीं कर रहा",
  "cust.waitingN": "{n} इंतज़ार में",
  "cust.joinT": "कतार में शामिल हों",
  "cust.nameLabel": "आपका नाम (वैकल्पिक)",
  "cust.joinBusy": "आपका नंबर लिया जा रहा है…",
  "cust.joinReassure": "न ऐप, न अकाउंट, बस एक नंबर।",
  "cust.youreNumber": "आपका नंबर",
  "cust.youreNext": "आप अगले हैं",
  "cust.oneAhead": "आपसे पहले 1 व्यक्ति",
  "cust.nAhead": "आपसे पहले {n} लोग",
  "cust.peopleWaiting": "इंतज़ार कर रहे लोग",
  "cust.reassure": "यह पेज अपने आप अपडेट होता है, इसे खुला रखें।",
  "cust.leave": "कतार छोड़ें",
  "cust.leaveConfirm": "कतार छोड़ें? आप अपना नंबर खो देंगे।",
  "cust.turnT": "आपकी बारी है",
  "cust.turnB": "कृपया काउंटर पर आएं।",
  "cust.imHere": "मैं यहां हूं",
  "cust.sending": "भेजा जा रहा है…",
  "cust.confirmed": "धन्यवाद, हमने उन्हें बता दिया है कि आप तैयार हैं।",
  "cust.done": "सब हो गया",
  "cust.servedBody": "इंतज़ार के लिए धन्यवाद।",
  "cust.skippedBody": "आपको छोड़ दिया गया। अब भी यहीं हैं तो दूसरा नंबर लें।",
  "cust.noShowBody": "यह नंबर बंद हो गया। अब भी यहीं हैं तो दूसरा नंबर लें।",
  "cust.joinAgain": "फिर से शामिल हों",
  "cust.poweredBy": "संचालित",
  "dash.navQueue": "कतार",
  "dash.navQr": "QR कोड",
  "dash.navSettings": "सेटिंग्स",
  "dash.signOut": "साइन आउट",
  "dash.opening": "आपकी कतार खुल रही है…",
  "dash.pausedB": "ग्राहक अभी नंबर नहीं ले सकते।",
  "dash.nobodyCounter": "काउंटर पर कोई नहीं",
  "dash.noNameGiven": "बिना नाम",
  "dash.confirmedHere": "ने कहा है कि वे यहां हैं",
  "dash.notConfirmed": "ने अभी पुष्टि नहीं की",
  "dash.callNext": "अगला बुलाएं",
  "dash.calling": "बुला रहे हैं…",
  "dash.noWaitingHint": "अभी कोई इंतज़ार नहीं कर रहा।",
  "dash.pause": "कतार रोकें",
  "dash.resume": "कतार चालू करें",
  "dash.atCounter": "काउंटर पर",
  "dash.waitingTitle": "इंतज़ार में",
  "dash.noName": "बिना नाम",
  "dash.stWait": "इंतज़ार में",
  "dash.stCalled": "सेवा में",
  "dash.stServed": "पूरा हुआ",
  "dash.stSkipped": "छोड़ा गया",
  "dash.stNoShow": "नहीं आए",
  "dash.firstRun": "अभी तक कोई नहीं है। तीन तेज़ कदम और आपकी कतार चालू:",
  "dash.step1": "अपना QR कोड लें। छापें या दरवाज़े के पास स्क्रीन पर लगाएं।",
  "dash.step1link": "मेरा QR कोड खोलें →",
  "dash.step2": "ग्राहक नंबर लेते हैं। स्कैन करते हैं, वैकल्पिक नाम डालते हैं और शामिल हो जाते हैं।",
  "dash.step3": "\"अगला बुलाएं\" दबाएं। उनका फ़ोन उसी पल अपडेट होता है।",
  "dash.emptyWaiting": "कोई इंतज़ार नहीं कर रहा। लोगों के आने पर नए नंबर यहां दिखते हैं।",
  "dash.nextUp": "अगला",
  "dash.finished": "पूरे हुए",
  "dash.counts": "{s} पूरे, {k} छोड़े गए, {n} नहीं आए",
  "dash.markServed": "पूरा चिह्नित करें",
  "dash.skip": "छोड़ें",
  "qr.intro":
    "इसे छापें और दरवाज़े या काउंटर पर लगाएं। लिंक कभी नहीं बदलता, आज छापा कोड हमेशा काम करता रहेगा।",
  "qr.linkLabel": "आपका कतार लिंक",
  "qr.download": "PNG डाउनलोड करें",
  "qr.print": "छापें",
  "qr.copy": "लिंक कॉपी करें",
  "qr.copied": "लिंक कॉपी हो गया।",
  "qr.making": "आपका QR कोड बन रहा है…",
  "qr.sheetCta": "कतार में शामिल होने के लिए स्कैन करें",
  "qr.fine":
    "ग्राहक बिना ऐप और अकाउंट के नंबर लेने के लिए स्कैन करते हैं। QR हर थीम में काला और सफ़ेद रहता है ताकि फ़ोन इसे पढ़ सकें।",
  "set.noteLabel": "ग्राहकों के लिए नोट",
  "set.noteHint": "आपके कतार पेज पर शामिल हों बटन के ऊपर दिखता है। वैकल्पिक।",
  "set.save": "बदलाव सहेजें",
  "set.saving": "सहेजा जा रहा है…",
  "set.saved": "सहेजा गया।",
  "set.goodToKnow": "जान लें",
  "set.linkBody": "यह स्थायी है, छापा हुआ QR नाम बदलने पर भी चलता रहेगा।",
  "set.signedInAs": "साइन इन किया",
  "set.errNote": "आपका नोट 200 अक्षरों या उससे कम का होना चाहिए।",
  "nf.title": "यह पेज मौजूद नहीं है।",
  "nf.body": "शायद यह हट गया है, या लिंक गलत लिखा गया है।",
  "nf.cta": "होम पेज पर जाएं",
};

const id: Pack = {
  "nav.about": "Tentang",
  "nav.signin": "Masuk",
  "nav.setup": "Siapkan bisnis Anda",
  "foot.made": "Lobby, dibuat oleh {name}.",
  "foot.mit": "Sumber terbuka dengan lisensi MIT.",
  "lang.title": "Pilih bahasa Anda",
  "lang.sub": "Anda bisa mengubahnya nanti lewat bendera di pojok kanan atas.",
  "lang.change": "Ganti bahasa",
  "lang.done": "Selesai",
  "common.loading": "Memuat…",
  "common.retry": "Coba lagi",
  "hero.eyebrow": "Antrean untuk toko, klinik, dan salon",
  "hero.h1a": "Ambil nomor.",
  "hero.h1b": "Tunggu di mana saja.",
  "hero.lede":
    "Satu QR code untuk bisnis Anda. Pelanggan memindainya, mengambil nomor, dan melihat posisi mereka di antrean. Saat giliran mereka, ponsel mereka memberi tahu.",
  "hero.fine":
    "Tanpa aplikasi untuk pelanggan, tanpa akun untuk mereka. Sumber terbuka dan berjalan di server Anda sendiri.",
  "demo.nowServing": "Sedang dilayani",
  "demo.yourNumber": "Nomor Anda",
  "how.title": "Cara kerjanya",
  "how.t1": "Cetak QR code Anda",
  "how.d1": "Satu kode permanen untuk pintu atau meja kasir Anda.",
  "how.t2": "Pelanggan mengambil nomor",
  "how.d2": "Mereka memindai, menambahkan nama jika mau, tanpa apa pun untuk dipasang.",
  "how.t3": "Tekan Panggil berikutnya",
  "how.d3": "Antrean berjalan dan layar mereka diperbarui sendiri.",
  "see.title": "Yang dilihat pelanggan Anda",
  "see.copy":
    "Satu layar dengan jawaban yang sama setiap saat. Berjalan di browser ponsel mana pun, dan saat Anda memanggil nomor mereka, layarnya berubah menjadi Giliran Anda.",
  "see.youreNumber": "Nomor Anda",
  "see.peopleAhead": "Orang sebelum Anda",
  "see.when": "Saat waktunya tiba",
  "see.itsTurn": "Giliran Anda!",
  "places.title": "Untuk tempat dengan meja kasir",
  "places.list":
    "Apotek · Klinik · Salon · Pangkas rambut · Bengkel · Bank · Kantor pos · Kantor pemerintah",
  "band.title": "Pengaturan butuh sekitar satu menit.",
  "auth.welcome": "Selamat datang kembali",
  "auth.setupSub": "Sebentar mengetik dan antrean Anda siap.",
  "auth.loginSub": "Masuk ke antrean Anda.",
  "auth.bizName": "Nama bisnis",
  "auth.yourName": "Nama Anda",
  "auth.email": "Email",
  "auth.password": "Kata sandi",
  "auth.pwHint": "Minimal 8 karakter.",
  "auth.creating": "Menyiapkan…",
  "auth.signingIn": "Masuk…",
  "auth.create": "Buat bisnis saya",
  "auth.haveAccount": "Sudah punya akun?",
  "auth.noAccount": "Belum punya akun?",
  "auth.backHome": "Kembali ke beranda",
  "err.bizName": "Masukkan nama bisnis Anda.",
  "err.name": "Masukkan nama Anda.",
  "err.email": "Masukkan email Anda.",
  "err.password": "Masukkan kata sandi Anda.",
  "err.pwLen": "Kata sandi harus minimal 8 karakter.",
  "cust.opening": "Membuka antrean…",
  "cust.wrong": "Ada yang tidak beres.",
  "cust.pausedT": "Antrean dijeda.",
  "cust.pausedB": "Bisnis ini sedang tidak menerima nomor, coba lagi nanti.",
  "cust.nobody": "Belum ada yang dilayani",
  "cust.noOneWaiting": "tidak ada yang menunggu",
  "cust.waitingN": "{n} menunggu",
  "cust.joinT": "Ikut antrean",
  "cust.nameLabel": "Nama Anda (opsional)",
  "cust.joinBusy": "Mengambil nomor Anda…",
  "cust.joinReassure": "Tanpa aplikasi, tanpa akun, hanya nomor.",
  "cust.youreNumber": "Nomor Anda",
  "cust.youreNext": "Anda berikutnya",
  "cust.oneAhead": "1 orang sebelum Anda",
  "cust.nAhead": "{n} orang sebelum Anda",
  "cust.peopleWaiting": "Sedang menunggu",
  "cust.reassure": "Halaman ini memperbarui sendiri, biarkan terbuka.",
  "cust.leave": "Keluar dari antrean",
  "cust.leaveConfirm": "Keluar dari antrean? Anda akan kehilangan nomor Anda.",
  "cust.turnT": "Giliran Anda",
  "cust.turnB": "Silakan menuju meja kasir.",
  "cust.imHere": "Saya di sini",
  "cust.sending": "Mengirim…",
  "cust.confirmed": "Terima kasih, kami sudah memberi tahu mereka Anda siap.",
  "cust.done": "Selesai",
  "cust.servedBody": "Terima kasih sudah menunggu.",
  "cust.skippedBody": "Anda dilewati. Jika masih di sini, ambil nomor lain.",
  "cust.noShowBody": "Nomor ini sudah ditutup. Jika masih di sini, ambil nomor lain.",
  "cust.joinAgain": "Ikut lagi",
  "cust.poweredBy": "Didukung oleh",
  "dash.navQueue": "Antrean",
  "dash.navQr": "QR code",
  "dash.navSettings": "Pengaturan",
  "dash.signOut": "Keluar",
  "dash.opening": "Membuka antrean Anda…",
  "dash.pausedB": "Pelanggan sedang tidak bisa mengambil nomor.",
  "dash.nobodyCounter": "Tidak ada di meja kasir",
  "dash.noNameGiven": "Tanpa nama",
  "dash.confirmedHere": "bilang sedang di sini",
  "dash.notConfirmed": "belum mengonfirmasi",
  "dash.callNext": "Panggil berikutnya",
  "dash.calling": "Memanggil…",
  "dash.noWaitingHint": "Tidak ada yang menunggu saat ini.",
  "dash.pause": "Jeda antrean",
  "dash.resume": "Lanjutkan antrean",
  "dash.atCounter": "Di meja kasir",
  "dash.waitingTitle": "Menunggu",
  "dash.noName": "Tanpa nama",
  "dash.stWait": "Menunggu",
  "dash.stCalled": "Dilayani",
  "dash.stServed": "Selesai dilayani",
  "dash.stSkipped": "Dilewati",
  "dash.stNoShow": "Tidak hadir",
  "dash.firstRun": "Belum ada siapa pun. Tiga langkah cepat dan antrean Anda jalan:",
  "dash.step1": "Ambil QR code Anda. Cetak atau taruh di layar dekat pintu.",
  "dash.step1link": "Buka QR code saya →",
  "dash.step2": "Pelanggan mengambil nomor. Mereka memindai, mengetik nama, lalu masuk.",
  "dash.step3": "Tekan Panggil berikutnya. Ponsel mereka langsung diperbarui.",
  "dash.emptyWaiting": "Tidak ada yang menunggu. Nomor baru muncul di sini saat orang datang.",
  "dash.nextUp": "Berikutnya",
  "dash.finished": "Selesai",
  "dash.counts": "{s} selesai dilayani, {k} dilewati, {n} tidak hadir",
  "dash.markServed": "Tandai sudah dilayani",
  "dash.skip": "Lewati",
  "qr.intro":
    "Cetak ini dan taruh di pintu atau meja kasir. Tautannya tidak pernah berubah, kode yang Anda cetak hari ini tetap berfungsi.",
  "qr.linkLabel": "Tautan antrean Anda",
  "qr.download": "Unduh PNG",
  "qr.print": "Cetak",
  "qr.copy": "Salin tautan",
  "qr.copied": "Tautan disalin.",
  "qr.making": "Membuat QR code Anda…",
  "qr.sheetCta": "Pindai untuk ikut antrean",
  "qr.fine":
    "Pelanggan memindai untuk mengambil nomor, tanpa aplikasi dan tanpa akun. QR tetap hitam putih di semua tema agar ponsel bisa membacanya.",
  "set.noteLabel": "Catatan untuk pelanggan",
  "set.noteHint": "Tampil di atas tombol Ikut di halaman antrean Anda. Opsional.",
  "set.save": "Simpan perubahan",
  "set.saving": "Menyimpan…",
  "set.saved": "Tersimpan.",
  "set.goodToKnow": "Perlu diketahui",
  "set.linkBody": "Tautannya permanen, QR cetak tetap berfungsi meski nama bisnis diganti.",
  "set.signedInAs": "Masuk sebagai",
  "set.errNote": "Catatan Anda maksimal 200 karakter.",
  "nf.title": "Halaman ini tidak ada.",
  "nf.body": "Mungkin sudah dipindah, atau tautannya salah ketik.",
  "nf.cta": "Ke halaman beranda",
};

const zh: Pack = {
  "nav.about": "关于",
  "nav.signin": "登录",
  "nav.setup": "设置你的店铺",
  "foot.made": "Lobby，由 {name} 制作。",
  "foot.mit": "MIT 许可证下的开源软件。",
  "lang.title": "选择你的语言",
  "lang.sub": "之后可以点击右上角的国旗随时更换。",
  "lang.change": "切换语言",
  "lang.done": "完成",
  "common.loading": "加载中…",
  "common.retry": "重试",
  "hero.eyebrow": "为商店、诊所和美容院打造的排队系统",
  "hero.h1a": "取一个号码。",
  "hero.h1b": "在哪里等都行。",
  "hero.lede":
    "你的店只需一个二维码。顾客扫码取号，随时看到自己在队中的位置。轮到他们时，手机会提醒他们。",
  "hero.fine": "顾客不用装应用，也不用注册账号。开源软件，运行在你自己的服务器上。",
  "demo.nowServing": "正在服务",
  "demo.yourNumber": "你的号码",
  "how.title": "使用方法",
  "how.t1": "打印你的二维码",
  "how.d1": "一个永久有效的码，贴在门口或柜台。",
  "how.t2": "顾客取号",
  "how.d2": "扫码即可，想写名字就写，什么都不用安装。",
  "how.t3": "按下“呼叫下一位”",
  "how.d3": "队伍前进，他们的屏幕自动更新。",
  "see.title": "顾客看到的界面",
  "see.copy":
    "一块屏幕，永远回答同样的问题。任何手机浏览器都能打开，你呼叫号码时它会变成“轮到你了”。",
  "see.youreNumber": "你的号码",
  "see.peopleAhead": "前面还有几人",
  "see.when": "轮到时",
  "see.itsTurn": "轮到你了！",
  "places.title": "适合有柜台的地方",
  "places.list": "药店 · 诊所 · 美容院 · 理发店 · 维修店 · 银行 · 邮局 · 政府办事窗口",
  "band.title": "大约一分钟即可完成设置。",
  "auth.welcome": "欢迎回来",
  "auth.setupSub": "输入一分钟，排队即可开始。",
  "auth.loginSub": "登录你的排队页面。",
  "auth.bizName": "店铺名称",
  "auth.yourName": "你的名字",
  "auth.email": "邮箱",
  "auth.password": "密码",
  "auth.pwHint": "至少 8 个字符。",
  "auth.creating": "正在创建…",
  "auth.signingIn": "正在登录…",
  "auth.create": "创建我的店铺",
  "auth.haveAccount": "已经有账号了？",
  "auth.noAccount": "还没有账号？",
  "auth.backHome": "返回首页",
  "err.bizName": "请输入店铺名称。",
  "err.name": "请输入你的名字。",
  "err.email": "请输入邮箱。",
  "err.password": "请输入密码。",
  "err.pwLen": "密码至少需要 8 个字符。",
  "cust.opening": "正在打开排队页面…",
  "cust.wrong": "出了点问题。",
  "cust.pausedT": "排队已暂停。",
  "cust.pausedB": "这家店暂时不发号了，请稍后再来看看。",
  "cust.nobody": "暂时还没有人被服务",
  "cust.noOneWaiting": "无人等待",
  "cust.waitingN": "{n} 人等待中",
  "cust.joinT": "加入排队",
  "cust.nameLabel": "你的名字（可不填）",
  "cust.joinBusy": "正在取号…",
  "cust.joinReassure": "不用装应用，不用注册，只要一个号码。",
  "cust.youreNumber": "你的号码",
  "cust.youreNext": "下一位就是你",
  "cust.oneAhead": "前面还有 1 人",
  "cust.nAhead": "前面还有 {n} 人",
  "cust.peopleWaiting": "等待人数",
  "cust.reassure": "此页面会自动更新，请保持打开。",
  "cust.leave": "离开队伍",
  "cust.leaveConfirm": "离开队伍？你会失去当前号码。",
  "cust.turnT": "轮到你了",
  "cust.turnB": "请到柜台来。",
  "cust.imHere": "我到了",
  "cust.sending": "发送中…",
  "cust.confirmed": "谢谢，我们已经告诉他们你准备好了。",
  "cust.done": "全部完成",
  "cust.servedBody": "感谢等待。",
  "cust.skippedBody": "你被跳过了。如果还在，请重新取号。",
  "cust.noShowBody": "这个号码已关闭。如果还在，请重新取号。",
  "cust.joinAgain": "重新排队",
  "cust.poweredBy": "由",
  "dash.navQueue": "排队",
  "dash.navQr": "二维码",
  "dash.navSettings": "设置",
  "dash.signOut": "退出登录",
  "dash.opening": "正在打开你的排队页面…",
  "dash.pausedB": "顾客现在无法取号。",
  "dash.nobodyCounter": "柜台没有人",
  "dash.noNameGiven": "没有名字",
  "dash.confirmedHere": "说已经到了",
  "dash.notConfirmed": "还没有确认",
  "dash.callNext": "呼叫下一位",
  "dash.calling": "呼叫中…",
  "dash.noWaitingHint": "现在没有人等待。",
  "dash.pause": "暂停排队",
  "dash.resume": "恢复排队",
  "dash.atCounter": "柜台服务中",
  "dash.waitingTitle": "等待中",
  "dash.noName": "没有名字",
  "dash.stWait": "等待中",
  "dash.stCalled": "服务中",
  "dash.stServed": "已服务",
  "dash.stSkipped": "已跳过",
  "dash.stNoShow": "未到场",
  "dash.firstRun": "现在还没人。三步就能让排队开始运转：",
  "dash.step1": "拿到你的二维码。打印出来，或放在门口的屏幕上。",
  "dash.step1link": "打开我的二维码 →",
  "dash.step2": "顾客取号：扫码、可选填名字，然后就排上了。",
  "dash.step3": "按下“呼叫下一位”，他们的手机立刻更新。",
  "dash.emptyWaiting": "没人等待。随着客人到来，新号码会出现在这里。",
  "dash.nextUp": "下一位",
  "dash.finished": "已完成",
  "dash.counts": "已服务 {s}，跳过 {k}，未到场 {n}",
  "dash.markServed": "标记为已服务",
  "dash.skip": "跳过",
  "qr.intro": "打印并贴在门口或柜台上。链接永不变，今天打印的码一直有效。",
  "qr.linkLabel": "你的排队链接",
  "qr.download": "下载 PNG",
  "qr.print": "打印",
  "qr.copy": "复制链接",
  "qr.copied": "链接已复制。",
  "qr.making": "正在生成二维码…",
  "qr.sheetCta": "扫码加入排队",
  "qr.fine": "顾客扫码即可取号，无需应用和账号。二维码在所有主题下都是黑白的，方便手机识别。",
  "set.noteLabel": "给顾客的留言",
  "set.noteHint": "显示在排队页“加入”按钮上方，可不填。",
  "set.save": "保存修改",
  "set.saving": "保存中…",
  "set.saved": "已保存。",
  "set.goodToKnow": "小提示",
  "set.linkBody": "链接是永久的，即使你改了店名，打印过的二维码依然有效。",
  "set.signedInAs": "登录身份",
  "set.errNote": "留言最多 200 个字符。",
  "nf.title": "这个页面不存在。",
  "nf.body": "它可能被移动了，或者链接输错了。",
  "nf.cta": "回到首页",
};

const ja: Pack = {
  "nav.about": "このアプリについて",
  "nav.signin": "ログイン",
  "nav.setup": "店舗を設定する",
  "foot.made": "Lobby は {name} が制作しました。",
  "foot.mit": "MIT ライセンスのオープンソース。",
  "lang.title": "言語を選んでください",
  "lang.sub": "あとから右上の旗から変更できます。",
  "lang.change": "言語を変更",
  "lang.done": "完了",
  "common.loading": "読み込み中…",
  "common.retry": "もう一度試す",
  "hero.eyebrow": "お店・クリニック・サロンのための順番待ち",
  "hero.h1a": "番号を取ります。",
  "hero.h1b": "どこで待ってもOK。",
  "hero.lede":
    "お店に必要なのは QR コードひとつ。お客さんが読み取って番号を取得し、順番をいつでも確認できます。番が回るとスマホが知らせます。",
  "hero.fine":
    "お客さんにアプリもアカウントも不要。オープンソースで、ご自身のサーバーで動きます。",
  "demo.nowServing": "今お呼びしている番号",
  "demo.yourNumber": "あなたの番号",
  "how.title": "使い方",
  "how.t1": "QR コードを印刷する",
  "how.d1": "入口やカウンターに貼れる、変わらない番号札です。",
  "how.t2": "お客さんが番号を取る",
  "how.d2": "読み取って、任意で名前を入力。インストールは一切不要。",
  "how.t3": "「次の方を呼ぶ」を押す",
  "how.d3": "列が進み、画面は自動で更新されます。",
  "see.title": "お客さんの画面",
  "see.copy":
    "いつも同じ答えを出す画面がひとつ。スマホのブラウザで動いて、番号を呼ぶと「あなたの番です」に変わります。",
  "see.youreNumber": "あなたの番号",
  "see.peopleAhead": "前の人数",
  "see.when": "そのとき",
  "see.itsTurn": "あなたの番です！",
  "places.title": "カウンターのある場所へ",
  "places.list": "薬局 · 診療所 · 美容室 · バーバー · 修理店 · 銀行 · 郵便局 · 公共機関",
  "band.title": "設定は約1分です。",
  "auth.welcome": "おかえりなさい",
  "auth.setupSub": "少し入力するだけで、順番待ちの準備ができました。",
  "auth.loginSub": "順番待ちにログインします。",
  "auth.bizName": "店名",
  "auth.yourName": "お名前",
  "auth.email": "メール",
  "auth.password": "パスワード",
  "auth.pwHint": "8文字以上。",
  "auth.creating": "作成中…",
  "auth.signingIn": "ログイン中…",
  "auth.create": "店舗を作成する",
  "auth.haveAccount": "アカウントをお持ちですか？",
  "auth.noAccount": "まだアカウントがありませんか？",
  "auth.backHome": "ホームに戻る",
  "err.bizName": "店名を入力してください。",
  "err.name": "お名前を入力してください。",
  "err.email": "メールアドレスを入力してください。",
  "err.password": "パスワードを入力してください。",
  "err.pwLen": "パスワードは8文字以上にしてください。",
  "cust.opening": "順番待ちを開いています…",
  "cust.wrong": "何か問題が起きました。",
  "cust.pausedT": "順番待ちは一時停止中です。",
  "cust.pausedB": "このお店は今番号を出していません。しばらくしてまたご確認ください。",
  "cust.nobody": "まだ誰も呼ばれていません",
  "cust.noOneWaiting": "待機中の人はいません",
  "cust.waitingN": "{n}人が待機中",
  "cust.joinT": "順番待ちに参加",
  "cust.nameLabel": "お名前（任意）",
  "cust.joinBusy": "番号を取得しています…",
  "cust.joinReassure": "アプリ不要、アカウント不要、番号だけ。",
  "cust.youreNumber": "あなたの番号",
  "cust.youreNext": "次はあなたです",
  "cust.oneAhead": "前に1人",
  "cust.nAhead": "前に{n}人",
  "cust.peopleWaiting": "待機人数",
  "cust.reassure": "この画面は自動で更新されます。開いたままにしてください。",
  "cust.leave": "列をやめる",
  "cust.leaveConfirm": "列をやめますか？ 番号は失われます。",
  "cust.turnT": "あなたの番です",
  "cust.turnB": "カウンターへお越しください。",
  "cust.imHere": "来ました",
  "cust.sending": "送信中…",
  "cust.confirmed": "ありがとうございます。準備ができた旨を伝えました。",
  "cust.done": "完了",
  "cust.servedBody": "お待ちいただきありがとうございました。",
  "cust.skippedBody": "スキップされました。まだいる方は別の番号をどうぞ。",
  "cust.noShowBody": "この番号は終了しました。まだいる方は別の番号をどうぞ。",
  "cust.joinAgain": "もう一度参加",
  "cust.poweredBy": "提供",
  "dash.navQueue": "順番待ち",
  "dash.navQr": "QR コード",
  "dash.navSettings": "設定",
  "dash.signOut": "ログアウト",
  "dash.opening": "順番待ちを開いています…",
  "dash.pausedB": "お客さんは今番号を取れません。",
  "dash.nobodyCounter": "カウンターに誰もいません",
  "dash.noNameGiven": "名前なし",
  "dash.confirmedHere": "さんが来場済みです",
  "dash.notConfirmed": "さんが未確認です",
  "dash.callNext": "次の方を呼ぶ",
  "dash.calling": "呼んでいます…",
  "dash.noWaitingHint": "今は待機中の人がいません。",
  "dash.pause": "一時停止",
  "dash.resume": "再開する",
  "dash.atCounter": "カウンターで対応中",
  "dash.waitingTitle": "待機中",
  "dash.noName": "名前なし",
  "dash.stWait": "待機中",
  "dash.stCalled": "対応中",
  "dash.stServed": "対応済み",
  "dash.stSkipped": "スキップ",
  "dash.stNoShow": "不在",
  "dash.firstRun": "まだ誰もいません。3つのステップで順番待ちが動き出します：",
  "dash.step1": "QR コードを入手。印刷するか、入口付近の画面に表示します。",
  "dash.step1link": "QR コードを開く →",
  "dash.step2": "お客さんが番号を取得。読み取り、任意で名前を入力するだけ。",
  "dash.step3": "「次の方を呼ぶ」を押すと、その場で画面が更新されます。",
  "dash.emptyWaiting": "待機中の人はいません。人が来るたびに新しい番号がここに表示されます。",
  "dash.nextUp": "次",
  "dash.finished": "終了した番号",
  "dash.counts": "対応 {s}、スキップ {k}、不在 {n}",
  "dash.markServed": "対応済みにする",
  "dash.skip": "スキップ",
  "qr.intro": "印刷して入口やカウンターへ。リンクは永遠に変わらないので、今日印刷したコードもずっと使えます。",
  "qr.linkLabel": "順番待ちのリンク",
  "qr.download": "PNG をダウンロード",
  "qr.print": "印刷",
  "qr.copy": "リンクをコピー",
  "qr.copied": "リンクをコピーしました。",
  "qr.making": "QR コードを作成中…",
  "qr.sheetCta": "読み取って順番待ちに参加",
  "qr.fine": "お客さんは読み取るだけで番号を取得できます。アプリもアカウントも不要。どんなテーマでも黒白のまま、スマホが読み取れます。",
  "set.noteLabel": "お客さんへのひとこと",
  "set.noteHint": "順番待ちページの参加ボタンの上に表示されます。任意です。",
  "set.save": "変更を保存",
  "set.saving": "保存中…",
  "set.saved": "保存しました。",
  "set.goodToKnow": "覚えておくと便利",
  "set.linkBody": "リンクは固定です。店名を変えても、印刷した QR は動き続けます。",
  "set.signedInAs": "ログイン中",
  "set.errNote": "ひとっことは200文字以内にしてください。",
  "nf.title": "このページは存在しません。",
  "nf.body": "移動したか、リンクを打ち間違えたようです。",
  "nf.cta": "ホームページへ",
};

const ko: Pack = {
  "nav.about": "소개",
  "nav.signin": "로그인",
  "nav.setup": "가게 설정하기",
  "foot.made": "Lobby, {name}이 만들었습니다.",
  "foot.mit": "MIT 라이선스의 오픈 소스.",
  "lang.title": "언어를 선택하세요",
  "lang.sub": "나중에 오른쪽 위 깃발에서 변경할 수 있습니다.",
  "lang.change": "언어 변경",
  "lang.done": "완료",
  "common.loading": "불러오는 중…",
  "common.retry": "다시 시도",
  "hero.eyebrow": "상점, 클리닉, 미용실을 위한 대기줄",
  "hero.h1a": "번호를 받으세요.",
  "hero.h1b": "어디서든 기다리세요.",
  "hero.lede":
    "가게에 QR 코드 하나면 충분합니다. 손님이 스캔해 번호를 받고 대기 순서를 확인합니다. 차례가 되면 휴대폰이 알려줍니다.",
  "hero.fine":
    "손에게는 앱도, 계정도 필요 없습니다. 오픈 소스이고 내 서버에서 돌아갑니다.",
  "demo.nowServing": "지금 호출 중",
  "demo.yourNumber": "내 번호",
  "how.title": "사용 방법",
  "how.t1": "QR 코드를 인쇄하세요",
  "how.d1": "출입문이나 계산대에 붙일 영구 코드 하나.",
  "how.t2": "손님이 번호를 받습니다",
  "how.d2": "스캔하고, 원하면 이름을 적고, 설치할 것 없음.",
  "how.t3": "\"다음 호출\"을 누르세요",
  "how.d3": "줄이 움직이고 화면은 저절로 갱신됩니다.",
  "see.title": "손님이 보는 화면",
  "see.copy":
    "항상 같은 답을 주는 화면 하나. 모든 휴대폰 브라우저에서 열리고, 번호를 부르면 \"내 차례\"로 바뀝니다.",
  "see.youreNumber": "내 번호",
  "see.peopleAhead": "내 앞 인원",
  "see.when": "그 순간",
  "see.itsTurn": "내 차례입니다!",
  "places.title": "카운터가 있는 곳이면 어디든",
  "places.list": "약국 · 클리닉 · 미용실 · 이발소 · 수리점 · 은행 · 우체국 · 관공서",
  "band.title": "설정은 1분이면 끝납니다.",
  "auth.welcome": "다시 오신 것을 환영합니다",
  "auth.setupSub": "잠깐 입력하면 대기줄이 준비됩니다.",
  "auth.loginSub": "대기줄에 로그인하세요.",
  "auth.bizName": "가게 이름",
  "auth.yourName": "이름",
  "auth.email": "이메일",
  "auth.password": "비밀번호",
  "auth.pwHint": "8자 이상.",
  "auth.creating": "만드는 중…",
  "auth.signingIn": "로그인 중…",
  "auth.create": "내 가게 만들기",
  "auth.haveAccount": "이미 계정이 있나요?",
  "auth.noAccount": "아직 계정이 없나요?",
  "auth.backHome": "홈으로 돌아가기",
  "err.bizName": "가게 이름을 입력하세요.",
  "err.name": "이름을 입력하세요.",
  "err.email": "이메일을 입력하세요.",
  "err.password": "비밀번호를 입력하세요.",
  "err.pwLen": "비밀번호는 8자 이상이어야 합니다.",
  "cust.opening": "대기줄을 여는 중…",
  "cust.wrong": "문제가 생겼습니다.",
  "cust.pausedT": "대기줄이 일시정지되었습니다.",
  "cust.pausedB": "이 가게는 지금 번호를 받지 않습니다. 잠시 후 다시 확인해 주세요.",
  "cust.nobody": "아직 호출된 사람이 없습니다",
  "cust.noOneWaiting": "기다리는 사람 없음",
  "cust.waitingN": "{n}명 대기",
  "cust.joinT": "대기줄에 합류",
  "cust.nameLabel": "이름 (선택)",
  "cust.joinBusy": "번호를 받는 중…",
  "cust.joinReassure": "앱도, 계정도 없이 번호만.",
  "cust.youreNumber": "내 번호",
  "cust.youreNext": "다음은 당신",
  "cust.oneAhead": "내 앞에 1명",
  "cust.nAhead": "내 앞에 {n}명",
  "cust.peopleWaiting": "대기 인원",
  "cust.reassure": "이 화면은 스스로 갱신됩니다. 켜둔 채로 두세요.",
  "cust.leave": "대기줄 나가기",
  "cust.leaveConfirm": "대기줄을 나가시겠어요? 번호를 잃게 됩니다.",
  "cust.turnT": "내 차례입니다",
  "cust.turnB": "카운터로 와 주세요.",
  "cust.imHere": "도착했습니다",
  "cust.sending": "보내는 중…",
  "cust.confirmed": "감사합니다. 준비되었다고 전했습니다.",
  "cust.done": "완료",
  "cust.servedBody": "기다려 주셔서 감사합니다.",
  "cust.skippedBody": "건너뛰었습니다. 아직 계시면 새 번호를 받으세요.",
  "cust.noShowBody": "이 번호는 마감되었습니다. 아직 계시면 새 번호를 받으세요.",
  "cust.joinAgain": "다시 합류",
  "cust.poweredBy": "제공",
  "dash.navQueue": "대기줄",
  "dash.navQr": "QR 코드",
  "dash.navSettings": "설정",
  "dash.signOut": "로그아웃",
  "dash.opening": "대기줄을 여는 중…",
  "dash.pausedB": "손님이 지금 번호를 받을 수 없습니다.",
  "dash.nobodyCounter": "카운터에 아무도 없음",
  "dash.noName": "이름 없음",
  "dash.noNameGiven": "이름 없음",
  "dash.confirmedHere": "님이 도착했다고 확인했습니다",
  "dash.notConfirmed": "님이 아직 확인하지 않았습니다",
  "dash.callNext": "다음 호출",
  "dash.calling": "호출 중…",
  "dash.noWaitingHint": "지금 기다리는 사람이 없습니다.",
  "dash.pause": "대기줄 일시정지",
  "dash.resume": "대기줄 재개",
  "dash.atCounter": "카운터에서",
  "dash.waitingTitle": "대기 중",
  "dash.stWait": "대기 중",
  "dash.stCalled": "호출됨",
  "dash.stServed": "처리 완료",
  "dash.stSkipped": "건너뜀",
  "dash.stNoShow": "노쇼",
  "dash.firstRun": "아직 아무도 없습니다. 세 단계면 대기줄이 시작됩니다:",
  "dash.step1": "QR 코드를 받으세요. 인쇄하거나 출입문 옆 화면에 두세요.",
  "dash.step1link": "내 QR 코드 열기 →",
  "dash.step2": "손님이 번호를 받습니다. 스캔하고, 이름을 적고, 합류합니다.",
  "dash.step3": "\"다음 호출\"을 누르면 그 순간 휴대폰이 갱신됩니다.",
  "dash.emptyWaiting": "기다리는 사람이 없습니다. 사람이 올수록 새 번호가 여기 표시됩니다.",
  "dash.nextUp": "다음",
  "dash.finished": "종료됨",
  "dash.counts": "처리 {s}, 건너뜀 {k}, 노쇼 {n}",
  "dash.markServed": "처리 완료로 표시",
  "dash.skip": "건너뛰기",
  "qr.intro": "인쇄해서 출입문이나 카운터에 붙이세요. 링크는 바뀌지 않아 오늘 인쇄한 코드도 계속 씁니다.",
  "qr.linkLabel": "대기줄 링크",
  "qr.download": "PNG 다운로드",
  "qr.print": "인쇄",
  "qr.copy": "링크 복사",
  "qr.copied": "링크를 복사했습니다.",
  "qr.making": "QR 코드 만드는 중…",
  "qr.sheetCta": "스캔해서 대기줄 합류",
  "qr.fine": "손님은 스캔만 하면 번호를 받습니다. 앱도 계정도 없고, QR은 모든 테마에서 흑백이라 휴대폰이 잘 읽습니다.",
  "set.noteLabel": "손님에게 남길 말",
  "set.noteHint": "대기줄 페이지의 합류 버튼 위에 표시됩니다. 선택 사항.",
  "set.save": "변경 저장",
  "set.saving": "저장 중…",
  "set.saved": "저장했습니다.",
  "set.goodToKnow": "알아두면 좋은 것",
  "set.linkBody": "링크는 영구적이라 가게 이름을 바꿔도 인쇄한 QR은 계속 작동합니다.",
  "set.signedInAs": "로그인 계정",
  "set.errNote": "남길 말은 200자 이하여야 합니다.",
  "nf.title": "존재하지 않는 페이지입니다.",
  "nf.body": "주소가 이동했거나 링크를 잘못 입력한 것 같습니다.",
  "nf.cta": "홈페이지로 이동",
};

export const asia: Lang[] = [
  { code: "hi", label: "Hindi", native: "हिन्दी", flag: "🇮🇳", dict: hi },
  { code: "id", label: "Indonesian", native: "Bahasa Indonesia", flag: "🇮🇩", dict: id },
  { code: "zh", label: "Chinese (Simplified)", native: "简体中文", flag: "🇨🇳", dict: zh },
  { code: "ja", label: "Japanese", native: "日本語", flag: "🇯🇵", dict: ja },
  { code: "ko", label: "Korean", native: "한국어", flag: "🇰🇷", dict: ko },
];
