import type { StringKey } from "./en";
import type { Lang } from "./types";

type Pack = Partial<Record<StringKey, string>>;

const hi: Pack = {
  "nav.about": "परिचय",
  "nav.signin": "साइन इन",
  "nav.setup": "अपना व्यवसाय सेट करें",
  "foot.made": "Lobby, {name} द्वारा बनाया गया।",
  "foot.mit": "MIT लाइसेंस के तहत ओपन सोर्स।",
  "lang.title": "अपनी भाषा चुनें",
  "lang.sub": "इसे बाद में ऊपर दाईं ओर झंडे से बदल सकते हैं।",
  "lang.change": "भाषा बदलें",
  "lang.done": "हो गया",
  "common.loading": "लोड हो रहा है…",
  "common.retry": "फिर कोशिश करें",
  "hero.eyebrow": "दुकानों, क्लीनिकों और सैलून के लिए कतारें",
  "hero.h1a": "एक नंबर लें।",
  "hero.h1b": "जहां चाहें वहीं इंतज़ार करें।",
  "hero.lede":
    "आपके व्यवसाय के लिए एक QR कोड। ग्राहक इसे स्कैन करते हैं, नंबर लेते हैं और कतार में अपनी जगह देखते हैं। उनकी बारी आने पर उनका फ़ोन बता देता है।",
  "hero.fine":
    "ग्राहकों के लिए कोई ऐप नहीं, उनके लिए कोई अकाउंट नहीं। ओपन सोर्स और आपके अपने सर्वर पर चलता है।",
  "demo.nowServing": "अभी सेवा में",
  "demo.yourNumber": "आपका नंबर",
  "how.title": "यह कैसे काम करता है",
  "how.t1": "अपना QR कोड छापें",
  "how.d1": "आपके दरवाज़े या काउंटर के लिए एक स्थायी कोड।",
  "how.t2": "ग्राहक नंबर लेते हैं",
  "how.d2": "वे स्कैन करते हैं, चाहें तो नाम डालते हैं, कुछ इंस्टॉल नहीं करना।",
  "how.t3": "\"अगला बुलाएं\" दबाएं",
  "how.d3": "कतार आगे बढ़ती है और उनकी स्क्रीन अपने आप अपडेट होती है।",
  "see.title": "आपके ग्राहक क्या देखते हैं",
  "see.copy":
    "हर बार एक ही स्क्रीन, एक ही जवाब। किसी भी फ़ोन ब्राउज़र में चलता है, और जब आप उनका नंबर बुलाते हैं तो यह \"आपकी बारी है\" पर बदल जाता है।",
  "see.youreNumber": "आपका नंबर",
  "see.peopleAhead": "आपसे पहले लोग",
  "see.when": "जब यह होता है",
  "see.itsTurn": "आपकी बारी है!",
  "places.title": "काउंटर वाली जगहों के लिए",
  "places.list":
    "फ़ार्मेसी · क्लीनिक · सैलून · बारबर शॉप · रिपेयर शॉप · बैंक · डाकघर · सरकारी दफ़्तर",
  "band.title": "सेटअप में लगभग एक मिनट लगता है।",
  "auth.welcome": "वापसी पर स्वागत है",
  "auth.setupSub": "एक मिनट टाइप करें और आपकी कतार तैयार।",
  "auth.loginSub": "अपनी कतार में साइन इन करें।",
  "auth.bizName": "व्यवसाय का नाम",
  "auth.yourName": "आपका नाम",
  "auth.email": "ईमेल",
  "auth.password": "पासवर्ड",
  "auth.pwHint": "कम से कम 8 अक्षर।",
  "auth.creating": "सेट हो रहा है…",
  "auth.signingIn": "साइन इन हो रहा है…",
  "auth.create": "मेरा व्यवसाय बनाएं",
  "auth.haveAccount": "पहले से अकाउंट है?",
  "auth.noAccount": "अभी अकाउंट नहीं है?",
  "auth.backHome": "होम पर वापस",
  "err.bizName": "अपने व्यवसाय का नाम डालें।",
  "err.name": "अपना नाम डालें।",
  "err.email": "अपना ईमेल डालें।",
  "err.password": "अपना पासवर्ड डालें।",
  "err.pwLen": "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए।",
  "cust.opening": "कतार खुल रही है…",
  "cust.wrong": "कुछ गड़बड़ हो गई।",
  "cust.pausedT": "कतार रुकी हुई है।",
  "cust.pausedB": "यह व्यवसाय अभी नंबर नहीं दे रहा, जल्दी फिर देखें।",
  "cust.nobody": "अभी किसे सेवा नहीं दी जा रही",
  "cust.noOneWaiting": "कोई इंतज़ार नहीं कर रहा",
  "cust.waitingN": "{n} इंतज़ार में",
  "cust.joinT": "कतार में शामिल हों",
  "cust.nameLabel": "आपका नाम (वैकल्पिक)",
  "cust.joinBusy": "आपका नंबर लिया जा रहा है…",
  "cust.joinReassure": "न ऐप, न अकाउंट, बस एक नंबर।",
  "cust.youreNumber": "आपका नंबर",
  "cust.youreNext": "आप अगले हैं",
  "cust.oneAhead": "आपसे पहले 1 व्यक्ति",
  "cust.nAhead": "आपसे पहले {n} लोग",
  "cust.peopleWaiting": "इंतज़ार कर रहे लोग",
  "cust.reassure": "यह पेज अपने आप अपडेट होता है, इसे खुला रखें।",
  "cust.leave": "कतार छोड़ें",
  "cust.leaveConfirm": "कतार छोड़ें? आप अपना नंबर खो देंगे।",
  "cust.turnT": "आपकी बारी है",
  "cust.turnB": "कृपया काउंटर पर आएं।",
  "cust.imHere": "मैं यहां हूं",
  "cust.sending": "भेजा जा रहा है…",
  "cust.confirmed": "धन्यवाद, हमने उन्हें बता दिया है कि आप तैयार हैं।",
  "cust.done": "सब हो गया",
  "cust.servedBody": "इंतज़ार के लिए धन्यवाद।",
  "cust.skippedBody": "आपको छोड़ दिया गया। अब भी यहीं हैं तो दूसरा नंबर लें।",
  "cust.noShowBody": "यह नंबर बंद हो गया। अब भी यहीं हैं तो दूसरा नंबर लें।",
  "cust.joinAgain": "फिर से शामिल हों",
  "cust.poweredBy": "संचालित",
  "dash.navQueue": "कतार",
  "dash.navQr": "QR कोड",
  "dash.navSettings": "सेटिंग्स",
  "dash.signOut": "साइन आउट",
  "dash.opening": "आपकी कतार खुल रही है…",
  "dash.pausedB": "ग्राहक अभी नंबर नहीं ले सकते।",
  "dash.nobodyCounter": "काउंटर पर कोई नहीं",
  "dash.noNameGiven": "बिना नाम",
  "dash.confirmedHere": "ने कहा है कि वे यहां हैं",
  "dash.notConfirmed": "ने अभी पुष्टि नहीं की",
  "dash.callNext": "अगला बुलाएं",
  "dash.calling": "बुला रहे हैं…",
  "dash.noWaitingHint": "अभी कोई इंतज़ार नहीं कर रहा।",
  "dash.pause": "कतार रोकें",
  "dash.resume": "कतार चालू करें",
  "dash.atCounter": "काउंटर पर",
  "dash.waitingTitle": "इंतज़ार में",
  "dash.noName": "बिना नाम",
  "dash.stWait": "इंतज़ार में",
  "dash.stCalled": "सेवा में",
  "dash.stServed": "पूरा हुआ",
  "dash.stSkipped": "छोड़ा गया",
  "dash.stNoShow": "नहीं आए",
  "dash.firstRun": "अभी तक कोई नहीं है। तीन तेज़ कदम और आपकी कतार चालू:",
  "dash.step1": "अपना QR कोड लें। छापें या दरवाज़े के पास स्क्रीन पर लगाएं।",
  "dash.step1link": "मेरा QR कोड खोलें →",
  "dash.step2": "ग्राहक नंबर लेते हैं। स्कैन करते हैं, वैकल्पिक नाम डालते हैं और शामिल हो जाते हैं।",
  "dash.step3": "\"अगला बुलाएं\" दबाएं। उनका फ़ोन उसी पल अपडेट होता है।",
  "dash.emptyWaiting": "कोई इंतज़ार नहीं कर रहा। लोगों के आने पर नए नंबर यहां दिखते हैं।",
  "dash.nextUp": "अगला",
  "dash.finished": "पूरे हुए",
  "dash.counts": "{s} पूरे, {k} छोड़े गए, {n} नहीं आए",
  "dash.markServed": "पूरा चिह्नित करें",
  "dash.skip": "छोड़ें",
  "qr.intro":
    "इसे छापें और दरवाज़े या काउंटर पर लगाएं। लिंक कभी नहीं बदलता, आज छापा कोड हमेशा काम करता रहेगा।",
  "qr.linkLabel": "आपका कतार लिंक",
  "qr.download": "PNG डाउनलोड करें",
  "qr.print": "छापें",
  "qr.copy": "लिंक कॉपी करें",
  "qr.copied": "लिंक कॉपी हो गया।",
  "qr.making": "आपका QR कोड बन रहा है…",
  "qr.sheetCta": "कतार में शामिल होने के लिए स्कैन करें",
  "qr.fine":
    "ग्राहक बिना ऐप और अकाउंट के नंबर लेने के लिए स्कैन करते हैं। QR हर थीम में काला और सफ़ेद रहता है ताकि फ़ोन इसे पढ़ सकें।",
  "set.noteLabel": "ग्राहकों के लिए नोट",
  "set.noteHint": "आपके कतार पेज पर शामिल हों बटन के ऊपर दिखता है। वैकल्पिक।",
  "set.save": "बदलाव सहेजें",
  "set.saving": "सहेजा जा रहा है…",
  "set.saved": "सहेजा गया।",
  "set.goodToKnow": "जान लें",
  "set.linkBody": "यह स्थायी है, छापा हुआ QR नाम बदलने पर भी चलता रहेगा।",
  "set.signedInAs": "साइन इन किया",
  "set.errNote": "आपका नोट 200 अक्षरों या उससे कम का होना चाहिए।",
  "nf.title": "यह पेज मौजूद नहीं है।",
  "nf.body": "शायद यह हट गया है, या लिंक गलत लिखा गया है।",
  "nf.cta": "होम पेज पर जाएं",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "लाइव डेमो",
  "common.live": "लाइव",
  "common.reconnecting": "फिर से जुड़ रहे हैं…",
  "common.offline": "आप ऑफ़लाइन हैं। यह पेज अपने आप अपडेट होगा।",
  "common.optional": "optional",
  "common.cancel": "रद्द करें",
  "common.remove": "हटाएँ",
  "common.add": "जोड़ें",
  "common.save": "Save",
  "common.saved": "सहेजा गया।",
  "common.minutes": "{n} मिनट",
  "common.branch": "स्थान",
  "common.allBranches": "सभी स्थान",
  "common.back": "Back",
  "band.body": "एक दुकान प्रकार से शुरू करें, रेस्तरां, क्लिनिक, सैलून, रिपेयर, और नाम बदल लें। नई शाखा खोलने पर और जगहें जोड़ें।",
  "band.try": "लाइव डेमो देखें",
  "demo.title": "इसे काम करते देखें",
  "demo.sub": "एक अभ्यास दुकान जहाँ आप बटन दबा सकते हैं। ग्राहक के रूप में जुड़ें, कर्मचारी के रूप में नंबर बुलाएँ, टीवी स्क्रीन देखें। यहाँ कुछ भी असली नहीं है।",
  "demo.paneCustomer": "ग्राहक का फ़ोन",
  "demo.paneStaff": "कर्मचारी का फ़ोन",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "टीवी स्क्रीन",
  "demo.joinName": "नाम (वैकल्पिक)",
  "demo.join": "नंबर लें",
  "demo.reset": "डेमो रीसेट करें",
  "demo.callNext": "अगला बुलाएँ",
  "demo.serve": "हो गया",
  "demo.skip": "छोड़ें",
  "demo.waitingList": "Waiting",
  "demo.hint": "एक नंबर बुलाकर देखें कि चारों पैनल एक साथ अपडेट होते हैं।",
  "auth.shopType": "यह किस तरह का धंधा है?",
  "auth.shopTypeHint": "हम कतारें और काउंटर बना देंगे। नाम बाद में बदल सकते हैं।",
  "auth.branchName": "पहला स्थान",
  "auth.inviteTitle": "आपको आमंत्रित किया गया है",
  "auth.inviteBody": "{business} आपको {role} के रूप में कतार संभालने के लिए आमंत्रित करता है।",
  "auth.joinTeam": "टीम में शामिल हों",
  "auth.inviteBad": "यह निमंत्रण अब मान्य नहीं है। अपने प्रबंधक से नया माँगें।",
  "cust.phoneLabel": "फ़ोन (वैकल्पिक)",
  "cust.estWait": "लगभग {n} मिनट प्रतीक्षा",
  "cust.pickQueue": "आपको क्या चाहिए?",
  "cust.pickBranch": "कौन-सा स्थान?",
  "cust.pickQueueHint": "नंबर लेने के लिए कतार चुनें।",
  "cust.held": "रुका हुआ",
  "cust.heldBody": "कर्मचारी जल्द ही आपको बुलाएँगे।",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "कतारें",
  "dash.navTeam": "टीम",
  "dash.navReports": "इतिहास",
  "dash.holdTitle": "रोका गया",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "चला गया",
  "dash.hold": "रोकें",
  "dash.release": "वापस कतार में लगाएँ",
  "dash.recall": "फिर से बुलाएँ",
  "dash.cancel": "Remove from queue",
  "dash.move": "स्थानांतरित करें",
  "dash.moveTo": "दूसरी कतार में ले जाएँ",
  "dash.call": "बुलाएँ",
  "dash.addWalkIn": "ग्राहक जोड़ें",
  "dash.addWalkInBody": "फ़ोन बुकिंग और सामने खड़े लोगों के लिए।",
  "dash.noteLabel": "टिप्पणी (वैकल्पिक)",
  "dash.counterLabel": "काउंटर",
  "dash.anyCounter": "कोई भी काउंटर",
  "dash.avgWait": "औसत प्रतीक्षा {n} मिनट",
  "dash.peopleWaiting": "{n} प्रतीक्षारत",
  "dash.tvLink": "टीवी स्क्रीन खोलें",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "इस शाखा में अभी कोई कतार नहीं है।",
  "dash.pickQueue": "कतार चुनें",
  "dash.roleTag": "आपकी भूमिका: {role}",
  "dash.noPermission": "आपकी भूमिका यह नहीं कर सकती।",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "इस कोड के लिए कतार",
  "qr.displayLink": "टीवी स्क्रीन लिंक",
  "sq.title": "कतारें और काउंटर",
  "sq.sub": "हर कतार के अपने नंबर और अपनी लाइन है।",
  "sq.locations": "स्थान",
  "sq.addLocation": "स्थान जोड़ें",
  "sq.locationName": "स्थान का नाम",
  "sq.address": "पता (वैकल्पिक)",
  "sq.phone": "फ़ोन (वैकल्पिक)",
  "sq.noLocations": "अभी कोई स्थान नहीं।",
  "sq.queues": "कतारें",
  "sq.addQueue": "कतार जोड़ें",
  "sq.queueName": "कतार का नाम",
  "sq.prefix": "नंबर के अक्षर",
  "sq.prefixHint": "नंबर से पहले दो अक्षर तक, जैसे A12।",
  "sq.description": "यह कतार किस काम की है? (वैकल्पिक)",
  "sq.avgTime": "सामान्य समय (मिनट)",
  "sq.counters": "काउंटर",
  "sq.counterName": "Counter name",
  "sq.addCounter": "काउंटर जोड़ें",
  "sq.paused": "रोका गया",
  "sq.open": "खुली",
  "sq.closed": "Closed",
  "sq.noQueues": "इस स्थान पर अभी कोई कतार नहीं है।",
  "sq.deleteQueue": "यह कतार हटाएँ",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "एक दुकान प्रकार से शुरू करें",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "रुके होने पर ग्राहक इस कतार में नंबर नहीं ले सकते।",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "आपकी टीम",
  "team.sub": "काउंटर पर काम करने वालों को बुलाएँ और तय करें कि हर कोई क्या कर सकता है।",
  "team.invite": "किसी को आमंत्रित करें",
  "team.invited": "निमंत्रण भेजा गया",
  "team.inviteEmail": "उनका ईमेल",
  "team.inviteRole": "वे क्या कर सकते हैं",
  "team.pending": "शामिल होने की प्रतीक्षा में",
  "team.noPending": "कोई लंबित निमंत्रण नहीं।",
  "team.revoke": "निमंत्रण रद्द करें",
  "team.role": "भूमिका",
  "team.roleOwner": "मालिक",
  "team.roleManager": "प्रबंधक",
  "team.roleStaff": "कर्मचारी",
  "team.roleViewer": "केवल पढ़ना",
  "team.remove": "टीम से हटाएँ",
  "team.lock": "हर जगह साइन आउट",
  "team.unlock": "साइन-इन की अनुमति दें",
  "team.allBranches": "सभी स्थान",
  "team.oneBranch": "One location",
  "team.pickBranch": "स्थान",
  "team.noTeam": "अभी आप अकेले हैं।",
  "team.linkCopied": "निमंत्रण लिंक कॉपी हो गया। उन्हें भेजें।",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "आज और पिछले हफ्ते असल में कैसा रहा।",
  "rep.joined": "लिए गए नंबर",
  "rep.served": "सेवित ग्राहक",
  "rep.avgWait": "औसत प्रतीक्षा",
  "rep.avgService": "औसत सेवा",
  "rep.peak": "चरम समय",
  "rep.abandoned": "बिना सेवा के चले गए",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "पिछले 7 दिन",
  "rep.days30": "पिछले 30 दिन",
  "rep.days90": "पिछले 90 दिन",
  "rep.byDay": "Each day",
  "rep.byHour": "सबसे व्यस्त घंटे",
  "rep.byQueue": "हर कतार",
  "rep.waited": "{n} मिनट प्रतीक्षा",
  "rep.servedIn": "{n} मिनट में सेवित",
  "rep.history": "जो भी आया",
  "rep.noHistory": "इस अवधि में इस कतार से कोई नहीं गुज़रा।",
  "rep.audit": "आपकी टीम द्वारा किए गए बदलाव",
  "rep.noAudit": "अभी तक कोई बदलाव दर्ज नहीं है।",
  "rep.noReports": "आपकी भूमिका रिपोर्ट नहीं देख सकती।",
  "set.brand": "रूप-रंग",
  "set.brandHint": "आपके रंग और लोगो ग्राहक पेज और टीवी स्क्रीन पर दिखते हैं।",
  "set.mainColour": "मुख्य रंग",
  "set.accentColour": "हाइलाइट रंग",
  "set.logo": "लोगो",
  "set.logoHint": "वेब लिंक पेस्ट करें या तस्वीर अपलोड करें। छोटी तस्वीर बेहतर है।",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "लोगो हटाएँ",
  "set.security": "आपका पासवर्ड",
  "set.currentPassword": "वर्तमान पासवर्ड",
  "set.newPassword": "नया पासवर्ड",
  "set.changePassword": "पासवर्ड बदलें",
  "set.passwordChanged": "पासवर्ड बदल गया। अन्य डिवाइस साइन आउट हो गए।",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "अभी सेवा में",
  "disp.waiting": "प्रतीक्षा में",
  "disp.others": "अन्य कतारें",
  "disp.fullscreen": "फ़ुल स्क्रीन",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "पहले नंबर का इंतज़ार",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "अनुमानित प्रतीक्षा",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "डिफ़ॉल्ट रूप से लाइव",
  "hero.statPhone": "हर फ़ोन पर काम करता है",
  "feat.title": "कतार को जो चाहिए, बस वही",
  "feat.copy": "Lobby एक ही काम अच्छे से करता है। नीचे की हर स्क्रीन आज ही उत्पाद का हिस्सा है।",
  "feat.qr.t": "एक कोड, हमेशा अद्यतन",
  "feat.qr.d": "हर स्थान के लिए स्थायी QR कोड। एक बार छापें। दुकान का नाम बदलने से कभी नहीं टूटता।",
  "feat.multi.t": "कई कतारें, एक स्क्रीन",
  "feat.multi.d": "काउंटर को सेवाओं में बाँटें, परामर्श, पिकअप, रिटर्न, अपने नंबर और काउंटर के साथ।",
  "feat.team.t": "दुकान के अनुरूप भूमिकाएँ",
  "feat.team.d": "कर्मचारियों को लिंक से बुलाएँ, शाखा से जोड़ें, और चाबियाँ मालिकों के पास रहें।",
  "feat.brand.t": "आपके धंधे जैसा",
  "feat.brand.d": "आपके रंग, लोगो और नोट हर ग्राहक के फ़ोन और टीवी पर दिखते हैं।",
  "feat.reports.t": "शाम के लिए सही आँकड़े",
  "feat.reports.d": "प्रतीक्षा समय, व्यस्त घंटे और पूरा इतिहास। अगले हफ्ते की ड्यूटी अब अंदाज़ा नहीं।",
  "feat.pause.t": "बिना उलझन के बंद करें",
  "feat.pause.d": "एक टैप से कतार रोकें। दरवाज़े का बोर्ड यह बताता है, और कोई बंद काउंटर पर नंबर नहीं लेता।",
  "flow.title": "दरवाज़े से निपटने तक चार कदमों में",
  "flow.s1.t": "ग्राहक कतार में जुड़ते हैं",
  "flow.s1.d": "वे कोड स्कैन करते हैं, सेवा चुनते हैं और नंबर लेते हैं। न ऐप, न खाता।",
  "flow.s2.t": "कर्मचारी अगले को बुलाते हैं",
  "flow.s2.d": "एक बड़ा बटन अगले व्यक्ति की सेवा करता है और कतार न्यायसंगत रखता है।",
  "flow.s3.t": "सब अपनी स्थिति देखते हैं",
  "flow.s3.d": "हर फ़ोन पर स्थिति, आगे कितने लोग और प्रतीक्षा दिखती है, लाइव, बिना रीफ़्रेश।",
  "flow.s4.t": "डिस्प्ले व्यवस्था बनाए रखता है",
  "flow.s4.d": "प्रतीक्षालय का टीवी दिखाता है कि किसकी सेवा हो रही है और अगला कौन है।",
  "dispsect.title": "आपके प्रतीक्षालय के लायक डिस्प्ले",
  "dispsect.copy": "किसी भी टीवी ब्राउज़र पर डिस्प्ले खोलें। बड़े नंबर, अगले पाँच और बाकी कतारें एक नज़र में। कर्मचारी काम करते ही अपडेट होता है।",
  "dispsect.cta": "लाइव डिस्प्ले देखें",
  "dash.servingCounters": "{n} सेवा में",
};

const id: Pack = {
  "nav.about": "Tentang",
  "nav.signin": "Masuk",
  "nav.setup": "Siapkan bisnis Anda",
  "foot.made": "Lobby, dibuat oleh {name}.",
  "foot.mit": "Sumber terbuka dengan lisensi MIT.",
  "lang.title": "Pilih bahasa Anda",
  "lang.sub": "Anda bisa mengubahnya nanti lewat bendera di pojok kanan atas.",
  "lang.change": "Ganti bahasa",
  "lang.done": "Selesai",
  "common.loading": "Memuat…",
  "common.retry": "Coba lagi",
  "hero.eyebrow": "Antrean untuk toko, klinik, dan salon",
  "hero.h1a": "Ambil nomor.",
  "hero.h1b": "Tunggu di mana saja.",
  "hero.lede":
    "Satu QR code untuk bisnis Anda. Pelanggan memindainya, mengambil nomor, dan melihat posisi mereka di antrean. Saat giliran mereka, ponsel mereka memberi tahu.",
  "hero.fine":
    "Tanpa aplikasi untuk pelanggan, tanpa akun untuk mereka. Sumber terbuka dan berjalan di server Anda sendiri.",
  "demo.nowServing": "Sedang dilayani",
  "demo.yourNumber": "Nomor Anda",
  "how.title": "Cara kerjanya",
  "how.t1": "Cetak QR code Anda",
  "how.d1": "Satu kode permanen untuk pintu atau meja kasir Anda.",
  "how.t2": "Pelanggan mengambil nomor",
  "how.d2": "Mereka memindai, menambahkan nama jika mau, tanpa apa pun untuk dipasang.",
  "how.t3": "Tekan Panggil berikutnya",
  "how.d3": "Antrean berjalan dan layar mereka diperbarui sendiri.",
  "see.title": "Yang dilihat pelanggan Anda",
  "see.copy":
    "Satu layar dengan jawaban yang sama setiap saat. Berjalan di browser ponsel mana pun, dan saat Anda memanggil nomor mereka, layarnya berubah menjadi Giliran Anda.",
  "see.youreNumber": "Nomor Anda",
  "see.peopleAhead": "Orang sebelum Anda",
  "see.when": "Saat waktunya tiba",
  "see.itsTurn": "Giliran Anda!",
  "places.title": "Untuk tempat dengan meja kasir",
  "places.list":
    "Apotek · Klinik · Salon · Pangkas rambut · Bengkel · Bank · Kantor pos · Kantor pemerintah",
  "band.title": "Pengaturan butuh sekitar satu menit.",
  "auth.welcome": "Selamat datang kembali",
  "auth.setupSub": "Sebentar mengetik dan antrean Anda siap.",
  "auth.loginSub": "Masuk ke antrean Anda.",
  "auth.bizName": "Nama bisnis",
  "auth.yourName": "Nama Anda",
  "auth.email": "Email",
  "auth.password": "Kata sandi",
  "auth.pwHint": "Minimal 8 karakter.",
  "auth.creating": "Menyiapkan…",
  "auth.signingIn": "Masuk…",
  "auth.create": "Buat bisnis saya",
  "auth.haveAccount": "Sudah punya akun?",
  "auth.noAccount": "Belum punya akun?",
  "auth.backHome": "Kembali ke beranda",
  "err.bizName": "Masukkan nama bisnis Anda.",
  "err.name": "Masukkan nama Anda.",
  "err.email": "Masukkan email Anda.",
  "err.password": "Masukkan kata sandi Anda.",
  "err.pwLen": "Kata sandi harus minimal 8 karakter.",
  "cust.opening": "Membuka antrean…",
  "cust.wrong": "Ada yang tidak beres.",
  "cust.pausedT": "Antrean dijeda.",
  "cust.pausedB": "Bisnis ini sedang tidak menerima nomor, coba lagi nanti.",
  "cust.nobody": "Belum ada yang dilayani",
  "cust.noOneWaiting": "tidak ada yang menunggu",
  "cust.waitingN": "{n} menunggu",
  "cust.joinT": "Ikut antrean",
  "cust.nameLabel": "Nama Anda (opsional)",
  "cust.joinBusy": "Mengambil nomor Anda…",
  "cust.joinReassure": "Tanpa aplikasi, tanpa akun, hanya nomor.",
  "cust.youreNumber": "Nomor Anda",
  "cust.youreNext": "Anda berikutnya",
  "cust.oneAhead": "1 orang sebelum Anda",
  "cust.nAhead": "{n} orang sebelum Anda",
  "cust.peopleWaiting": "Sedang menunggu",
  "cust.reassure": "Halaman ini memperbarui sendiri, biarkan terbuka.",
  "cust.leave": "Keluar dari antrean",
  "cust.leaveConfirm": "Keluar dari antrean? Anda akan kehilangan nomor Anda.",
  "cust.turnT": "Giliran Anda",
  "cust.turnB": "Silakan menuju meja kasir.",
  "cust.imHere": "Saya di sini",
  "cust.sending": "Mengirim…",
  "cust.confirmed": "Terima kasih, kami sudah memberi tahu mereka Anda siap.",
  "cust.done": "Selesai",
  "cust.servedBody": "Terima kasih sudah menunggu.",
  "cust.skippedBody": "Anda dilewati. Jika masih di sini, ambil nomor lain.",
  "cust.noShowBody": "Nomor ini sudah ditutup. Jika masih di sini, ambil nomor lain.",
  "cust.joinAgain": "Ikut lagi",
  "cust.poweredBy": "Didukung oleh",
  "dash.navQueue": "Antrean",
  "dash.navQr": "Kode QR",
  "dash.navSettings": "Pengaturan",
  "dash.signOut": "Keluar",
  "dash.opening": "Membuka antrean Anda…",
  "dash.pausedB": "Pelanggan sedang tidak bisa mengambil nomor.",
  "dash.nobodyCounter": "Tidak ada di meja kasir",
  "dash.noNameGiven": "Tanpa nama",
  "dash.confirmedHere": "bilang sedang di sini",
  "dash.notConfirmed": "belum mengonfirmasi",
  "dash.callNext": "Panggil berikutnya",
  "dash.calling": "Memanggil…",
  "dash.noWaitingHint": "Tidak ada yang menunggu saat ini.",
  "dash.pause": "Jeda antrean",
  "dash.resume": "Lanjutkan antrean",
  "dash.atCounter": "Di meja kasir",
  "dash.waitingTitle": "Menunggu",
  "dash.noName": "Tanpa nama",
  "dash.stWait": "Menunggu",
  "dash.stCalled": "Dilayani",
  "dash.stServed": "Selesai dilayani",
  "dash.stSkipped": "Dilewati",
  "dash.stNoShow": "Tidak hadir",
  "dash.firstRun": "Belum ada siapa pun. Tiga langkah cepat dan antrean Anda jalan:",
  "dash.step1": "Ambil QR code Anda. Cetak atau taruh di layar dekat pintu.",
  "dash.step1link": "Buka QR code saya →",
  "dash.step2": "Pelanggan mengambil nomor. Mereka memindai, mengetik nama, lalu masuk.",
  "dash.step3": "Tekan Panggil berikutnya. Ponsel mereka langsung diperbarui.",
  "dash.emptyWaiting": "Tidak ada yang menunggu. Nomor baru muncul di sini saat orang datang.",
  "dash.nextUp": "Berikutnya",
  "dash.finished": "Selesai",
  "dash.counts": "{s} selesai dilayani, {k} dilewati, {n} tidak hadir",
  "dash.markServed": "Tandai sudah dilayani",
  "dash.skip": "Lewati",
  "qr.intro":
    "Cetak ini dan taruh di pintu atau meja kasir. Tautannya tidak pernah berubah, kode yang Anda cetak hari ini tetap berfungsi.",
  "qr.linkLabel": "Tautan antrean Anda",
  "qr.download": "Unduh PNG",
  "qr.print": "Cetak",
  "qr.copy": "Salin tautan",
  "qr.copied": "Tautan disalin.",
  "qr.making": "Membuat QR code Anda…",
  "qr.sheetCta": "Pindai untuk ikut antrean",
  "qr.fine":
    "Pelanggan memindai untuk mengambil nomor, tanpa aplikasi dan tanpa akun. QR tetap hitam putih di semua tema agar ponsel bisa membacanya.",
  "set.noteLabel": "Catatan untuk pelanggan",
  "set.noteHint": "Tampil di atas tombol Ikut di halaman antrean Anda. Opsional.",
  "set.save": "Simpan perubahan",
  "set.saving": "Menyimpan…",
  "set.saved": "Tersimpan.",
  "set.goodToKnow": "Perlu diketahui",
  "set.linkBody": "Tautannya permanen, QR cetak tetap berfungsi meski nama bisnis diganti.",
  "set.signedInAs": "Masuk sebagai",
  "set.errNote": "Catatan Anda maksimal 200 karakter.",
  "nf.title": "Halaman ini tidak ada.",
  "nf.body": "Mungkin sudah dipindah, atau tautannya salah ketik.",
  "nf.cta": "Ke halaman beranda",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "Demo langsung",
  "common.live": "Langsung",
  "common.reconnecting": "Menyambung ulang…",
  "common.offline": "Anda sedang offline. Halaman ini akan menyegarkan sendiri.",
  "common.optional": "optional",
  "common.cancel": "Batal",
  "common.remove": "Hapus",
  "common.add": "Tambah",
  "common.save": "Save",
  "common.saved": "Tersimpan.",
  "common.minutes": "{n} mnt",
  "common.branch": "Lokasi",
  "common.allBranches": "Semua lokasi",
  "common.back": "Back",
  "band.body": "Mulai dari jenis usaha, restoran, klinik, salon, bengkel, lalu ubah namanya. Tambah lokasi baru saat membuka cabang.",
  "band.try": "Coba demo langsung",
  "demo.title": "Lihat cara kerjanya",
  "demo.sub": "Toko latihan tempat Anda bisa menekan tombol. Gabung sebagai pelanggan, panggil nomor sebagai staf, dan lihat layar TV. Tidak ada yang nyata di sini.",
  "demo.paneCustomer": "Ponsel pelanggan",
  "demo.paneStaff": "Ponsel staf",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "Layar TV",
  "demo.joinName": "Nama (opsional)",
  "demo.join": "Ambil nomor",
  "demo.reset": "Setel ulang demo",
  "demo.callNext": "Panggil berikutnya",
  "demo.serve": "Selesai",
  "demo.skip": "Lewati",
  "demo.waitingList": "Waiting",
  "demo.hint": "Coba panggil nomor dan lihat keempat panel menyegar bersamaan.",
  "auth.shopType": "Ini jenis usaha apa?",
  "auth.shopTypeHint": "Kami akan membuat antrean dan loket. Semua nama bisa diubah nanti.",
  "auth.branchName": "Lokasi pertama",
  "auth.inviteTitle": "Anda diundang",
  "auth.inviteBody": "{business} mengundang Anda untuk mengelola antrean sebagai {role}.",
  "auth.joinTeam": "Bergabung dengan tim",
  "auth.inviteBad": "Undangan ini sudah tidak berlaku. Minta yang baru kepada manajer Anda.",
  "cust.phoneLabel": "Telepon (opsional)",
  "cust.estWait": "Antrean sekitar {n} mnt",
  "cust.pickQueue": "Apa yang Anda butuhkan?",
  "cust.pickBranch": "Lokasi mana?",
  "cust.pickQueueHint": "Pilih antrean untuk mengambil nomor.",
  "cust.held": "Ditahan",
  "cust.heldBody": "Staf akan memanggil Anda sebentar lagi.",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "Antrean",
  "dash.navTeam": "Tim",
  "dash.navReports": "Riwayat",
  "dash.holdTitle": "Ditahan",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "Pergi",
  "dash.hold": "Tahan",
  "dash.release": "Kembalikan ke antrean",
  "dash.recall": "Panggil lagi",
  "dash.cancel": "Remove from queue",
  "dash.move": "Pindahkan",
  "dash.moveTo": "Pindah antrean",
  "dash.call": "Panggil",
  "dash.addWalkIn": "Tambah pelanggan",
  "dash.addWalkInBody": "Untuk pemesanan lewat telepon dan orang yang ada di depan Anda.",
  "dash.noteLabel": "Catatan (opsional)",
  "dash.counterLabel": "Loket",
  "dash.anyCounter": "Loket mana saja",
  "dash.avgWait": "Rata-rata tunggu {n} mnt",
  "dash.peopleWaiting": "{n} menunggu",
  "dash.tvLink": "Buka layar TV",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "Cabang ini belum punya antrean.",
  "dash.pickQueue": "Pilih antrean",
  "dash.roleTag": "Peran Anda: {role}",
  "dash.noPermission": "Peran Anda tidak bisa melakukan itu.",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "Antrean untuk kode ini",
  "qr.displayLink": "Tautan layar TV",
  "sq.title": "Antrean dan loket",
  "sq.sub": "Setiap antrean punya nomor dan barisnya sendiri.",
  "sq.locations": "Lokasi",
  "sq.addLocation": "Tambah lokasi",
  "sq.locationName": "Nama lokasi",
  "sq.address": "Alamat (opsional)",
  "sq.phone": "Telepon (opsional)",
  "sq.noLocations": "Belum ada lokasi.",
  "sq.queues": "Antrean",
  "sq.addQueue": "Tambah antrean",
  "sq.queueName": "Nama antrean",
  "sq.prefix": "Huruf nomor",
  "sq.prefixHint": "Maksimal dua huruf sebelum nomor, seperti A12.",
  "sq.description": "Antrean ini untuk apa? (opsional)",
  "sq.avgTime": "Waktu umum (menit)",
  "sq.counters": "Loket",
  "sq.counterName": "Counter name",
  "sq.addCounter": "Tambah loket",
  "sq.paused": "Dijeda",
  "sq.open": "Terbuka",
  "sq.closed": "Closed",
  "sq.noQueues": "Belum ada antrean di lokasi ini.",
  "sq.deleteQueue": "Hapus antrean ini",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "Mulai dari jenis usaha",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "Pelanggan tidak bisa mengambil nomor di antrean ini saat dijeda.",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "Tim Anda",
  "team.sub": "Undang orang yang bekerja di loket dan pilih apa yang boleh mereka lakukan.",
  "team.invite": "Undang seseorang",
  "team.invited": "Undangan terkirim",
  "team.inviteEmail": "Email mereka",
  "team.inviteRole": "Apa yang bisa mereka lakukan",
  "team.pending": "Menunggu untuk bergabung",
  "team.noPending": "Tidak ada undangan tertunda.",
  "team.revoke": "Batalkan undangan",
  "team.role": "Peran",
  "team.roleOwner": "Pemilik",
  "team.roleManager": "Manajer",
  "team.roleStaff": "Staf",
  "team.roleViewer": "Hanya lihat",
  "team.remove": "Keluarkan dari tim",
  "team.lock": "Keluar dari semua",
  "team.unlock": "Izinkan masuk",
  "team.allBranches": "Semua lokasi",
  "team.oneBranch": "One location",
  "team.pickBranch": "Lokasi",
  "team.noTeam": "Saat ini hanya Anda.",
  "team.linkCopied": "Tautan undangan disalin. Kirimkan kepada mereka.",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "Bagaimana hari ini dan minggu lalu sebenarnya berjalan.",
  "rep.joined": "Nomor yang diambil",
  "rep.served": "Pelanggan dilayani",
  "rep.avgWait": "Rata-rata tunggu",
  "rep.avgService": "Rata-rata layanan",
  "rep.peak": "Jam puncak",
  "rep.abandoned": "Pergi tanpa dilayani",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "7 hari terakhir",
  "rep.days30": "30 hari terakhir",
  "rep.days90": "90 hari terakhir",
  "rep.byDay": "Each day",
  "rep.byHour": "Jam tersibuk",
  "rep.byQueue": "Setiap antrean",
  "rep.waited": "menunggu {n} mnt",
  "rep.servedIn": "dilayani dalam {n} mnt",
  "rep.history": "Semua yang datang",
  "rep.noHistory": "Belum ada yang melewati antrean ini pada periode ini.",
  "rep.audit": "Perubahan oleh tim Anda",
  "rep.noAudit": "Belum ada perubahan yang tercatat.",
  "rep.noReports": "Peran Anda tidak bisa melihat laporan.",
  "set.brand": "Tampilan",
  "set.brandHint": "Warna dan logo Anda tampil di halaman pelanggan dan layar TV.",
  "set.mainColour": "Warna utama",
  "set.accentColour": "Warna aksen",
  "set.logo": "Logo",
  "set.logoHint": "Tempel tautan web atau unggah gambar. Yang kecil lebih baik.",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "Hapus logo",
  "set.security": "Kata sandi Anda",
  "set.currentPassword": "Kata sandi saat ini",
  "set.newPassword": "Kata sandi baru",
  "set.changePassword": "Ganti kata sandi",
  "set.passwordChanged": "Kata sandi diganti. Perangkat lain telah keluar.",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "Sedang dipanggil",
  "disp.waiting": "Menunggu",
  "disp.others": "Antrean lain",
  "disp.fullscreen": "Layar penuh",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "Menunggu nomor pertama",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "Perkiraan tunggu",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "Langsung secara bawaan",
  "hero.statPhone": "Bisa dipakai di ponsel apa pun",
  "feat.title": "Semua yang dibutuhkan antrean, tidak lebih",
  "feat.copy": "Lobby melakukan satu hal dengan baik. Setiap layar di bawah sudah bagian dari produk hari ini.",
  "feat.qr.t": "Satu kode, selalu terkini",
  "feat.qr.d": "QR code permanen untuk tiap lokasi. Cetak sekali. Mengganti nama toko tidak pernah merusaknya.",
  "feat.multi.t": "Banyak antrean, satu layar",
  "feat.multi.d": "Bagi loket menjadi layanan, konsultasi, ambil, retur, dengan nomor dan loket sendiri.",
  "feat.team.t": "Peran yang cocok untuk toko",
  "feat.team.d": "Undang staf lewat tautan, ikat ke cabang, dan biarkan pemilik memegang kunci.",
  "feat.brand.t": "Seperti usaha Anda",
  "feat.brand.d": "Warna, logo, dan catatan Anda tampil di ponsel setiap pelanggan dan di TV.",
  "feat.reports.t": "Fakta untuk malam yang tenang",
  "feat.reports.d": "Waktu tunggu, jam sibuk, dan riwayat lengkap. Jadwal minggu depan bukan tebakan lagi.",
  "feat.pause.t": "Tutup tanpa kebingungan",
  "feat.pause.d": "Jeda antrean dengan sekali ketuk. Papan pintu memberi tahu, dan tidak ada yang ambil nomor ke loket yang tutup.",
  "flow.title": "Dari pintu sampai selesai dalam empat langkah",
  "flow.s1.t": "Pelanggan bergabung ke antrean",
  "flow.s1.d": "Mereka memindai kode, memilih layanan, dan mengambil nomor. Tanpa app, tanpa akun.",
  "flow.s2.t": "Staf memanggil berikutnya",
  "flow.s2.d": "Satu tombol besar melayani orang berikutnya dan menjaga antrean tetap adil.",
  "flow.s3.t": "Semua melihat statusnya",
  "flow.s3.d": "Setiap ponsel menunjukkan posisi, sisa orang di depan, dan estimasi tunggu, langsung, tanpa muat ulang.",
  "flow.s4.t": "Layar menjaga ketertiban",
  "flow.s4.d": "TV di ruang tunggu menunjukkan siapa yang dilayani dan siapa berikutnya.",
  "dispsect.title": "Layar yang layak untuk ruang tunggu Anda",
  "dispsect.copy": "Buka tampilan di browser TV mana pun. Nomor besar, lima berikutnya, dan antrean lain sekali lihat. Diperbarui begitu staf bertindak.",
  "dispsect.cta": "Lihat tampilan langsung",
  "dash.servingCounters": "{n} melayani",
};

const zh: Pack = {
  "nav.about": "关于",
  "nav.signin": "登录",
  "nav.setup": "设置你的店铺",
  "foot.made": "Lobby，由 {name} 制作。",
  "foot.mit": "MIT 许可证下的开源软件。",
  "lang.title": "选择你的语言",
  "lang.sub": "之后可以点击右上角的国旗随时更换。",
  "lang.change": "切换语言",
  "lang.done": "完成",
  "common.loading": "加载中…",
  "common.retry": "重试",
  "hero.eyebrow": "为商店、诊所和美容院打造的排队系统",
  "hero.h1a": "取一个号码。",
  "hero.h1b": "在哪里等都行。",
  "hero.lede":
    "你的店只需一个二维码。顾客扫码取号，随时看到自己在队中的位置。轮到他们时，手机会提醒他们。",
  "hero.fine": "顾客不用装应用，也不用注册账号。开源软件，运行在你自己的服务器上。",
  "demo.nowServing": "正在服务",
  "demo.yourNumber": "你的号码",
  "how.title": "使用方法",
  "how.t1": "打印你的二维码",
  "how.d1": "一个永久有效的码，贴在门口或柜台。",
  "how.t2": "顾客取号",
  "how.d2": "扫码即可，想写名字就写，什么都不用安装。",
  "how.t3": "按下“呼叫下一位”",
  "how.d3": "队伍前进，他们的屏幕自动更新。",
  "see.title": "顾客看到的界面",
  "see.copy":
    "一块屏幕，永远回答同样的问题。任何手机浏览器都能打开，你呼叫号码时它会变成“轮到你了”。",
  "see.youreNumber": "你的号码",
  "see.peopleAhead": "前面还有几人",
  "see.when": "轮到时",
  "see.itsTurn": "轮到你了！",
  "places.title": "适合有柜台的地方",
  "places.list": "药店 · 诊所 · 美容院 · 理发店 · 维修店 · 银行 · 邮局 · 政府办事窗口",
  "band.title": "大约一分钟即可完成设置。",
  "auth.welcome": "欢迎回来",
  "auth.setupSub": "输入一分钟，排队即可开始。",
  "auth.loginSub": "登录你的排队页面。",
  "auth.bizName": "店铺名称",
  "auth.yourName": "你的名字",
  "auth.email": "邮箱",
  "auth.password": "密码",
  "auth.pwHint": "至少 8 个字符。",
  "auth.creating": "正在创建…",
  "auth.signingIn": "正在登录…",
  "auth.create": "创建我的店铺",
  "auth.haveAccount": "已经有账号了？",
  "auth.noAccount": "还没有账号？",
  "auth.backHome": "返回首页",
  "err.bizName": "请输入店铺名称。",
  "err.name": "请输入你的名字。",
  "err.email": "请输入邮箱。",
  "err.password": "请输入密码。",
  "err.pwLen": "密码至少需要 8 个字符。",
  "cust.opening": "正在打开排队页面…",
  "cust.wrong": "出了点问题。",
  "cust.pausedT": "排队已暂停。",
  "cust.pausedB": "这家店暂时不发号了，请稍后再来看看。",
  "cust.nobody": "暂时还没有人被服务",
  "cust.noOneWaiting": "无人等待",
  "cust.waitingN": "{n} 人等待中",
  "cust.joinT": "加入排队",
  "cust.nameLabel": "你的名字（可不填）",
  "cust.joinBusy": "正在取号…",
  "cust.joinReassure": "不用装应用，不用注册，只要一个号码。",
  "cust.youreNumber": "你的号码",
  "cust.youreNext": "下一位就是你",
  "cust.oneAhead": "前面还有 1 人",
  "cust.nAhead": "前面还有 {n} 人",
  "cust.peopleWaiting": "等待人数",
  "cust.reassure": "此页面会自动更新，请保持打开。",
  "cust.leave": "离开队伍",
  "cust.leaveConfirm": "离开队伍？你会失去当前号码。",
  "cust.turnT": "轮到你了",
  "cust.turnB": "请到柜台来。",
  "cust.imHere": "我到了",
  "cust.sending": "发送中…",
  "cust.confirmed": "谢谢，我们已经告诉他们你准备好了。",
  "cust.done": "全部完成",
  "cust.servedBody": "感谢等待。",
  "cust.skippedBody": "你被跳过了。如果还在，请重新取号。",
  "cust.noShowBody": "这个号码已关闭。如果还在，请重新取号。",
  "cust.joinAgain": "重新排队",
  "cust.poweredBy": "由",
  "dash.navQueue": "排队",
  "dash.navQr": "二维码",
  "dash.navSettings": "设置",
  "dash.signOut": "退出登录",
  "dash.opening": "正在打开你的排队页面…",
  "dash.pausedB": "顾客现在无法取号。",
  "dash.nobodyCounter": "柜台没有人",
  "dash.noNameGiven": "没有名字",
  "dash.confirmedHere": "说已经到了",
  "dash.notConfirmed": "还没有确认",
  "dash.callNext": "呼叫下一位",
  "dash.calling": "呼叫中…",
  "dash.noWaitingHint": "现在没有人等待。",
  "dash.pause": "暂停排队",
  "dash.resume": "恢复排队",
  "dash.atCounter": "柜台服务中",
  "dash.waitingTitle": "等待中",
  "dash.noName": "没有名字",
  "dash.stWait": "等待中",
  "dash.stCalled": "服务中",
  "dash.stServed": "已服务",
  "dash.stSkipped": "已跳过",
  "dash.stNoShow": "未到场",
  "dash.firstRun": "现在还没人。三步就能让排队开始运转：",
  "dash.step1": "拿到你的二维码。打印出来，或放在门口的屏幕上。",
  "dash.step1link": "打开我的二维码 →",
  "dash.step2": "顾客取号：扫码、可选填名字，然后就排上了。",
  "dash.step3": "按下“呼叫下一位”，他们的手机立刻更新。",
  "dash.emptyWaiting": "没人等待。随着客人到来，新号码会出现在这里。",
  "dash.nextUp": "下一位",
  "dash.finished": "已完成",
  "dash.counts": "已服务 {s}，跳过 {k}，未到场 {n}",
  "dash.markServed": "标记为已服务",
  "dash.skip": "跳过",
  "qr.intro": "打印并贴在门口或柜台上。链接永不变，今天打印的码一直有效。",
  "qr.linkLabel": "你的排队链接",
  "qr.download": "下载 PNG",
  "qr.print": "打印",
  "qr.copy": "复制链接",
  "qr.copied": "链接已复制。",
  "qr.making": "正在生成二维码…",
  "qr.sheetCta": "扫码加入排队",
  "qr.fine": "顾客扫码即可取号，无需应用和账号。二维码在所有主题下都是黑白的，方便手机识别。",
  "set.noteLabel": "给顾客的留言",
  "set.noteHint": "显示在排队页“加入”按钮上方，可不填。",
  "set.save": "保存修改",
  "set.saving": "保存中…",
  "set.saved": "已保存。",
  "set.goodToKnow": "小提示",
  "set.linkBody": "链接是永久的，即使你改了店名，打印过的二维码依然有效。",
  "set.signedInAs": "登录身份",
  "set.errNote": "留言最多 200 个字符。",
  "nf.title": "这个页面不存在。",
  "nf.body": "它可能被移动了，或者链接输错了。",
  "nf.cta": "回到首页",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "在线演示",
  "common.live": "实时",
  "common.reconnecting": "正在重新连接…",
  "common.offline": "你已离线。本页会在网络恢复后自动更新。",
  "common.optional": "optional",
  "common.cancel": "取消",
  "common.remove": "移除",
  "common.add": "添加",
  "common.save": "Save",
  "common.saved": "已保存。",
  "common.minutes": "{n} 分钟",
  "common.branch": "地点",
  "common.allBranches": "所有地点",
  "common.back": "Back",
  "band.body": "从店铺类型开始，餐厅、诊所、美容院、维修店，名字随时可改。开新店时再加地点。",
  "band.try": "查看在线演示",
  "demo.title": "看看它如何运作",
  "demo.sub": "一个可以随便按按钮的练习店。以顾客身份加入，以员工身份叫号，看看电视屏幕。这里的一切都不是真的。",
  "demo.paneCustomer": "顾客手机",
  "demo.paneStaff": "员工手机",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "电视屏幕",
  "demo.joinName": "姓名（可选）",
  "demo.join": "取号",
  "demo.reset": "重置演示",
  "demo.callNext": "呼叫下一位",
  "demo.serve": "完成",
  "demo.skip": "跳过",
  "demo.waitingList": "Waiting",
  "demo.hint": "试着呼叫一个号码，四个面板会同时更新。",
  "auth.shopType": "这是什么类型的生意？",
  "auth.shopTypeHint": "我们会为你创建队列和窗口，之后可以随时改名。",
  "auth.branchName": "第一个地点",
  "auth.inviteTitle": "你已被邀请",
  "auth.inviteBody": "{business} 邀请你以 {role} 身份管理排队。",
  "auth.joinTeam": "加入团队",
  "auth.inviteBad": "此邀请已失效。请向你的经理索取新的邀请。",
  "cust.phoneLabel": "电话（可选）",
  "cust.estWait": "预计等待 {n} 分钟",
  "cust.pickQueue": "你需要什么服务？",
  "cust.pickBranch": "哪个地点？",
  "cust.pickQueueHint": "选择一个队列来取号。",
  "cust.held": "暂缓",
  "cust.heldBody": "工作人员很快会叫到你。",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "队列",
  "dash.navTeam": "团队",
  "dash.navReports": "历史",
  "dash.holdTitle": "暂缓",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "已离开",
  "dash.hold": "暂缓",
  "dash.release": "放回队列",
  "dash.recall": "再次呼叫",
  "dash.cancel": "Remove from queue",
  "dash.move": "转移",
  "dash.moveTo": "转移到其他队列",
  "dash.call": "呼叫",
  "dash.addWalkIn": "添加顾客",
  "dash.addWalkInBody": "用于电话预约和站在你面前的人。",
  "dash.noteLabel": "备注（可选）",
  "dash.counterLabel": "窗口",
  "dash.anyCounter": "任意窗口",
  "dash.avgWait": "平均等待 {n} 分钟",
  "dash.peopleWaiting": "{n} 人在等待",
  "dash.tvLink": "打开电视屏幕",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "该地点还没有队列。",
  "dash.pickQueue": "选择队列",
  "dash.roleTag": "你的角色：{role}",
  "dash.noPermission": "你的角色无法执行此操作。",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "此码对应的队列",
  "qr.displayLink": "电视屏幕链接",
  "sq.title": "队列与窗口",
  "sq.sub": "每个队列有自己的号码和队列线。",
  "sq.locations": "地点",
  "sq.addLocation": "添加地点",
  "sq.locationName": "地点名称",
  "sq.address": "地址（可选）",
  "sq.phone": "电话（可选）",
  "sq.noLocations": "还没有地点。",
  "sq.queues": "队列",
  "sq.addQueue": "添加队列",
  "sq.queueName": "队列名称",
  "sq.prefix": "号码前缀",
  "sq.prefixHint": "号码前最多两个字母，如 A12。",
  "sq.description": "这个队列是做什么的？（可选）",
  "sq.avgTime": "通常时长（分钟）",
  "sq.counters": "窗口",
  "sq.counterName": "Counter name",
  "sq.addCounter": "添加窗口",
  "sq.paused": "已暂停",
  "sq.open": "开放中",
  "sq.closed": "Closed",
  "sq.noQueues": "该地点还没有队列。",
  "sq.deleteQueue": "删除此队列",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "从店铺类型开始",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "暂停期间，顾客无法在此队列取号。",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "你的团队",
  "team.sub": "邀请在柜台工作的人，并选择每个人能做什么。",
  "team.invite": "邀请成员",
  "team.invited": "邀请已发送",
  "team.inviteEmail": "对方的邮箱",
  "team.inviteRole": "他们能做什么",
  "team.pending": "等待加入",
  "team.noPending": "没有待处理的邀请。",
  "team.revoke": "取消邀请",
  "team.role": "角色",
  "team.roleOwner": "店主",
  "team.roleManager": "经理",
  "team.roleStaff": "员工",
  "team.roleViewer": "只读",
  "team.remove": "移出团队",
  "team.lock": "退出所有设备",
  "team.unlock": "允许登录",
  "team.allBranches": "所有地点",
  "team.oneBranch": "One location",
  "team.pickBranch": "地点",
  "team.noTeam": "目前只有你一个人。",
  "team.linkCopied": "邀请链接已复制，发给对方即可。",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "今天和上周的实际运行情况。",
  "rep.joined": "取号数",
  "rep.served": "服务人数",
  "rep.avgWait": "平均等待",
  "rep.avgService": "平均服务时长",
  "rep.peak": "高峰时段",
  "rep.abandoned": "未被服务即离开",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "最近 7 天",
  "rep.days30": "最近 30 天",
  "rep.days90": "最近 90 天",
  "rep.byDay": "Each day",
  "rep.byHour": "最繁忙时段",
  "rep.byQueue": "各队列",
  "rep.waited": "等待 {n} 分钟",
  "rep.servedIn": "{n} 分钟内完成",
  "rep.history": "所有来过的人",
  "rep.noHistory": "本时段内该队列暂无人经过。",
  "rep.audit": "团队所做的更改",
  "rep.noAudit": "暂无更改记录。",
  "rep.noReports": "你的角色无法查看报表。",
  "set.brand": "外观",
  "set.brandHint": "你的颜色和 logo 会显示在顾客页面和电视屏幕上。",
  "set.mainColour": "主色",
  "set.accentColour": "点缀色",
  "set.logo": "Logo",
  "set.logoHint": "粘贴网页链接或上传图片，小图更合适。",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "移除 Logo",
  "set.security": "你的密码",
  "set.currentPassword": "当前密码",
  "set.newPassword": "新密码",
  "set.changePassword": "修改密码",
  "set.passwordChanged": "密码已修改，其他设备已退出登录。",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "正在呼叫",
  "disp.waiting": "等待中",
  "disp.others": "其他队列",
  "disp.fullscreen": "全屏",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "等待第一个号码",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "预计等待",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "默认实时",
  "hero.statPhone": "任何手机都能用",
  "feat.title": "排队需要的一切，仅此而已",
  "feat.copy": "Lobby 只做好一件事。下面的每块屏幕都已是产品的一部分。",
  "feat.qr.t": "一个码，永远有效",
  "feat.qr.d": "每个地点一个永久二维码。打印一次。店名怎么改都不会失效。",
  "feat.multi.t": "多个队列，一块屏幕",
  "feat.multi.d": "把柜台拆分成服务，咨询、领取、退货，各有编号和窗口。",
  "feat.team.t": "适合小店的角色",
  "feat.team.d": "用链接邀请员工，绑定到分店，钥匙仍由店主保管。",
  "feat.brand.t": "呈现你的品牌",
  "feat.brand.d": "你的颜色、logo 和提示会出现在每位顾客的手机和电视上。",
  "feat.reports.t": "让晚班心里有数",
  "feat.reports.d": "等待时长、高峰时段和完整历史。下周排班不用再靠猜。",
  "feat.pause.t": "关店不混乱",
  "feat.pause.d": "一键暂停队列。门口的牌子会说明，没人会在关闭的窗口取号。",
  "flow.title": "从进门到办完，只需四步",
  "flow.s1.t": "顾客加入排队",
  "flow.s1.d": "扫码、选服务、取号。不用装 App，不用注册。",
  "flow.s2.t": "员工呼叫下一位",
  "flow.s2.d": "一个大按钮服务下一位，让队伍保持公平。",
  "flow.s3.t": "每个人都能看到自己的状态",
  "flow.s3.d": "每部手机都能看到位置、前面还有几人和等待时间，实时刷新，无需手动刷新。",
  "flow.s4.t": "大屏维持秩序",
  "flow.s4.d": "等候区的电视显示正在服务谁、下一位是谁。",
  "dispsect.title": "配得上你等候区的大屏",
  "dispsect.copy": "在任何电视浏览器上打开显示大屏。巨大号码、接下来五位和其他队列一目了然。员工一操作就即时更新。",
  "dispsect.cta": "查看实时大屏",
  "dash.servingCounters": "{n} 个服务中",
};

const ja: Pack = {
  "nav.about": "このアプリについて",
  "nav.signin": "ログイン",
  "nav.setup": "店舗を設定する",
  "foot.made": "Lobby は {name} が制作しました。",
  "foot.mit": "MIT ライセンスのオープンソース。",
  "lang.title": "言語を選んでください",
  "lang.sub": "あとから右上の旗から変更できます。",
  "lang.change": "言語を変更",
  "lang.done": "完了",
  "common.loading": "読み込み中…",
  "common.retry": "もう一度試す",
  "hero.eyebrow": "お店・クリニック・サロンのための順番待ち",
  "hero.h1a": "番号を取ります。",
  "hero.h1b": "どこで待ってもOK。",
  "hero.lede":
    "お店に必要なのは QR コードひとつ。お客さんが読み取って番号を取得し、順番をいつでも確認できます。番が回るとスマホが知らせます。",
  "hero.fine":
    "お客さんにアプリもアカウントも不要。オープンソースで、ご自身のサーバーで動きます。",
  "demo.nowServing": "今お呼びしている番号",
  "demo.yourNumber": "あなたの番号",
  "how.title": "使い方",
  "how.t1": "QR コードを印刷する",
  "how.d1": "入口やカウンターに貼れる、変わらない番号札です。",
  "how.t2": "お客さんが番号を取る",
  "how.d2": "読み取って、任意で名前を入力。インストールは一切不要。",
  "how.t3": "「次の方を呼ぶ」を押す",
  "how.d3": "列が進み、画面は自動で更新されます。",
  "see.title": "お客さんの画面",
  "see.copy":
    "いつも同じ答えを出す画面がひとつ。スマホのブラウザで動いて、番号を呼ぶと「あなたの番です」に変わります。",
  "see.youreNumber": "あなたの番号",
  "see.peopleAhead": "前の人数",
  "see.when": "そのとき",
  "see.itsTurn": "あなたの番です！",
  "places.title": "カウンターのある場所へ",
  "places.list": "薬局 · 診療所 · 美容室 · バーバー · 修理店 · 銀行 · 郵便局 · 公共機関",
  "band.title": "設定は約1分です。",
  "auth.welcome": "おかえりなさい",
  "auth.setupSub": "少し入力するだけで、順番待ちの準備ができました。",
  "auth.loginSub": "順番待ちにログインします。",
  "auth.bizName": "店名",
  "auth.yourName": "お名前",
  "auth.email": "メール",
  "auth.password": "パスワード",
  "auth.pwHint": "8文字以上。",
  "auth.creating": "作成中…",
  "auth.signingIn": "ログイン中…",
  "auth.create": "店舗を作成する",
  "auth.haveAccount": "アカウントをお持ちですか？",
  "auth.noAccount": "まだアカウントがありませんか？",
  "auth.backHome": "ホームに戻る",
  "err.bizName": "店名を入力してください。",
  "err.name": "お名前を入力してください。",
  "err.email": "メールアドレスを入力してください。",
  "err.password": "パスワードを入力してください。",
  "err.pwLen": "パスワードは8文字以上にしてください。",
  "cust.opening": "順番待ちを開いています…",
  "cust.wrong": "何か問題が起きました。",
  "cust.pausedT": "順番待ちは一時停止中です。",
  "cust.pausedB": "このお店は今番号を出していません。しばらくしてまたご確認ください。",
  "cust.nobody": "まだ誰も呼ばれていません",
  "cust.noOneWaiting": "待機中の人はいません",
  "cust.waitingN": "{n}人が待機中",
  "cust.joinT": "順番待ちに参加",
  "cust.nameLabel": "お名前（任意）",
  "cust.joinBusy": "番号を取得しています…",
  "cust.joinReassure": "アプリ不要、アカウント不要、番号だけ。",
  "cust.youreNumber": "あなたの番号",
  "cust.youreNext": "次はあなたです",
  "cust.oneAhead": "前に1人",
  "cust.nAhead": "前に{n}人",
  "cust.peopleWaiting": "待機人数",
  "cust.reassure": "この画面は自動で更新されます。開いたままにしてください。",
  "cust.leave": "列をやめる",
  "cust.leaveConfirm": "列をやめますか？ 番号は失われます。",
  "cust.turnT": "あなたの番です",
  "cust.turnB": "カウンターへお越しください。",
  "cust.imHere": "来ました",
  "cust.sending": "送信中…",
  "cust.confirmed": "ありがとうございます。準備ができた旨を伝えました。",
  "cust.done": "完了",
  "cust.servedBody": "お待ちいただきありがとうございました。",
  "cust.skippedBody": "スキップされました。まだいる方は別の番号をどうぞ。",
  "cust.noShowBody": "この番号は終了しました。まだいる方は別の番号をどうぞ。",
  "cust.joinAgain": "もう一度参加",
  "cust.poweredBy": "提供",
  "dash.navQueue": "順番待ち",
  "dash.navQr": "QR コード",
  "dash.navSettings": "設定",
  "dash.signOut": "ログアウト",
  "dash.opening": "順番待ちを開いています…",
  "dash.pausedB": "お客さんは今番号を取れません。",
  "dash.nobodyCounter": "カウンターに誰もいません",
  "dash.noNameGiven": "名前なし",
  "dash.confirmedHere": "さんが来場済みです",
  "dash.notConfirmed": "さんが未確認です",
  "dash.callNext": "次の方を呼ぶ",
  "dash.calling": "呼んでいます…",
  "dash.noWaitingHint": "今は待機中の人がいません。",
  "dash.pause": "一時停止",
  "dash.resume": "再開する",
  "dash.atCounter": "カウンターで対応中",
  "dash.waitingTitle": "待機中",
  "dash.noName": "名前なし",
  "dash.stWait": "待機中",
  "dash.stCalled": "対応中",
  "dash.stServed": "対応済み",
  "dash.stSkipped": "スキップ",
  "dash.stNoShow": "不在",
  "dash.firstRun": "まだ誰もいません。3つのステップで順番待ちが動き出します：",
  "dash.step1": "QR コードを入手。印刷するか、入口付近の画面に表示します。",
  "dash.step1link": "QR コードを開く →",
  "dash.step2": "お客さんが番号を取得。読み取り、任意で名前を入力するだけ。",
  "dash.step3": "「次の方を呼ぶ」を押すと、その場で画面が更新されます。",
  "dash.emptyWaiting": "待機中の人はいません。人が来るたびに新しい番号がここに表示されます。",
  "dash.nextUp": "次",
  "dash.finished": "終了した番号",
  "dash.counts": "対応 {s}、スキップ {k}、不在 {n}",
  "dash.markServed": "対応済みにする",
  "dash.skip": "スキップ",
  "qr.intro": "印刷して入口やカウンターへ。リンクは永遠に変わらないので、今日印刷したコードもずっと使えます。",
  "qr.linkLabel": "順番待ちのリンク",
  "qr.download": "PNG をダウンロード",
  "qr.print": "印刷",
  "qr.copy": "リンクをコピー",
  "qr.copied": "リンクをコピーしました。",
  "qr.making": "QR コードを作成中…",
  "qr.sheetCta": "読み取って順番待ちに参加",
  "qr.fine": "お客さんは読み取るだけで番号を取得できます。アプリもアカウントも不要。どんなテーマでも黒白のまま、スマホが読み取れます。",
  "set.noteLabel": "お客さんへのひとこと",
  "set.noteHint": "順番待ちページの参加ボタンの上に表示されます。任意です。",
  "set.save": "変更を保存",
  "set.saving": "保存中…",
  "set.saved": "保存しました。",
  "set.goodToKnow": "覚えておくと便利",
  "set.linkBody": "リンクは固定です。店名を変えても、印刷した QR は動き続けます。",
  "set.signedInAs": "ログイン中",
  "set.errNote": "ひとっことは200文字以内にしてください。",
  "nf.title": "このページは存在しません。",
  "nf.body": "移動したか、リンクを打ち間違えたようです。",
  "nf.cta": "ホームページへ",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "ライブデモ",
  "common.live": "ライブ",
  "common.reconnecting": "再接続中…",
  "common.offline": "オフラインです。このページは自動的に更新されます。",
  "common.optional": "optional",
  "common.cancel": "キャンセル",
  "common.remove": "削除",
  "common.add": "追加",
  "common.save": "Save",
  "common.saved": "保存しました。",
  "common.minutes": "{n} 分",
  "common.branch": "拠点",
  "common.allBranches": "すべての拠点",
  "common.back": "Back",
  "band.body": "店の種類から始めましょう、レストラン、クリニック、サロン、修理店、名前はあとから変更できます。新しい店を開いたら場所を追加してください。",
  "band.try": "ライブデモを見る",
  "demo.title": "動作を見る",
  "demo.sub": "ボタンを押せる練習用のお店です。お客様として参加し、スタッフとして番号を呼び、TV画面を見てください。ここにあるものは何も実際のものではありません。",
  "demo.paneCustomer": "お客様のスマホ",
  "demo.paneStaff": "スタッフのスマホ",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "TV画面",
  "demo.joinName": "名前（任意）",
  "demo.join": "番号を取る",
  "demo.reset": "デモをリセット",
  "demo.callNext": "次を呼ぶ",
  "demo.serve": "完了",
  "demo.skip": "スキップ",
  "demo.waitingList": "Waiting",
  "demo.hint": "番号を呼び出して、4つのパネルが同時に更新される様子を見てください。",
  "auth.shopType": "どんなお店ですか？",
  "auth.shopTypeHint": "キューとカウンターを作成します。名前はあとから変更できます。",
  "auth.branchName": "最初の拠点",
  "auth.inviteTitle": "招待されました",
  "auth.inviteBody": "{business} があなたを{role}として行列の管理に招待しました。",
  "auth.joinTeam": "チームに参加",
  "auth.inviteBad": "この招待はすでに無効です。新しい招待を管理者に依頼してください。",
  "cust.phoneLabel": "電話番号（任意）",
  "cust.estWait": "約 {n} 分待ち",
  "cust.pickQueue": "ご用件は？",
  "cust.pickBranch": "どの拠点ですか？",
  "cust.pickQueueHint": "番号を取るキューを選んでください。",
  "cust.held": "保留中",
  "cust.heldBody": "まもなくスタッフがお呼びします。",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "キュー",
  "dash.navTeam": "チーム",
  "dash.navReports": "履歴",
  "dash.holdTitle": "保留中",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "退室",
  "dash.hold": "保留",
  "dash.release": "行列に戻す",
  "dash.recall": "もう一度呼ぶ",
  "dash.cancel": "Remove from queue",
  "dash.move": "移動",
  "dash.moveTo": "別のキューへ移動",
  "dash.call": "呼ぶ",
  "dash.addWalkIn": "お客さんを追加",
  "dash.addWalkInBody": "電話予約や目の前にいる人向け。",
  "dash.noteLabel": "メモ（任意）",
  "dash.counterLabel": "カウンター",
  "dash.anyCounter": "どのカウンターでも",
  "dash.avgWait": "平均待ち {n} 分",
  "dash.peopleWaiting": "{n}名待機中",
  "dash.tvLink": "TV画面を開く",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "この拠点にはまだキューがありません。",
  "dash.pickQueue": "キューを選択",
  "dash.roleTag": "あなたの役割: {role}",
  "dash.noPermission": "この役割ではできません。",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "このコードのキュー",
  "qr.displayLink": "TV画面のリンク",
  "sq.title": "キューとカウンター",
  "sq.sub": "各キューは固有の番号と独自の列を持ちます。",
  "sq.locations": "拠点",
  "sq.addLocation": "拠点を追加",
  "sq.locationName": "拠点名",
  "sq.address": "住所（任意）",
  "sq.phone": "電話番号（任意）",
  "sq.noLocations": "まだ拠点がありません。",
  "sq.queues": "キュー",
  "sq.addQueue": "キューを追加",
  "sq.queueName": "キュー名",
  "sq.prefix": "番号の頭文字",
  "sq.prefixHint": "番号の前に2文字まで。例：A12。",
  "sq.description": "このキューの用途は？（任意）",
  "sq.avgTime": "標準所要時間（分）",
  "sq.counters": "カウンター",
  "sq.counterName": "Counter name",
  "sq.addCounter": "カウンターを追加",
  "sq.paused": "一時停止中",
  "sq.open": "受付中",
  "sq.closed": "Closed",
  "sq.noQueues": "この拠点にはまだキューがありません。",
  "sq.deleteQueue": "このキューを削除",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "店の種類から始める",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "一時停止中は、このキューで番号を取れません。",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "あなたのチーム",
  "team.sub": "カウンターで働く人を招待し、それぞれにできることを選びます。",
  "team.invite": "誰かを招待",
  "team.invited": "招待を送信しました",
  "team.inviteEmail": "相手のメールアドレス",
  "team.inviteRole": "できること",
  "team.pending": "参加待ち",
  "team.noPending": "保留中の招待はありません。",
  "team.revoke": "招待を取り消す",
  "team.role": "役割",
  "team.roleOwner": "オーナー",
  "team.roleManager": "マネージャー",
  "team.roleStaff": "スタッフ",
  "team.roleViewer": "閲覧のみ",
  "team.remove": "チームから外す",
  "team.lock": "全端末でサインアウト",
  "team.unlock": "サインインを許可",
  "team.allBranches": "すべての拠点",
  "team.oneBranch": "One location",
  "team.pickBranch": "拠点",
  "team.noTeam": "今のところあなた一人です。",
  "team.linkCopied": "招待リンクをコピーしました。送ってください。",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "今日と先週の実際の様子。",
  "rep.joined": "取得した番号",
  "rep.served": "対応したお客さん",
  "rep.avgWait": "平均待ち時間",
  "rep.avgService": "平均対応時間",
  "rep.peak": "ピーク時間",
  "rep.abandoned": "対応前に退室",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "過去7日",
  "rep.days30": "過去30日",
  "rep.days90": "過去90日",
  "rep.byDay": "Each day",
  "rep.byHour": "混雑時間帯",
  "rep.byQueue": "キューごと",
  "rep.waited": "{n} 分待機",
  "rep.servedIn": "{n}分で対応",
  "rep.history": "来店したすべての人",
  "rep.noHistory": "この期間、このキューを利用した人はいません。",
  "rep.audit": "チームによる変更",
  "rep.noAudit": "まだ変更は記録されていません。",
  "rep.noReports": "この役割ではレポートを表示できません。",
  "set.brand": "見た目",
  "set.brandHint": "あなたの色とロゴは顧客ページとTV画面に表示されます。",
  "set.mainColour": "メインカラー",
  "set.accentColour": "アクセントカラー",
  "set.logo": "ロゴ",
  "set.logoHint": "Webリンクを貼るか画像をアップロード。小さいほうが最適です。",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "ロゴを削除",
  "set.security": "あなたのパスワード",
  "set.currentPassword": "現在のパスワード",
  "set.newPassword": "新しいパスワード",
  "set.changePassword": "パスワードを変更",
  "set.passwordChanged": "パスワードを変更しました。他のデバイスはサインアウトされました。",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "呼び出し中",
  "disp.waiting": "待機中",
  "disp.others": "その他のキュー",
  "disp.fullscreen": "全画面",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "最初の番号を待っています",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "待ち時間の目安",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "標準でライブ",
  "hero.statPhone": "どのスマホでも動く",
  "feat.title": "行列に必要なものだけ、余計なものは何も",
  "feat.copy": "Lobbyは一つのことを丁寧にやります。下のすべての画面は今日すでに製品の一部です。",
  "feat.qr.t": "1つのコード、常に最新",
  "feat.qr.d": "拠点ごとの恒久QRコード。一度印刷すれば、お店の名前を変えても壊れません。",
  "feat.multi.t": "複数のキュー、1つの画面",
  "feat.multi.d": "カウンターを業務別に分割、相談、受取、返品、固有の番号とカウンターで。",
  "feat.team.t": "お店に合う役割",
  "feat.team.d": "リンクでスタッフを招待し、店舗に紐づけ、鍵はオーナーが持ちます。",
  "feat.brand.t": "お店らしさ",
  "feat.brand.d": "あなたの色、ロゴ、メモは顧客のスマホとTVに表示されます。",
  "feat.reports.t": "静かな夜のための事実",
  "feat.reports.d": "待ち時間、混雑時間帯、完全な履歴。来週のシフトはもう当てずっぽうではありません。",
  "feat.pause.t": "混乱せずにお休み",
  "feat.pause.d": "ワンタップでキューを一時停止。ドアの掲示がそれを伝え、閉じたカウンターで番号を取る人はいません。",
  "flow.title": "入口から完了まで4ステップ",
  "flow.s1.t": "お客さんが行列に加わる",
  "flow.s1.d": "コードを読み取り、サービスを選び、番号を取ります。アプリもアカウントも不要。",
  "flow.s2.t": "スタッフが次の人を呼ぶ",
  "flow.s2.d": "大きなボタンが次の人に順番を回し、行列を公平に保ちます。",
  "flow.s3.t": "誰でも自分の状況がわかる",
  "flow.s3.d": "各スマホで順番、前の人数、待ち時間がわかります、リロードなしでライブに。",
  "flow.s4.t": "画面が順番を整える",
  "flow.s4.d": "待合室のTVで、誰が呼ばれているか次の人が誰かがわかります。",
  "dispsect.title": "待合室にふさわしい画面",
  "dispsect.copy": "どのTVブラウザでも画面を開けます。大きな番号、次の5名、ほかのキューがひと目でわかります。スタッフが動くとすぐ更新されます。",
  "dispsect.cta": "ライブ画面を見る",
  "dash.servingCounters": "{n}対応中",
};

const ko: Pack = {
  "nav.about": "소개",
  "nav.signin": "로그인",
  "nav.setup": "가게 설정하기",
  "foot.made": "Lobby, {name}이 만들었습니다.",
  "foot.mit": "MIT 라이선스의 오픈 소스.",
  "lang.title": "언어를 선택하세요",
  "lang.sub": "나중에 오른쪽 위 깃발에서 변경할 수 있습니다.",
  "lang.change": "언어 변경",
  "lang.done": "완료",
  "common.loading": "불러오는 중…",
  "common.retry": "다시 시도",
  "hero.eyebrow": "상점, 클리닉, 미용실을 위한 대기줄",
  "hero.h1a": "번호를 받으세요.",
  "hero.h1b": "어디서든 기다리세요.",
  "hero.lede":
    "가게에 QR 코드 하나면 충분합니다. 손님이 스캔해 번호를 받고 대기 순서를 확인합니다. 차례가 되면 휴대폰이 알려줍니다.",
  "hero.fine":
    "손에게는 앱도, 계정도 필요 없습니다. 오픈 소스이고 내 서버에서 돌아갑니다.",
  "demo.nowServing": "지금 호출 중",
  "demo.yourNumber": "내 번호",
  "how.title": "사용 방법",
  "how.t1": "QR 코드를 인쇄하세요",
  "how.d1": "출입문이나 계산대에 붙일 영구 코드 하나.",
  "how.t2": "손님이 번호를 받습니다",
  "how.d2": "스캔하고, 원하면 이름을 적고, 설치할 것 없음.",
  "how.t3": "\"다음 호출\"을 누르세요",
  "how.d3": "줄이 움직이고 화면은 저절로 갱신됩니다.",
  "see.title": "손님이 보는 화면",
  "see.copy":
    "항상 같은 답을 주는 화면 하나. 모든 휴대폰 브라우저에서 열리고, 번호를 부르면 \"내 차례\"로 바뀝니다.",
  "see.youreNumber": "내 번호",
  "see.peopleAhead": "내 앞 인원",
  "see.when": "그 순간",
  "see.itsTurn": "내 차례입니다!",
  "places.title": "카운터가 있는 곳이면 어디든",
  "places.list": "약국 · 클리닉 · 미용실 · 이발소 · 수리점 · 은행 · 우체국 · 관공서",
  "band.title": "설정은 1분이면 끝납니다.",
  "auth.welcome": "다시 오신 것을 환영합니다",
  "auth.setupSub": "잠깐 입력하면 대기줄이 준비됩니다.",
  "auth.loginSub": "대기줄에 로그인하세요.",
  "auth.bizName": "가게 이름",
  "auth.yourName": "이름",
  "auth.email": "이메일",
  "auth.password": "비밀번호",
  "auth.pwHint": "8자 이상.",
  "auth.creating": "만드는 중…",
  "auth.signingIn": "로그인 중…",
  "auth.create": "내 가게 만들기",
  "auth.haveAccount": "이미 계정이 있나요?",
  "auth.noAccount": "아직 계정이 없나요?",
  "auth.backHome": "홈으로 돌아가기",
  "err.bizName": "가게 이름을 입력하세요.",
  "err.name": "이름을 입력하세요.",
  "err.email": "이메일을 입력하세요.",
  "err.password": "비밀번호를 입력하세요.",
  "err.pwLen": "비밀번호는 8자 이상이어야 합니다.",
  "cust.opening": "대기줄을 여는 중…",
  "cust.wrong": "문제가 생겼습니다.",
  "cust.pausedT": "대기줄이 일시정지되었습니다.",
  "cust.pausedB": "이 가게는 지금 번호를 받지 않습니다. 잠시 후 다시 확인해 주세요.",
  "cust.nobody": "아직 호출된 사람이 없습니다",
  "cust.noOneWaiting": "기다리는 사람 없음",
  "cust.waitingN": "{n}명 대기",
  "cust.joinT": "대기줄에 합류",
  "cust.nameLabel": "이름 (선택)",
  "cust.joinBusy": "번호를 받는 중…",
  "cust.joinReassure": "앱도, 계정도 없이 번호만.",
  "cust.youreNumber": "내 번호",
  "cust.youreNext": "다음은 당신",
  "cust.oneAhead": "내 앞에 1명",
  "cust.nAhead": "내 앞에 {n}명",
  "cust.peopleWaiting": "대기 인원",
  "cust.reassure": "이 화면은 스스로 갱신됩니다. 켜둔 채로 두세요.",
  "cust.leave": "대기줄 나가기",
  "cust.leaveConfirm": "대기줄을 나가시겠어요? 번호를 잃게 됩니다.",
  "cust.turnT": "내 차례입니다",
  "cust.turnB": "카운터로 와 주세요.",
  "cust.imHere": "도착했습니다",
  "cust.sending": "보내는 중…",
  "cust.confirmed": "감사합니다. 준비되었다고 전했습니다.",
  "cust.done": "완료",
  "cust.servedBody": "기다려 주셔서 감사합니다.",
  "cust.skippedBody": "건너뛰었습니다. 아직 계시면 새 번호를 받으세요.",
  "cust.noShowBody": "이 번호는 마감되었습니다. 아직 계시면 새 번호를 받으세요.",
  "cust.joinAgain": "다시 합류",
  "cust.poweredBy": "제공",
  "dash.navQueue": "대기줄",
  "dash.navQr": "QR 코드",
  "dash.navSettings": "설정",
  "dash.signOut": "로그아웃",
  "dash.opening": "대기줄을 여는 중…",
  "dash.pausedB": "손님이 지금 번호를 받을 수 없습니다.",
  "dash.nobodyCounter": "카운터에 아무도 없음",
  "dash.noName": "이름 없음",
  "dash.noNameGiven": "이름 없음",
  "dash.confirmedHere": "님이 도착했다고 확인했습니다",
  "dash.notConfirmed": "님이 아직 확인하지 않았습니다",
  "dash.callNext": "다음 호출",
  "dash.calling": "호출 중…",
  "dash.noWaitingHint": "지금 기다리는 사람이 없습니다.",
  "dash.pause": "대기줄 일시정지",
  "dash.resume": "대기줄 재개",
  "dash.atCounter": "카운터에서",
  "dash.waitingTitle": "대기 중",
  "dash.stWait": "대기 중",
  "dash.stCalled": "호출됨",
  "dash.stServed": "처리 완료",
  "dash.stSkipped": "건너뜀",
  "dash.stNoShow": "노쇼",
  "dash.firstRun": "아직 아무도 없습니다. 세 단계면 대기줄이 시작됩니다:",
  "dash.step1": "QR 코드를 받으세요. 인쇄하거나 출입문 옆 화면에 두세요.",
  "dash.step1link": "내 QR 코드 열기 →",
  "dash.step2": "손님이 번호를 받습니다. 스캔하고, 이름을 적고, 합류합니다.",
  "dash.step3": "\"다음 호출\"을 누르면 그 순간 휴대폰이 갱신됩니다.",
  "dash.emptyWaiting": "기다리는 사람이 없습니다. 사람이 올수록 새 번호가 여기 표시됩니다.",
  "dash.nextUp": "다음",
  "dash.finished": "종료됨",
  "dash.counts": "처리 {s}, 건너뜀 {k}, 노쇼 {n}",
  "dash.markServed": "처리 완료로 표시",
  "dash.skip": "건너뛰기",
  "qr.intro": "인쇄해서 출입문이나 카운터에 붙이세요. 링크는 바뀌지 않아 오늘 인쇄한 코드도 계속 씁니다.",
  "qr.linkLabel": "대기줄 링크",
  "qr.download": "PNG 다운로드",
  "qr.print": "인쇄",
  "qr.copy": "링크 복사",
  "qr.copied": "링크를 복사했습니다.",
  "qr.making": "QR 코드 만드는 중…",
  "qr.sheetCta": "스캔해서 대기줄 합류",
  "qr.fine": "손님은 스캔만 하면 번호를 받습니다. 앱도 계정도 없고, QR은 모든 테마에서 흑백이라 휴대폰이 잘 읽습니다.",
  "set.noteLabel": "손님에게 남길 말",
  "set.noteHint": "대기줄 페이지의 합류 버튼 위에 표시됩니다. 선택 사항.",
  "set.save": "변경 저장",
  "set.saving": "저장 중…",
  "set.saved": "저장했습니다.",
  "set.goodToKnow": "알아두면 좋은 것",
  "set.linkBody": "링크는 영구적이라 가게 이름을 바꿔도 인쇄한 QR은 계속 작동합니다.",
  "set.signedInAs": "로그인 계정",
  "set.errNote": "남길 말은 200자 이하여야 합니다.",
  "nf.title": "존재하지 않는 페이지입니다.",
  "nf.body": "주소가 이동했거나 링크를 잘못 입력한 것 같습니다.",
  "nf.cta": "홈페이지로 이동",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "라이브 데모",
  "common.live": "라이브",
  "common.reconnecting": "다시 연결 중…",
  "common.offline": "오프라인 상태입니다. 이 페이지는 자동으로 업데이트됩니다.",
  "common.optional": "optional",
  "common.cancel": "취소",
  "common.remove": "제거",
  "common.add": "추가",
  "common.save": "Save",
  "common.saved": "저장됨.",
  "common.minutes": "{n}분",
  "common.branch": "지점",
  "common.allBranches": "모든 지점",
  "common.back": "Back",
  "band.body": "가게 유형에서 시작하세요, 식당, 클리닉, 미용실, 수리점, 이름은 나중에 바꿀 수 있습니다. 새 지점을 열면 위치를 추가하세요.",
  "band.try": "라이브 데모 보기",
  "demo.title": "작동 방식 보기",
  "demo.sub": "버튼을 눌러 볼 수 있는 연습용 가게입니다. 고객으로 참여하고, 직원으로 번호를 호출하며 TV 화면을 지켜보세요. 여기的一切都是假的。",
  "demo.paneCustomer": "고객 휴대폰",
  "demo.paneStaff": "직원 휴대폰",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "TV 화면",
  "demo.joinName": "이름 (선택)",
  "demo.join": "번호 받기",
  "demo.reset": "데모 초기화",
  "demo.callNext": "다음 호출",
  "demo.serve": "완료",
  "demo.skip": "건너뛰기",
  "demo.waitingList": "Waiting",
  "demo.hint": "번호를 호출해 보고 네 패널이 동시에 갱신되는 것을 확인하세요.",
  "auth.shopType": "어떤 종류의 가게인가요?",
  "auth.shopTypeHint": "대기열과 창구를 만들어 드립니다. 이름은 나중에 변경할 수 있습니다.",
  "auth.branchName": "첫 번째 지점",
  "auth.inviteTitle": "초대되었습니다",
  "auth.inviteBody": "{business}님이 {role}로서 대기열을 관리하도록 초대했습니다.",
  "auth.joinTeam": "팀에 합류",
  "auth.inviteBad": "이 초대는 더 이상 유효하지 않습니다. 관리자에게 새 초대를 요청하세요.",
  "cust.phoneLabel": "전화 (선택)",
  "cust.estWait": "약 {n}분 대기",
  "cust.pickQueue": "무엇이 필요하신가요?",
  "cust.pickBranch": "어느 지점인가요?",
  "cust.pickQueueHint": "번호를 받으려면 대기열을 선택하세요.",
  "cust.held": "대기 중",
  "cust.heldBody": "곧 직원이 호출합니다.",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "대기열",
  "dash.navTeam": "팀",
  "dash.navReports": "기록",
  "dash.holdTitle": "보류됨",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "이탈",
  "dash.hold": "보류",
  "dash.release": "대기열로 되돌리기",
  "dash.recall": "다시 호출",
  "dash.cancel": "Remove from queue",
  "dash.move": "이동",
  "dash.moveTo": "다른 대기열로 이동",
  "dash.call": "호출",
  "dash.addWalkIn": "고객 추가",
  "dash.addWalkInBody": "전화 예약과 앞에 있는 사람들을 위해.",
  "dash.noteLabel": "메모 (선택)",
  "dash.counterLabel": "창구",
  "dash.anyCounter": "임의의 창구",
  "dash.avgWait": "평균 대기 {n}분",
  "dash.peopleWaiting": "{n}명 대기 중",
  "dash.tvLink": "TV 화면 열기",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "이 지점에는 아직 대기열이 없습니다.",
  "dash.pickQueue": "대기열 선택",
  "dash.roleTag": "내 역할: {role}",
  "dash.noPermission": "해당 역할로는 할 수 없습니다.",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "이 코드의 대기열",
  "qr.displayLink": "TV 화면 링크",
  "sq.title": "대기열과 창구",
  "sq.sub": "각 대기열은 자체 번호와 자체 줄을 가집니다.",
  "sq.locations": "지점",
  "sq.addLocation": "지점 추가",
  "sq.locationName": "지점 이름",
  "sq.address": "주소 (선택)",
  "sq.phone": "전화 (선택)",
  "sq.noLocations": "아직 지점이 없습니다.",
  "sq.queues": "대기열",
  "sq.addQueue": "대기열 추가",
  "sq.queueName": "대기열 이름",
  "sq.prefix": "번호 앞글자",
  "sq.prefixHint": "번호 앞에 두 글자까지, 예: A12.",
  "sq.description": "이 대기열은 무엇인가요? (선택)",
  "sq.avgTime": "소요 시간 (분)",
  "sq.counters": "창구",
  "sq.counterName": "Counter name",
  "sq.addCounter": "창구 추가",
  "sq.paused": "일시 중지",
  "sq.open": "운영 중",
  "sq.closed": "Closed",
  "sq.noQueues": "이 지점에는 아직 대기열이 없습니다.",
  "sq.deleteQueue": "이 대기열 삭제",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "가게 유형으로 시작",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "일시 중지 중에는 이 대기열에서 번호를 받을 수 없습니다.",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "내 팀",
  "team.sub": "창구에서 일하는 사람을 초대하고 각자가 할 수 있는 일을 선택하세요.",
  "team.invite": "누군가 초대",
  "team.invited": "초대장을 보냈습니다",
  "team.inviteEmail": "상대 이메일",
  "team.inviteRole": "할 수 있는 일",
  "team.pending": "합류 대기 중",
  "team.noPending": "대기 중인 초대가 없습니다.",
  "team.revoke": "초대 철회",
  "team.role": "역할",
  "team.roleOwner": "사장님",
  "team.roleManager": "매니저",
  "team.roleStaff": "직원",
  "team.roleViewer": "열람 전용",
  "team.remove": "팀에서 제거",
  "team.lock": "모두 로그아웃",
  "team.unlock": "로그인 허용",
  "team.allBranches": "모든 지점",
  "team.oneBranch": "One location",
  "team.pickBranch": "지점",
  "team.noTeam": "지금은 당신뿐입니다.",
  "team.linkCopied": "초대 링크가 복사되었습니다. 전달하세요.",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "오늘과 지난주에 실제로 어떻게 운영되었는지.",
  "rep.joined": "받은 번호",
  "rep.served": "서비스한 고객",
  "rep.avgWait": "평균 대기",
  "rep.avgService": "평균 서비스",
  "rep.peak": "피크 시간",
  "rep.abandoned": "서비스 전 이탈",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "최근 7일",
  "rep.days30": "최근 30일",
  "rep.days90": "최근 90일",
  "rep.byDay": "Each day",
  "rep.byHour": "혼잡 시간대",
  "rep.byQueue": "대기열별",
  "rep.waited": "{n}분 대기",
  "rep.servedIn": "{n}분 만에 완료",
  "rep.history": "방문한 모든 사람",
  "rep.noHistory": "이 기간 동안 이 대기열을 이용한 사람이 없습니다.",
  "rep.audit": "팀이 한 변경 사항",
  "rep.noAudit": "아직 기록된 변경이 없습니다.",
  "rep.noReports": "해당 역할로는 보고서를 볼 수 없습니다.",
  "set.brand": "외관",
  "set.brandHint": "브랜드 색상과 로고가 고객 페이지와 TV 화면에 표시됩니다.",
  "set.mainColour": "기본 색상",
  "set.accentColour": "강조 색상",
  "set.logo": "로고",
  "set.logoHint": "웹 링크를 붙여넣거나 이미지를 업로드하세요. 작은 것이 좋습니다.",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "로고 제거",
  "set.security": "내 비밀번호",
  "set.currentPassword": "현재 비밀번호",
  "set.newPassword": "새 비밀번호",
  "set.changePassword": "비밀번호 변경",
  "set.passwordChanged": "비밀번호가 변경되었습니다. 다른 기기에서 로그아웃되었습니다.",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "지금 호출 중",
  "disp.waiting": "대기",
  "disp.others": "다른 대기열",
  "disp.fullscreen": "전체 화면",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "첫 번째 번호 대기 중",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "예상 대기",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "기본값 라이브",
  "hero.statPhone": "어떤 휴대폰에서도 작동",
  "feat.title": "대기열에 필요한 것만, 그 이상도 그 이하도 아님",
  "feat.copy": "Lobby는 한 가지 일을 잘합니다. 아래의 모든 화면은 오늘 이미 제품의 일부입니다.",
  "feat.qr.t": "하나의 코드, 항상 최신",
  "feat.qr.d": "지점마다 고정 QR 코드. 한 번 인쇄하면, 가게 이름을 바꿔도 그대로입니다.",
  "feat.multi.t": "여러 대기열, 하나의 화면",
  "feat.multi.d": "창구를 서비스별로 나누세요, 상담, 수령, 반품, 각자의 번호와 창구로.",
  "feat.team.t": "가게에 맞는 역할",
  "feat.team.d": "링크로 직원을 초대하고 지점에 연결하며, 열쇠는 사장이 쥡니다.",
  "feat.brand.t": "브랜드 그대로",
  "feat.brand.d": "브랜드 색상, 로고, 안내 문구가 모든 고객 휴대폰과 TV에 표시됩니다.",
  "feat.reports.t": "한적한 저녁을 위한 데이터",
  "feat.reports.d": "대기 시간, 혼잡 시간대, 전체 기록. 다음 주 근무표가 더 이상 추측이 아닙니다.",
  "feat.pause.t": "혼란 없이 마감",
  "feat.pause.d": "한 번의 탭으로 대기열을 일시 중지합니다. 문간 안내가 이를 알리고, 닫힌 창구에서 번호를 받는 사람은 없습니다.",
  "flow.title": "입구에서 끝까지 네 단계",
  "flow.s1.t": "고객이 대기열에 들어옵니다",
  "flow.s1.d": "코드를 스캔하고 서비스를 골라 번호를 받습니다. 앱도 계정도 필요 없어요.",
  "flow.s2.t": "직원이 다음 분을 호출합니다",
  "flow.s2.d": "큰 버튼 한 번으로 다음 분을 호출하고 대기열을 공정하게 유지합니다.",
  "flow.s3.t": "누구나 자신의 상태를 확인",
  "flow.s3.d": "각 휴대폰에서 순서, 앞 인원, 대기 시간을 확인할 수 있습니다, 새로고침 없이 실시간으로.",
  "flow.s4.t": "화면이 질서를 지킵니다",
  "flow.s4.d": "대기실 TV에서 누구를 호출 중이고 다음이 누구인지 확인할 수 있습니다.",
  "dispsect.title": "대기실에 어울리는 화면",
  "dispsect.copy": "TV 브라우저에서 화면을 여세요. 큰 번호, 다음 다섯 명, 다른 대기열이 한눈에 보입니다. 직원이 움직이면 즉시 갱신됩니다.",
  "dispsect.cta": "라이브 화면 보기",
  "dash.servingCounters": "{n}개 운영 중",
};

export const asia: Lang[] = [
  { code: "hi", label: "Hindi", native: "हिन्दी", flag: "in", dict: hi },
  { code: "id", label: "Indonesian", native: "Bahasa Indonesia", flag: "id", dict: id },
  { code: "zh", label: "Chinese (Simplified)", native: "简体中文", flag: "cn", dict: zh },
  { code: "ja", label: "Japanese", native: "日本語", flag: "jp", dict: ja },
  { code: "ko", label: "Korean", native: "한국어", flag: "kr", dict: ko },
];
