export const en = {
  // Header, footer, language picker
  "nav.about": "About",
  "nav.signin": "Sign in",
  "nav.setup": "Set up your business",
  "foot.made": "Lobby, made by {name}.",
  "foot.mit": "Open source under the MIT licence.",
  "lang.title": "Choose your language",
  "lang.sub": "You can change it later from the flag in the top corner.",
  "lang.change": "Change language",
  "lang.done": "Done",

  // Shared states
  "common.loading": "Loading…",
  "common.retry": "Try again",

  // Landing
  "hero.eyebrow": "Queues for shops, clinics and salons",
  "hero.h1a": "Take a number.",
  "hero.h1b": "Wait anywhere.",
  "hero.lede":
    "One QR code for your business. Customers scan it, take a number, and watch their place in line. When it's their turn, their phone tells them.",
  "hero.fine": "No app for customers, no account for them. Open source and runs on your own server.",
  "demo.nowServing": "Now serving",
  "demo.yourNumber": "Your number",
  "how.title": "How it works",
  "how.t1": "Print your QR code",
  "how.d1": "One permanent code for your door or counter.",
  "how.t2": "Customers take a number",
  "how.d2": "They scan, add a name if they want, nothing to install.",
  "how.t3": "Press Call next",
  "how.d3": "The line moves and their screen updates itself.",
  "see.title": "What your customers see",
  "see.copy":
    "One screen with the same answers every time. It works in any phone browser, and when you call their number it flips to It's your turn.",
  "see.youreNumber": "You're number",
  "see.peopleAhead": "People ahead of you",
  "see.when": "When it happens",
  "see.itsTurn": "It's your turn!",
  "places.title": "Made for places with a counter",
  "places.list":
    "Pharmacies · Clinics · Salons · Barbershops · Repair shops · Banks · Post offices · Government offices",
  "band.title": "Set up takes about a minute.",

  // Auth
  "auth.welcome": "Welcome back",
  "auth.setupSub": "A minute of typing and your queue is ready.",
  "auth.loginSub": "Sign in to your queue.",
  "auth.bizName": "Business name",
  "auth.yourName": "Your name",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.pwHint": "At least 8 characters.",
  "auth.creating": "Setting up…",
  "auth.signingIn": "Signing in…",
  "auth.create": "Create my business",
  "auth.haveAccount": "Already have an account?",
  "auth.noAccount": "No account yet?",
  "auth.backHome": "Back to home",
  "err.bizName": "Enter your business name.",
  "err.name": "Enter your name.",
  "err.email": "Enter your email.",
  "err.password": "Enter your password.",
  "err.pwLen": "Password must be at least 8 characters.",

  // Customer queue
  "cust.opening": "Opening the queue…",
  "cust.wrong": "Something went wrong.",
  "cust.pausedT": "Queue paused.",
  "cust.pausedB": "This business isn't taking numbers right now, please check back soon.",
  "cust.nobody": "Nobody being served yet",
  "cust.noOneWaiting": "no one waiting",
  "cust.waitingN": "{n} waiting",
  "cust.joinT": "Join the queue",
  "cust.nameLabel": "Your name (optional)",
  "cust.joinBusy": "Taking your number…",
  "cust.joinReassure": "No app to install, no account, just a number.",
  "cust.youreNumber": "You're number",
  "cust.youreNext": "You're next",
  "cust.oneAhead": "1 person ahead of you",
  "cust.nAhead": "{n} people ahead of you",
  "cust.peopleWaiting": "People waiting",
  "cust.reassure": "This page updates by itself, keep it open.",
  "cust.leave": "Leave the queue",
  "cust.leaveConfirm": "Leave the queue? You'll lose your number.",
  "cust.turnT": "It's your turn",
  "cust.turnB": "Please head to the counter.",
  "cust.imHere": "I'm here",
  "cust.sending": "Sending…",
  "cust.confirmed": "Thanks, we've told them you're ready.",
  "cust.done": "All done",
  "cust.servedBody": "Thanks for waiting.",
  "cust.skippedBody": "You were skipped. If you're still here, take another number.",
  "cust.noShowBody": "This number was closed. If you're still here, take another number.",
  "cust.joinAgain": "Join again",
  "cust.poweredBy": "Powered by",

  // Dashboard
  "dash.navQueue": "Queue",
  "dash.navQr": "QR code",
  "dash.navSettings": "Settings",
  "dash.signOut": "Sign out",
  "dash.opening": "Opening your queue…",
  "dash.pausedB": "Customers can't take a number right now.",
  "dash.nobodyCounter": "Nobody at the counter",
  "dash.noNameGiven": "No name given",
  "dash.confirmedHere": "says they're here",
  "dash.notConfirmed": "hasn't confirmed yet",
  "dash.callNext": "Call next",
  "dash.calling": "Calling…",
  "dash.noWaitingHint": "No one is waiting right now.",
  "dash.pause": "Pause queue",
  "dash.resume": "Resume queue",
  "dash.atCounter": "At the counter",
  "dash.waitingTitle": "Waiting",
  "dash.noName": "No name",
  "dash.stWait": "Waiting",
  "dash.stCalled": "Being served",
  "dash.stServed": "Served",
  "dash.stSkipped": "Skipped",
  "dash.stNoShow": "No show",
  "dash.firstRun": "No one's here yet. Three quick steps and your queue is live:",
  "dash.step1": "Get your QR code. Print it, or put it on a screen by the door.",
  "dash.step1link": "Open my QR code →",
  "dash.step2": "Customers take a number. They scan, type an optional name, and they're in.",
  "dash.step3": "Press Call next. Their phone updates the moment you do.",
  "dash.emptyWaiting": "No one is waiting. New numbers appear here as people join.",
  "dash.nextUp": "Next up",
  "dash.finished": "Finished",
  "dash.counts": "{s} served, {k} skipped, {n} no show",
  "dash.markServed": "Mark as served",
  "dash.skip": "Skip",

  // QR page
  "qr.intro":
    "Print this and put it by the door or on the counter. The link never changes, so a code you print today keeps working.",
  "qr.linkLabel": "Your queue link",
  "qr.download": "Download PNG",
  "qr.print": "Print",
  "qr.copy": "Copy link",
  "qr.copied": "Link copied.",
  "qr.making": "Making your QR code…",
  "qr.sheetCta": "Scan to join the queue",
  "qr.fine":
    "Customers scan this to take a number, no app, no account. The QR stays black and white in every theme so phones can read it.",

  // Settings
  "set.noteLabel": "Note for customers",
  "set.noteHint": "Shown above the Join button on your queue page. Optional.",
  "set.save": "Save changes",
  "set.saving": "Saving…",
  "set.saved": "Saved.",
  "set.goodToKnow": "Good to know",
  "set.linkBody": "It's permanent, so a printed QR code keeps working even if you rename the business.",
  "set.signedInAs": "Signed in as",
  "set.errNote": "Your note must be 200 characters or fewer.",

  // 404
  "nf.title": "This page doesn't exist.",
  "nf.body": "It may have moved, or the link was mistyped.",
  "nf.cta": "Go to the home page",
} as const;

export type StringKey = keyof typeof en;
