export const en = {
  // Header, footer, language picker
  "nav.about": "About",
  "nav.signin": "Sign in",
  "nav.setup": "Set up your business",
  "nav.demo": "Live demo",
  "foot.made": "Lobby, made by {name}.",
  "foot.mit": "Open source under the MIT licence.",
  "lang.title": "Choose your language",
  "lang.sub": "You can switch it any time from the globe up top.",
  "lang.change": "Change language",
  "lang.done": "Done",
  "lang.close": "Close",
  "lang.search": "Search languages",
  "lang.noMatch": "No language matches that.",
  "theme.toggle": "Switch theme",

  // Shared states
  "common.loading": "Loading…",
  "common.retry": "Try again",
  "common.live": "Live",
  "common.reconnecting": "Reconnecting…",
  "common.offline": "You're offline. This page will update again by itself.",
  "common.optional": "optional",
  "common.cancel": "Cancel",
  "common.remove": "Remove",
  "common.add": "Add",
  "common.save": "Save",
  "common.saved": "Saved.",
  "common.minutes": "{n} min",
  "common.branch": "Location",
  "common.allBranches": "All locations",
  "common.back": "Back",
  "common.noneYet": "none yet",

  // Landing
  "hero.eyebrow": "Queues for shops, clinics and salons",
  "hero.h1a": "Queues, without the chaos.",
  "hero.h1b": "",
  "hero.lede":
    "One QR code on the door. Customers scan it, take a number, and watch their place in line from anywhere. Staff press one button, and the TV keeps everyone informed.",
  "hero.fine": "No app for customers, no sign-up for them. Open source, runs on your own server.",
  "demo.nowServing": "Now serving",
  "demo.yourNumber": "Your number",
  "how.title": "How it works",
  "how.t1": "Print your QR code",
  "how.d1": "One permanent code for your door or counter.",
  "how.t2": "Customers take a number",
  "how.d2": "They scan, add a name if they want, nothing to install.",
  "how.t3": "Press Call next",
  "how.d3": "The line moves and their screen updates itself.",
  "see.title": "What your customers see",
  "see.copy":
    "One screen with the same answers every time. It works in any phone browser, and when you call their number it flips to It's your turn.",
  "see.youreNumber": "You're number",
  "see.peopleAhead": "People ahead of you",
  "see.when": "When it happens",
  "see.itsTurn": "It's your turn!",
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "Live by default",
  "hero.statPhone": "Works on any phone",
  "feat.title": "Everything a queue needs, nothing it doesn't",
  "feat.copy": "Lobby does one job well. Every screen below is part of the product today.",
  "feat.qr.t": "One code, always current",
  "feat.qr.d": "A permanent QR code for each location. Print it once, renaming the business never breaks it.",
  "feat.multi.t": "Many queues, one screen",
  "feat.multi.d": "Split the counter into services like consultation, pickup, or returns, each with its own numbers and counters.",
  "feat.team.t": "Roles that fit a shop",
  "feat.team.d": "Invite staff by link, pin them to a branch, and keep owners in charge of the keys.",
  "feat.brand.t": "Looks like your business",
  "feat.brand.d": "Your colours, logo, and note show up on every customer's phone and the TV.",
  "feat.reports.t": "Facts for the quiet evening",
  "feat.reports.d": "Wait times, busiest hours, and a full history, so next week's rota isn't a guess.",
  "feat.pause.t": "Close without confusion",
  "feat.pause.d": "Pause a queue with one tap. The door sign says so, and no one takes a number into a closed counter.",
  "flow.title": "From door to done in four steps",
  "flow.s1.t": "Customers join",
  "flow.s1.d": "They scan the code, pick a service, and take a number. No app, no account.",
  "flow.s2.t": "Staff call next",
  "flow.s2.d": "One big button serves the next person and keeps the line fair.",
  "flow.s3.t": "Everyone sees their status",
  "flow.s3.d": "Each phone shows their place, who's ahead, and the wait, live, without refreshing.",
  "flow.s4.t": "The display keeps order",
  "flow.s4.d": "A TV in the waiting area shows who's being served and who's next.",
  "dispsect.title": "A display your waiting room deserves",
  "dispsect.copy":
    "Open the display on any TV browser. Huge numbers, the next five in line, and other queues at a glance. It updates the second your staff do.",
  "dispsect.cta": "See a live display",
  "places.title": "Made for places with a counter",
  "places.list":
    "Pharmacies · Clinics · Salons · Barbershops · Repair shops · Banks · Post offices · Government offices",
  "band.title": "Your queue could be live in a minute.",
  "band.body":
    "Start from a shop type (restaurant, clinic, salon, repair shop) and edit the names. Add more locations whenever you open another.",
  "band.try": "Try the live demo",
  "demo.title": "See it working",
  "demo.sub":
    "A practice shop you can press buttons on. Join as a customer, call numbers as staff, and watch the TV screen. Nothing here is real.",
  "demo.paneCustomer": "Customer's phone",
  "demo.paneStaff": "Staff's phone",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "TV screen",
  "demo.joinName": "Name (optional)",
  "demo.join": "Take a number",
  "demo.reset": "Reset the demo",
  "demo.callNext": "Call next",
  "demo.serve": "Done",
  "demo.skip": "Skip",
  "demo.waitingList": "Waiting",
  "demo.hint": "Try calling a number and watch all four panels update at once.",

  // Auth
  "auth.welcome": "Welcome back",
  "auth.setupSub": "A minute of typing and your queue is ready.",
  "auth.loginSub": "Sign in to your queue.",
  "auth.bizName": "Business name",
  "auth.yourName": "Your name",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.pwHint": "At least 8 characters.",
  "auth.creating": "Setting up…",
  "auth.signingIn": "Signing in…",
  "auth.create": "Create my business",
  "auth.haveAccount": "Already have an account?",
  "auth.noAccount": "No account yet?",
  "auth.backHome": "Back to home",
  "auth.shopType": "What kind of business is it?",
  "auth.shopTypeHint": "We'll create the queues and counters for you. You can change every name later.",
  "auth.branchName": "First location",
  "auth.inviteTitle": "You've been invited",
  "auth.inviteBody": "{business} invited you to work the queue as {role}.",
  "auth.joinTeam": "Join the team",
  "auth.inviteBad": "This invitation is no longer valid. Ask your manager for a new one.",
  "err.bizName": "Enter your business name.",
  "err.name": "Enter your name.",
  "err.email": "Enter your email.",
  "err.password": "Enter your password.",
  "err.pwLen": "Password must be at least 8 characters.",

  // Customer queue
  "cust.opening": "Opening the queue…",
  "cust.wrong": "Something went wrong.",
  "cust.pausedT": "Queue paused.",
  "cust.pausedB": "This business isn't taking numbers right now, please check back soon.",
  "cust.nobody": "Nobody being served yet",
  "cust.noOneWaiting": "no one waiting",
  "cust.waitingN": "{n} waiting",
  "cust.joinT": "Join the queue",
  "cust.nameLabel": "Your name (optional)",
  "cust.phoneLabel": "Phone (optional)",
  "cust.joinBusy": "Taking your number…",
  "cust.joinReassure": "No app to install, no account, just a number.",
  "cust.youreNumber": "You're number",
  "cust.youreNext": "You're next",
  "cust.oneAhead": "1 person ahead of you",
  "cust.nAhead": "{n} people ahead of you",
  "cust.peopleWaiting": "People waiting",
  "cust.estWait": "About {n} min wait",
  "cust.waitEstimate": "Estimated wait",
  "cust.reassure": "This page updates by itself, just keep it open.",
  "cust.leave": "Leave the queue",
  "cust.leaveConfirm": "Leave the queue? You'll lose your number.",
  "cust.turnT": "It's your turn",
  "cust.turnB": "Please head to the counter.",
  "cust.imHere": "I'm here",
  "cust.sending": "Sending…",
  "cust.confirmed": "Thanks, we've told them you're ready.",
  "cust.done": "All done",
  "cust.servedBody": "Thanks for waiting.",
  "cust.skippedBody": "You were skipped. If you're still here, take another number.",
  "cust.noShowBody": "This number was closed. If you're still here, take another number.",
  "cust.joinAgain": "Join again",
  "cust.poweredBy": "Powered by",
  "cust.pickQueue": "What do you need?",
  "cust.pickBranch": "Which location?",
  "cust.pickQueueHint": "Choose a queue to get a number.",
  "cust.held": "On hold",
  "cust.heldBody": "Staff will call you shortly.",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",

  // Dashboard
  "dash.navQueue": "Queue",
  "dash.navQr": "QR code",
  "dash.navSetup": "Queues",
  "dash.navTeam": "Team",
  "dash.navReports": "History",
  "dash.navSettings": "Settings",
  "dash.signOut": "Sign out",
  "dash.opening": "Opening your queue…",
  "dash.pausedB": "Customers can't take a number right now.",
  "dash.nobodyCounter": "Nobody at the counter",
  "dash.noNameGiven": "No name given",
  "dash.confirmedHere": "says they're here",
  "dash.notConfirmed": "hasn't confirmed yet",
  "dash.callNext": "Call next",
  "dash.calling": "Calling…",
  "dash.noWaitingHint": "Nobody's waiting right now.",
  "dash.pause": "Pause queue",
  "dash.resume": "Resume queue",
  "dash.atCounter": "At the counter",
  "dash.waitingTitle": "Waiting",
  "dash.holdTitle": "On hold",
  "dash.doneTitle": "Finished",
  "dash.noName": "No name",
  "dash.stWait": "Waiting",
  "dash.stCalled": "Being served",
  "dash.stHold": "On hold",
  "dash.stServed": "Served",
  "dash.stSkipped": "Skipped",
  "dash.stNoShow": "No show",
  "dash.stCancelled": "Left",
  "dash.firstRun": "No one's here yet. Three quick steps and your queue is live:",
  "dash.step1": "Get your QR code. Print it, or put it on a screen by the door.",
  "dash.step1link": "Open my QR code →",
  "dash.step2": "Customers take a number. They scan, type an optional name, and they're in.",
  "dash.step3": "Press Call next. Their phone updates the moment you do.",
  "dash.emptyWaiting": "Nobody's waiting yet. New numbers land here as people join.",
  "dash.nextUp": "Next up",
  "dash.finished": "Finished",
  "dash.counts": "{s} served, {k} skipped, {n} no show",
  "dash.markServed": "Mark as served",
  "dash.skip": "Skip",
  "dash.hold": "Hold",
  "dash.release": "Put back in line",
  "dash.recall": "Call again",
  "dash.cancel": "Remove from queue",
  "dash.move": "Move",
  "dash.moveTo": "Move to queue",
  "dash.call": "Call",
  "dash.addWalkIn": "Add a customer",
  "dash.addWalkInBody": "For phone bookings and people standing in front of you.",
  "dash.noteLabel": "Note (optional)",
  "dash.counterLabel": "Counter",
  "dash.anyCounter": "Any counter",
  "dash.avgWait": "Average wait {n} min",
  "dash.peopleWaiting": "{n} waiting",
  "dash.servingCounters": "{n} serving",
  "dash.tvLink": "Open the TV screen",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "This branch has no queues yet.",
  "dash.pickQueue": "Choose a queue",
  "dash.roleTag": "Your role: {role}",
  "dash.noPermission": "Your role can't do that.",

  // QR page
  "qr.intro":
    "Print this and put it by the door or on the counter. The link never changes, so a code you print today keeps working.",
  "qr.linkLabel": "Your queue link",
  "qr.download": "Download PNG",
  "qr.print": "Print",
  "qr.copy": "Copy link",
  "qr.copied": "Link copied.",
  "qr.making": "Making your QR code…",
  "qr.sheetCta": "Scan to join the queue",
  "qr.fine":
    "Customers scan this to take a number, no app, no account. The QR stays black and white in every theme so phones can read it.",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "Queue for this code",
  "qr.displayLink": "TV screen link",

  // Queues, counters and locations
  "sq.title": "Queues and counters",
  "sq.sub": "Each queue has its own numbers and its own line.",
  "sq.locations": "Locations",
  "sq.addLocation": "Add a location",
  "sq.locationName": "Location name",
  "sq.address": "Address (optional)",
  "sq.phone": "Phone (optional)",
  "sq.noLocations": "No locations yet.",
  "sq.queues": "Queues",
  "sq.addQueue": "Add a queue",
  "sq.queueName": "Queue name",
  "sq.prefix": "Number letters",
  "sq.prefixHint": "Up to two letters shown before the number, like A12.",
  "sq.description": "What is this queue for? (optional)",
  "sq.avgTime": "Typical time (minutes)",
  "sq.counters": "Counters",
  "sq.counterName": "Counter name",
  "sq.addCounter": "Add a counter",
  "sq.paused": "Paused",
  "sq.open": "Taking numbers",
  "sq.closed": "Closed",
  "sq.noQueues": "No queues in this location yet.",
  "sq.deleteQueue": "Remove this queue",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "Start from a shop type",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "Customers can't take a number in this queue while it's paused.",
  "sq.movedBody": "Customer moved to another queue.",

  // Team
  "team.title": "Your team",
  "team.sub": "Invite the people who work the counter and choose what each of them can do.",
  "team.invite": "Invite someone",
  "team.invited": "Invitation sent",
  "team.inviteEmail": "Their email",
  "team.inviteRole": "What they can do",
  "team.pending": "Waiting to join",
  "team.noPending": "No invitations waiting. All quiet here.",
  "team.revoke": "Cancel invitation",
  "team.role": "Role",
  "team.roleOwner": "Owner",
  "team.roleManager": "Manager",
  "team.roleStaff": "Staff",
  "team.roleViewer": "Viewer",
  "team.remove": "Remove from team",
  "team.lock": "Sign out everywhere",
  "team.unlock": "Allow sign-in",
  "team.allBranches": "All locations",
  "team.oneBranch": "One location",
  "team.pickBranch": "Location",
  "team.noTeam": "You're the only one here so far.",
  "team.linkCopied": "Invitation link copied. Send it to them.",
  "team.onlyYou": "You can't change your own role.",

  // History and reports
  "rep.title": "History",
  "rep.sub": "How today and the last week actually went.",
  "rep.joined": "Numbers taken",
  "rep.served": "Customers served",
  "rep.avgWait": "Average wait",
  "rep.avgService": "Average service",
  "rep.peak": "Busiest hour",
  "rep.abandoned": "Walked away",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "Last 7 days",
  "rep.days30": "Last 30 days",
  "rep.days90": "Last 90 days",
  "rep.byDay": "Each day",
  "rep.byHour": "Busiest hours",
  "rep.byQueue": "Each queue",
  "rep.waited": "waited {n} min",
  "rep.servedIn": "served in {n} min",
  "rep.history": "Everyone who came through",
  "rep.noHistory": "Nobody has been through this queue in this period yet.",
  "rep.audit": "Changes made by your team",
  "rep.noAudit": "No changes recorded yet.",
  "rep.noReports": "Your role cannot see reports.",
  "rep.allQueues": "All queues",

  // Settings
  "set.noteLabel": "Note for customers",
  "set.noteHint": "Shown above the Join button on your queue page. Optional.",
  "set.save": "Save changes",
  "set.saving": "Saving…",
  "set.saved": "Saved.",
  "set.goodToKnow": "Good to know",
  "set.linkBody": "It's permanent, so a printed QR code keeps working even if you rename the business.",
  "set.signedInAs": "Signed in as",
  "set.errNote": "Your note must be 200 characters or fewer.",
  "set.brand": "Look and feel",
  "set.brandHint": "Your colours and logo show on the customer page and the TV screen.",
  "set.mainColour": "Main colour",
  "set.accentColour": "Highlight colour",
  "set.logo": "Logo",
  "set.logoHint": "Paste a web link or upload a picture. Small is best.",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "Remove logo",
  "set.security": "Your password",
  "set.currentPassword": "Current password",
  "set.newPassword": "New password",
  "set.changePassword": "Change password",
  "set.passwordChanged": "Password changed. Other devices have been signed out.",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",

  // TV display
  "disp.nowServing": "Now serving",
  "disp.waiting": "Waiting",
  "disp.others": "Other queues",
  "disp.fullscreen": "Full screen",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "Waiting for the first number",

  // 404
  "nf.title": "This page doesn't exist.",
  "nf.body": "It may have moved, or the link was mistyped.",
  "nf.cta": "Go to the home page",
} as const;

export type StringKey = keyof typeof en;