import type { StringKey } from "./en";
import type { Lang } from "./types";

type Pack = Partial<Record<StringKey, string>>;

const ru: Pack = {
  "nav.about": "О проекте",
  "nav.signin": "Войти",
  "nav.setup": "Настроить бизнес",
  "foot.made": "Lobby создал {name}.",
  "foot.mit": "Открытый код, лицензия MIT.",
  "lang.title": "Выберите язык",
  "lang.sub": "Позже его можно сменить по флагу в правом верхнем углу.",
  "lang.change": "Сменить язык",
  "lang.done": "Готово",
  "common.loading": "Загрузка…",
  "common.retry": "Попробовать снова",
  "hero.eyebrow": "Очереди для магазинов, клиник и салонов",
  "hero.h1a": "Берите номер.",
  "hero.h1b": "Ждите где угодно.",
  "hero.lede":
    "Один QR-код для вашего бизнеса. Клиенты сканируют его, берут номер и видят своё место в очереди. Когда до них доходит очередь, телефон их уведомляет.",
  "hero.fine":
    "Ни приложений, ни аккаунтов для клиентов. Открытый код, работает на вашем сервере.",
  "demo.nowServing": "Сейчас обслуживают",
  "demo.yourNumber": "Ваш номер",
  "how.title": "Как это работает",
  "how.t1": "Распечатайте QR-код",
  "how.d1": "Постоянный код для двери или стойки.",
  "how.t2": "Клиенты берут номер",
  "how.d2": "Сканируют, добавляют имя по желанию, ничего ставить не нужно.",
  "how.t3": "Нажмите «Вызвать следующего»",
  "how.d3": "Очередь двигается, экран обновляется сам.",
  "see.title": "Что видят ваши клиенты",
  "see.copy":
    "Один экран с одинаковыми ответами. Работает в любом браузере телефона, а когда вы вызываете номер, экран меняется на «Ваша очередь».",
  "see.youreNumber": "Ваш номер",
  "see.peopleAhead": "Человек перед вами",
  "see.when": "Когда это случается",
  "see.itsTurn": "Ваша очередь!",
  "places.title": "Для мест со стойкой",
  "places.list":
    "Аптеки · Клиники · Салоны · Парикмахерские · Мастерские · Банки · Почта · Госучреждения",
  "band.title": "Настройка занимает минуту.",
  "auth.welcome": "С возвращением",
  "auth.setupSub": "Минута ввода, и очередь готова.",
  "auth.loginSub": "Войдите в свою очередь.",
  "auth.bizName": "Название бизнеса",
  "auth.yourName": "Ваше имя",
  "auth.email": "Эл. почта",
  "auth.password": "Пароль",
  "auth.pwHint": "Не менее 8 символов.",
  "auth.creating": "Создаём…",
  "auth.signingIn": "Входим…",
  "auth.create": "Создать бизнес",
  "auth.haveAccount": "Уже есть аккаунт?",
  "auth.noAccount": "Ещё нет аккаунта?",
  "auth.backHome": "На главную",
  "err.bizName": "Введите название бизнеса.",
  "err.name": "Введите имя.",
  "err.email": "Введите почту.",
  "err.password": "Введите пароль.",
  "err.pwLen": "Пароль должен быть не короче 8 символов.",
  "cust.opening": "Открываем очередь…",
  "cust.wrong": "Что-то пошло не так.",
  "cust.pausedT": "Очередь на паузе.",
  "cust.pausedB": "Сейчас номера не выдаются, загляните позже.",
  "cust.nobody": "Сейчас никого не обслуживают",
  "cust.noOneWaiting": "никто не ждёт",
  "cust.waitingN": "ждут: {n}",
  "cust.joinT": "Встать в очередь",
  "cust.nameLabel": "Ваше имя (необязательно)",
  "cust.joinBusy": "Выдаём номер…",
  "cust.joinReassure": "Без приложений и аккаунтов, просто номер.",
  "cust.youreNumber": "Ваш номер",
  "cust.youreNext": "Вы следующий",
  "cust.oneAhead": "1 человек перед вами",
  "cust.nAhead": "Перед вами {n} человек",
  "cust.peopleWaiting": "Ждут",
  "cust.reassure": "Страница обновляется сама, не закрывайте её.",
  "cust.leave": "Выйти из очереди",
  "cust.leaveConfirm": "Выйти из очереди? Вы потеряете номер.",
  "cust.turnT": "Ваша очередь",
  "cust.turnB": "Пожалуйста, подойдите к стойке.",
  "cust.imHere": "Я на месте",
  "cust.sending": "Отправляем…",
  "cust.confirmed": "Спасибо, мы передали, что вы готовы.",
  "cust.done": "Всё готово",
  "cust.servedBody": "Спасибо за ожидание.",
  "cust.skippedBody": "Вас пропустили. Если вы ещё здесь, возьмите новый номер.",
  "cust.noShowBody": "Номер закрыт. Если вы ещё здесь, возьмите новый номер.",
  "cust.joinAgain": "Встать в очередь снова",
  "cust.poweredBy": "На платформе",
  "dash.navQueue": "Очередь",
  "dash.navQr": "QR-код",
  "dash.navSettings": "Настройки",
  "dash.signOut": "Выйти",
  "dash.opening": "Открываем вашу очередь…",
  "dash.pausedB": "Клиенты сейчас не могут взять номер.",
  "dash.nobodyCounter": "У стойки никого",
  "dash.noNameGiven": "Без имени",
  "dash.confirmedHere": "подтвердил, что на месте",
  "dash.notConfirmed": "ещё не подтвердил",
  "dash.callNext": "Вызвать следующего",
  "dash.calling": "Вызываем…",
  "dash.noWaitingHint": "Сейчас никто не ждёт.",
  "dash.pause": "Пауза",
  "dash.resume": "Продолжить",
  "dash.atCounter": "У стойки",
  "dash.waitingTitle": "Ждут",
  "dash.noName": "Без имени",
  "dash.stWait": "Ждёт",
  "dash.stCalled": "Обслуживается",
  "dash.stServed": "Обслужен",
  "dash.stSkipped": "Пропущен",
  "dash.stNoShow": "Не пришёл",
  "dash.firstRun": "Пока никого нет. Три шага, и очередь заработает:",
  "dash.step1": "Возьмите QR-код. Распечатайте или выведите на экран у входа.",
  "dash.step1link": "Открыть мой QR-код →",
  "dash.step2": "Клиенты берут номер: сканируют, вводят имя по желанию и встают в очередь.",
  "dash.step3": "Нажмите «Вызвать следующего». Телефон обновится сразу.",
  "dash.emptyWaiting": "Никто не ждёт. Новые номера появятся здесь по мере прихода людей.",
  "dash.nextUp": "Следующий",
  "dash.finished": "Завершено",
  "dash.counts": "обслужено {s}, пропущено {k}, не пришли {n}",
  "dash.markServed": "Отметить обслуженным",
  "dash.skip": "Пропустить",
  "qr.intro":
    "Распечатайте и повесьте у входа или на стойке. Ссылка не меняется, код, напечатанный сегодня, работает всегда.",
  "qr.linkLabel": "Ссылка на очередь",
  "qr.download": "Скачать PNG",
  "qr.print": "Печать",
  "qr.copy": "Копировать ссылку",
  "qr.copied": "Ссылка скопирована.",
  "qr.making": "Создаём QR-код…",
  "qr.sheetCta": "Отсканируйте, чтобы встать в очередь",
  "qr.fine":
    "Клиенты сканируют, чтобы взять номер, без приложений и аккаунтов. QR остаётся чёрно-белым в любой теме, чтобы телефоны его читали.",
  "set.noteLabel": "Заметка для клиентов",
  "set.noteHint": "Показывается над кнопкой вступления на странице очереди. Необязательно.",
  "set.save": "Сохранить",
  "set.saving": "Сохраняем…",
  "set.saved": "Сохранено.",
  "set.goodToKnow": "Полезно знать",
  "set.linkBody": "Ссылка постоянная: напечатанный QR работает, даже если переименовать бизнес.",
  "set.signedInAs": "Вход выполнен как",
  "set.errNote": "Заметка должна быть не длиннее 200 символов.",
  "nf.title": "Такой страницы нет.",
  "nf.body": "Возможно, она переместилась или ссылка набрана с ошибкой.",
  "nf.cta": "На главную",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "Демо",
  "common.live": "В эфире",
  "common.reconnecting": "Переподключение…",
  "common.offline": "Нет соединения. Эта страница обновится автоматически.",
  "common.optional": "optional",
  "common.cancel": "Отмена",
  "common.remove": "Удалить",
  "common.add": "Добавить",
  "common.save": "Save",
  "common.saved": "Сохранено.",
  "common.minutes": "{n} мин",
  "common.branch": "Локация",
  "common.allBranches": "Все локации",
  "common.back": "Back",
  "band.body": "Начните с типа бизнеса — ресторан, клиника, салон, мастерская — и переименуйте, что нужно. Добавляйте новые локации, когда открываете ещё одну.",
  "band.try": "Посмотреть демо",
  "demo.title": "Посмотрите в деле",
  "demo.sub": "Магазин-тренажёр, где можно нажимать кнопки. Присоединяйтесь как клиент, вызывайте номера как сотрудник и смотрите на экран ТВ. Здесь ничего не настоящее.",
  "demo.paneCustomer": "Телефон клиента",
  "demo.paneStaff": "Телефон сотрудника",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "Экран ТВ",
  "demo.joinName": "Имя (необязательно)",
  "demo.join": "Взять номер",
  "demo.reset": "Сбросить демо",
  "demo.callNext": "Вызвать следующего",
  "demo.serve": "Готово",
  "demo.skip": "Пропустить",
  "demo.waitingList": "Waiting",
  "demo.hint": "Вызовите номер и посмотрите, как все четыре панели обновляются одновременно.",
  "auth.shopType": "Какой это бизнес?",
  "auth.shopTypeHint": "Мы создадим очереди и окна. Позже можно переименовать всё что угодно.",
  "auth.branchName": "Пер первая локация",
  "auth.inviteTitle": "Вас пригласили",
  "auth.inviteBody": "{business} приглашает вас управлять очередью как {role}.",
  "auth.joinTeam": "Вступить в команду",
  "auth.inviteBad": "Это приглашение больше не действует. Попросите у руководителя новое.",
  "cust.phoneLabel": "Телефон (необязательно)",
  "cust.estWait": "Ожидание около {n} мин",
  "cust.pickQueue": "Что вам нужно?",
  "cust.pickBranch": "Какая локация?",
  "cust.pickQueueHint": "Выберите очередь, чтобы взять номер.",
  "cust.held": "Отложен",
  "cust.heldBody": "Персонал вызовет вас в ближайшее время.",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "Очереди",
  "dash.navTeam": "Команда",
  "dash.navReports": "История",
  "dash.holdTitle": "Отложен",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "Ушёл",
  "dash.hold": "Отложить",
  "dash.release": "Вернуть в очередь",
  "dash.recall": "Вызвать снова",
  "dash.cancel": "Remove from queue",
  "dash.move": "Переместить",
  "dash.moveTo": "Переместить в другую очередь",
  "dash.call": "Вызвать",
  "dash.addWalkIn": "Добавить клиента",
  "dash.addWalkInBody": "Для бронирований по телефону и людей перед вами.",
  "dash.noteLabel": "Заметка (необязательно)",
  "dash.counterLabel": "Окно",
  "dash.anyCounter": "Любое окно",
  "dash.avgWait": "Среднее ожидание {n} мин",
  "dash.peopleWaiting": "{n} в очереди",
  "dash.tvLink": "Открыть экран ТВ",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "В этом филиале пока нет очередей.",
  "dash.pickQueue": "Выберите очередь",
  "dash.roleTag": "Ваша роль: {role}",
  "dash.noPermission": "Ваша роль не может этого делать.",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "Очередь для этого кода",
  "qr.displayLink": "Ссылка на экран ТВ",
  "sq.title": "Очереди и окна",
  "sq.sub": "У каждой очереди свои номера и своя линия.",
  "sq.locations": "Локации",
  "sq.addLocation": "Добавить локацию",
  "sq.locationName": "Название локации",
  "sq.address": "Адрес (необязательно)",
  "sq.phone": "Телефон (необязательно)",
  "sq.noLocations": "Локаций пока нет.",
  "sq.queues": "Очереди",
  "sq.addQueue": "Добавить очередь",
  "sq.queueName": "Название очереди",
  "sq.prefix": "Буквы номера",
  "sq.prefixHint": "До двух букв перед номером, например A12.",
  "sq.description": "Для чего эта очередь? (необязательно)",
  "sq.avgTime": "Обычное время (минуты)",
  "sq.counters": "Окна",
  "sq.counterName": "Counter name",
  "sq.addCounter": "Добавить окно",
  "sq.paused": "На паузе",
  "sq.open": "Открыта",
  "sq.closed": "Closed",
  "sq.noQueues": "В этой локации пока нет очередей.",
  "sq.deleteQueue": "Удалить эту очередь",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "Начать с типа бизнеса",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "Пока очередь на паузе, клиенты не могут взять номер.",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "Ваша команда",
  "team.sub": "Пригласите тех, кто работает за стойкой, и решите, что каждый может делать.",
  "team.invite": "Пригласить",
  "team.invited": "Приглашение отправлено",
  "team.inviteEmail": "Его адрес электронной почты",
  "team.inviteRole": "Что они могут делать",
  "team.pending": "Ожидает вступления",
  "team.noPending": "Нет ожидающих приглашений.",
  "team.revoke": "Отозвать приглашение",
  "team.role": "Роль",
  "team.roleOwner": "Владелец",
  "team.roleManager": "Менеджер",
  "team.roleStaff": "Сотрудник",
  "team.roleViewer": "Только просмотр",
  "team.remove": "Удалить из команды",
  "team.lock": "Выйти на всех устройствах",
  "team.unlock": "Разрешить вход",
  "team.allBranches": "Все локации",
  "team.oneBranch": "One location",
  "team.pickBranch": "Локация",
  "team.noTeam": "Пока здесь только вы.",
  "team.linkCopied": "Ссылка-приглашение скопирована. Отправьте её.",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "Как на самом деле прошли сегодня и прошлая неделя.",
  "rep.joined": "Взятые номера",
  "rep.served": "Обслужено клиентов",
  "rep.avgWait": "Среднее ожидание",
  "rep.avgService": "Среднее обслуживание",
  "rep.peak": "Час пик",
  "rep.abandoned": "Ушли без обслуживания",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "Последние 7 дней",
  "rep.days30": "Последние 30 дней",
  "rep.days90": "Последние 90 дней",
  "rep.byDay": "Each day",
  "rep.byHour": "Самые загруженные часы",
  "rep.byQueue": "Каждая очередь",
  "rep.waited": "просидел {n} мин",
  "rep.servedIn": "обслужен за {n} мин",
  "rep.history": "Все, кто приходил",
  "rep.noHistory": "За этот период через эту очередь никто не проходил.",
  "rep.audit": "Изменения, внесённые командой",
  "rep.noAudit": "Изменений пока не записано.",
  "rep.noReports": "Ваша роль не может просматривать отчёты.",
  "set.brand": "Внешний вид",
  "set.brandHint": "Ваши цвета и логотип появляются на странице клиента и экране ТВ.",
  "set.mainColour": "Основной цвет",
  "set.accentColour": "Акцентный цвет",
  "set.logo": "Логотип",
  "set.logoHint": "Вставьте веб-ссылку или загрузите картинку. Лучше небольшого размера.",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "Удалить логотип",
  "set.security": "Ваш пароль",
  "set.currentPassword": "Текущий пароль",
  "set.newPassword": "Новый пароль",
  "set.changePassword": "Изменить пароль",
  "set.passwordChanged": "Пароль изменён. Другие устройства вышли из системы.",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "Сейчас обслуживают",
  "disp.waiting": "В ожидании",
  "disp.others": "Другие очереди",
  "disp.fullscreen": "Полный экран",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "Ждём первый номер",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "Ожидаемое ожидание",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "Сразу в реальном времени",
  "hero.statPhone": "Работает на любом телефоне",
  "feat.title": "Всё, что нужно очереди, — и ничего лишнего",
  "feat.copy": "Lobby отлично делает одну вещь. Каждый экран ниже уже часть продукта.",
  "feat.qr.t": "Один код, всегда актуален",
  "feat.qr.d": "Постоянный QR-код на каждую локацию. Распечатайте один раз — смена названия магазина никогда его не сломает.",
  "feat.multi.t": "Много очередей, один экран",
  "feat.multi.d": "Разделите окно на услуги — консультация, выдача, возврат — со своими номерами и окнами.",
  "feat.team.t": "Роли, подходящие магазину",
  "feat.team.d": "Приглашайте сотрудников по ссылке, привязывайте к филиалу и оставляйте ключи владельцам.",
  "feat.brand.t": "Как ваш бизнес",
  "feat.brand.d": "Ваши цвета, логотип и заметка появляются на телефоне каждого клиента и на ТВ.",
  "feat.reports.t": "Факты для спокойного вечера",
  "feat.reports.d": "Время ожидания, часы пик и полная история — расписание на неделю вперёд больше не догадка.",
  "feat.pause.t": "Закрывайтесь без хаоса",
  "feat.pause.d": "Поставьте очередь на паузу одним нажатием. Табличка у двери сообщает об этом, и никто не возьмёт номер к закрытому окну.",
  "flow.title": "От двери до готово за четыре шага",
  "flow.s1.t": "Клиенты встают в очередь",
  "flow.s1.d": "Сканируют код, выбирают услугу и берут номер. Без приложения и без регистрации.",
  "flow.s2.t": "Персонал вызывает следующего",
  "flow.s2.d": "Одна большая кнопка обслуживает следующего и сохраняет справедливость очереди.",
  "flow.s3.t": "Все видят свой статус",
  "flow.s3.d": "Каждый телефон показывает позицию, сколько людей впереди и ожидание — вживую, без обновления.",
  "flow.s4.t": "Экран поддерживает порядок",
  "flow.s4.d": "ТВ в зале ожидания показывает, кого обслуживают и кто следующий.",
  "dispsect.title": "Экран, которого заслуживает ваш зал ожидания",
  "dispsect.copy": "Откройте экран в любом TV-браузере. Крупные номера, следующие пять и другие очереди с первого взгляда. Обновляется, как только сотрудники работают.",
  "dispsect.cta": "Смотреть живой экран",
  "dash.servingCounters": "{n} обслуживают",
};

const tr: Pack = {
  "nav.about": "Hakkında",
  "nav.signin": "Giriş yap",
  "nav.setup": "İşletmeni kur",
  "foot.made": "Lobby, {name} tarafından geliştirildi.",
  "foot.mit": "MIT lisansı altında açık kaynak.",
  "lang.title": "Dilini seç",
  "lang.sub": "Daha sonra sağ üstteki bayraktan değiştirebilirsin.",
  "lang.change": "Dil değiştir",
  "lang.done": "Tamam",
  "common.loading": "Yükleniyor…",
  "common.retry": "Tekrar dene",
  "hero.eyebrow": "Dükkanlar, klinikler ve kuaförler için sıralar",
  "hero.h1a": "Bir numara al.",
  "hero.h1b": "İstediğin yerde bekle.",
  "hero.lede":
    "İşletmen için tek bir QR kod. Müşteriler tarar, numara alır ve sıradaki yerini görür. Sıra onlara geldiğinde telefonları haber verir.",
  "hero.fine":
    "Müşterilerin için uygulama yok, onlar için hesap yok. Açık kaynak ve kendi sunucunda çalışır.",
  "demo.nowServing": "Şu an servis ediliyor",
  "demo.yourNumber": "Senin numaran",
  "how.title": "Nasıl çalışır",
  "how.t1": "QR kodunu bastır",
  "how.d1": "Kapın veya tezgahın için kalıcı bir kod.",
  "how.t2": "Müşteriler numara alır",
  "how.d2": "Tarar, isterse isim yazar, kuracak bir şey yok.",
  "how.t3": "Sıradakini çağır'a bas",
  "how.d3": "Sıra ilerler, ekranları kendiliğinden güncellenir.",
  "see.title": "Müşterilerin ne görür",
  "see.copy":
    "Her zaman aynı cevapları veren tek bir ekran. Tüm telefon tarayıcılarında çalışır ve numaralarını çağırdığında Sıra sende'ye döner.",
  "see.youreNumber": "Senin numaran",
  "see.peopleAhead": "Önündeki kişiler",
  "see.when": "Olduğu zaman",
  "see.itsTurn": "Sıra sende!",
  "places.title": "Tezgahı olan yerler için",
  "places.list":
    "Eczaneler · Klinikler · Kuaförler · Berberler · Tamirhaneler · Bankalar · Postaneler · Kamu daireleri",
  "band.title": "Kurma işlemi bir dakika sürer.",
  "auth.welcome": "Tekrar hoş geldin",
  "auth.setupSub": "Bir dakika yaz, sıran hazır olsun.",
  "auth.loginSub": "Sıranla giriş yap.",
  "auth.bizName": "İşletme adı",
  "auth.yourName": "Adın",
  "auth.email": "E-posta",
  "auth.password": "Şifre",
  "auth.pwHint": "En az 8 karakter.",
  "auth.creating": "Kuruluyor…",
  "auth.signingIn": "Giriş yapılıyor…",
  "auth.create": "İşletmemi oluştur",
  "auth.haveAccount": "Zaten hesabın var mı?",
  "auth.noAccount": "Henüz hesabın yok mu?",
  "auth.backHome": "Ana sayfaya dön",
  "err.bizName": "İşletme adını yaz.",
  "err.name": "Adını yaz.",
  "err.email": "E-postanı yaz.",
  "err.password": "Şifreni yaz.",
  "err.pwLen": "Şifre en az 8 karakter olmalı.",
  "cust.opening": "Sıra açılıyor…",
  "cust.wrong": "Bir şeyler ters gitti.",
  "cust.pausedT": "Sıra duraklatıldı.",
  "cust.pausedB": "Bu işletme şu an numara vermiyor, sonra tekrar bak.",
  "cust.nobody": "Henüz servis edilen yok",
  "cust.noOneWaiting": "bekleyen yok",
  "cust.waitingN": "{n} kişi bekliyor",
  "cust.joinT": "Sıraya katıl",
  "cust.nameLabel": "Adın (isteğe bağlı)",
  "cust.joinBusy": "Numaran alınıyor…",
  "cust.joinReassure": "Uygulama yok, hesap yok, sadece numara.",
  "cust.youreNumber": "Senin numaran",
  "cust.youreNext": "Sıradaki sensin",
  "cust.oneAhead": "Önünde 1 kişi",
  "cust.nAhead": "Önünde {n} kişi",
  "cust.peopleWaiting": "Bekleyenler",
  "cust.reassure": "Bu sayfa kendini günceller, açık bırak.",
  "cust.leave": "Sıradan ayrıl",
  "cust.leaveConfirm": "Sıradan ayrılın mı? Numaranı kaybedersin.",
  "cust.turnT": "Sıra sende",
  "cust.turnB": "Lütfen tezgaha gel.",
  "cust.imHere": "Buradayım",
  "cust.sending": "Gönderiliyor…",
  "cust.confirmed": "Teşekkürler, hazır olduğunu söyledik.",
  "cust.done": "Tamamlandı",
  "cust.servedBody": "Beklediğin için teşekkürler.",
  "cust.skippedBody": "Atlandın. Hâlâ buradaysan yeni bir numara al.",
  "cust.noShowBody": "Bu numara kapandı. Hâlâ buradaysan yeni bir numara al.",
  "cust.joinAgain": "Tekrar katıl",
  "cust.poweredBy": "Altyapı",
  "dash.navQueue": "Sıra",
  "dash.navQr": "QR kod",
  "dash.navSettings": "Ayarlar",
  "dash.signOut": "Çıkış yap",
  "dash.opening": "Sıran açılıyor…",
  "dash.pausedB": "Müşteriler şu an numara alamaz.",
  "dash.nobodyCounter": "Tezgahta kimse yok",
  "dash.noNameGiven": "İsimsiz",
  "dash.confirmedHere": "burada olduğunu söyledi",
  "dash.notConfirmed": "henüz onaylamadı",
  "dash.callNext": "Sıradakini çağır",
  "dash.calling": "Çağrılıyor…",
  "dash.noWaitingHint": "Şu an bekleyen yok.",
  "dash.pause": "Sırayı duraklat",
  "dash.resume": "Sırayı sürdür",
  "dash.atCounter": "Tezgahta",
  "dash.waitingTitle": "Bekliyor",
  "dash.noName": "İsim yok",
  "dash.stWait": "Bekliyor",
  "dash.stCalled": "Servis ediliyor",
  "dash.stServed": "Servis edildi",
  "dash.stSkipped": "Atlandı",
  "dash.stNoShow": "Gelmedi",
  "dash.firstRun": "Henüz kimse yok. Üç hızlı adım ve sıran hazır:",
  "dash.step1": "QR kodunu al. Bastır veya kapı yanındaki ekrana koy.",
  "dash.step1link": "QR kodumu aç →",
  "dash.step2": "Müşteriler numara alır: tarar, isteğe bağlı isim yazar, sıraya girer.",
  "dash.step3": "Sıradakini çağır'a bas. Telefonları o an güncellenir.",
  "dash.emptyWaiting": "Bekleyen yok. İnsan geldikçe yeni numaralar burada görünür.",
  "dash.nextUp": "Sıradaki",
  "dash.finished": "Bitenler",
  "dash.counts": "{s} servis edildi, {k} atlandı, {n} gelmedi",
  "dash.markServed": "Servis edildi olarak işaretle",
  "dash.skip": "Atla",
  "qr.intro":
    "Bunu bastır ve kapıya veya tezgaha koy. Bağlantı hiç değişmez, bugün bastığın kod çalışmaya devam eder.",
  "qr.linkLabel": "Sıra bağlantın",
  "qr.download": "PNG indir",
  "qr.print": "Yazdır",
  "qr.copy": "Bağlantıyı kopyala",
  "qr.copied": "Bağlantı kopyalandı.",
  "qr.making": "QR kodun yapılıyor…",
  "qr.sheetCta": "Sıraya katılmak için tara",
  "qr.fine":
    "Müşteriler uygulama ve hesap olmadan numara almak için tarar. QR, telefonlar okuyabilsin diye her temada siyah beyaz kalır.",
  "set.noteLabel": "Müşteriler için not",
  "set.noteHint": "Sıra sayfandaki Katıl düğmesinin üstünde görünür. İsteğe bağlı.",
  "set.save": "Değişiklikleri kaydet",
  "set.saving": "Kaydediliyor…",
  "set.saved": "Kaydedildi.",
  "set.goodToKnow": "Bilmen gerekenler",
  "set.linkBody": "Bağlantı kalıcıdır, işletme adını değiştirsensen bile basılı QR çalışmaya devam eder.",
  "set.signedInAs": "Oturum açılan hesap",
  "set.errNote": "Notun en fazla 200 karakter olmalı.",
  "nf.title": "Böyle bir sayfa yok.",
  "nf.body": "Taşınmış olabilir ya da bağlantı yanlış yazılmıştır.",
  "nf.cta": "Ana sayfaya git",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "Canlı demo",
  "common.live": "Canlı",
  "common.reconnecting": "Yeniden bağlanıyor…",
  "common.offline": "Çevrimdışısınız. Bu sayfa kendiliğinden güncellenecek.",
  "common.optional": "optional",
  "common.cancel": "Vazgeç",
  "common.remove": "Kaldır",
  "common.add": "Ekle",
  "common.save": "Save",
  "common.saved": "Kaydedildi.",
  "common.minutes": "{n} dk",
  "common.branch": "Şube",
  "common.allBranches": "Tüm şubeler",
  "common.back": "Back",
  "band.body": "Bir işletme türüyle başlayın — restoran, klinik, kuaför, servis — ve adları düzenleyin. Yeni bir şube açtığınızda yer ekleyin.",
  "band.try": "Canlı demoyu dene",
  "demo.title": "Çalışırken görün",
  "demo.sub": "Düğmelere basabileceğiniz bir alıştırma mağazası. Müşteri olarak katılın, personel olarak numara çağırın ve TV ekranına bakın. Buradaki hiçbir şey gerçek değil.",
  "demo.paneCustomer": "Müşteri telefonu",
  "demo.paneStaff": "Personel telefonu",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "TV ekranı",
  "demo.joinName": "Ad (isteğe bağlı)",
  "demo.join": "Numara al",
  "demo.reset": "Demoyu sıfırla",
  "demo.callNext": "Sonrakini çağır",
  "demo.serve": "Tamam",
  "demo.skip": "Atla",
  "demo.waitingList": "Waiting",
  "demo.hint": "Bir numara çağırın ve dört panelin birden güncellendiğini izleyin.",
  "auth.shopType": "Ne tür bir işletme?",
  "auth.shopTypeHint": "Kuyruk ve gişeleri biz oluşturacağız. Her adı sonra değiştirebilirsiniz.",
  "auth.branchName": "İlk şube",
  "auth.inviteTitle": "Davet edildiniz",
  "auth.inviteBody": "{business} sizi {role} olarak sırayı yönetmeye davet ediyor.",
  "auth.joinTeam": "Ekibe katıl",
  "auth.inviteBad": "Bu davet artık geçerli değil. Yöneticinizden yenisini isteyin.",
  "cust.phoneLabel": "Telefon (isteğe bağlı)",
  "cust.estWait": "Yaklaşık {n} dk bekleme",
  "cust.pickQueue": "Neye ihtiyacınız var?",
  "cust.pickBranch": "Hangi şube?",
  "cust.pickQueueHint": "Numara almak için bir kuyruk seçin.",
  "cust.held": "Beklemede",
  "cust.heldBody": "Personel sizi birazdan çağıracak.",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "Kuyruklar",
  "dash.navTeam": "Ekip",
  "dash.navReports": "Geçmiş",
  "dash.holdTitle": "Beklemede",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "Gitti",
  "dash.hold": "Beklet",
  "dash.release": "Sıraya geri koy",
  "dash.recall": "Tekrar çağır",
  "dash.cancel": "Remove from queue",
  "dash.move": "Taşı",
  "dash.moveTo": "Başka kuyruğa taşı",
  "dash.call": "Çağır",
  "dash.addWalkIn": "Müşteri ekle",
  "dash.addWalkInBody": "Telefon rezervasyonları ve karşınızda duranlar için.",
  "dash.noteLabel": "Not (isteğe bağlı)",
  "dash.counterLabel": "Gişe",
  "dash.anyCounter": "Herhangi bir gişe",
  "dash.avgWait": "Ortalama bekleme {n} dk",
  "dash.peopleWaiting": "{n} bekliyor",
  "dash.tvLink": "TV ekranını aç",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "Bu şubede henüz kuyruk yok.",
  "dash.pickQueue": "Bir kuyruk seçin",
  "dash.roleTag": "Rolünüz: {role}",
  "dash.noPermission": "Rolünüz bunu yapamaz.",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "Bu kod için kuyruk",
  "qr.displayLink": "TV ekranı bağlantısı",
  "sq.title": "Kuyruklar ve gişeler",
  "sq.sub": "Her kuyruğun kendi numaraları ve kendi sırası var.",
  "sq.locations": "Şubeler",
  "sq.addLocation": "Şube ekle",
  "sq.locationName": "Şube adı",
  "sq.address": "Adres (isteğe bağlı)",
  "sq.phone": "Telefon (isteğe bağlı)",
  "sq.noLocations": "Henüz şube yok.",
  "sq.queues": "Kuyruklar",
  "sq.addQueue": "Kuyruk ekle",
  "sq.queueName": "Kuyruk adı",
  "sq.prefix": "Numara harfleri",
  "sq.prefixHint": "Numaradan önce en fazla iki harf, örn. A12.",
  "sq.description": "Bu kuyruk ne için? (isteğe bağlı)",
  "sq.avgTime": "Tipik süre (dakika)",
  "sq.counters": "Gişeler",
  "sq.counterName": "Counter name",
  "sq.addCounter": "Gişe ekle",
  "sq.paused": "Duraklatıldı",
  "sq.open": "Açık",
  "sq.closed": "Closed",
  "sq.noQueues": "Bu şubede henüz kuyruk yok.",
  "sq.deleteQueue": "Bu kuyruğu kaldır",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "Bir işletme türüyle başla",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "Kuyruk duraklatıldığında müşteriler numara alamaz.",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "Ekibiniz",
  "team.sub": "Tezgâhta çalışanları davet edin ve herkesin ne yapabileceğini seçin.",
  "team.invite": "Birini davet et",
  "team.invited": "Davet gönderildi",
  "team.inviteEmail": "E-posta adresi",
  "team.inviteRole": "Neler yapabilirler",
  "team.pending": "Katılmayı bekliyor",
  "team.noPending": "Bekleyen davet yok.",
  "team.revoke": "Daveti iptal et",
  "team.role": "Rol",
  "team.roleOwner": "Sahip",
  "team.roleManager": "Yönetici",
  "team.roleStaff": "Personel",
  "team.roleViewer": "Salt okunur",
  "team.remove": "Ekipten çıkar",
  "team.lock": "Her yerden çıkış yap",
  "team.unlock": "Girişe izin ver",
  "team.allBranches": "Tüm şubeler",
  "team.oneBranch": "One location",
  "team.pickBranch": "Şube",
  "team.noTeam": "Şu an yalnızsanız.",
  "team.linkCopied": "Davet bağlantısı kopyalandı. Gönderin.",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "Bugün ve geçen hafta gerçekte nasıl geçti.",
  "rep.joined": "Alınan numaralar",
  "rep.served": "Servis yapılan müşteri",
  "rep.avgWait": "Ortalama bekleme",
  "rep.avgService": "Ortalama hizmet",
  "rep.peak": "Yoğun saat",
  "rep.abandoned": "Servis almadan gitti",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "Son 7 gün",
  "rep.days30": "Son 30 gün",
  "rep.days90": "Son 90 gün",
  "rep.byDay": "Each day",
  "rep.byHour": "En yoğun saatler",
  "rep.byQueue": "Her kuyruk",
  "rep.waited": "{n} dk bekledi",
  "rep.servedIn": "{n} dk içinde servis",
  "rep.history": "Gelen herkes",
  "rep.noHistory": "Bu dönemde bu kuyruktan kimse geçmedi.",
  "rep.audit": "Ekibinizin yaptığı değişiklikler",
  "rep.noAudit": "Henüz değişiklik kaydedilmedi.",
  "rep.noReports": "Rolünüz raporları göremez.",
  "set.brand": "Görünüm",
  "set.brandHint": "Renkleriniz ve logonuz müşteri sayfasında ve TV ekranında görünür.",
  "set.mainColour": "Ana renk",
  "set.accentColour": "Vurgu rengi",
  "set.logo": "Logo",
  "set.logoHint": "Bir web bağlantısı yapıştırın veya görsel yükleyin. Küçük olan en iyisidir.",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "Logoyu kaldır",
  "set.security": "Şifreniz",
  "set.currentPassword": "Mevcut şifre",
  "set.newPassword": "Yeni şifre",
  "set.changePassword": "Şifreyi değiştir",
  "set.passwordChanged": "Şifre değiştirildi. Diğer cihazlar oturumu kapattı.",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "Şimdi çağrılıyor",
  "disp.waiting": "Bekleyen",
  "disp.others": "Diğer kuyruklar",
  "disp.fullscreen": "Tam ekran",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "İlk numara bekleniyor",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "Tahmini bekleme",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "Varsayılan olarak canlı",
  "hero.statPhone": "Her telefonda çalışır",
  "feat.title": "Bir kuyruğun ihtiyaç duyduğu her şey, fazlası değil",
  "feat.copy": "Lobby tek bir işi iyi yapar. Aşağıdaki her ekran bugün ürünün parçası.",
  "feat.qr.t": "Tek kod, hep güncel",
  "feat.qr.d": "Şube başına kalıcı bir QR kod. Bir kez yazdırın — mağaza adını değiştirmek asla bozmaz.",
  "feat.multi.t": "Çoklu kuyruk, tek ekran",
  "feat.multi.d": "Gişeyi hizmetlere bölün — danışma, teslim, iade — kendi numaraları ve gişeleriyle.",
  "feat.team.t": "Dükkâna uyan roller",
  "feat.team.d": "Personeli davet bağlantısıyla çağırın, şubeye bağlayın ve anahtarları sahiplerinde tutun.",
  "feat.brand.t": "İşletmenize özgü",
  "feat.brand.d": "Renkleriniz, logonuz ve notunuz her müşterinin telefonunda ve TV'de görünür.",
  "feat.reports.t": "Sakin akşam için gerçekler",
  "feat.reports.d": "Bekleme süreleri, yoğun saatler ve tam geçmiş — gelecek haftanın çizelgesi artık tahmin değil.",
  "feat.pause.t": "Karışmadan kapatın",
  "feat.pause.d": "Tek dokunuşla kuyruğu duraklatın. Kapıdaki tabela bunu söyler ve kimse kapalı gişeden numara almaz.",
  "flow.title": "Kapıdan bitişe dört adımda",
  "flow.s1.t": "Müşteriler sıraya katılır",
  "flow.s1.d": "Kodu tararlar, hizmet seçer ve numara alırlar. Uygulama yok, hesap yok.",
  "flow.s2.t": "Personel sıradakini çağırır",
  "flow.s2.d": "Tek bir büyük düğme sıradaki kişiyi çağırır ve sırayı adil tutar.",
  "flow.s3.t": "Herkes durumunu görür",
  "flow.s3.d": "Her telefon konumu, önünüzdeki kişi sayısını ve bekleme süresini gösterir — canlı, yenilemeden.",
  "flow.s4.t": "Ekran düzeni korur",
  "flow.s4.d": "Bekleme alanındaki bir TV kimin çağrıldığını ve sıradakini gösterir.",
  "dispsect.title": "Bekleme alanınıza yakışan bir ekran",
  "dispsect.copy": "Ekranı herhangi bir TV tarayıcısında açın. Büyük numaralar, sıradaki beş ve diğer kuyruklar tek bakışta. Personel hareket ettiği anda güncellenir.",
  "dispsect.cta": "Canlı ekranı gör",
  "dash.servingCounters": "{n} hizmette",
};

const ar: Pack = {
  "nav.about": "حول",
  "nav.signin": "تسجيل الدخول",
  "nav.setup": "إعداد عملك",
  "foot.made": "أنشأ Lobby {name}.",
  "foot.mit": "مفتوح المصدر برخصة MIT.",
  "lang.title": "اختر لغتك",
  "lang.sub": "يمكنك تغييرها لاحقاً من العلم في الزاوية العليا.",
  "lang.change": "تغيير اللغة",
  "lang.done": "تم",
  "common.loading": "جارٍ التحميل…",
  "common.retry": "حاول مجدداً",
  "hero.eyebrow": "طوابير للمتاجر والعيادات وصالونات التجميل",
  "hero.h1a": "خذ رقماً.",
  "hero.h1b": "انتظر أينما شئت.",
  "hero.lede":
    "رمز QR واحد لعملك. يمسحه الزبائن فيأخذون رقماً ويرون مكانهم في الطابور. وعندما يحين دورهم يخبرهم هاتفهم.",
  "hero.fine":
    "لا تطبيق للزبائن ولا حساب لهم. مفتوح المصدر ويعمل على خادمك الخاص.",
  "demo.nowServing": "يُخدم الآن",
  "demo.yourNumber": "رقمك",
  "how.title": "كيف يعمل",
  "how.t1": "اطبع رمز QR",
  "how.d1": "رمز دائم لبابك أو طاولتك.",
  "how.t2": "الزبائن يأخذون رقماً",
  "how.d2": "يمسحون ويضيفون اسماً إن أرادوا، ولا شيء يُثبَّت.",
  "how.t3": "اضغط استدعاء التالي",
  "how.d3": "يتقدم الطابور وتحتفل شاشتهم بأنفسها.",
  "see.title": "ما يراه زبائنك",
  "see.copy":
    "شاشة واحدة بإجابات ثابتة في كل مرة. تعمل في أي متصفح للهاتف، وعندما تستدعي رقمهم تتحول إلى حان دورك.",
  "see.youreNumber": "رقمك",
  "see.peopleAhead": "أشخاص أمامك",
  "see.when": "عندما يحدث",
  "see.itsTurn": "حان دورك!",
  "places.title": "لأماكن فيها طاولة استقبال",
  "places.list":
    "صيدليات · عيادات · صالونات · محلات حلاقة · ورش · بنوك · مكاتب بريد · مصالح حكومية",
  "band.title": "الاستعداد يستغرق دقيقة تقريباً.",
  "auth.welcome": "مرحباً بعودتك",
  "auth.setupSub": "دقيقة من الكتابة وطابورك جاهز.",
  "auth.loginSub": "سجّل الدخول إلى طابورك.",
  "auth.bizName": "اسم العمل",
  "auth.yourName": "اسمك",
  "auth.email": "البريد الإلكتروني",
  "auth.password": "كلمة المرور",
  "auth.pwHint": "8 أحرف على الأقل.",
  "auth.creating": "جارٍ الإنشاء…",
  "auth.signingIn": "جارٍ الدخول…",
  "auth.create": "أنشئ مشغلي",
  "auth.haveAccount": "لديك حساب بالفعل؟",
  "auth.noAccount": "ليس لديك حساب بعد؟",
  "auth.backHome": "العودة إلى الرئيسية",
  "err.bizName": "أدخل اسم عملك.",
  "err.name": "أدخل اسمك.",
  "err.email": "أدخل بريدك الإلكتروني.",
  "err.password": "أدخل كلمة المرور.",
  "err.pwLen": "يجب أن تتكوّن كلمة المرور من 8 أحرف على الأقل.",
  "cust.opening": "جارٍ فتح الطابور…",
  "cust.wrong": "حدث خطأ ما.",
  "cust.pausedT": "الطابور متوقف مؤقتاً.",
  "cust.pausedB": "هذا العمل لا يأخذ أرقاماً الآن، عد بعد قليل.",
  "cust.nobody": "لا أحد يُخدم حالياً",
  "cust.noOneWaiting": "لا أحد ينتظر",
  "cust.waitingN": "{n} ينتظرون",
  "cust.joinT": "انضم إلى الطابور",
  "cust.nameLabel": "اسمك (اختياري)",
  "cust.joinBusy": "جارٍ أخذ رقمك…",
  "cust.joinReassure": "لا تطبيق ولا حساب، رقم فقط.",
  "cust.youreNumber": "رقمك",
  "cust.youreNext": "أنت التالي",
  "cust.oneAhead": "شخص واحد أمامك",
  "cust.nAhead": "{n} أشخاص أمامك",
  "cust.peopleWaiting": "المنتظرون",
  "cust.reassure": "تتحدث هذه الصفحة بنفسها، أبقها مفتوحة.",
  "cust.leave": "غادر الطابور",
  "cust.leaveConfirm": "هل تغادر الطابور؟ ستفقد رقمك.",
  "cust.turnT": "حان دورك",
  "cust.turnB": "تفضّل بالتوجّه إلى الطاولة.",
  "cust.imHere": "أنا هنا",
  "cust.sending": "جارٍ الإرسال…",
  "cust.confirmed": "شكراً، أخبرناهم بأنك مستعد.",
  "cust.done": "انتهى",
  "cust.servedBody": "شكراً لانتظارك.",
  "cust.skippedBody": "تم تجاوزك. إن كنت هنا فخذ رقماً آخر.",
  "cust.noShowBody": "أُغلق هذا الرقم. إن كنت هنا فخذ رقماً آخر.",
  "cust.joinAgain": "انضم مجدداً",
  "cust.poweredBy": "مدعوم بـ",
  "dash.navQueue": "الطابور",
  "dash.navQr": "رمز QR",
  "dash.navSettings": "الإعدادات",
  "dash.signOut": "تسجيل الخروج",
  "dash.opening": "جارٍ فتح طابورك…",
  "dash.pausedB": "لا يستطيع الزبائن أخذ أرقام الآن.",
  "dash.nobodyCounter": "لا أحد عند الطاولة",
  "dash.noNameGiven": "بدون اسم",
  "dash.confirmedHere": "قال إنه هنا",
  "dash.notConfirmed": "لم يؤكد بعد",
  "dash.callNext": "استدعاء التالي",
  "dash.calling": "جارٍ الاستدعاء…",
  "dash.noWaitingHint": "لا أحد ينتظر حالياً.",
  "dash.pause": "إيقاف الطابور مؤقتاً",
  "dash.resume": "استئناف الطابور",
  "dash.atCounter": "عند الطاولة",
  "dash.waitingTitle": "منتظرون",
  "dash.noName": "بدون اسم",
  "dash.stWait": "منتظر",
  "dash.stCalled": "قيد الخدمة",
  "dash.stServed": "تمت الخدمة",
  "dash.stSkipped": "تم تجاوزه",
  "dash.stNoShow": "لم يحضر",
  "dash.firstRun": "لا أحد بعد. ثلاث خطوات سريعة ويبدأ طابورك:",
  "dash.step1": "احصل على رمز QR. اطبعه أو ضعه على شاشة قرب الباب.",
  "dash.step1link": "افتح رمز QR الخاص بي ←",
  "dash.step2": "الزبائن يأخذون رقماً: يمسحون ويكتبون اسماً اختيارياً وينضمون.",
  "dash.step3": "اضغط استدعاء التالي. يتحدث هاتفهم في اللحظة نفسها.",
  "dash.emptyWaiting": "لا أحد ينتظر. تظهر الأرقام الجديدة هنا مع وصول الناس.",
  "dash.nextUp": "التالي",
  "dash.finished": "منتهية",
  "dash.counts": "{s} تمت خدمتهم، {k} تم تجاوزهم، {n} لم يحضروا",
  "dash.markServed": "تعليم كمخدوم",
  "dash.skip": "تخطي",
  "qr.intro":
    "اطبعه وضعه عند الباب أو على الطاولة. الرابط لا يتغيّر، الرمز المطبوع اليوم يستمر بالعمل.",
  "qr.linkLabel": "رابط طابورك",
  "qr.download": "تنزيل PNG",
  "qr.print": "طباعة",
  "qr.copy": "نسخ الرابط",
  "qr.copied": "تم نسخ الرابط.",
  "qr.making": "جارٍ إنشاء رمز QR…",
  "qr.sheetCta": "امسح للانضمام إلى الطابور",
  "qr.fine":
    "يمسح الزبائن هذا لأخذ رقم، بلا تطبيق ولا حساب. يبقى رمز QR أبيض وأسود في كل السمات حتى يقرؤه الهاتف.",
  "set.noteLabel": "ملاحظة للزبائن",
  "set.noteHint": "تظهر فوق زر الانضمام في صفحة طابورك. اختيارية.",
  "set.save": "حفظ التغييرات",
  "set.saving": "جارٍ الحفظ…",
  "set.saved": "تم الحفظ.",
  "set.goodToKnow": "مفيد أن تعرف",
  "set.linkBody": "الرابط دائم، الرمز المطبوع يستمر بالعمل حتى لو غيّرت اسم العمل.",
  "set.signedInAs": "مسجّل الدخول باسم",
  "set.errNote": "يجب ألا تتجاوز ملاحظتك 200 حرف.",
  "nf.title": "هذه الصفحة غير موجودة.",
  "nf.body": "ربما انتقلت أو كُتب الرابط خطأً.",
  "nf.cta": "اذهب إلى الصفحة الرئيسية",
  // Added by scripts/sync-lang.mjs: English until translated.
  "nav.demo": "عرض مباشر",
  "common.live": "مباشر",
  "common.reconnecting": "إعادة اتصال…",
  "common.offline": "أنت غير متصل. سيتحدث هذا تلقائيًا.",
  "common.optional": "optional",
  "common.cancel": "إلغاء",
  "common.remove": "إزالة",
  "common.add": "إضافة",
  "common.save": "Save",
  "common.saved": "تم الحفظ.",
  "common.minutes": "{n} دقيقة",
  "common.branch": "الموقع",
  "common.allBranches": "كل المواقع",
  "common.back": "Back",
  "band.body": "ابدأ بنوع النشاط — مطعم، عيادة، صالون، ورشة — وعدّل الأسماء. أضف مواقع جديدة عند فتح فرع آخر.",
  "band.try": "جرّب العرض المباشر",
  "demo.title": "شاهده يعمل",
  "demo.sub": "متجر تدريبي يمكنك الضغط على أزراره. انضم كعميل، واستدعِ الأرقام كموظف، وشاهد شاشة التلفاز. لا شيء هنا حقيقي.",
  "demo.paneCustomer": "هاتف العميل",
  "demo.paneStaff": "هاتف الموظف",
  "demo.paneBoard": "The queue",
  "demo.paneTv": "شاشة التلفاز",
  "demo.joinName": "الاسم (اختياري)",
  "demo.join": "خذ رقماً",
  "demo.reset": "إعادة ضبط العرض",
  "demo.callNext": "استدعاء التالي",
  "demo.serve": "تم",
  "demo.skip": "تخطٍ",
  "demo.waitingList": "Waiting",
  "demo.hint": "جرّب استدعاء رقم وشاهد كيف تُحدَّث اللوحات الأربع معًا.",
  "auth.shopType": "ما نوع هذا النشاط؟",
  "auth.shopTypeHint": "سنُنشئ الطوابير والنوافذ. يمكنك تغيير كل اسم لاحقًا.",
  "auth.branchName": "أول موقع",
  "auth.inviteTitle": "تمت دعوتك",
  "auth.inviteBody": "يدعوك {business} لإدارة الطابور بصفتك {role}.",
  "auth.joinTeam": "انضم إلى الفريق",
  "auth.inviteBad": "لم يعد هذا الدعوة صالحة. اطلب من مديرك دعوة جديدة.",
  "cust.phoneLabel": "الهاتف (اختياري)",
  "cust.estWait": "انتظار حوالي {n} دقيقة",
  "cust.pickQueue": "ما الذي تحتاجه؟",
  "cust.pickBranch": "أي موقع؟",
  "cust.pickQueueHint": "اختر طابوراً لأخذ رقم.",
  "cust.held": "في الانتظار",
  "cust.heldBody": "سيستدعيك الموظفون بعد قليل.",
  "cust.alreadyIn": "You already have a number in this queue.",
  "cust.full": "This queue is full right now. Please ask a member of staff.",
  "dash.navSetup": "الطوابير",
  "dash.navTeam": "الفريق",
  "dash.navReports": "السجل",
  "dash.holdTitle": "في الانتظار",
  "dash.doneTitle": "Finished",
  "dash.stHold": "On hold",
  "dash.stCancelled": "غادر",
  "dash.hold": "تعليق",
  "dash.release": "إعادته للطابور",
  "dash.recall": "استدعاء مجددًا",
  "dash.cancel": "Remove from queue",
  "dash.move": "نقل",
  "dash.moveTo": "نقل إلى طابور آخر",
  "dash.call": "استدعاء",
  "dash.addWalkIn": "إضافة عميل",
  "dash.addWalkInBody": "لحجوزات الهاتف والناس الذين أمامك.",
  "dash.noteLabel": "ملاحظة (اختياري)",
  "dash.counterLabel": "نافذة",
  "dash.anyCounter": "أي نافذة",
  "dash.avgWait": "متوسط الانتظار {n} دقيقة",
  "dash.peopleWaiting": "{n} في الانتظار",
  "dash.tvLink": "فتح شاشة التلفاز",
  "dash.viewers": "{n} screens watching",
  "dash.noQueue": "لا توجد طوابير في هذا الفرع بعد.",
  "dash.pickQueue": "اختر طابوراً",
  "dash.roleTag": "دورك: {role}",
  "dash.noPermission": "دورك لا يسمح بذلك.",
  "qr.perQueue": "One code per queue",
  "qr.pickQueue": "الطابور لهذا الرمز",
  "qr.displayLink": "رابط شاشة التلفاز",
  "sq.title": "الطوابير والنوافذ",
  "sq.sub": "لكل طابور أرقامه وخطه الخاص.",
  "sq.locations": "المواقع",
  "sq.addLocation": "إضافة موقع",
  "sq.locationName": "اسم الموقع",
  "sq.address": "العنوان (اختياري)",
  "sq.phone": "الهاتف (اختياري)",
  "sq.noLocations": "لا مواقع بعد.",
  "sq.queues": "الطوابير",
  "sq.addQueue": "إضافة طابور",
  "sq.queueName": "اسم الطابور",
  "sq.prefix": "حروف الرقم",
  "sq.prefixHint": "حرفان كحد أقصى قبل الرقم، مثل A12.",
  "sq.description": "ما الغرض من هذا الطابور؟ (اختياري)",
  "sq.avgTime": "الوقت المعتاد (دقائق)",
  "sq.counters": "نوافذ",
  "sq.counterName": "Counter name",
  "sq.addCounter": "إضافة نافذة",
  "sq.paused": "متوقف مؤقتًا",
  "sq.open": "مفتوح",
  "sq.closed": "Closed",
  "sq.noQueues": "لا توجد طوابير في هذا الموقع بعد.",
  "sq.deleteQueue": "إزالة هذا الطابور",
  "sq.deleteCounter": "Remove this counter",
  "sq.deleteLocation": "Remove this location",
  "sq.startFrom": "ابدأ بنوع النشاط",
  "sq.applyTemplate": "Use these queues",
  "sq.pausedBody": "لا يستطيع العملاء أخذ رقم في هذا الطابور أثناء الإيقاف المؤقت.",
  "sq.movedBody": "Customer moved to another queue.",
  "team.title": "فريقك",
  "team.sub": "ادعُ من يعملون عند النافذة واختر ما يستطيع كلٌّ منهم فعله.",
  "team.invite": "دعوة شخص",
  "team.invited": "تم إرسال الدعوة",
  "team.inviteEmail": "بريدهم الإلكتروني",
  "team.inviteRole": "ما يمكنهم فعله",
  "team.pending": "بانتظار الانضمام",
  "team.noPending": "لا توجد دعوات معلقة.",
  "team.revoke": "إلغاء الدعوة",
  "team.role": "الدور",
  "team.roleOwner": "المالك",
  "team.roleManager": "مدير",
  "team.roleStaff": "موظف",
  "team.roleViewer": "قراءة فقط",
  "team.remove": "إزالة من الفريق",
  "team.lock": "تسجيل الخروج من كل الأجهزة",
  "team.unlock": "السماح بالدخول",
  "team.allBranches": "كل المواقع",
  "team.oneBranch": "One location",
  "team.pickBranch": "الموقع",
  "team.noTeam": "أنت الوحيد حتى الآن.",
  "team.linkCopied": "تم نسخ رابط الدعوة. أرسله لهم.",
  "team.onlyYou": "You can't change your own role.",
  "rep.title": "History",
  "rep.sub": "كيف كان الأمس والأسبوع الماضي فعليًا.",
  "rep.joined": "الأرقام المأخوذة",
  "rep.served": "عملاء تم خدمتهم",
  "rep.avgWait": "متوسط الانتظار",
  "rep.avgService": "متوسط الخدمة",
  "rep.peak": "ساعة الذروة",
  "rep.abandoned": "غادروا دون خدمة",
  "rep.noShow": "No shows",
  "rep.skipped": "Skipped",
  "rep.days7": "آخر 7 أيام",
  "rep.days30": "آخر 30 يومًا",
  "rep.days90": "آخر 90 يومًا",
  "rep.byDay": "Each day",
  "rep.byHour": "الساعات الأكثر ازدحامًا",
  "rep.byQueue": "كل طابور",
  "rep.waited": "انتظر {n} دقيقة",
  "rep.servedIn": "تمت خدمته في {n} دقيقة",
  "rep.history": "كل من مرّ من هنا",
  "rep.noHistory": "لم يمر أحد بهذا الطابور في هذه الفترة.",
  "rep.audit": "التغييرات التي أجراها فريقك",
  "rep.noAudit": "لم تُسجَّل أي تغييرات بعد.",
  "rep.noReports": "دورك لا يمكنه رؤية التقارير.",
  "set.brand": "المظهر",
  "set.brandHint": "ألوانك وشعارك يظهران في صفحة العميل وشاشة التلفاز.",
  "set.mainColour": "اللون الرئيسي",
  "set.accentColour": "لون التمييز",
  "set.logo": "الشعار",
  "set.logoHint": "الصق رابط ويب أو ارفع صورة. الأصغر أفضل.",
  "set.logoUploaded": "Logo updated.",
  "set.removeLogo": "إزالة الشعار",
  "set.security": "كلمة المرور الخاصة بك",
  "set.currentPassword": "كلمة المرور الحالية",
  "set.newPassword": "كلمة مرور جديدة",
  "set.changePassword": "تغيير كلمة المرور",
  "set.passwordChanged": "تم تغيير كلمة المرور. تم تسجيل الخروج من الأجهزة الأخرى.",
  "set.pauseAll": "Stop taking numbers everywhere",
  "set.pauseAllHint": "Useful for lunch breaks or stock-taking.",
  "disp.nowServing": "يُستدعى الآن",
  "disp.waiting": "منتظرون",
  "disp.others": "طوابير أخرى",
  "disp.fullscreen": "ملء الشاشة",
  "disp.exitFullscreen": "Leave full screen",
  "disp.awaiting": "في انتظار أول رقم",
  // Added by scripts/sync-lang.mjs: English until translated.
  "cust.waitEstimate": "الوقت المتوقع للانتظار",
  "rep.allQueues": "All queues",
  // Added by scripts/sync-lang.mjs: English until translated.
  "hero.statShops": "Screens rebuilt for the counter",
  "hero.statLive": "مباشر افتراضيًا",
  "hero.statPhone": "يعمل على أي هاتف",
  "feat.title": "كل ما يحتاجه الطابور، ولا شيء زائد",
  "feat.copy": "ينجز Lobby مهمة واحدة بشكل ممتاز. كل شاشة أدناه جزء من المنتج اليوم.",
  "feat.qr.t": "رمز واحد، محدّث دائمًا",
  "feat.qr.d": "رمز QR ثابت لكل موقع. اطبعه مرة واحدة — تغيير اسم المتجر لا يكسره أبدًا.",
  "feat.multi.t": "طوابير كثيرة، شاشة واحدة",
  "feat.multi.d": "قسّم النافذة إلى خدمات — استشارة، استلام، مرتجعات — لكل منها أرقامها ونوافذها.",
  "feat.team.t": "أدوار تناسب المتجر",
  "feat.team.d": "ادعُ الموظفين عبر رابط، واربطهم بفرع، واترك المفاتيح لأصحاب المتجر.",
  "feat.brand.t": "يشبه نشاطك",
  "feat.brand.d": "ألوانك وشعارك وملاحظتك تظهر على هاتف كل عميل وفي التلفاز.",
  "feat.reports.t": "حقائق لأمسية هادئة",
  "feat.reports.d": "أوقات الانتظار، ساعات الذروة وسجل كامل — جدول الأسبوع القادم لم يعد تخمينًا.",
  "feat.pause.t": "أغلق دون حيرة",
  "feat.pause.d": "أوقف الطابور بضغطة واحدة. لوحة الباب تُخبر بذلك، ولن يأخذ أحد رقمًا عند نافذة مغلقة.",
  "flow.title": "من الباب إلى الإتمام في أربع خطوات",
  "flow.s1.t": "ينضم العملاء إلى الطابور",
  "flow.s1.d": "يمسحون الرمز، يختارون خدمة، ويأخذون رقمًا. لا تطبيق ولا حساب.",
  "flow.s2.t": "يستدعي الموظف التالي",
  "flow.s2.d": "زر كبير يخدم الشخص التالي ويحافظ على عدالة الطابور.",
  "flow.s3.t": "الجميع يرى حالته",
  "flow.s3.d": "يعرض كل هاتف موقعك ومن أمامك ووقت الانتظار — مباشرةً دون تحديث.",
  "flow.s4.t": "الشاشة تحافظ على النظام",
  "flow.s4.d": "تلفاز في غرفة الانتظار يعرض من يُخدم ومن التالي.",
  "dispsect.title": "شاشة تليق بغرفة انتظارك",
  "dispsect.copy": "افتح الشاشة على أي متصفح تلفاز. أرقام كبيرة، والخمسة التاليون وطوابير أخرى بنظرة واحدة. تتحدث بمجرد عمل الموظفين.",
  "dispsect.cta": "شاهد شاشة مباشرة",
  "dash.servingCounters": "{n} في الخدمة",
};

export const eurasia: Lang[] = [
  { code: "ru", label: "Russian", native: "Русский", flag: "🇷🇺", dict: ru },
  { code: "tr", label: "Turkish", native: "Türkçe", flag: "🇹🇷", dict: tr },
  { code: "ar", label: "Arabic", native: "العربية", flag: "🇸🇦", dir: "rtl", dict: ar },
];
