import type { StringKey } from "./en";
import type { Lang } from "./types";

type Pack = Record<StringKey, string>;

const ru: Pack = {
  "nav.about": "О проекте",
  "nav.signin": "Войти",
  "nav.setup": "Настроить бизнес",
  "foot.made": "Lobby создал {name}.",
  "foot.mit": "Открытый код, лицензия MIT.",
  "lang.title": "Выберите язык",
  "lang.sub": "Позже его можно сменить по флагу в правом верхнем углу.",
  "lang.change": "Сменить язык",
  "lang.done": "Готово",
  "common.loading": "Загрузка…",
  "common.retry": "Попробовать снова",
  "hero.eyebrow": "Очереди для магазинов, клиник и салонов",
  "hero.h1a": "Берите номер.",
  "hero.h1b": "Ждите где угодно.",
  "hero.lede":
    "Один QR-код для вашего бизнеса. Клиенты сканируют его, берут номер и видят своё место в очереди. Когда до них доходит очередь, телефон их уведомляет.",
  "hero.fine":
    "Ни приложений, ни аккаунтов для клиентов. Открытый код, работает на вашем сервере.",
  "demo.nowServing": "Сейчас обслуживают",
  "demo.yourNumber": "Ваш номер",
  "how.title": "Как это работает",
  "how.t1": "Распечатайте QR-код",
  "how.d1": "Постоянный код для двери или стойки.",
  "how.t2": "Клиенты берут номер",
  "how.d2": "Сканируют, добавляют имя по желанию, ничего ставить не нужно.",
  "how.t3": "Нажмите «Вызвать следующего»",
  "how.d3": "Очередь двигается, экран обновляется сам.",
  "see.title": "Что видят ваши клиенты",
  "see.copy":
    "Один экран с одинаковыми ответами. Работает в любом браузере телефона, а когда вы вызываете номер, экран меняется на «Ваша очередь».",
  "see.youreNumber": "Ваш номер",
  "see.peopleAhead": "Человек перед вами",
  "see.when": "Когда это случается",
  "see.itsTurn": "Ваша очередь!",
  "places.title": "Для мест со стойкой",
  "places.list":
    "Аптеки · Клиники · Салоны · Парикмахерские · Мастерские · Банки · Почта · Госучреждения",
  "band.title": "Настройка занимает минуту.",
  "auth.welcome": "С возвращением",
  "auth.setupSub": "Минута ввода, и очередь готова.",
  "auth.loginSub": "Войдите в свою очередь.",
  "auth.bizName": "Название бизнеса",
  "auth.yourName": "Ваше имя",
  "auth.email": "Эл. почта",
  "auth.password": "Пароль",
  "auth.pwHint": "Не менее 8 символов.",
  "auth.creating": "Создаём…",
  "auth.signingIn": "Входим…",
  "auth.create": "Создать бизнес",
  "auth.haveAccount": "Уже есть аккаунт?",
  "auth.noAccount": "Ещё нет аккаунта?",
  "auth.backHome": "На главную",
  "err.bizName": "Введите название бизнеса.",
  "err.name": "Введите имя.",
  "err.email": "Введите почту.",
  "err.password": "Введите пароль.",
  "err.pwLen": "Пароль должен быть не короче 8 символов.",
  "cust.opening": "Открываем очередь…",
  "cust.wrong": "Что-то пошло не так.",
  "cust.pausedT": "Очередь на паузе.",
  "cust.pausedB": "Сейчас номера не выдаются, загляните позже.",
  "cust.nobody": "Сейчас никого не обслуживают",
  "cust.noOneWaiting": "никто не ждёт",
  "cust.waitingN": "ждут: {n}",
  "cust.joinT": "Встать в очередь",
  "cust.nameLabel": "Ваше имя (необязательно)",
  "cust.joinBusy": "Выдаём номер…",
  "cust.joinReassure": "Без приложений и аккаунтов, просто номер.",
  "cust.youreNumber": "Ваш номер",
  "cust.youreNext": "Вы следующий",
  "cust.oneAhead": "1 человек перед вами",
  "cust.nAhead": "Перед вами {n} человек",
  "cust.peopleWaiting": "Ждут",
  "cust.reassure": "Страница обновляется сама, не закрывайте её.",
  "cust.leave": "Выйти из очереди",
  "cust.leaveConfirm": "Выйти из очереди? Вы потеряете номер.",
  "cust.turnT": "Ваша очередь",
  "cust.turnB": "Пожалуйста, подойдите к стойке.",
  "cust.imHere": "Я на месте",
  "cust.sending": "Отправляем…",
  "cust.confirmed": "Спасибо, мы передали, что вы готовы.",
  "cust.done": "Всё готово",
  "cust.servedBody": "Спасибо за ожидание.",
  "cust.skippedBody": "Вас пропустили. Если вы ещё здесь, возьмите новый номер.",
  "cust.noShowBody": "Номер закрыт. Если вы ещё здесь, возьмите новый номер.",
  "cust.joinAgain": "Встать в очередь снова",
  "cust.poweredBy": "На платформе",
  "dash.navQueue": "Очередь",
  "dash.navQr": "QR-код",
  "dash.navSettings": "Настройки",
  "dash.signOut": "Выйти",
  "dash.opening": "Открываем вашу очередь…",
  "dash.pausedB": "Клиенты сейчас не могут взять номер.",
  "dash.nobodyCounter": "У стойки никого",
  "dash.noNameGiven": "Без имени",
  "dash.confirmedHere": "подтвердил, что на месте",
  "dash.notConfirmed": "ещё не подтвердил",
  "dash.callNext": "Вызвать следующего",
  "dash.calling": "Вызываем…",
  "dash.noWaitingHint": "Сейчас никто не ждёт.",
  "dash.pause": "Пауза",
  "dash.resume": "Продолжить",
  "dash.atCounter": "У стойки",
  "dash.waitingTitle": "Ждут",
  "dash.noName": "Без имени",
  "dash.stWait": "Ждёт",
  "dash.stCalled": "Обслуживается",
  "dash.stServed": "Обслужен",
  "dash.stSkipped": "Пропущен",
  "dash.stNoShow": "Не пришёл",
  "dash.firstRun": "Пока никого нет. Три шага, и очередь заработает:",
  "dash.step1": "Возьмите QR-код. Распечатайте или выведите на экран у входа.",
  "dash.step1link": "Открыть мой QR-код →",
  "dash.step2": "Клиенты берут номер: сканируют, вводят имя по желанию и встают в очередь.",
  "dash.step3": "Нажмите «Вызвать следующего». Телефон обновится сразу.",
  "dash.emptyWaiting": "Никто не ждёт. Новые номера появятся здесь по мере прихода людей.",
  "dash.nextUp": "Следующий",
  "dash.finished": "Завершено",
  "dash.counts": "обслужено {s}, пропущено {k}, не пришли {n}",
  "dash.markServed": "Отметить обслуженным",
  "dash.skip": "Пропустить",
  "qr.intro":
    "Распечатайте и повесьте у входа или на стойке. Ссылка не меняется, код, напечатанный сегодня, работает всегда.",
  "qr.linkLabel": "Ссылка на очередь",
  "qr.download": "Скачать PNG",
  "qr.print": "Печать",
  "qr.copy": "Копировать ссылку",
  "qr.copied": "Ссылка скопирована.",
  "qr.making": "Создаём QR-код…",
  "qr.sheetCta": "Отсканируйте, чтобы встать в очередь",
  "qr.fine":
    "Клиенты сканируют, чтобы взять номер, без приложений и аккаунтов. QR остаётся чёрно-белым в любой теме, чтобы телефоны его читали.",
  "set.noteLabel": "Заметка для клиентов",
  "set.noteHint": "Показывается над кнопкой вступления на странице очереди. Необязательно.",
  "set.save": "Сохранить",
  "set.saving": "Сохраняем…",
  "set.saved": "Сохранено.",
  "set.goodToKnow": "Полезно знать",
  "set.linkBody": "Ссылка постоянная: напечатанный QR работает, даже если переименовать бизнес.",
  "set.signedInAs": "Вход выполнен как",
  "set.errNote": "Заметка должна быть не длиннее 200 символов.",
  "nf.title": "Такой страницы нет.",
  "nf.body": "Возможно, она переместилась или ссылка набрана с ошибкой.",
  "nf.cta": "На главную",
};

const tr: Pack = {
  "nav.about": "Hakkında",
  "nav.signin": "Giriş yap",
  "nav.setup": "İşletmeni kur",
  "foot.made": "Lobby, {name} tarafından geliştirildi.",
  "foot.mit": "MIT lisansı altında açık kaynak.",
  "lang.title": "Dilini seç",
  "lang.sub": "Daha sonra sağ üstteki bayraktan değiştirebilirsin.",
  "lang.change": "Dil değiştir",
  "lang.done": "Tamam",
  "common.loading": "Yükleniyor…",
  "common.retry": "Tekrar dene",
  "hero.eyebrow": "Dükkanlar, klinikler ve kuaförler için sıralar",
  "hero.h1a": "Bir numara al.",
  "hero.h1b": "İstediğin yerde bekle.",
  "hero.lede":
    "İşletmen için tek bir QR kod. Müşteriler tarar, numara alır ve sıradaki yerini görür. Sıra onlara geldiğinde telefonları haber verir.",
  "hero.fine":
    "Müşterilerin için uygulama yok, onlar için hesap yok. Açık kaynak ve kendi sunucunda çalışır.",
  "demo.nowServing": "Şu an servis ediliyor",
  "demo.yourNumber": "Senin numaran",
  "how.title": "Nasıl çalışır",
  "how.t1": "QR kodunu bastır",
  "how.d1": "Kapın veya tezgahın için kalıcı bir kod.",
  "how.t2": "Müşteriler numara alır",
  "how.d2": "Tarar, isterse isim yazar, kuracak bir şey yok.",
  "how.t3": "Sıradakini çağır'a bas",
  "how.d3": "Sıra ilerler, ekranları kendiliğinden güncellenir.",
  "see.title": "Müşterilerin ne görür",
  "see.copy":
    "Her zaman aynı cevapları veren tek bir ekran. Tüm telefon tarayıcılarında çalışır ve numaralarını çağırdığında Sıra sende'ye döner.",
  "see.youreNumber": "Senin numaran",
  "see.peopleAhead": "Önündeki kişiler",
  "see.when": "Olduğu zaman",
  "see.itsTurn": "Sıra sende!",
  "places.title": "Tezgahı olan yerler için",
  "places.list":
    "Eczaneler · Klinikler · Kuaförler · Berberler · Tamirhaneler · Bankalar · Postaneler · Kamu daireleri",
  "band.title": "Kurma işlemi bir dakika sürer.",
  "auth.welcome": "Tekrar hoş geldin",
  "auth.setupSub": "Bir dakika yaz, sıran hazır olsun.",
  "auth.loginSub": "Sıranla giriş yap.",
  "auth.bizName": "İşletme adı",
  "auth.yourName": "Adın",
  "auth.email": "E-posta",
  "auth.password": "Şifre",
  "auth.pwHint": "En az 8 karakter.",
  "auth.creating": "Kuruluyor…",
  "auth.signingIn": "Giriş yapılıyor…",
  "auth.create": "İşletmemi oluştur",
  "auth.haveAccount": "Zaten hesabın var mı?",
  "auth.noAccount": "Henüz hesabın yok mu?",
  "auth.backHome": "Ana sayfaya dön",
  "err.bizName": "İşletme adını yaz.",
  "err.name": "Adını yaz.",
  "err.email": "E-postanı yaz.",
  "err.password": "Şifreni yaz.",
  "err.pwLen": "Şifre en az 8 karakter olmalı.",
  "cust.opening": "Sıra açılıyor…",
  "cust.wrong": "Bir şeyler ters gitti.",
  "cust.pausedT": "Sıra duraklatıldı.",
  "cust.pausedB": "Bu işletme şu an numara vermiyor, sonra tekrar bak.",
  "cust.nobody": "Henüz servis edilen yok",
  "cust.noOneWaiting": "bekleyen yok",
  "cust.waitingN": "{n} kişi bekliyor",
  "cust.joinT": "Sıraya katıl",
  "cust.nameLabel": "Adın (isteğe bağlı)",
  "cust.joinBusy": "Numaran alınıyor…",
  "cust.joinReassure": "Uygulama yok, hesap yok, sadece numara.",
  "cust.youreNumber": "Senin numaran",
  "cust.youreNext": "Sıradaki sensin",
  "cust.oneAhead": "Önünde 1 kişi",
  "cust.nAhead": "Önünde {n} kişi",
  "cust.peopleWaiting": "Bekleyenler",
  "cust.reassure": "Bu sayfa kendini günceller, açık bırak.",
  "cust.leave": "Sıradan ayrıl",
  "cust.leaveConfirm": "Sıradan ayrılın mı? Numaranı kaybedersin.",
  "cust.turnT": "Sıra sende",
  "cust.turnB": "Lütfen tezgaha gel.",
  "cust.imHere": "Buradayım",
  "cust.sending": "Gönderiliyor…",
  "cust.confirmed": "Teşekkürler, hazır olduğunu söyledik.",
  "cust.done": "Tamamlandı",
  "cust.servedBody": "Beklediğin için teşekkürler.",
  "cust.skippedBody": "Atlandın. Hâlâ buradaysan yeni bir numara al.",
  "cust.noShowBody": "Bu numara kapandı. Hâlâ buradaysan yeni bir numara al.",
  "cust.joinAgain": "Tekrar katıl",
  "cust.poweredBy": "Altyapı",
  "dash.navQueue": "Sıra",
  "dash.navQr": "QR kod",
  "dash.navSettings": "Ayarlar",
  "dash.signOut": "Çıkış yap",
  "dash.opening": "Sıran açılıyor…",
  "dash.pausedB": "Müşteriler şu an numara alamaz.",
  "dash.nobodyCounter": "Tezgahta kimse yok",
  "dash.noNameGiven": "İsimsiz",
  "dash.confirmedHere": "burada olduğunu söyledi",
  "dash.notConfirmed": "henüz onaylamadı",
  "dash.callNext": "Sıradakini çağır",
  "dash.calling": "Çağrılıyor…",
  "dash.noWaitingHint": "Şu an bekleyen yok.",
  "dash.pause": "Sırayı duraklat",
  "dash.resume": "Sırayı sürdür",
  "dash.atCounter": "Tezgahta",
  "dash.waitingTitle": "Bekliyor",
  "dash.noName": "İsim yok",
  "dash.stWait": "Bekliyor",
  "dash.stCalled": "Servis ediliyor",
  "dash.stServed": "Servis edildi",
  "dash.stSkipped": "Atlandı",
  "dash.stNoShow": "Gelmedi",
  "dash.firstRun": "Henüz kimse yok. Üç hızlı adım ve sıran hazır:",
  "dash.step1": "QR kodunu al. Bastır veya kapı yanındaki ekrana koy.",
  "dash.step1link": "QR kodumu aç →",
  "dash.step2": "Müşteriler numara alır: tarar, isteğe bağlı isim yazar, sıraya girer.",
  "dash.step3": "Sıradakini çağır'a bas. Telefonları o an güncellenir.",
  "dash.emptyWaiting": "Bekleyen yok. İnsan geldikçe yeni numaralar burada görünür.",
  "dash.nextUp": "Sıradaki",
  "dash.finished": "Bitenler",
  "dash.counts": "{s} servis edildi, {k} atlandı, {n} gelmedi",
  "dash.markServed": "Servis edildi olarak işaretle",
  "dash.skip": "Atla",
  "qr.intro":
    "Bunu bastır ve kapıya veya tezgaha koy. Bağlantı hiç değişmez, bugün bastığın kod çalışmaya devam eder.",
  "qr.linkLabel": "Sıra bağlantın",
  "qr.download": "PNG indir",
  "qr.print": "Yazdır",
  "qr.copy": "Bağlantıyı kopyala",
  "qr.copied": "Bağlantı kopyalandı.",
  "qr.making": "QR kodun yapılıyor…",
  "qr.sheetCta": "Sıraya katılmak için tara",
  "qr.fine":
    "Müşteriler uygulama ve hesap olmadan numara almak için tarar. QR, telefonlar okuyabilsin diye her temada siyah beyaz kalır.",
  "set.noteLabel": "Müşteriler için not",
  "set.noteHint": "Sıra sayfandaki Katıl düğmesinin üstünde görünür. İsteğe bağlı.",
  "set.save": "Değişiklikleri kaydet",
  "set.saving": "Kaydediliyor…",
  "set.saved": "Kaydedildi.",
  "set.goodToKnow": "Bilmen gerekenler",
  "set.linkBody": "Bağlantı kalıcıdır, işletme adını değiştirsensen bile basılı QR çalışmaya devam eder.",
  "set.signedInAs": "Oturum açılan hesap",
  "set.errNote": "Notun en fazla 200 karakter olmalı.",
  "nf.title": "Böyle bir sayfa yok.",
  "nf.body": "Taşınmış olabilir ya da bağlantı yanlış yazılmıştır.",
  "nf.cta": "Ana sayfaya git",
};

const ar: Pack = {
  "nav.about": "حول",
  "nav.signin": "تسجيل الدخول",
  "nav.setup": "إعداد عملك",
  "foot.made": "أنشأ Lobby {name}.",
  "foot.mit": "مفتوح المصدر برخصة MIT.",
  "lang.title": "اختر لغتك",
  "lang.sub": "يمكنك تغييرها لاحقاً من العلم في الزاوية العليا.",
  "lang.change": "تغيير اللغة",
  "lang.done": "تم",
  "common.loading": "جارٍ التحميل…",
  "common.retry": "حاول مجدداً",
  "hero.eyebrow": "طوابير للمتاجر والعيادات وصالونات التجميل",
  "hero.h1a": "خذ رقماً.",
  "hero.h1b": "انتظر أينما شئت.",
  "hero.lede":
    "رمز QR واحد لعملك. يمسحه الزبائن فيأخذون رقماً ويرون مكانهم في الطابور. وعندما يحين دورهم يخبرهم هاتفهم.",
  "hero.fine":
    "لا تطبيق للزبائن ولا حساب لهم. مفتوح المصدر ويعمل على خادمك الخاص.",
  "demo.nowServing": "يُخدم الآن",
  "demo.yourNumber": "رقمك",
  "how.title": "كيف يعمل",
  "how.t1": "اطبع رمز QR",
  "how.d1": "رمز دائم لبابك أو طاولتك.",
  "how.t2": "الزبائن يأخذون رقماً",
  "how.d2": "يمسحون ويضيفون اسماً إن أرادوا، ولا شيء يُثبَّت.",
  "how.t3": "اضغط استدعاء التالي",
  "how.d3": "يتقدم الطابور وتحتفل شاشتهم بأنفسها.",
  "see.title": "ما يراه زبائنك",
  "see.copy":
    "شاشة واحدة بإجابات ثابتة في كل مرة. تعمل في أي متصفح للهاتف، وعندما تستدعي رقمهم تتحول إلى حان دورك.",
  "see.youreNumber": "رقمك",
  "see.peopleAhead": "أشخاص أمامك",
  "see.when": "عندما يحدث",
  "see.itsTurn": "حان دورك!",
  "places.title": "لأماكن فيها طاولة استقبال",
  "places.list":
    "صيدليات · عيادات · صالونات · محلات حلاقة · ورش · بنوك · مكاتب بريد · مصالح حكومية",
  "band.title": "الاستعداد يستغرق دقيقة تقريباً.",
  "auth.welcome": "مرحباً بعودتك",
  "auth.setupSub": "دقيقة من الكتابة وطابورك جاهز.",
  "auth.loginSub": "سجّل الدخول إلى طابورك.",
  "auth.bizName": "اسم العمل",
  "auth.yourName": "اسمك",
  "auth.email": "البريد الإلكتروني",
  "auth.password": "كلمة المرور",
  "auth.pwHint": "8 أحرف على الأقل.",
  "auth.creating": "جارٍ الإنشاء…",
  "auth.signingIn": "جارٍ الدخول…",
  "auth.create": "أنشئ مشغلي",
  "auth.haveAccount": "لديك حساب بالفعل؟",
  "auth.noAccount": "ليس لديك حساب بعد؟",
  "auth.backHome": "العودة إلى الرئيسية",
  "err.bizName": "أدخل اسم عملك.",
  "err.name": "أدخل اسمك.",
  "err.email": "أدخل بريدك الإلكتروني.",
  "err.password": "أدخل كلمة المرور.",
  "err.pwLen": "يجب أن تتكوّن كلمة المرور من 8 أحرف على الأقل.",
  "cust.opening": "جارٍ فتح الطابور…",
  "cust.wrong": "حدث خطأ ما.",
  "cust.pausedT": "الطابور متوقف مؤقتاً.",
  "cust.pausedB": "هذا العمل لا يأخذ أرقاماً الآن، عد بعد قليل.",
  "cust.nobody": "لا أحد يُخدم حالياً",
  "cust.noOneWaiting": "لا أحد ينتظر",
  "cust.waitingN": "{n} ينتظرون",
  "cust.joinT": "انضم إلى الطابور",
  "cust.nameLabel": "اسمك (اختياري)",
  "cust.joinBusy": "جارٍ أخذ رقمك…",
  "cust.joinReassure": "لا تطبيق ولا حساب، رقم فقط.",
  "cust.youreNumber": "رقمك",
  "cust.youreNext": "أنت التالي",
  "cust.oneAhead": "شخص واحد أمامك",
  "cust.nAhead": "{n} أشخاص أمامك",
  "cust.peopleWaiting": "المنتظرون",
  "cust.reassure": "تتحدث هذه الصفحة بنفسها، أبقها مفتوحة.",
  "cust.leave": "غادر الطابور",
  "cust.leaveConfirm": "هل تغادر الطابور؟ ستفقد رقمك.",
  "cust.turnT": "حان دورك",
  "cust.turnB": "تفضّل بالتوجّه إلى الطاولة.",
  "cust.imHere": "أنا هنا",
  "cust.sending": "جارٍ الإرسال…",
  "cust.confirmed": "شكراً، أخبرناهم بأنك مستعد.",
  "cust.done": "انتهى",
  "cust.servedBody": "شكراً لانتظارك.",
  "cust.skippedBody": "تم تجاوزك. إن كنت هنا فخذ رقماً آخر.",
  "cust.noShowBody": "أُغلق هذا الرقم. إن كنت هنا فخذ رقماً آخر.",
  "cust.joinAgain": "انضم مجدداً",
  "cust.poweredBy": "مدعوم بـ",
  "dash.navQueue": "الطابور",
  "dash.navQr": "رمز QR",
  "dash.navSettings": "الإعدادات",
  "dash.signOut": "تسجيل الخروج",
  "dash.opening": "جارٍ فتح طابورك…",
  "dash.pausedB": "لا يستطيع الزبائن أخذ أرقام الآن.",
  "dash.nobodyCounter": "لا أحد عند الطاولة",
  "dash.noNameGiven": "بدون اسم",
  "dash.confirmedHere": "قال إنه هنا",
  "dash.notConfirmed": "لم يؤكد بعد",
  "dash.callNext": "استدعاء التالي",
  "dash.calling": "جارٍ الاستدعاء…",
  "dash.noWaitingHint": "لا أحد ينتظر حالياً.",
  "dash.pause": "إيقاف الطابور مؤقتاً",
  "dash.resume": "استئناف الطابور",
  "dash.atCounter": "عند الطاولة",
  "dash.waitingTitle": "منتظرون",
  "dash.noName": "بدون اسم",
  "dash.stWait": "منتظر",
  "dash.stCalled": "قيد الخدمة",
  "dash.stServed": "تمت الخدمة",
  "dash.stSkipped": "تم تجاوزه",
  "dash.stNoShow": "لم يحضر",
  "dash.firstRun": "لا أحد بعد. ثلاث خطوات سريعة ويبدأ طابورك:",
  "dash.step1": "احصل على رمز QR. اطبعه أو ضعه على شاشة قرب الباب.",
  "dash.step1link": "افتح رمز QR الخاص بي ←",
  "dash.step2": "الزبائن يأخذون رقماً: يمسحون ويكتبون اسماً اختيارياً وينضمون.",
  "dash.step3": "اضغط استدعاء التالي. يتحدث هاتفهم في اللحظة نفسها.",
  "dash.emptyWaiting": "لا أحد ينتظر. تظهر الأرقام الجديدة هنا مع وصول الناس.",
  "dash.nextUp": "التالي",
  "dash.finished": "منتهية",
  "dash.counts": "{s} تمت خدمتهم، {k} تم تجاوزهم، {n} لم يحضروا",
  "dash.markServed": "تعليم كمخدوم",
  "dash.skip": "تخطي",
  "qr.intro":
    "اطبعه وضعه عند الباب أو على الطاولة. الرابط لا يتغيّر، الرمز المطبوع اليوم يستمر بالعمل.",
  "qr.linkLabel": "رابط طابورك",
  "qr.download": "تنزيل PNG",
  "qr.print": "طباعة",
  "qr.copy": "نسخ الرابط",
  "qr.copied": "تم نسخ الرابط.",
  "qr.making": "جارٍ إنشاء رمز QR…",
  "qr.sheetCta": "امسح للانضمام إلى الطابور",
  "qr.fine":
    "يمسح الزبائن هذا لأخذ رقم، بلا تطبيق ولا حساب. يبقى رمز QR أبيض وأسود في كل السمات حتى يقرؤه الهاتف.",
  "set.noteLabel": "ملاحظة للزبائن",
  "set.noteHint": "تظهر فوق زر الانضمام في صفحة طابورك. اختيارية.",
  "set.save": "حفظ التغييرات",
  "set.saving": "جارٍ الحفظ…",
  "set.saved": "تم الحفظ.",
  "set.goodToKnow": "مفيد أن تعرف",
  "set.linkBody": "الرابط دائم، الرمز المطبوع يستمر بالعمل حتى لو غيّرت اسم العمل.",
  "set.signedInAs": "مسجّل الدخول باسم",
  "set.errNote": "يجب ألا تتجاوز ملاحظتك 200 حرف.",
  "nf.title": "هذه الصفحة غير موجودة.",
  "nf.body": "ربما انتقلت أو كُتب الرابط خطأً.",
  "nf.cta": "اذهب إلى الصفحة الرئيسية",
};

export const eurasia: Lang[] = [
  { code: "ru", label: "Russian", native: "Русский", flag: "ru", dict: ru },
  { code: "tr", label: "Turkish", native: "Türkçe", flag: "tr", dict: tr },
  { code: "ar", label: "Arabic", native: "العربية", flag: "sa", dir: "rtl", dict: ar },
];
