import type { StringKey } from "./en";
import type { Lang } from "./types";

type Pack = Record<StringKey, string>;

const fr: Pack = {
  "nav.about": "À propos",
  "nav.signin": "Se connecter",
  "nav.setup": "Créer votre commerce",
  "foot.made": "Lobby, créé par {name}.",
  "foot.mit": "Open source sous licence MIT.",
  "lang.title": "Choisissez votre langue",
  "lang.sub": "Vous pourrez la changer plus tard avec le drapeau en haut à droite.",
  "lang.change": "Changer de langue",
  "lang.done": "Terminé",
  "common.loading": "Chargement…",
  "common.retry": "Réessayer",
  "hero.eyebrow": "Files d'attente pour boutiques, cliniques et salons",
  "hero.h1a": "Prenez un numéro.",
  "hero.h1b": "Attendez où vous voulez.",
  "hero.lede":
    "Un QR code pour votre commerce. Les clients le scannent, prennent un numéro et voient leur place dans la file. Quand leur tour arrive, leur téléphone les prévient.",
  "hero.fine":
    "Pas d'application pour vos clients, pas de compte pour eux. Open source, hébergé sur votre propre serveur.",
  "demo.nowServing": "En cours d'appel",
  "demo.yourNumber": "Votre numéro",
  "how.title": "Comment ça marche",
  "how.t1": "Imprimez votre QR code",
  "how.d1": "Un code permanent pour votre porte ou votre comptoir.",
  "how.t2": "Les clients prennent un numéro",
  "how.d2": "Ils scannent, ajoutent un nom s'ils veulent, rien à installer.",
  "how.t3": "Appuyez sur Appeler",
  "how.d3": "La file avance et leur écran se met à jour tout seul.",
  "see.title": "Ce que voient vos clients",
  "see.copy":
    "Un seul écran, les mêmes réponses à chaque fois. Ça marche dans tous les navigateurs mobiles, et quand vous appelez leur numéro, l'écran passe à C'est votre tour.",
  "see.youreNumber": "Votre numéro",
  "see.peopleAhead": "Personnes avant vous",
  "see.when": "Quand ça arrive",
  "see.itsTurn": "C'est votre tour !",
  "places.title": "Fait pour les lieux avec un comptoir",
  "places.list":
    "Pharmacies · Cliniques · Salons · Barbiers · Ateliers de réparation · Banques · Postes · Services publics",
  "band.title": "La prise de service prend une minute.",
  "auth.welcome": "Bon retour",
  "auth.setupSub": "Une minute de saisie et votre file est prête.",
  "auth.loginSub": "Connectez-vous à votre file.",
  "auth.bizName": "Nom du commerce",
  "auth.yourName": "Votre nom",
  "auth.email": "E-mail",
  "auth.password": "Mot de passe",
  "auth.pwHint": "8 caractères minimum.",
  "auth.creating": "Création en cours…",
  "auth.signingIn": "Connexion…",
  "auth.create": "Créer mon commerce",
  "auth.haveAccount": "Vous avez déjà un compte ?",
  "auth.noAccount": "Pas encore de compte ?",
  "auth.backHome": "Retour à l'accueil",
  "err.bizName": "Saisissez le nom de votre commerce.",
  "err.name": "Saisissez votre nom.",
  "err.email": "Saisissez votre e-mail.",
  "err.password": "Saisissez votre mot de passe.",
  "err.pwLen": "Le mot de passe doit contenir au moins 8 caractères.",
  "cust.opening": "Ouverture de la file…",
  "cust.wrong": "Quelque chose s'est mal passé.",
  "cust.pausedT": "File en pause.",
  "cust.pausedB": "Ce commerce ne prend pas de numéros pour l'instant, revenez bientôt.",
  "cust.nobody": "Personne n'est servi pour l'instant",
  "cust.noOneWaiting": "personne n'attend",
  "cust.waitingN": "{n} en attente",
  "cust.joinT": "Rejoindre la file",
  "cust.nameLabel": "Votre nom (facultatif)",
  "cust.joinBusy": "Prise du numéro…",
  "cust.joinReassure": "Pas d'application, pas de compte, juste un numéro.",
  "cust.youreNumber": "Votre numéro",
  "cust.youreNext": "C'est vous le suivant",
  "cust.oneAhead": "1 personne avant vous",
  "cust.nAhead": "{n} personnes avant vous",
  "cust.peopleWaiting": "En attente",
  "cust.reassure": "Cette page se met à jour toute seule, gardez-la ouverte.",
  "cust.leave": "Quitter la file",
  "cust.leaveConfirm": "Quitter la file ? Vous perdrez votre numéro.",
  "cust.turnT": "C'est votre tour",
  "cust.turnB": "Rendez-vous au comptoir.",
  "cust.imHere": "J'y suis",
  "cust.sending": "Envoi…",
  "cust.confirmed": "Merci, nous leur avons dit que vous étiez prêt.",
  "cust.done": "Terminé",
  "cust.servedBody": "Merci d'avoir attendu.",
  "cust.skippedBody": "Vous avez été passé. Si vous êtes encore là, prenez un autre numéro.",
  "cust.noShowBody": "Ce numéro est fermé. Si vous êtes encore là, prenez un autre numéro.",
  "cust.joinAgain": "Rejoindre à nouveau",
  "cust.poweredBy": "Propulsé par",
  "dash.navQueue": "File",
  "dash.navQr": "QR code",
  "dash.navSettings": "Réglages",
  "dash.signOut": "Se déconnecter",
  "dash.opening": "Ouverture de votre file…",
  "dash.pausedB": "Les clients ne peuvent pas prendre de numéro pour l'instant.",
  "dash.nobodyCounter": "Personne au comptoir",
  "dash.noNameGiven": "Sans nom",
  "dash.confirmedHere": "a dit qu'il était là",
  "dash.notConfirmed": "n'a pas encore confirmé",
  "dash.callNext": "Appeler",
  "dash.calling": "Appel…",
  "dash.noWaitingHint": "Personne n'attend pour l'instant.",
  "dash.pause": "Mettre en pause",
  "dash.resume": "Reprendre la file",
  "dash.atCounter": "Au comptoir",
  "dash.waitingTitle": "En attente",
  "dash.noName": "Sans nom",
  "dash.stWait": "En attente",
  "dash.stCalled": "En cours d'appel",
  "dash.stServed": "Servi",
  "dash.stSkipped": "Passé",
  "dash.stNoShow": "Absent",
  "dash.firstRun": "Personne n'est encore là. Trois étapes rapides et votre file est lancée :",
  "dash.step1": "Récupérez votre QR code. Imprimez-le ou posez-le sur un écran près de la porte.",
  "dash.step1link": "Ouvrir mon QR code →",
  "dash.step2": "Les clients prennent un numéro. Ils scannent, tapent un nom, et c'est parti.",
  "dash.step3": "Appuyez sur Appeler. Leur téléphone se met à jour dans la seconde.",
  "dash.emptyWaiting": "Personne n'attend. Les nouveaux numéros apparaissent ici au fil des arrivées.",
  "dash.nextUp": "Suivant",
  "dash.finished": "Terminés",
  "dash.counts": "{s} servis, {k} passés, {n} absents",
  "dash.markServed": "Marquer servi",
  "dash.skip": "Passer",
  "qr.intro":
    "Imprimez-le et posez-le près de la porte ou sur le comptoir. Le lien ne change jamais, un code imprimé aujourd'hui continue de fonctionner.",
  "qr.linkLabel": "Lien de votre file",
  "qr.download": "Télécharger le PNG",
  "qr.print": "Imprimer",
  "qr.copy": "Copier le lien",
  "qr.copied": "Lien copié.",
  "qr.making": "Création de votre QR code…",
  "qr.sheetCta": "Scannez pour rejoindre la file",
  "qr.fine":
    "Vos clients scannent pour prendre un numéro, sans application ni compte. Le QR reste en noir et blanc dans tous les thèmes pour rester lisible.",
  "set.noteLabel": "Note pour les clients",
  "set.noteHint": "Affichée au-dessus du bouton Rejoindre sur votre page. Facultatif.",
  "set.save": "Enregistrer",
  "set.saving": "Enregistrement…",
  "set.saved": "Enregistré.",
  "set.goodToKnow": "Bon à savoir",
  "set.linkBody": "Il est permanent, un QR imprimé continue de marcher même si vous changez de nom.",
  "set.signedInAs": "Connecté en tant que",
  "set.errNote": "Votre note doit faire 200 caractères ou moins.",
  "nf.title": "Cette page n'existe pas.",
  "nf.body": "Elle a peut-être bougé, ou le lien est mal tapé.",
  "nf.cta": "Aller à la page d'accueil",
};

const es: Pack = {
  "nav.about": "Acerca de",
  "nav.signin": "Iniciar sesión",
  "nav.setup": "Crear tu negocio",
  "foot.made": "Lobby, creado por {name}.",
  "foot.mit": "Código abierto con licencia MIT.",
  "lang.title": "Elige tu idioma",
  "lang.sub": "Puedes cambiarlo después con la bandera de la esquina superior.",
  "lang.change": "Cambiar idioma",
  "lang.done": "Listo",
  "common.loading": "Cargando…",
  "common.retry": "Reintentar",
  "hero.eyebrow": "Filas para tiendas, clínicas y salones",
  "hero.h1a": "Toma un número.",
  "hero.h1b": "Espera donde quieras.",
  "hero.lede":
    "Un código QR para tu negocio. Tus clientes lo escanean, toman un número y ven su lugar en la fila. Cuando les toca, su teléfono les avisa.",
  "hero.fine":
    "Sin apps para tus clientes, sin cuentas para ellos. Código abierto y corre en tu propio servidor.",
  "demo.nowServing": "Atendiendo ahora",
  "demo.yourNumber": "Tu número",
  "how.title": "Cómo funciona",
  "how.t1": "Imprime tu código QR",
  "how.d1": "Un código permanente para tu puerta o tu mostrador.",
  "how.t2": "Los clientes toman un número",
  "how.d2": "Escanean, añaden un nombre si quieren, sin instalar nada.",
  "how.t3": "Pulsa Llamar al siguiente",
  "how.d3": "La fila avanza y su pantalla se actualiza sola.",
  "see.title": "Lo que ven tus clientes",
  "see.copy":
    "Una sola pantalla con las mismas respuestas de siempre. Funciona en cualquier navegador móvil y, cuando llamas a su número, cambia a Es tu turno.",
  "see.youreNumber": "Tu número",
  "see.peopleAhead": "Personas antes que tú",
  "see.when": "Cuando pasa",
  "see.itsTurn": "¡Es tu turno!",
  "places.title": "Hecho para lugares con mostrador",
  "places.list":
    "Farmacias · Clínicas · Salones · Barberías · Talleres · Bancos · Oficinas de correos · Oficinas públicas",
  "band.title": "Configurar lleva unos minutos.",
  "auth.welcome": "Bienvenido de nuevo",
  "auth.setupSub": "Un minuto escribiendo y tu fila está lista.",
  "auth.loginSub": "Inicia sesión en tu fila.",
  "auth.bizName": "Nombre del negocio",
  "auth.yourName": "Tu nombre",
  "auth.email": "Correo",
  "auth.password": "Contraseña",
  "auth.pwHint": "Al menos 8 caracteres.",
  "auth.creating": "Creando…",
  "auth.signingIn": "Entrando…",
  "auth.create": "Crear mi negocio",
  "auth.haveAccount": "¿Ya tienes cuenta?",
  "auth.noAccount": "¿Aún no tienes cuenta?",
  "auth.backHome": "Volver al inicio",
  "err.bizName": "Escribe el nombre de tu negocio.",
  "err.name": "Escribe tu nombre.",
  "err.email": "Escribe tu correo.",
  "err.password": "Escribe tu contraseña.",
  "err.pwLen": "La contraseña debe tener al menos 8 caracteres.",
  "cust.opening": "Abriendo la fila…",
  "cust.wrong": "Algo salió mal.",
  "cust.pausedT": "Fila en pausa.",
  "cust.pausedB": "Este negocio no está tomando números ahora, vuelve pronto.",
  "cust.nobody": "Nadie siendo atendido todavía",
  "cust.noOneWaiting": "nadie esperando",
  "cust.waitingN": "{n} esperando",
  "cust.joinT": "Unirse a la fila",
  "cust.nameLabel": "Tu nombre (opcional)",
  "cust.joinBusy": "Tomando tu número…",
  "cust.joinReassure": "Sin app, sin cuenta, solo un número.",
  "cust.youreNumber": "Tu número",
  "cust.youreNext": "Eres el siguiente",
  "cust.oneAhead": "1 persona antes que tú",
  "cust.nAhead": "{n} personas antes que tú",
  "cust.peopleWaiting": "Esperando",
  "cust.reassure": "Esta página se actualiza sola, déjala abierta.",
  "cust.leave": "Salir de la fila",
  "cust.leaveConfirm": "¿Salir de la fila? Perderás tu número.",
  "cust.turnT": "Es tu turno",
  "cust.turnB": "Acércate al mostrador.",
  "cust.imHere": "Estoy aquí",
  "cust.sending": "Enviando…",
  "cust.confirmed": "Gracias, les hemos dicho que estás listo.",
  "cust.done": "Todo listo",
  "cust.servedBody": "Gracias por esperar.",
  "cust.skippedBody": "Fuiste saltado. Si sigues aquí, toma otro número.",
  "cust.noShowBody": "Este número se cerró. Si sigues aquí, toma otro número.",
  "cust.joinAgain": "Unirse otra vez",
  "cust.poweredBy": "Funciona con",
  "dash.navQueue": "Fila",
  "dash.navQr": "Código QR",
  "dash.navSettings": "Ajustes",
  "dash.signOut": "Cerrar sesión",
  "dash.opening": "Abriendo tu fila…",
  "dash.pausedB": "Los clientes no pueden tomar un número ahora.",
  "dash.nobodyCounter": "Nadie en el mostrador",
  "dash.noNameGiven": "Sin nombre",
  "dash.confirmedHere": "dice que está aquí",
  "dash.notConfirmed": "aún no ha confirmado",
  "dash.callNext": "Llamar al siguiente",
  "dash.calling": "Llamando…",
  "dash.noWaitingHint": "Nadie está esperando ahora.",
  "dash.pause": "Pausar fila",
  "dash.resume": "Reanudar fila",
  "dash.atCounter": "En el mostrador",
  "dash.waitingTitle": "Esperando",
  "dash.noName": "Sin nombre",
  "dash.stWait": "Esperando",
  "dash.stCalled": "Siendo atendido",
  "dash.stServed": "Atendido",
  "dash.stSkipped": "Saltado",
  "dash.stNoShow": "No presentado",
  "dash.firstRun": "Todavía no hay nadie. Tres pasos rápidos y tu fila está en marcha:",
  "dash.step1": "Consigue tu código QR. Imprímelo o ponlo en una pantalla junto a la puerta.",
  "dash.step1link": "Abrir mi código QR →",
  "dash.step2": "Los clientes toman un número. Escanean, escriben un nombre opcional y entran.",
  "dash.step3": "Pulsa Llamar al siguiente. Su teléfono se actualiza al instante.",
  "dash.emptyWaiting": "Nadie espera. Los números nuevos aparecen aquí según llega la gente.",
  "dash.nextUp": "Siguiente",
  "dash.finished": "Terminados",
  "dash.counts": "{s} atendidos, {k} saltados, {n} no presentados",
  "dash.markServed": "Marcar atendido",
  "dash.skip": "Saltar",
  "qr.intro":
    "Imprímelo y ponlo en la puerta o en el mostrador. El enlace nunca cambia, un código impreso hoy sigue funcionando.",
  "qr.linkLabel": "Enlace de tu fila",
  "qr.download": "Descargar PNG",
  "qr.print": "Imprimir",
  "qr.copy": "Copiar enlace",
  "qr.copied": "Enlace copiado.",
  "qr.making": "Creando tu código QR…",
  "qr.sheetCta": "Escanea para unirte a la fila",
  "qr.fine":
    "Tus clientes escanean para tomar un número, sin app ni cuenta. El QR se mantiene en blanco y negro en todos los temas para que los teléfonos lo lean.",
  "set.noteLabel": "Nota para los clientes",
  "set.noteHint": "Se muestra sobre el botón de unirse en tu página. Opcional.",
  "set.save": "Guardar cambios",
  "set.saving": "Guardando…",
  "set.saved": "Guardado.",
  "set.goodToKnow": "Bueno saber",
  "set.linkBody": "Es permanente, un QR impreso sigue funcionando aunque cambies el nombre.",
  "set.signedInAs": "Sesión iniciada como",
  "set.errNote": "Tu nota debe tener 200 caracteres o menos.",
  "nf.title": "Esta página no existe.",
  "nf.body": "Puede que se haya movido o que el enlace esté mal escrito.",
  "nf.cta": "Ir a la página de inicio",
};

const pt: Pack = {
  "nav.about": "Sobre",
  "nav.signin": "Entrar",
  "nav.setup": "Criar seu negócio",
  "foot.made": "Lobby, criado por {name}.",
  "foot.mit": "Código aberto sob licença MIT.",
  "lang.title": "Escolha seu idioma",
  "lang.sub": "Você pode mudar depois com a bandeira no canto superior.",
  "lang.change": "Mudar idioma",
  "lang.done": "Pronto",
  "common.loading": "Carregando…",
  "common.retry": "Tentar de novo",
  "hero.eyebrow": "Filas para lojas, clínicas e salões",
  "hero.h1a": "Pegue um número.",
  "hero.h1b": "Espere onde quiser.",
  "hero.lede":
    "Um QR code para o seu negócio. Os clientes escaneiam, pegam um número e veem a posição na fila. Quando é a vez deles, o celular deles avisa.",
  "hero.fine":
    "Sem app para seus clientes, sem conta para eles. Código aberto e roda no seu próprio servidor.",
  "demo.nowServing": "Atendendo agora",
  "demo.yourNumber": "Seu número",
  "how.title": "Como funciona",
  "how.t1": "Imprima seu QR code",
  "how.d1": "Um código permanente para sua porta ou balcão.",
  "how.t2": "Os clientes pegam um número",
  "how.d2": "Eles escaneiam, colocam um nome se quiserem, nada para instalar.",
  "how.t3": "Aperte Chamar próximo",
  "how.d3": "A fila anda e a tela deles se atualiza sozinha.",
  "see.title": "O que seus clientes veem",
  "see.copy":
    "Uma tela só, sempre com as mesmas respostas. Funciona em qualquer navegador de celular e, quando você chama o número, ela vira É a sua vez.",
  "see.youreNumber": "Seu número",
  "see.peopleAhead": "Pessoas antes de você",
  "see.when": "Quando acontece",
  "see.itsTurn": "É a sua vez!",
  "places.title": "Feito para lugares com balcão",
  "places.list":
    "Farmácias · Clínicas · Salões · Barbearias · Oficinas · Bancos · Correios · Órgãos públicos",
  "band.title": "A configuração leva cerca de um minuto.",
  "auth.welcome": "Bem-vindo de volta",
  "auth.setupSub": "Um minuto digitando e sua fila está pronta.",
  "auth.loginSub": "Entre na sua fila.",
  "auth.bizName": "Nome do negócio",
  "auth.yourName": "Seu nome",
  "auth.email": "E-mail",
  "auth.password": "Senha",
  "auth.pwHint": "Pelo menos 8 caracteres.",
  "auth.creating": "Criando…",
  "auth.signingIn": "Entrando…",
  "auth.create": "Criar meu negócio",
  "auth.haveAccount": "Já tem uma conta?",
  "auth.noAccount": "Ainda não tem conta?",
  "auth.backHome": "Voltar para o início",
  "err.bizName": "Digite o nome do seu negócio.",
  "err.name": "Digite seu nome.",
  "err.email": "Digite seu e-mail.",
  "err.password": "Digite sua senha.",
  "err.pwLen": "A senha precisa de pelo menos 8 caracteres.",
  "cust.opening": "Abrindo a fila…",
  "cust.wrong": "Algo deu errado.",
  "cust.pausedT": "Fila pausada.",
  "cust.pausedB": "Este negócio não está pegando números agora, volte em breve.",
  "cust.nobody": "Ninguém sendo atendido ainda",
  "cust.noOneWaiting": "ninguém esperando",
  "cust.waitingN": "{n} esperando",
  "cust.joinT": "Entrar na fila",
  "cust.nameLabel": "Seu nome (opcional)",
  "cust.joinBusy": "Pegando seu número…",
  "cust.joinReassure": "Sem app, sem conta, só um número.",
  "cust.youreNumber": "Seu número",
  "cust.youreNext": "Você é o próximo",
  "cust.oneAhead": "1 pessoa antes de você",
  "cust.nAhead": "{n} pessoas antes de você",
  "cust.peopleWaiting": "Esperando",
  "cust.reassure": "Esta página se atualiza sozinha, mantenha ela aberta.",
  "cust.leave": "Sair da fila",
  "cust.leaveConfirm": "Sair da fila? Você vai perder seu número.",
  "cust.turnT": "É a sua vez",
  "cust.turnB": "Por favor, vá ao balcão.",
  "cust.imHere": "Estou aqui",
  "cust.sending": "Enviando…",
  "cust.confirmed": "Obrigado, avisamos que você está pronto.",
  "cust.done": "Tudo certo",
  "cust.servedBody": "Obrigado por esperar.",
  "cust.skippedBody": "Você foi pulado. Se ainda está aqui, pegue outro número.",
  "cust.noShowBody": "Este número foi encerrado. Se ainda está aqui, pegue outro número.",
  "cust.joinAgain": "Entrar de novo",
  "cust.poweredBy": "Funciona com",
  "dash.navQueue": "Fila",
  "dash.navQr": "QR code",
  "dash.navSettings": "Ajustes",
  "dash.signOut": "Sair",
  "dash.opening": "Abrindo sua fila…",
  "dash.pausedB": "Clientes não podem pegar número agora.",
  "dash.nobodyCounter": "Ninguém no balcão",
  "dash.noNameGiven": "Sem nome",
  "dash.confirmedHere": "disse que está aqui",
  "dash.notConfirmed": "ainda não confirmou",
  "dash.callNext": "Chamar próximo",
  "dash.calling": "Chamando…",
  "dash.noWaitingHint": "Ninguém está esperando agora.",
  "dash.pause": "Pausar fila",
  "dash.resume": "Retomar fila",
  "dash.atCounter": "No balcão",
  "dash.waitingTitle": "Esperando",
  "dash.noName": "Sem nome",
  "dash.stWait": "Esperando",
  "dash.stCalled": "Sendo atendido",
  "dash.stServed": "Atendido",
  "dash.stSkipped": "Pulado",
  "dash.stNoShow": "Não compareceu",
  "dash.firstRun": "Ainda não tem ninguém. Três passos rápidos e sua fila está no ar:",
  "dash.step1": "Pegue seu QR code. Imprima ou coloque numa tela perto da porta.",
  "dash.step1link": "Abrir meu QR code →",
  "dash.step2": "Os clientes pegam um número. Escaneiam, digita um nome opcional e entram.",
  "dash.step3": "Aperte Chamar próximo. O celular deles atualiza na hora.",
  "dash.emptyWaiting": "Ninguém esperando. Números novos aparecem aqui conforme as pessoas entram.",
  "dash.nextUp": "Próximo",
  "dash.finished": "Concluídos",
  "dash.counts": "{s} atendidos, {k} pulados, {n} não compareceram",
  "dash.markServed": "Marcar como atendido",
  "dash.skip": "Pular",
  "qr.intro":
    "Imprima e coloque na porta ou no balcão. O link nunca muda, um código impresso hoje continua funcionando.",
  "qr.linkLabel": "Link da sua fila",
  "qr.download": "Baixar PNG",
  "qr.print": "Imprimir",
  "qr.copy": "Copiar link",
  "qr.copied": "Link copiado.",
  "qr.making": "Criando seu QR code…",
  "qr.sheetCta": "Escaneie para entrar na fila",
  "qr.fine":
    "Clientes escaneiam para pegar um número, sem app e sem conta. O QR fica preto e branco em todos os temas para os celulares lerem.",
  "set.noteLabel": "Nota para os clientes",
  "set.noteHint": "Aparece acima do botão de entrar na sua página. Opcional.",
  "set.save": "Salvar alterações",
  "set.saving": "Salvando…",
  "set.saved": "Salvo.",
  "set.goodToKnow": "Bom saber",
  "set.linkBody": "É permanente, um QR impresso continua funcionando mesmo se você mudar o nome.",
  "set.signedInAs": "Conectado como",
  "set.errNote": "Sua nota precisa de 200 caracteres ou menos.",
  "nf.title": "Esta página não existe.",
  "nf.body": "Ela pode ter mudado de lugar, ou o link foi digitado errado.",
  "nf.cta": "Ir para a página inicial",
};

const de: Pack = {
  "nav.about": "Über uns",
  "nav.signin": "Anmelden",
  "nav.setup": "Betrieb einrichten",
  "foot.made": "Lobby, erstellt von {name}.",
  "foot.mit": "Open Source unter der MIT-Lizenz.",
  "lang.title": "Sprache wählen",
  "lang.sub": "Du kannst sie später über die Flagge oben rechts ändern.",
  "lang.change": "Sprache ändern",
  "lang.done": "Fertig",
  "common.loading": "Wird geladen…",
  "common.retry": "Erneut versuchen",
  "hero.eyebrow": "Warteschlangen für Läden, Kliniken und Salons",
  "hero.h1a": "Nummer ziehen.",
  "hero.h1b": "Überall warten.",
  "hero.lede":
    "Ein QR-Code für deinen Betrieb. Kunden scannen ihn, ziehen eine Nummer und sehen ihren Platz in der Schlange. Wenn sie dran sind, sagt es ihr Handy.",
  "hero.fine":
    "Keine App für deine Kunden, kein Konto für sie. Open Source und läuft auf deinem eigenen Server.",
  "demo.nowServing": "Wird bedient",
  "demo.yourNumber": "Deine Nummer",
  "how.title": "So funktioniert es",
  "how.t1": "QR-Code ausdrucken",
  "how.d1": "Ein dauerhafter Code für deine Tür oder Theke.",
  "how.t2": "Kunden ziehen eine Nummer",
  "how.d2": "Sie scannen, tragen optional einen Namen ein, nichts zu installieren.",
  "how.t3": "Nächsten aufrufen",
  "how.d3": "Die Schlange rückt vor und ihr Bildschirm aktualisiert sich selbst.",
  "see.title": "Was deine Kunden sehen",
  "see.copy":
    "Ein Bildschirm, immer mit denselben Antworten. Funktioniert in jedem Handy-Browser, und wenn du ihre Nummer aufrufst, wechselt es zu Du bist dran.",
  "see.youreNumber": "Deine Nummer",
  "see.peopleAhead": "Personen vor dir",
  "see.when": "Wenn es soweit ist",
  "see.itsTurn": "Du bist dran!",
  "places.title": "Gemacht für Orte mit Theke",
  "places.list":
    "Apotheken · Kliniken · Salons · Barbiere · Werkstätten · Banken · Postämter · Behörden",
  "band.title": "Einrichtung dauert etwa eine Minute.",
  "auth.welcome": "Willkommen zurück",
  "auth.setupSub": "Eine Minute tippen und deine Schlange ist bereit.",
  "auth.loginSub": "Bei deiner Schlange anmelden.",
  "auth.bizName": "Betriebsname",
  "auth.yourName": "Dein Name",
  "auth.email": "E-Mail",
  "auth.password": "Passwort",
  "auth.pwHint": "Mindestens 8 Zeichen.",
  "auth.creating": "Wird eingerichtet…",
  "auth.signingIn": "Anmeldung…",
  "auth.create": "Betrieb erstellen",
  "auth.haveAccount": "Schon ein Konto?",
  "auth.noAccount": "Noch kein Konto?",
  "auth.backHome": "Zur Startseite",
  "err.bizName": "Gib den Namen deines Betriebs ein.",
  "err.name": "Gib deinen Namen ein.",
  "err.email": "Gib deine E-Mail ein.",
  "err.password": "Gib dein Passwort ein.",
  "err.pwLen": "Das Passwort braucht mindestens 8 Zeichen.",
  "cust.opening": "Schlange wird geöffnet…",
  "cust.wrong": "Etwas ist schiefgelaufen.",
  "cust.pausedT": "Schlange pausiert.",
  "cust.pausedB": "Dieser Betrieb nimmt gerade keine Nummern an, schau bald wieder vorbei.",
  "cust.nobody": "Noch niemand wird bedient",
  "cust.noOneWaiting": "niemand wartet",
  "cust.waitingN": "{n} warten",
  "cust.joinT": "Schlange beitreten",
  "cust.nameLabel": "Dein Name (optional)",
  "cust.joinBusy": "Nummer wird gezogen…",
  "cust.joinReassure": "Keine App, kein Konto, nur eine Nummer.",
  "cust.youreNumber": "Deine Nummer",
  "cust.youreNext": "Du bist der Nächste",
  "cust.oneAhead": "1 Person vor dir",
  "cust.nAhead": "{n} Personen vor dir",
  "cust.peopleWaiting": "Wartende",
  "cust.reassure": "Diese Seite aktualisiert sich selbst, lass sie offen.",
  "cust.leave": "Schlange verlassen",
  "cust.leaveConfirm": "Schlange verlassen? Du verlierst deine Nummer.",
  "cust.turnT": "Du bist dran",
  "cust.turnB": "Bitte komm zur Theke.",
  "cust.imHere": "Ich bin da",
  "cust.sending": "Wird gesendet…",
  "cust.confirmed": "Danke, wir haben ihnen gesagt, dass du bereit bist.",
  "cust.done": "Erledigt",
  "cust.servedBody": "Danke fürs Warten.",
  "cust.skippedBody": "Du wurdest übersprungen. Bist du noch da, zieh eine neue Nummer.",
  "cust.noShowBody": "Diese Nummer wurde geschlossen. Bist du noch da, zieh eine neue Nummer.",
  "cust.joinAgain": "Wieder beitreten",
  "cust.poweredBy": "Bereitgestellt von",
  "dash.navQueue": "Schlange",
  "dash.navQr": "QR-Code",
  "dash.navSettings": "Einstellungen",
  "dash.signOut": "Abmelden",
  "dash.opening": "Deine Schlange wird geöffnet…",
  "dash.pausedB": "Kunden können gerade keine Nummer ziehen.",
  "dash.nobodyCounter": "Niemand an der Theke",
  "dash.noNameGiven": "Ohne Namen",
  "dash.confirmedHere": "sagt, er ist da",
  "dash.notConfirmed": "hat noch nicht bestätigt",
  "dash.callNext": "Nächsten aufrufen",
  "dash.calling": "Wird aufgerufen…",
  "dash.noWaitingHint": "Gerade wartet niemand.",
  "dash.pause": "Schlange pausieren",
  "dash.resume": "Schlange fortsetzen",
  "dash.atCounter": "An der Theke",
  "dash.waitingTitle": "Wartend",
  "dash.noName": "Ohne Namen",
  "dash.stWait": "Wartend",
  "dash.stCalled": "Wird bedient",
  "dash.stServed": "Bedient",
  "dash.stSkipped": "Übersprungen",
  "dash.stNoShow": "Nicht erschienen",
  "dash.firstRun": "Noch ist niemand da. Drei schnelle Schritte und deine Schlange läuft:",
  "dash.step1": "Hol deinen QR-Code. Drucke ihn oder stell ihn auf einen Bildschirm an die Tür.",
  "dash.step1link": "Meinen QR-Code öffnen →",
  "dash.step2": "Kunden ziehen eine Nummer. Sie scannen, geben optional einen Namen ein, fertig.",
  "dash.step3": "Nächsten aufrufen. Ihr Handy aktualisiert sich im selben Moment.",
  "dash.emptyWaiting": "Niemand wartet. Neue Nummern erscheinen hier, sobald Leute kommen.",
  "dash.nextUp": "Als Nächstes",
  "dash.finished": "Erledigt",
  "dash.counts": "{s} bedient, {k} übersprungen, {n} nicht erschienen",
  "dash.markServed": "Als bedient markieren",
  "dash.skip": "Überspringen",
  "qr.intro":
    "Drucke ihn und häng ihn an die Theke oder an die Tür. Der Link ändert sich nie, ein gedruckter Code funktioniert auch morgen noch.",
  "qr.linkLabel": "Link zu deiner Schlange",
  "qr.download": "PNG herunterladen",
  "qr.print": "Drucken",
  "qr.copy": "Link kopieren",
  "qr.copied": "Link kopiert.",
  "qr.making": "QR-Code wird erstellt…",
  "qr.sheetCta": "Scannen und beitreten",
  "qr.fine":
    "Kunden scannen, um eine Nummer zu ziehen, ohne App und ohne Konto. Der QR-Code bleibt in jedem Design schwarz-weiß, damit Handys ihn lesen können.",
  "set.noteLabel": "Hinweis für Kunden",
  "set.noteHint": "Wird über dem Beitreten-Button auf deiner Seite angezeigt. Optional.",
  "set.save": "Änderungen speichern",
  "set.saving": "Wird gespeichert…",
  "set.saved": "Gespeichert.",
  "set.goodToKnow": "Gut zu wissen",
  "set.linkBody": "Er ist dauerhaft, ein gedruckter QR-Code funktioniert auch bei umbenanntem Betrieb.",
  "set.signedInAs": "Angemeldet als",
  "set.errNote": "Dein Hinweis darf höchstens 200 Zeichen haben.",
  "nf.title": "Diese Seite gibt es nicht.",
  "nf.body": "Sie wurde vielleicht verschoben oder der Link ist falsch getippt.",
  "nf.cta": "Zur Startseite",
};

const it: Pack = {
  "nav.about": "Chi siamo",
  "nav.signin": "Accedi",
  "nav.setup": "Crea la tua attività",
  "foot.made": "Lobby, creato da {name}.",
  "foot.mit": "Open source con licenza MIT.",
  "lang.title": "Scegli la lingua",
  "lang.sub": "Potrai cambiarla in seguito con la bandiera in alto a destra.",
  "lang.change": "Cambia lingua",
  "lang.done": "Fatto",
  "common.loading": "Caricamento…",
  "common.retry": "Riprova",
  "hero.eyebrow": "Casse per negozi, cliniche e saloni",
  "hero.h1a": "Prendi un numero.",
  "hero.h1b": "Aspetta dove vuoi.",
  "hero.lede":
    "Un solo QR code per la tua attività. I clienti lo scansionano, prendono un numero e vedono il loro posto in fila. Quando tocca a loro, il telefono li avvisa.",
  "hero.fine":
    "Nessuna app per i tuoi clienti, nessun conto per loro. Open source e gira sul tuo server.",
  "demo.nowServing": "In servizio ora",
  "demo.yourNumber": "Il tuo numero",
  "how.title": "Come funziona",
  "how.t1": "Stampa il tuo QR code",
  "how.d1": "Un codice permanente per la tua porta o il tuo banco.",
  "how.t2": "I clienti prendono un numero",
  "how.d2": "Scansionano, aggiungono un nome se vogliono, niente da installare.",
  "how.t3": "Premi Chiama il prossimo",
  "how.d3": "La fila avanza e il loro schermo si aggiorna da solo.",
  "see.title": "Cosa vedono i tuoi clienti",
  "see.copy":
    "Un solo schermo, sempre con le stesse risposte. Funziona in qualsiasi browser del telefono e, quando chiami il numero, diventa Tocca a te.",
  "see.youreNumber": "Il tuo numero",
  "see.peopleAhead": "Persone prima di te",
  "see.when": "Quando succede",
  "see.itsTurn": "Tocca a te!",
  "places.title": "Pensato per i posti con il banco",
  "places.list":
    "Farmacie · Cliniche · Saloni · Barbieri · Officine · Banche · Uffici postali · Uffici pubblici",
  "band.title": "La configurazione richiede un minuto.",
  "auth.welcome": "Bentornato",
  "auth.setupSub": "Un minuto di digitazione e la tua fila è pronta.",
  "auth.loginSub": "Accedi alla tua fila.",
  "auth.bizName": "Nome dell'attività",
  "auth.yourName": "Il tuo nome",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.pwHint": "Almeno 8 caratteri.",
  "auth.creating": "Creazione…",
  "auth.signingIn": "Accesso…",
  "auth.create": "Crea la mia attività",
  "auth.haveAccount": "Hai già un account?",
  "auth.noAccount": "Non hai ancora un account?",
  "auth.backHome": "Torna alla home",
  "err.bizName": "Inserisci il nome della tua attività.",
  "err.name": "Inserisci il tuo nome.",
  "err.email": "Inserisci la tua email.",
  "err.password": "Inserisci la tua password.",
  "err.pwLen": "La password deve avere almeno 8 caratteri.",
  "cust.opening": "Apertura della fila…",
  "cust.wrong": "Qualcosa è andato storto.",
  "cust.pausedT": "Fila in pausa.",
  "cust.pausedB": "Quest'attività non prende numeri ora, controlla più tardi.",
  "cust.nobody": "Nessuno servito finora",
  "cust.noOneWaiting": "nessuno in attesa",
  "cust.waitingN": "{n} in attesa",
  "cust.joinT": "Entra in fila",
  "cust.nameLabel": "Il tuo nome (facoltativo)",
  "cust.joinBusy": "Prendiamo il tuo numero…",
  "cust.joinReassure": "Niente app, niente conto, solo un numero.",
  "cust.youreNumber": "Il tuo numero",
  "cust.youreNext": "Sei il prossimo",
  "cust.oneAhead": "1 persona prima di te",
  "cust.nAhead": "{n} persone prima di te",
  "cust.peopleWaiting": "In attesa",
  "cust.reassure": "Questa pagina si aggiorna da sola, tienila aperta.",
  "cust.leave": "Esci dalla fila",
  "cust.leaveConfirm": "Esci dalla fila? Perderai il tuo numero.",
  "cust.turnT": "Tocca a te",
  "cust.turnB": "Vieni al banco, per favore.",
  "cust.imHere": "Sono qui",
  "cust.sending": "Invio…",
  "cust.confirmed": "Grazie, abbiamo detto loro che sei pronto.",
  "cust.done": "Tutto fatto",
  "cust.servedBody": "Grazie per aver aspettato.",
  "cust.skippedBody": "Sei stato saltato. Se sei ancora qui, prendi un altro numero.",
  "cust.noShowBody": "Questo numero è chiuso. Se sei ancora qui, prendi un altro numero.",
  "cust.joinAgain": "Entra di nuovo",
  "cust.poweredBy": "Offerto da",
  "dash.navQueue": "Fila",
  "dash.navQr": "QR code",
  "dash.navSettings": "Impostazioni",
  "dash.signOut": "Esci",
  "dash.opening": "Apertura della tua fila…",
  "dash.pausedB": "I clienti non possono prendere un numero ora.",
  "dash.nobodyCounter": "Nessuno al banco",
  "dash.noNameGiven": "Senza nome",
  "dash.confirmedHere": "ha detto che è qui",
  "dash.notConfirmed": "non ha ancora confermato",
  "dash.callNext": "Chiama il prossimo",
  "dash.calling": "Chiamata…",
  "dash.noWaitingHint": "Nessuno sta aspettando ora.",
  "dash.pause": "Metti in pausa",
  "dash.resume": "Riprendi la fila",
  "dash.atCounter": "Al banco",
  "dash.waitingTitle": "In attesa",
  "dash.noName": "Senza nome",
  "dash.stWait": "In attesa",
  "dash.stCalled": "In servizio",
  "dash.stServed": "Servito",
  "dash.stSkipped": "Saltato",
  "dash.stNoShow": "Assente",
  "dash.firstRun": "Non c'è ancora nessuno. Tre passi rapidi e la tua fila è attiva:",
  "dash.step1": "Prendi il tuo QR code. Stampalo o mettilo su uno schermo vicino alla porta.",
  "dash.step1link": "Apri il mio QR code →",
  "dash.step2": "I clienti prendono un numero. Scansionano, scrivono un nome facoltativo ed entrano.",
  "dash.step3": "Premi Chiama il prossimo. Il loro telefono si aggiorna subito.",
  "dash.emptyWaiting": "Nessuno aspetta. I nuovi numeri compaiono man mano che la gente arriva.",
  "dash.nextUp": "Il prossimo",
  "dash.finished": "Conclusi",
  "dash.counts": "{s} serviti, {k} saltati, {n} assenti",
  "dash.markServed": "Segna come servito",
  "dash.skip": "Salta",
  "qr.intro":
    "Stampalo e mettilo sulla porta o sul banco. Il link non cambia mai, un codice stampato oggi continua a funzionare.",
  "qr.linkLabel": "Link della tua fila",
  "qr.download": "Scarica PNG",
  "qr.print": "Stampa",
  "qr.copy": "Copia link",
  "qr.copied": "Link copiato.",
  "qr.making": "Creazione del tuo QR code…",
  "qr.sheetCta": "Scansiona per entrare in fila",
  "qr.fine":
    "I clienti scansionano per prendere un numero, senza app e senza conto. Il QR resta in bianco e nero in ogni tema così i telefoni lo leggono.",
  "set.noteLabel": "Nota per i clienti",
  "set.noteHint": "Appare sopra il pulsante Entra nella tua pagina. Facoltativa.",
  "set.save": "Salva modifiche",
  "set.saving": "Salvataggio…",
  "set.saved": "Salvato.",
  "set.goodToKnow": "Buono a sapersi",
  "set.linkBody": "È permanente, un QR stampato funziona anche se rinomini l'attività.",
  "set.signedInAs": "Accesso come",
  "set.errNote": "La nota deve avere 200 caratteri o meno.",
  "nf.title": "Questa pagina non esiste.",
  "nf.body": "Forse si è spostata o il link è stato scritto male.",
  "nf.cta": "Vai alla pagina iniziale",
};

const nl: Pack = {
  "nav.about": "Over ons",
  "nav.signin": "Inloggen",
  "nav.setup": "Je bedrijf instellen",
  "foot.made": "Lobby, gemaakt door {name}.",
  "foot.mit": "Open source onder de MIT-licentie.",
  "lang.title": "Kies je taal",
  "lang.sub": "Je kunt hierna wijzigen met de vlag rechtsboven.",
  "lang.change": "Taal wijzigen",
  "lang.done": "Klaar",
  "common.loading": "Laden…",
  "common.retry": "Opnieuw proberen",
  "hero.eyebrow": "Wachtrijen voor winkels, klinieken en salons",
  "hero.h1a": "Neem een nummer.",
  "hero.h1b": "Wacht waar je wilt.",
  "hero.lede":
    "Eén QR-code voor je bedrijf. Klanten scannen hem, nemen een nummer en zien hun plek in de rij. Als hun beurt is, vertelt hun telefoon het.",
  "hero.fine":
    "Geen app voor je klanten, geen account voor hen. Open source en draait op je eigen server.",
  "demo.nowServing": "Nu in behandeling",
  "demo.yourNumber": "Jouw nummer",
  "how.title": "Hoe het werkt",
  "how.t1": "Print je QR-code",
  "how.d1": "Eén permanent code voor je deur of balie.",
  "how.t2": "Klanten nemen een nummer",
  "how.d2": "Ze scannen, voegen optioneel een naam toe, niets te installeren.",
  "how.t3": "Druk op Volgende roepen",
  "how.d3": "De rij schuift op en hun scherm werkt zichzelf bij.",
  "see.title": "Wat je klanten zien",
  "see.copy":
    "Eén scherm, elke keer dezelfde antwoorden. Het werkt in elke mobiele browser en als je hun nummer roept, verandert het in Jour beurt.",
  "see.youreNumber": "Jouw nummer",
  "see.peopleAhead": "Mensen voor je",
  "see.when": "Wanneer het zover is",
  "see.itsTurn": "Jour beurt!",
  "places.title": "Gemaakt voor plekken met een balie",
  "places.list":
    "Apotheken · Klinieken · Salons · Kappers · Reparatiebedrijven · Banken · Postkantoren · Overheidskantoren",
  "band.title": "Instellen duurt ongeveer een minuut.",
  "auth.welcome": "Welkom terug",
  "auth.setupSub": "Een minuut typen en je wachtrij is klaar.",
  "auth.loginSub": "Log in op je wachtrij.",
  "auth.bizName": "Bedrijfsnaam",
  "auth.yourName": "Jouw naam",
  "auth.email": "E-mail",
  "auth.password": "Wachtwoord",
  "auth.pwHint": "Minstens 8 tekens.",
  "auth.creating": "Instellen…",
  "auth.signingIn": "Inloggen…",
  "auth.create": "Mijn bedrijf aanmaken",
  "auth.haveAccount": "Al een account?",
  "auth.noAccount": "Nog geen account?",
  "auth.backHome": "Terug naar home",
  "err.bizName": "Vul de naam van je bedrijf in.",
  "err.name": "Vul je naam in.",
  "err.email": "Vul je e-mail in.",
  "err.password": "Vul je wachtwoord in.",
  "err.pwLen": "Het wachtwoord moet minstens 8 tekens hebben.",
  "cust.opening": "Wachtrij openen…",
  "cust.wrong": "Er is iets misgegaan.",
  "cust.pausedT": "Wachtrij gepauzeerd.",
  "cust.pausedB": "Dit bedrijf neemt nu geen nummers aan, kom snel terug.",
  "cust.nobody": "Nog niemand in behandeling",
  "cust.noOneWaiting": "niemand wacht",
  "cust.waitingN": "{n} wachten",
  "cust.joinT": "Sluit aan in de rij",
  "cust.nameLabel": "Jouw naam (optioneel)",
  "cust.joinBusy": "Je nummer wordt genomen…",
  "cust.joinReassure": "Geen app, geen account, alleen een nummer.",
  "cust.youreNumber": "Jouw nummer",
  "cust.youreNext": "Jij bent de volgende",
  "cust.oneAhead": "1 persoon voor je",
  "cust.nAhead": "{n} mensen voor je",
  "cust.peopleWaiting": "Wachtenden",
  "cust.reassure": "Deze pagina werkt zichzelf bij, houd hem open.",
  "cust.leave": "Verlaat de rij",
  "cust.leaveConfirm": "De rij verlaten? Je verliest je nummer.",
  "cust.turnT": "Jour beurt",
  "cust.turnB": "Ga naar de balie.",
  "cust.imHere": "Ik ben er",
  "cust.sending": "Versturen…",
  "cust.confirmed": "Bedankt, we hebben ze verteld dat je klaar bent.",
  "cust.done": "Klaar",
  "cust.servedBody": "Bedankt voor het wachten.",
  "cust.skippedBody": "Je bent overgeslagen. Ben je er nog, neem dan een nieuw nummer.",
  "cust.noShowBody": "Dit nummer is gesloten. Ben je er nog, neem dan een nieuw nummer.",
  "cust.joinAgain": "Weer aansluiten",
  "cust.poweredBy": "Mogelijk gemaakt door",
  "dash.navQueue": "Wachtrij",
  "dash.navQr": "QR-code",
  "dash.navSettings": "Instellingen",
  "dash.signOut": "Uitloggen",
  "dash.opening": "Je wachtrij openen…",
  "dash.pausedB": "Klanten kunnen nu geen nummer nemen.",
  "dash.nobodyCounter": "Niemand aan de balie",
  "dash.noNameGiven": "Geen naam",
  "dash.confirmedHere": "zegt dat die er is",
  "dash.notConfirmed": "heeft nog niet bevestigd",
  "dash.callNext": "Volgende roepen",
  "dash.calling": "Roepen…",
  "dash.noWaitingHint": "Op dit moment wacht niemand.",
  "dash.pause": "Wachtrij pauzeren",
  "dash.resume": "Wachtrij hervatten",
  "dash.atCounter": "Aan de balie",
  "dash.waitingTitle": "Wachtend",
  "dash.noName": "Geen naam",
  "dash.stWait": "Wachtend",
  "dash.stCalled": "In behandeling",
  "dash.stServed": "Afgehandeld",
  "dash.stSkipped": "Overgeslagen",
  "dash.stNoShow": "Niet verschenen",
  "dash.firstRun": "Er is nog niemand. Drie snelle stappen en je wachtrij draait:",
  "dash.step1": "Pak je QR-code. Print hem of zet hem op een scherm bij de deur.",
  "dash.step1link": "Mijn QR-code openen →",
  "dash.step2": "Klanten nemen een nummer. Ze scannen, typen een optionele naam en zijn er.",
  "dash.step3": "Druk op Volgende roepen. Hun telefoon werkt meteen bij.",
  "dash.emptyWaiting": "Niemand wacht. Nieuwe nummers verschijnen hier zodra mensen aansluiten.",
  "dash.nextUp": "Als volgende",
  "dash.finished": "Afgerond",
  "dash.counts": "{s} afgehandeld, {k} overgeslagen, {n} niet verschenen",
  "dash.markServed": "Markeren als afgehandeld",
  "dash.skip": "Overslaan",
  "qr.intro":
    "Print hem en hang hem bij de deur of op de balie. De link verandert nooit, een code die je vandaag print blijft werken.",
  "qr.linkLabel": "Link naar je wachtrij",
  "qr.download": "PNG downloaden",
  "qr.print": "Printen",
  "qr.copy": "Link kopiëren",
  "qr.copied": "Link gekopieerd.",
  "qr.making": "Je QR-code maken…",
  "qr.sheetCta": "Scan om aan te sluiten",
  "qr.fine":
    "Klanten scannen om een nummer te nemen, zonder app en zonder account. De QR blijft zwart-wit in elk thema zodat telefoons hem kunnen lezen.",
  "set.noteLabel": "Notitie voor klanten",
  "set.noteHint": "Wordt getoond boven de Aansluiten-knop op je pagina. Optioneel.",
  "set.save": "Wijzigingen opslaan",
  "set.saving": "Opslaan…",
  "set.saved": "Opgeslagen.",
  "set.goodToKnow": "Goed om te weten",
  "set.linkBody": "De link is permanent, een geprinte QR blijft werken ook als je de naam wijzigt.",
  "set.signedInAs": "Ingelogd als",
  "set.errNote": "Je notitie mag maximaal 200 tekens hebben.",
  "nf.title": "Deze pagina bestaat niet.",
  "nf.body": "Misschien is hij verplaatst of is de link verkeerd getypt.",
  "nf.cta": "Naar de startpagina",
};

export const westEurope: Lang[] = [
  { code: "fr", label: "French", native: "Français", flag: "fr", dict: fr },
  { code: "es", label: "Spanish", native: "Español", flag: "es", dict: es },
  { code: "pt", label: "Portuguese (Brazil)", native: "Português (Brasil)", flag: "br", dict: pt },
  { code: "de", label: "German", native: "Deutsch", flag: "de", dict: de },
  { code: "it", label: "Italian", native: "Italiano", flag: "it", dict: it },
  { code: "nl", label: "Dutch", native: "Nederlands", flag: "nl", dict: nl },
];
